# -*- coding: utf-8 -*-
"""Phase 4.0 — Beauty (20) and Food & Beverage (20) concept knowledge."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_concept_lib import CONCEPT, flush

# C(kid, name, domain, sub, tension, insight, trigger, belief, territory,
#   decision, reasoning, why, problem, impact, use, avoid, adv, lim, suit,
#   unsuit, alts, ap_problem, ap_why, ap_fix, ind, aud, obj, pos)
def C(kid, name, domain, sub, tension, insight, trigger, belief, territory,
      decision, reasoning, why, problem, impact, use, avoid, adv, lim, suit,
      unsuit, alts, app, apw, apf, ind="*", aud="*", obj="*", pos="*",
      cat="*", ch="*", examples=None, avoid_patterns=None, iscore=8, prio=8, conf=0.85):
    CONCEPT(kid, name, domain, sub, tension, insight, trigger, belief, territory,
            decision, reasoning, why, problem, impact,
            use=use, avoid=avoid, adv=adv, lim=lim, suit=suit, unsuit=unsuit,
            alts=alts, aps=[(app, apw, apf)], examples=examples,
            avoid_patterns=avoid_patterns, ind=ind, aud=aud, obj=obj, pos=pos, cat=cat, ch=ch,
            iscore=iscore, prio=prio, conf=conf)


# ═══════════════════════ BEAUTY (20) ═══════════════════════
C("human_tension.beauty.ageing_identity.001", "Ageing as identity loss, not appearance loss", "human_tension", "beauty",
  "She is not afraid of looking older; she is afraid of no longer recognising the person looking back.",
  "Mature buyers reject correction language because it frames who they are now as a defect to be undone.",
  "Recognition, and the relief of being addressed as continuous rather than diminished.",
  "That maintaining who she already is counts as ambition, not as giving up.",
  "Continuity of self — a brand that helps her stay recognisable rather than become someone else.",
  "Frame the campaign around staying recognisably herself rather than reversing what has changed.",
  "Correction language implies the current face is a mistake, and nobody buys an accusation twice.",
  "Continuity removes the implied criticism that suppresses purchase intent in this segment.",
  "Category messaging defaults to reversal and repair, which mature buyers read as an insult.",
  "Raises emotional relevance and premium justification with buyers who have rejected fear-led claims.",
  ["Skincare for buyers over 35", "Brands positioned on longevity rather than transformation"],
  ["Discount-led promotion", "First-time buyers with no established routine"],
  "Emotional relevance with a sceptical segment", "Slower to communicate a functional benefit",
  "Premium and luxury skincare", "Flash sales and acquisition-led promotion",
  ["A results-first frame where the audience is new to the category"],
  "A before-and-after pair with the before shot lit unkindly",
  "It stages the audience's own face as the problem, which reads as contempt rather than proof",
  "Show one state, held over time, and let duration carry the claim",
  ind="beauty", aud=["women_35_50", "premium_consumers"], pos=["premium", "luxury"], iscore=9, prio=9, conf=0.9,
  examples=["A portrait of the same person a decade apart, unremarked", "Copy that names what has not changed"],
  avoid_patterns=["Before and after", "Reversal and repair language", "Clock and countdown imagery"])

C("human_tension.beauty.claim_exhaustion.001", "Exhaustion with unverifiable claims", "human_tension", "beauty",
  "She has been promised the same result by nine brands and has no way to tell which one was telling the truth.",
  "Claim fatigue is not scepticism about efficacy; it is scepticism about being able to verify anything at all.",
  "The relief of being handed something she can check herself.",
  "That this brand expects to be checked, and has arranged for her to be able to.",
  "Verifiability — the brand that hands over the means of checking rather than asking for belief.",
  "Give the audience a way to verify the claim themselves rather than restating it more loudly.",
  "A claim that can be tested is structurally different from a claim that must be believed.",
  "Handing over the means of verification is the only move a competitor cannot copy by asserting harder.",
  "Every brand in the category makes the same promise, so louder promises no longer move anyone.",
  "Converts a saturated claim into a differentiated position without changing the formula.",
  ["Categories where every competitor claims the same benefit", "Audiences with high claim exposure"],
  ["Genuinely novel mechanisms with no comparison set", "Categories where verification is impossible"],
  "Differentiates without needing a better product", "Requires the claim to actually survive checking",
  "Efficacy-led beauty in saturated categories", "Fragrance and mood-led propositions",
  ["A provenance frame where the mechanism genuinely is novel"],
  "Adding a percentage to the same claim everyone else makes",
  "A number inside an unverifiable claim is still unverifiable, and the audience has learned that",
  "State what the audience can observe for themselves, and by when",
  ind="beauty", obj=["awareness", "product_launch"], iscore=9, prio=9, conf=0.9,
  avoid_patterns=["Louder claims", "Unattributed percentages", "Clinical-looking graphics with no study"])

C("consumer_insight.beauty.routine_as_control.001", "The routine is the product", "consumer_insight", "beauty",
  "Her days are largely dictated by other people, and the ten minutes at the basin are not.",
  "Skincare routines persist because they are one of the few sequences a person fully controls, not because of the ingredients.",
  "The quiet satisfaction of a sequence completed exactly as intended.",
  "That the ritual itself is worth protecting, and this brand understands what it is for.",
  "Ownership of the daily moment rather than of the ingredient.",
  "Anchor the campaign in the moment of use rather than in what the product contains.",
  "Buyers describe their routine unprompted and their ingredients only when asked, which says which one they value.",
  "Owning a moment is defensible; owning an ingredient is not, because ingredients are licensable.",
  "Ingredient-led campaigns compete on a fact any competitor can also state.",
  "Builds an ownable territory that survives a competitor matching the formula.",
  ["Multi-step routines", "Repeat-purchase categories"],
  ["Single-use treatments", "Clinical products bought for one specific problem"],
  "Defensible against formula parity", "Slower to communicate what the product does",
  "Daily-use skincare", "One-off corrective treatments",
  ["An ingredient-led frame where the mechanism is genuinely proprietary"],
  "Showing the product being applied by a model who is plainly not enjoying it",
  "Ritual only reads as ritual when the person appears to want to be there",
  "Show the moment before or after application rather than the application itself",
  ind="beauty", cat="skincare", iscore=8, prio=9, conf=0.88)

C("consumer_insight.beauty.ingredient_literacy.001", "Ingredient literacy as social currency", "consumer_insight", "beauty",
  "She has learned the vocabulary and now has nowhere to spend it except in comment sections.",
  "Ingredient-literate buyers are performing competence as much as buying efficacy, and brands that talk down to them lose twice.",
  "The satisfaction of being addressed as someone who already knows.",
  "That this brand assumes her competence rather than teaching her from zero.",
  "Peer address — a brand that talks to her the way another informed buyer would.",
  "Address the audience as already informed and lead with what they do not yet know.",
  "Explaining the basics to someone who has done the reading signals the brand has not.",
  "Assumed competence is flattering in a way no discount is, and it is free.",
  "Category communication defaults to education, which insults the segment most likely to buy.",
  "Raises credibility with high-intent buyers and shortens their evaluation.",
  ["Actives and high-engagement categories", "Audiences who research before buying"],
  ["Mass-market entry products", "Audiences new to the category"],
  "Credibility with high-intent buyers", "Excludes the genuinely uninformed",
  "Actives-led skincare", "Mass-market first-purchase products",
  ["An educational frame for a genuinely new mechanism"],
  "A campaign that defines a well-known ingredient as though it were novel",
  "It tells the informed buyer the brand has not met anyone like her",
  "Lead with an interaction or a trade-off the informed buyer has not considered",
  ind="beauty", aud=["women_25_35", "premium_consumers"], iscore=8, prio=8, conf=0.86)

C("campaign_territory.beauty.evidence_theatre.001", "Evidence as the territory, not the proof", "campaign_territory", "beauty",
  "She wants proof but has learned that most proof is staged, so proof itself now needs proving.",
  "Audiences read the staging of evidence more than the evidence, and over-produced proof reads as less credible than plain proof.",
  "Trust arriving through restraint rather than through insistence.",
  "That a brand confident in its result does not need to dramatise it.",
  "Understatement as credibility — the brand that shows less because it needs to show less.",
  "State the result plainly and let the absence of dramatisation carry the credibility.",
  "Dramatisation and confidence read as opposites: the more a claim is staged, the less it is believed.",
  "Restraint is expensive to fake, which is exactly why it reads as true.",
  "Efficacy communication escalates into spectacle, and spectacle is what the audience has learned to discount.",
  "Raises believability without changing the underlying claim.",
  ["Efficacy claims in saturated categories", "Premium positioning"],
  ["Value positioning where salience matters more than belief", "Feed contexts requiring immediate arrest"],
  "Believability at premium price points", "Low salience in crowded feeds",
  "Premium efficacy-led beauty", "Promotional and discount communication",
  ["A high-salience frame where the asset must survive a feed"],
  "Adding a laboratory setting to a claim that has no study behind it",
  "Borrowed credibility collapses the moment anyone asks for the study",
  "Show only what the brand can actually substantiate, and stop there",
  ind="beauty", pos=["premium", "luxury"], iscore=8, prio=8, conf=0.87)

C("campaign_territory.beauty.unfinished_face.001", "The face mid-routine", "campaign_territory", "beauty",
  "Every image she sees is of a finished face, and her own face is mostly unfinished.",
  "Category imagery shows outcomes exclusively, which makes the audience the only person in the world at an intermediate stage.",
  "Recognition, and the small relief of not being the only one halfway through.",
  "That the brand has seen a real face at a real hour and is not embarrassed by it.",
  "The honest intermediate — a brand willing to be present before the result.",
  "Build the campaign around the unfinished state rather than the achieved one.",
  "Outcome-only imagery makes the product feel like something used by people who do not need it.",
  "Being seen mid-process is rarer in this category than being seen at your best, which makes it ownable.",
  "Every competitor owns the finished face, so the finished face is not available as a position.",
  "Opens an unoccupied territory in a category where imagery is otherwise interchangeable.",
  ["Categories saturated with outcome imagery", "Brands positioned on honesty"],
  ["Luxury positioning built on aspiration", "Colour cosmetics sold on the finished look"],
  "An unoccupied position in a crowded category", "Conflicts with aspiration-led luxury",
  "Honest and clinical beauty", "Aspirational luxury and colour cosmetics",
  ["An outcome-led frame where the category is not yet saturated"],
  "Styling the unfinished state until it becomes another finished look",
  "The territory only exists while the image is genuinely unpolished",
  "Keep the deliberate imperfection actually imperfect",
  ind="beauty", iscore=8, prio=8, conf=0.85)

C("idea_pattern.beauty.absence_proof.001", "Prove by what is missing", "idea_pattern", "beauty",
  "She judges a product by what it does, and has no way to notice what it stopped happening.",
  "Preventative benefits are invisible by definition, so the audience under-values exactly the products that work best.",
  "The delayed realisation that nothing went wrong, and that this was the point.",
  "That the absence of a problem is a result worth paying for.",
  "The unremarkable day — a brand that sells the absence of an event.",
  "Build the idea around what did not happen rather than what did.",
  "A prevented problem leaves no evidence, so the idea has to supply the counterfactual the audience cannot see.",
  "Naming the absence converts an invisible benefit into a noticeable one without overclaiming.",
  "Preventative products lose to corrective ones because correction is visible and prevention is not.",
  "Makes an invisible benefit communicable, which is the core problem of the preventative category.",
  ["Sun care, preventative and maintenance products", "Benefits that are absences"],
  ["Corrective products with a visible result", "Categories where the benefit is immediate"],
  "Communicates an invisible benefit", "Requires the audience to imagine a counterfactual",
  "Preventative skincare and sun care", "Corrective and immediate-result products",
  ["A direct-result frame where the benefit is genuinely visible"],
  "Showing the damage that would have happened, in graphic detail",
  "Fear-led prevention performs on attention and badly on purchase in this category",
  "Show the ordinary day that the product made unremarkable",
  ind="beauty", cat="skincare", iscore=8, prio=8, conf=0.86)

C("human_tension.beauty.price_guilt.001", "The guilt of the expensive jar", "human_tension", "beauty",
  "She can afford it and still feels she should not, because spending this much on her own face feels indefensible.",
  "Premium beauty purchase is blocked less by price than by the need for a justification she can say out loud.",
  "Permission — the relief of having a reason that survives being questioned.",
  "That the purchase is defensible on grounds other than vanity.",
  "Justified spending — a brand that supplies the reason, not just the product.",
  "Give the audience a defensible reason for the price that is not about looking better.",
  "The barrier is social rather than financial, so a discount does not remove it and a reason does.",
  "A stated reason travels: she can repeat it to whoever asks, and a discount cannot be repeated.",
  "Premium beauty defaults to aspiration, which deepens the guilt instead of resolving it.",
  "Removes the real barrier to premium purchase without discounting.",
  ["Premium and luxury price points", "Categories where price is the stated objection"],
  ["Value positioning", "Gifting occasions where the buyer is not the user"],
  "Resolves the actual barrier", "Requires a genuine substantiable reason",
  "Premium skincare", "Value and promotional communication",
  ["A pure desirability frame where the audience feels no guilt"],
  "Justifying the price by naming the ingredient cost",
  "Cost is not a reason; it explains the price without making it worth paying",
  "Name what the price buys that a cheaper product cannot deliver at all",
  ind="beauty", pos=["premium", "luxury"], iscore=9, prio=9, conf=0.88)

C("consumer_insight.beauty.mirror_moment.001", "The mirror is a private audience", "consumer_insight", "beauty",
  "She is not preparing for other people so much as settling an argument she has been having with herself.",
  "The decisive moment in beauty is private and precedes any social encounter, which is why social-proof advertising underperforms.",
  "Composure — the feeling of having settled something before leaving the house.",
  "That the product serves her own judgement rather than anyone else's approval.",
  "Self-address — a brand that speaks to the private audience rather than the public one.",
  "Address the private moment before the social one rather than the reaction of other people.",
  "Purchase intent forms in a solitary moment, so imagery of admiring bystanders addresses the wrong scene.",
  "Speaking to the private judgement is more accurate and, unusually in this category, less crowded.",
  "Beauty advertising defaults to third-party admiration, which is not where the decision is made.",
  "Aligns the work with where purchase intent actually forms.",
  ["Personal-use categories", "Products used before a social occasion"],
  ["Gifting propositions", "Products bought explicitly for an audience"],
  "Addresses the real decision moment", "Loses the aspiration of social proof",
  "Everyday and premium personal care", "Gifting and occasion-led propositions",
  ["A social-proof frame for products bought to be seen"],
  "Cutting from the mirror to a room full of admiring people",
  "The cut relocates the decision to a scene where it does not happen",
  "Stay in the private moment and end there",
  ind="beauty", iscore=8, prio=8, conf=0.86)

C("campaign_territory.beauty.expertise_lineage.001", "Named hands rather than a named laboratory", "campaign_territory", "beauty",
  "She is asked to trust an institution, and institutions have been wrong about this category before.",
  "Trust attaches to identifiable people far more readily than to unnamed research facilities.",
  "The reassurance of knowing who is accountable.",
  "That a specific person stands behind this and could be asked about it.",
  "Named accountability — the brand where somebody's name is on the result.",
  "Attach the claim to a named person who can be held to it rather than to an unnamed facility.",
  "An institution cannot be embarrassed and a person can, which is what makes a person's word worth more.",
  "Accountability is transferable to the audience as a reason to trust, and it costs nothing to state.",
  "Category credibility is claimed through anonymous laboratory imagery that nobody is accountable for.",
  "Converts generic institutional credibility into specific personal credibility.",
  ["Founder-led and clinician-led brands", "Categories with a trust deficit"],
  ["Large corporate brands with no identifiable author", "Categories where anonymity is preferred"],
  "Transfers trust from institution to person", "Ties the brand to an individual's reputation",
  "Founder and clinician-led beauty", "Corporate and house brands",
  ["Third-party certification where no individual can be named"],
  "A stock-photo scientist in a coat with no name attached",
  "An anonymous expert is an institution again, and carries none of the accountability",
  "Name the person, state their standing, and let them make the claim",
  ind="beauty", iscore=8, prio=8, conf=0.86)

C("human_tension.beauty.sensitive_fear.001", "Fear of making it worse", "human_tension", "beauty",
  "Her skin has reacted badly before and the memory of that outweighs any promised improvement.",
  "For reactive skin the decision is loss-averse, not gain-seeking, so benefit-led messaging addresses the wrong calculation.",
  "Safety — the specific relief of an assurance that the worst case has been considered.",
  "That the brand has thought about what happens if it goes wrong for her.",
  "Downside management — a brand that leads with the risk rather than the reward.",
  "Lead with what the product will not do rather than with what it promises to achieve.",
  "A loss-averse buyer discounts upside entirely until the downside has been addressed.",
  "Addressing the actual calculation is the only way to move a buyer who is not weighing benefit at all.",
  "Sensitive-skin communication leads with gentleness as an adjective rather than as an assurance.",
  "Unblocks purchase for a segment that benefit-led messaging cannot reach.",
  ["Sensitive and reactive skin", "First-time users of an active ingredient"],
  ["Performance-led propositions", "Audiences seeking maximum strength"],
  "Reaches a segment other messaging cannot", "Caps the strength of the benefit claim",
  "Sensitive-skin and first-active products", "High-strength performance products",
  ["A performance frame for experienced users"],
  "Describing the product as gentle without saying what was removed",
  "Gentle is an adjective; a loss-averse buyer needs a specific exclusion",
  "Name what is absent from the formula and why that matters to her",
  ind="beauty", iscore=8, prio=8, conf=0.87)

C("consumer_insight.beauty.regimen_guilt.001", "The abandoned routine", "consumer_insight", "beauty",
  "She has three half-used products in a drawer and every new purchase carries the memory of the last one she gave up on.",
  "Repeat purchase is blocked by the buyer's own track record, not by dissatisfaction with the product.",
  "Forgiveness — permission to have failed at the last one.",
  "That this is not another commitment she will fail.",
  "Low-commitment entry — a brand that asks for less and therefore gets kept.",
  "Ask for a smaller commitment than the category usually demands.",
  "The barrier is the buyer's expectation of her own inconsistency, which a bigger promise makes worse.",
  "Reducing the ask removes the predicted failure, which is what actually stops the purchase.",
  "Category messaging escalates the routine, adding steps to a buyer who has abandoned shorter ones.",
  "Raises conversion and repeat rate by removing an anticipated failure.",
  ["Multi-step categories", "Audiences with abandoned products at home"],
  ["Enthusiast segments who want more steps", "Professional and clinical protocols"],
  "Removes an unspoken purchase barrier", "Caps the basket size per purchase",
  "Everyday skincare", "Enthusiast and professional regimens",
  ["A maximal-routine frame for enthusiast audiences"],
  "A campaign presenting a seven-step routine as the minimum",
  "It confirms exactly the failure the buyer already expects of herself",
  "Present the smallest version that still works, and say it is enough",
  ind="beauty", iscore=8, prio=8, conf=0.86)

C("idea_pattern.beauty.category_reversal.001", "Say the thing the category cannot", "idea_pattern", "beauty",
  "Every brand tells her the same flattering thing, and none of them will say the obvious unflattering one.",
  "In categories where all messaging is positive, a single honest limitation is the most credible thing available.",
  "Surprise, then trust — the sequence that follows hearing something true.",
  "That a brand willing to say this is probably telling the truth about the rest.",
  "Stated limitation — the brand that names its own boundary.",
  "State one true limitation of the product prominently rather than burying it.",
  "In a field of uniform positives, a limitation is the only statement carrying information.",
  "A brand that volunteers a weakness has spent something real, which is why the claim is believed.",
  "Uniform positivity has made every claim in the category equally weightless.",
  "Buys credibility for the remaining claims at the cost of one.",
  ["Saturated categories with uniform messaging", "Brands with a genuine trade-off worth stating"],
  ["Regulated claims where a limitation creates liability", "Categories with real safety concerns"],
  "Credibility that competitors cannot copy cheaply", "Sacrifices one claim permanently",
  "Saturated beauty categories", "Regulated and safety-critical communication",
  ["A conventional benefit frame where no honest limitation exists"],
  "Naming a limitation nobody cared about as though it were a confession",
  "A fake concession is read as a technique, and costs more credibility than it buys",
  "Name a limitation that genuinely affects the purchase decision",
  ind="beauty", iscore=8, prio=8, conf=0.85)

C("human_tension.beauty.time_scarcity.001", "The routine that lost to the alarm", "human_tension", "beauty",
  "She knows what she should do in the morning and has eleven minutes in which to do all of it.",
  "The competitor for a morning skincare product is not another brand; it is the decision to skip it entirely.",
  "Relief at being given permission to do less without losing the result.",
  "That doing less is a legitimate strategy rather than a compromise.",
  "The realistic morning — a brand designed for the time she actually has.",
  "Position the product against the decision to skip rather than against a competitor.",
  "Share is lost to omission far more than to switching, so the competitive frame is wrong.",
  "Competing with omission opens a claim no rival brand is making.",
  "Category communication assumes a routine nobody in the segment actually completes.",
  "Reframes the competitive set to where volume is genuinely lost.",
  ["Morning and daily-use products", "Time-pressured audiences"],
  ["Evening and ritual-led propositions", "Enthusiast audiences with time to spend"],
  "Competes where share is actually lost", "Concedes the enthusiast segment",
  "Everyday morning products", "Ritual-led evening propositions",
  ["A ritual frame for evening and weekend products"],
  "Showing a serene unhurried morning in a bright empty bathroom",
  "It depicts a morning the target audience does not have, which reads as being for somebody else",
  "Show the real constraint and the product working inside it",
  ind="beauty", iscore=8, prio=8, conf=0.86)

C("consumer_insight.beauty.recommendation_chain.001", "Bought on somebody's word", "consumer_insight", "beauty",
  "She trusts one friend's opinion more than every review she has read combined.",
  "Beauty purchase runs on personal recommendation, and mass advertising's real job is to make the recommendation easier to give.",
  "Confidence in passing it on — the small pride of a recommendation that lands.",
  "That recommending this brand will reflect well on her.",
  "The repeatable reason — a brand that arms its buyers with something worth saying.",
  "Build the campaign around a single line the buyer can repeat to a friend.",
  "The decisive channel is conversation, and conversation carries one sentence, not a campaign.",
  "A repeatable line makes the buyer an effective advocate, which mass reach alone cannot.",
  "Campaigns are built for the audience rather than for the person the audience will tell.",
  "Improves word-of-mouth conversion, the channel that actually closes in this category.",
  ["Recommendation-driven categories", "Brands with strong existing advocacy"],
  ["Impulse purchase at shelf", "Categories with no social discussion"],
  "Improves the channel that closes", "Requires ruthless message reduction",
  "Beauty and personal care", "Impulse and shelf-led categories",
  ["A shelf-standout frame for impulse categories"],
  "A campaign with three equally weighted messages",
  "Nobody repeats three things, so the recommendation carries none of them",
  "Reduce to one line and make it easy to say out loud",
  ind="beauty", iscore=8, prio=8, conf=0.86)

C("campaign_territory.beauty.slow_making.001", "Time as the ingredient", "campaign_territory", "beauty",
  "She is asked to pay more and has no way to see what the extra money bought.",
  "Where formulas are comparable, the production process is the only remaining source of visible difference.",
  "Respect for something that could not be hurried.",
  "That the price reflects time that cannot be compressed.",
  "Duration — the brand whose process is the product.",
  "Make the length of the process the subject of the campaign rather than the result.",
  "Time is the one input a competitor cannot match without incurring the same cost.",
  "A process that takes longer is verifiable and expensive to fake, which makes it defensible.",
  "Premium beauty justifies price with adjectives, which any competitor can also use.",
  "Substantiates a premium without relying on an unverifiable efficacy claim.",
  ["Genuinely slow production processes", "Premium and heritage positioning"],
  ["Mass-produced products", "Brands positioned on innovation and speed"],
  "A defensible premium", "Only available to brands whose process is genuinely slow",
  "Craft and heritage beauty", "Mass and innovation-led brands",
  ["An efficacy frame where the process is unremarkable"],
  "Implying a slow process the brand does not actually use",
  "The claim is checkable, and being caught costs more than the premium was worth",
  "State the actual duration and what happens during it",
  ind="beauty", pos=["premium", "luxury", "traditional"], iscore=8, prio=8, conf=0.87)

C("human_tension.beauty.male_category_entry.001", "The aisle he will not stand in", "human_tension", "beauty",
  "He would use the product and will not be seen choosing it.",
  "Male adoption in beauty is blocked at the point of selection, not at the point of use.",
  "Ease — the absence of a decision that has to be defended.",
  "That using this requires no explanation to anyone.",
  "Unremarkable use — a brand that removes the social cost of choosing.",
  "Remove the social cost of selection rather than arguing that the product is masculine.",
  "The barrier is being observed choosing, so masculine styling addresses the wrong moment entirely.",
  "Removing the observed decision unlocks a segment that reassurance-led messaging never reaches.",
  "Male beauty communication over-signals masculinity, which draws attention to the very act being avoided.",
  "Opens a segment blocked by a social rather than a product barrier.",
  ["Male grooming and skincare", "Categories with a gendered purchase barrier"],
  ["Established male categories with no stigma", "Female-primary propositions"],
  "Unlocks a blocked segment", "Under-signals to men who want the signal",
  "Male entry-level skincare", "Established grooming categories",
  ["An explicit performance frame where the category is already normalised"],
  "Packaging and imagery that shout masculinity in a dark palette",
  "Loud gendering marks the product as needing a defence, which confirms the stigma",
  "Treat the purchase as unremarkable and let the product be ordinary",
  ind="beauty", iscore=7, prio=8, conf=0.84)

C("idea_pattern.beauty.single_promise.001", "One promise, kept completely", "idea_pattern", "beauty",
  "She has bought products that promised five things and delivered none of them convincingly.",
  "Multi-benefit claims reduce believability in aggregate: each additional promise discounts the others.",
  "Confidence — the clarity of a brand that has decided what it is for.",
  "That a product doing one thing is more likely to do it properly.",
  "Deliberate narrowness — the brand that does less on purpose.",
  "Claim exactly one benefit and refuse the others explicitly.",
  "Each added claim divides the audience's belief rather than adding to it.",
  "Refusing adjacent claims is a costly signal, which is why it is believed.",
  "Category products accumulate claims until none of them is credible.",
  "Raises believability and simplifies the purchase decision at once.",
  ["Crowded categories with multi-benefit competitors", "Single-mechanism products"],
  ["Genuine multi-benefit formulations", "Value propositions built on doing more for less"],
  "Higher believability per claim", "Loses buyers seeking a single product for everything",
  "Focused single-benefit products", "All-in-one value propositions",
  ["A multi-benefit frame where the value proposition is convenience"],
  "Claiming one benefit prominently while listing four more in the small print",
  "The small print undoes the focus and the buyer notices",
  "Say what the product does not do, in the same size as what it does",
  ind="beauty", iscore=8, prio=8, conf=0.86)

C("campaign_territory.beauty.local_formulation.001", "Made for this climate", "campaign_territory", "beauty",
  "She is using a product formulated for a climate she does not live in.",
  "Imported beauty is developed for temperate conditions, and buyers in humid markets experience that as the product not working.",
  "Recognition of a condition she experiences daily and never sees addressed.",
  "That someone formulated for the weather outside her window.",
  "Climate specificity — the brand that names the actual conditions of use.",
  "Build the campaign on the specific local conditions the product was made for.",
  "Efficacy is conditional on environment, so a product developed elsewhere genuinely performs differently.",
  "Local specificity is unavailable to a global competitor without reformulating.",
  "Imported brands communicate universally, leaving a real performance gap unaddressed.",
  "Creates a defensible position against larger imported competitors.",
  ["Local brands competing with imports", "Markets with distinctive climate conditions"],
  ["Global brands with a single formulation", "Temperate markets matching the origin climate"],
  "Defensible against global competitors", "Limits the addressable market by geography",
  "Local beauty brands in humid markets", "Global single-formula brands",
  ["A global-quality frame where the local difference is negligible"],
  "Claiming local formulation while selling the same product sold everywhere",
  "The claim is checkable through the ingredient list and collapses when checked",
  "State the specific reformulation and the condition it addresses",
  ind="beauty", iscore=8, prio=8, conf=0.86)

C("consumer_insight.beauty.gift_uncertainty.001", "The gift that might insult", "consumer_insight", "beauty",
  "He wants to buy her skincare and is afraid the gift will read as a comment on her face.",
  "Beauty gifting is blocked by the giver's fear of implying a flaw, which is why gift messaging that names benefits fails.",
  "Relief at a safe choice — the confidence of a gift that cannot be misread.",
  "That this gift carries no implied criticism.",
  "Safe generosity — a brand that makes the gift unambiguous.",
  "Position gift propositions on pleasure rather than on any benefit or correction.",
  "A benefit implies a deficiency, and a gift implying a deficiency is a risk no giver will take.",
  "Removing the implied criticism is the only thing that unblocks the giver's decision.",
  "Gift communication inherits benefit-led messaging, which makes the gift dangerous to give.",
  "Unlocks gifting occasions that benefit-led messaging actively blocks.",
  ["Gifting seasons", "Products bought by someone other than the user"],
  ["Self-purchase communication", "Clinical and corrective products"],
  "Unblocks the giver's decision", "Cannot carry an efficacy claim",
  "Beauty gifting propositions", "Self-purchase efficacy communication",
  ["A benefit-led frame for self-purchase"],
  "A gift campaign that leads with what the product corrects",
  "It hands the giver a message they cannot deliver without insulting the recipient",
  "Lead on the experience of receiving it and leave the benefit unstated",
  ind="beauty", obj="seasonal", iscore=8, prio=8, conf=0.85)

C("idea_pattern.beauty.permission_to_stop.001", "Permission to do nothing", "idea_pattern", "beauty",
  "She has been told her skin needs more attention every year of her adult life.",
  "In a category built on escalating routines, permission to reduce is the most differentiated thing a brand can offer.",
  "Relief, immediate and physical.",
  "That less can be a considered choice rather than neglect.",
  "Deliberate restraint — the brand that argues for doing less.",
  "Argue for reducing the routine rather than extending it.",
  "Every competitor is arguing for more, so the argument for less is structurally unoccupied.",
  "The position is defensible because a competitor adopting it must abandon most of their range.",
  "Category growth strategy has been additive for a decade, leaving the subtractive position empty.",
  "Occupies a genuinely unclaimed position at the cost of basket size.",
  ["Brands with a focused range", "Audiences experiencing routine fatigue"],
  ["Broad ranges dependent on multi-product baskets", "Enthusiast segments"],
  "A structurally unoccupied position", "Directly conflicts with range extension",
  "Focused single-product brands", "Broad multi-step ranges",
  ["An additive frame for enthusiast segments"],
  "Arguing for less while selling a six-product set",
  "The range contradicts the message and the audience reads the range",
  "Only take this position if the range genuinely supports it",
  ind="beauty", iscore=8, prio=8, conf=0.85)

# ═══════════════════════ FOOD & BEVERAGE (20) ═══════════════════════
C("human_tension.food_beverage.small_treat_guilt.001", "The affordable indulgence and its defence", "human_tension", "food_beverage",
  "The daily coffee is the one purchase she does not need, and the one she would defend hardest.",
  "Small daily treats are defended more fiercely than large purchases because they represent autonomy rather than spending.",
  "Vindication — the feeling of a small choice being taken seriously.",
  "That the ritual is worth what it costs and does not need defending.",
  "Defended autonomy — a brand that takes a small daily choice seriously.",
  "Treat the daily purchase as a considered decision rather than an impulse.",
  "The buyer has already justified the spend to herself and resents being sold to as though impulsive.",
  "Matching the buyer's own framing removes the friction that impulse-led messaging creates.",
  "Category communication treats the purchase as impulse, which contradicts how the buyer experiences it.",
  "Aligns messaging with an existing, strongly held self-justification.",
  ["Daily-purchase food and drink", "Premium everyday categories"],
  ["Genuine impulse categories", "Bulk and stock-up purchases"],
  "Aligns with the buyer's own framing", "Slower than impulse-led messaging",
  "Daily premium coffee and food", "Bulk and impulse categories",
  ["An impulse frame for genuine impulse categories"],
  "Positioning a daily purchase as a rare indulgence",
  "Calling a daily habit rare tells the buyer the brand does not know them",
  "Treat it as the routine it is, and make the routine worth having",
  ind="food_beverage", iscore=8, prio=9, conf=0.88)

C("consumer_insight.food_beverage.provenance_scepticism.001", "Origin stories nobody checks", "consumer_insight", "food_beverage",
  "She has read the farm story on the packet and does not believe a word of it.",
  "Provenance claims have become so uniform that specificity, not sentiment, is now the only credible form.",
  "Interest — the small engagement of a fact specific enough to be checked.",
  "That this origin claim is real because it is too specific to be invented.",
  "Checkable provenance — the brand that names things a marketer would not bother to invent.",
  "State provenance through specific verifiable detail rather than through narrative.",
  "Uniform farm narratives have trained the audience to discount the whole form.",
  "A detail specific enough to verify is expensive to fake, which is what restores its credibility.",
  "Provenance storytelling has converged on the same sentimental register across the category.",
  "Restores credibility to a claim the category has exhausted.",
  ["Single-origin and provenance-led products", "Categories with a heritage claim"],
  ["Blended and multi-origin products", "Categories where origin is irrelevant"],
  "Credibility in an exhausted claim space", "Requires genuinely specific facts",
  "Single-origin food and drink", "Blended and commodity products",
  ["A taste-led frame where origin is not differentiating"],
  "A soft-focus photograph of a farmer at sunrise with no name",
  "The unnamed farmer is the category default and reads as stock imagery",
  "Name the place, the person and the year, or drop the claim",
  ind="food_beverage", iscore=8, prio=8, conf=0.87)

C("campaign_territory.food_beverage.the_regulars.001", "The people who are always there", "campaign_territory", "food_beverage",
  "She wants somewhere that feels like hers, and every new place is designed to feel like everyone's.",
  "Belonging in hospitality comes from recognising other customers, not from the décor or the menu.",
  "The particular comfort of being known without being greeted.",
  "That this place has regulars, and she could become one.",
  "Membership without a card — a place that visibly belongs to the people already in it.",
  "Build the campaign on the existing customers rather than on the offer.",
  "New customers evaluate a venue by who is already in it more than by what it serves.",
  "Existing regulars are unavailable to a competitor and cannot be replicated by design spend.",
  "Venue advertising sells the space and the menu, which every competitor can also show.",
  "Converts an existing asset into a differentiator that cannot be copied.",
  ["Independent venues with a genuine regular base", "Neighbourhood positioning"],
  ["New openings with no customer base", "Transient and tourist-led locations"],
  "Uses an asset competitors cannot copy", "Requires real regulars to exist",
  "Neighbourhood cafes and restaurants", "New openings and tourist venues",
  ["A product-led frame for a new opening with no history"],
  "Casting models as regulars in a venue that has none",
  "Real regulars are recognisable as real, and staged ones are recognisable as staged",
  "Photograph the actual customers or choose a different territory",
  ind="food_beverage", iscore=8, prio=8, conf=0.86)

C("human_tension.food_beverage.feeding_others.001", "Cooking as an unacknowledged shift", "human_tension", "food_beverage",
  "She cooks every day for people who notice only when it is missing.",
  "Everyday cooking is invisible labour, and food brands address the meal while ignoring the person making it.",
  "Being seen — the specific relief of unacknowledged effort being named.",
  "That the work of feeding people is real work worth making easier.",
  "Acknowledged effort — a brand that addresses the cook rather than the meal.",
  "Address the person doing the cooking rather than the people eating.",
  "The purchase decision belongs to the cook, and the category speaks to the eaters.",
  "Naming invisible labour is rare in the category and lands disproportionately with the actual buyer.",
  "Family food advertising shows the family enjoying the meal and never the person who made it.",
  "Speaks to the decision maker rather than to the consumer.",
  ["Family and everyday meal products", "Products bought by one person for several"],
  ["Individual consumption products", "Out-of-home and impulse categories"],
  "Addresses the actual buyer", "Loses the warmth of family imagery",
  "Family meal and staple products", "Individual and impulse consumption",
  ["A shared-enjoyment frame where the buyer is also the eater"],
  "The family at the table with the cook absent from the frame",
  "It reproduces exactly the invisibility the idea set out to name",
  "Keep the cook in the frame and make the meal secondary",
  ind="food_beverage", iscore=8, prio=8, conf=0.87)

C("idea_pattern.food_beverage.honest_constraint.001", "Sell what you ran out of", "idea_pattern", "food_beverage",
  "Every menu promises everything is available and half of it is not what she wanted anyway.",
  "Scarcity that is real and stated builds more trust than abundance that is claimed and unreliable.",
  "Urgency without pressure — the pull of something genuinely finite.",
  "That the limits are real, and so is everything else the brand says.",
  "Honest scarcity — a venue that tells you what it has run out of.",
  "State what is unavailable as prominently as what is available.",
  "A stated limit is verifiable, and the audience generalises verified statements to unverified ones.",
  "Volunteering an inconvenience is a costly signal that cheap claims cannot imitate.",
  "Hospitality communication promises full availability and routinely fails to deliver it.",
  "Builds transferable credibility at the cost of one message.",
  ["Daily-changing menus", "Genuinely limited production"],
  ["Fixed always-available ranges", "Categories where availability is guaranteed"],
  "Credibility that transfers to other claims", "Requires the scarcity to be genuine",
  "Seasonal and daily-changing food", "Fixed-range products",
  ["An abundance frame for a fixed reliable range"],
  "Manufacturing scarcity on a product that is always available",
  "Fake scarcity is detected within two visits and costs the venue its credibility",
  "Only state a limit that is actually a limit",
  ind="food_beverage", iscore=8, prio=8, conf=0.85)

C("consumer_insight.food_beverage.late_night_need.001", "The hour when nothing is open", "consumer_insight", "food_beverage",
  "At two in the morning she does not want the best food, she wants food that exists.",
  "Late-night purchase is decided entirely by availability, and quality messaging at that hour addresses a criterion nobody is using.",
  "Relief — the specific gratitude of a place being open.",
  "That this place will be there when the others are not.",
  "Dependability at an unreasonable hour — the brand defined by when rather than what.",
  "Lead with availability rather than quality when the purchase occasion is late night.",
  "At that hour the choice set is availability-limited, so quality is not a deciding variable.",
  "Owning an hour is unavailable to competitors who close, and requires no product change.",
  "Late-night operators advertise their food, competing on a criterion the occasion does not use.",
  "Aligns the message with the actual decision criterion for the occasion.",
  ["Late-night and off-hours operations", "Delivery in low-competition windows"],
  ["Peak-hour dining", "Destination restaurants chosen in advance"],
  "Matches the real decision criterion", "Says nothing about the food",
  "Late-night delivery and off-hours venues", "Destination and occasion dining",
  ["A quality-led frame for planned dining occasions"],
  "A late-night campaign showing an elaborately plated dish",
  "Nobody at that hour is choosing on presentation, so the asset speaks to no one",
  "Lead with the hours and let the food be ordinary",
  ind="food_beverage", obj="conversion", iscore=8, prio=8, conf=0.86)

C("campaign_territory.food_beverage.the_second_visit.001", "Built for coming back", "campaign_territory", "food_beverage",
  "The first visit is a decision and every visit after that is a habit she barely notices making.",
  "Venue economics run on return frequency, and almost all venue advertising is written for a first visit.",
  "Familiarity — the ease of a place that no longer requires deciding.",
  "That this is somewhere to return to rather than somewhere to try.",
  "The habit, not the trial — a brand that recruits for the second visit.",
  "Write the campaign for the returning customer rather than the first-time visitor.",
  "Profitability depends on frequency, so an acquisition-only message optimises the wrong number.",
  "Speaking to returners is rare in the category and addresses where the value actually is.",
  "Hospitality marketing is almost entirely trial-led, leaving retention unaddressed.",
  "Shifts communication towards the driver of venue profitability.",
  ["Established venues with a returning base", "Frequency-driven economics"],
  ["New openings needing trial", "Tourist and one-visit locations"],
  "Addresses the profitable behaviour", "Weak at driving first trial",
  "Established neighbourhood venues", "New openings and tourist trade",
  ["A trial-led frame for a new opening"],
  "A loyalty message aimed at people who have never visited",
  "It asks for a habit from someone who has not yet made a decision",
  "Separate the trial message from the return message and run them at different people",
  ind="food_beverage", iscore=8, prio=8, conf=0.85)

C("human_tension.food_beverage.health_compromise.001", "The choice that has to be both", "human_tension", "food_beverage",
  "She wants the food to be good for her children and to be eaten by them.",
  "Parents are optimising two variables at once, and health-led food messaging addresses only one of them.",
  "Confidence — the rare certainty of a choice that satisfies both requirements.",
  "That she does not have to choose between nutrition and it being finished.",
  "Both, not either — a brand that resolves a compromise rather than asking for one.",
  "Address the trade-off between nutrition and acceptance rather than one side of it.",
  "A product that fails either test is not bought twice, so single-variable messaging misses the real criterion.",
  "Naming the trade-off signals the brand understands the actual decision, which competitors' claims do not.",
  "Children's food splits into health messaging and fun messaging, and parents need both resolved.",
  "Addresses the compound criterion that governs repeat purchase.",
  ["Children's food and snacks", "Household purchases for reluctant consumers"],
  ["Adult self-purchase", "Indulgence categories with no health dimension"],
  "Addresses the real decision", "More complex to communicate than a single claim",
  "Children's and family food", "Adult indulgence categories",
  ["A single-claim frame where the audience is the consumer"],
  "A health claim illustrated with a child refusing the food",
  "The image proves the product fails the second test the parent is applying",
  "Show the food being eaten, and let the nutrition claim sit quietly beside it",
  ind="food_beverage", iscore=8, prio=9, conf=0.87)

C("consumer_insight.food_beverage.menu_anxiety.001", "Ordering under observation", "consumer_insight", "food_beverage",
  "She is choosing in front of other people and would rather order badly than look uncertain.",
  "Menu decisions are made under mild social pressure, which pushes diners towards familiar choices and away from the interesting ones.",
  "Ease — the small relief of an obvious right answer.",
  "That there is a safe interesting choice, and it is signposted.",
  "Removing the risk of ordering — a venue that makes the adventurous choice safe.",
  "Signpost one confident recommendation rather than presenting equal options.",
  "Choice under observation produces conservative decisions, so an unranked menu suppresses trial of the best dishes.",
  "A single clear recommendation removes the social risk that blocks the more interesting order.",
  "Menus present all dishes as equal, which pushes diners to the most familiar item.",
  "Raises average order value and trial of signature dishes.",
  ["Menus with unfamiliar or signature dishes", "Group dining"],
  ["Single-dish venues", "Menus where every item is familiar"],
  "Raises trial of signature items", "Concentrates demand on fewer dishes",
  "Restaurants with distinctive dishes", "Single-item and fast-service venues",
  ["An equal-presentation menu where every dish is familiar"],
  "Marking six dishes as the chef's recommendation",
  "Six recommendations is no recommendation and restores the original problem",
  "Recommend one, and let the rest be equal",
  ind="food_beverage", iscore=8, prio=8, conf=0.85)

C("idea_pattern.food_beverage.origin_of_the_recipe.001", "Whose recipe is it", "idea_pattern", "food_beverage",
  "She is eating a dish with a history and the menu tells her only what is in it.",
  "A dish with an attributed author is experienced as more considered than an identical dish without one.",
  "Curiosity, and the sense of eating something that came from somewhere.",
  "That the food was made by someone in particular rather than assembled to a specification.",
  "Attributed cooking — a kitchen where dishes have authors.",
  "Attribute each signature dish to the person it came from.",
  "Attribution converts a specification into a story without changing the food.",
  "The author is unavailable to a competitor even when the recipe is not.",
  "Menus describe composition, which any competitor can replicate exactly.",
  "Differentiates identical dishes at no production cost.",
  ["Venues with genuine recipe heritage", "Family and chef-led operations"],
  ["Chain operations with centralised recipes", "Venues with no attributable history"],
  "Differentiates without changing the product", "Requires a genuine attributable origin",
  "Family and chef-led restaurants", "Chain and franchise operations",
  ["A composition-led menu where no attribution is honest"],
  "Inventing a grandmother for a recipe developed by a consultant",
  "Fabricated heritage is discovered and costs more than the differentiation was worth",
  "Attribute honestly, including to the consultant if that is the truth",
  ind="food_beverage", iscore=7, prio=8, conf=0.84)

C("campaign_territory.food_beverage.the_ordinary_ingredient.001", "One thing, taken seriously", "campaign_territory", "food_beverage",
  "She is offered elaborate food and mostly wants one thing done properly.",
  "In a category competing on complexity, unusual seriousness about a common ingredient is more distinctive than novelty.",
  "Respect — the pleasure of watching something ordinary treated as though it mattered.",
  "That effort has gone somewhere she can taste rather than somewhere she can see.",
  "Depth over breadth — a brand that is obsessive about one ordinary thing.",
  "Make one ordinary ingredient the entire subject of the campaign.",
  "Complexity is the category default, so focus reads as confidence rather than as limitation.",
  "Obsessive focus is expensive to fake and immediately legible in the product.",
  "Menus compete by adding ingredients, which raises cost without raising distinctiveness.",
  "Creates distinctiveness through subtraction rather than addition.",
  ["Single-ingredient-led venues", "Brands with genuine technical depth"],
  ["Broad menus competing on variety", "Value propositions built on choice"],
  "Distinctiveness without added cost", "Narrows the addressable occasion",
  "Focused and specialist venues", "Broad-menu family restaurants",
  ["A variety-led frame where breadth is the proposition"],
  "Claiming obsession about an ingredient the kitchen buys pre-prepared",
  "The claim is disproved by the first bite and by any staff member who is asked",
  "Only claim depth where the kitchen genuinely has it",
  ind="food_beverage", iscore=8, prio=8, conf=0.86)

C("human_tension.food_beverage.dietary_exclusion.001", "The person the table works around", "human_tension", "food_beverage",
  "She has a restriction and has learned to apologise for it before anyone else has to.",
  "Diners with dietary restrictions experience eating out as an imposition on others, which shapes venue choice more than the menu does.",
  "Ease — the relief of not being an inconvenience.",
  "That her requirement is ordinary here rather than accommodated.",
  "No special arrangements — a venue where the restriction is unremarkable.",
  "Present the restricted option as an ordinary choice rather than as an accommodation.",
  "The social cost of being accommodated is what deters the visit, not the absence of options.",
  "Removing the accommodation framing is free and addresses the actual barrier.",
  "Venues signal dietary options as exceptions, which amplifies exactly the discomfort that deters the group booking.",
  "Unlocks group bookings that hinge on one person's requirement.",
  ["Venues with genuine dietary range", "Group and family dining"],
  ["Venues that cannot accommodate restrictions", "Single-diner occasions"],
  "Unlocks group decisions", "Requires the kitchen to genuinely deliver",
  "Group and family restaurants", "Specialist venues with fixed menus",
  ["An explicit accommodation frame where the range is genuinely limited"],
  "A separate menu section labelled for the restriction",
  "Separation is the accommodation framing the idea set out to remove",
  "Integrate the options into the main menu without special marking",
  ind="food_beverage", iscore=8, prio=8, conf=0.86)

C("consumer_insight.food_beverage.price_per_experience.001", "What the price is actually buying", "consumer_insight", "food_beverage",
  "She is comparing a meal to another meal when she is really choosing between an evening and a different evening.",
  "Diners evaluate expensive meals against other uses of an evening, not against cheaper meals.",
  "Anticipation — the sense of an evening rather than a transaction.",
  "That the price buys the occasion rather than the food.",
  "The evening, not the meal — a venue that sells time rather than plates.",
  "Position the price against alternative uses of the evening rather than against other restaurants.",
  "The real comparison set is other occasions, so competing on plate price argues in the wrong frame.",
  "Reframing the comparison removes the direct price competition entirely.",
  "Premium venues justify price by describing the food, which invites direct plate-for-plate comparison.",
  "Removes price comparison against cheaper direct competitors.",
  ["Premium and occasion dining", "Tasting menus and long-format meals"],
  ["Fast service and convenience", "Value-led propositions"],
  "Escapes direct price comparison", "Requires the occasion to genuinely deliver",
  "Occasion and tasting-menu dining", "Fast and value dining",
  ["A value frame where speed and price are the proposition"],
  "Justifying the price by listing the cost of the ingredients",
  "Ingredient cost invites the comparison the idea was avoiding",
  "Describe the length and shape of the evening instead",
  ind="food_beverage", pos=["premium", "luxury"], iscore=8, prio=8, conf=0.86)

C("idea_pattern.food_beverage.what_it_replaces.001", "Name what it displaces", "idea_pattern", "food_beverage",
  "She is not adding this to her life, she is choosing it instead of something else.",
  "Every food purchase displaces another, and brands that name the displaced alternative compete on a clearer basis.",
  "Decisiveness — the clarity of a straight swap.",
  "That the switch is small, specific and reversible.",
  "The explicit swap — a brand that names what it replaces.",
  "Name the specific thing the product replaces rather than the benefit it adds.",
  "Consumption is substitutive, so an additive frame misdescribes the decision the buyer is making.",
  "A named swap is easier to act on than an abstract benefit, and it competes where the choice happens.",
  "Category messaging is additive, which asks for a behaviour change nobody actually makes.",
  "Converts an abstract benefit into a specific actionable substitution.",
  ["Substitution products", "New categories entering an established habit"],
  ["Genuinely additive occasions", "Products with no obvious alternative"],
  "Matches how the decision is made", "Names a competitor by implication",
  "Substitution-led products", "Genuinely new occasions",
  ["An additive frame for a genuinely new occasion"],
  "Naming a swap the audience has no intention of making",
  "An implausible substitution makes the whole proposition unbelievable",
  "Name a swap the audience is already half considering",
  ind="food_beverage", iscore=8, prio=8, conf=0.85)

C("campaign_territory.food_beverage.made_this_morning.001", "The short distance from kitchen to table", "campaign_territory", "food_beverage",
  "She has no way of knowing when the food she is eating was made.",
  "Freshness is universally claimed and almost never specified, so a specific time is disproportionately credible.",
  "Confidence in the ordinary — knowing rather than assuming.",
  "That freshness here is a fact rather than a claim.",
  "Stated timing — a brand that puts a clock on its own product.",
  "State when the product was made rather than claiming it is fresh.",
  "A time is checkable and an adjective is not, and the category has exhausted the adjective.",
  "A specific time commits the operation to something, which is why the audience believes it.",
  "Freshness claims are universal in the category and therefore carry no information.",
  "Restores meaning to a claim the category has emptied.",
  ["Operations with genuinely short production cycles", "Bakery, prepared food and daily production"],
  ["Long-shelf-life products", "Centralised production with long distribution"],
  "Makes an exhausted claim informative", "Commits the operation to a standard",
  "Daily-production food", "Long-shelf-life and distributed products",
  ["A taste-led frame where production timing is unremarkable"],
  "Claiming daily production for a product delivered twice a week",
  "Staff and customers both know, and the claim collapses locally first",
  "State the true frequency even when it is less impressive",
  ind="food_beverage", iscore=8, prio=8, conf=0.86)

C("human_tension.food_beverage.eating_alone.001", "The table for one", "human_tension", "food_beverage",
  "She eats alone often and every restaurant is designed as though that were a temporary condition.",
  "Solo diners are a large and growing segment that the category still treats as an exception to be seated quickly.",
  "Being welcome — the difference between being served and being accommodated.",
  "That eating alone here is ordinary rather than conspicuous.",
  "The good table for one — a venue designed around solo dining rather than tolerating it.",
  "Design the proposition around eating alone rather than around groups.",
  "The segment is large, underserved and chooses venues specifically on this basis.",
  "Serving an underserved segment well is more defensible than competing for the contested one.",
  "Restaurant communication assumes groups, leaving a substantial segment addressed by nobody.",
  "Opens an underserved segment with high frequency and low competition.",
  ["Urban venues with high solo footfall", "Counter and bar service formats"],
  ["Group and celebration venues", "Family-format restaurants"],
  "An underserved high-frequency segment", "Reduces average party size",
  "Urban counter-service venues", "Group and celebration dining",
  ["A group-led frame for celebration venues"],
  "A solo dining campaign photographed from across the room",
  "The distant framing reproduces exactly the conspicuousness the idea addresses",
  "Photograph from the diner's own position, at the table",
  ind="food_beverage", iscore=8, prio=8, conf=0.85)

C("consumer_insight.food_beverage.delivery_disappointment.001", "The gap between the photo and the box", "consumer_insight", "food_beverage",
  "She has ordered from the picture enough times to have stopped believing the picture.",
  "Delivery photography sets an expectation the format cannot meet, and the resulting disappointment suppresses reorder more than any single bad meal.",
  "Trust restored — the small satisfaction of getting what was shown.",
  "That what arrives will look like what was ordered.",
  "Accurate depiction — a brand whose photograph is a promise it keeps.",
  "Photograph the food as it actually arrives rather than as it is plated in a kitchen.",
  "Reorder rate depends on expectation being met, and inflated imagery guarantees it is not.",
  "Accuracy is a differentiator precisely because the whole category has inflated its imagery.",
  "Delivery brands photograph dine-in plating, which structurally cannot survive the journey.",
  "Raises reorder rate by aligning expectation with delivery.",
  ["Delivery-first operations", "Categories with a large presentation gap"],
  ["Dine-in only venues", "Products that travel without change"],
  "Raises the number that matters in delivery", "Less arresting in a listing grid",
  "Delivery-led food", "Dine-in and destination venues",
  ["An aspirational frame for dine-in propositions"],
  "Photographing the delivery meal on a ceramic plate with garnish",
  "The customer receives a box, and the difference is the reason they do not reorder",
  "Photograph it in the packaging it arrives in",
  ind="food_beverage", ch="facebook", iscore=8, prio=9, conf=0.88)

C("idea_pattern.food_beverage.the_staff_choice.001", "What the people who work here eat", "idea_pattern", "food_beverage",
  "She wants to know what is actually good and the menu is not going to tell her.",
  "Staff consumption is the most credible recommendation a venue has and almost none of them use it.",
  "Insider access — the sense of having been let in on something.",
  "That the recommendation is honest because the recommender eats it by choice.",
  "The staff table — a venue that reveals its own preferences.",
  "Build the campaign around what the staff actually order.",
  "Staff have no incentive to misreport what they eat, which is what makes the signal credible.",
  "The signal is free, unavailable to competitors and impossible to fake convincingly.",
  "Venues recommend by margin, and customers have learned to discount the recommendation.",
  "Provides a credible recommendation mechanism at no cost.",
  ["Venues with genuine staff enthusiasm", "Independent operations"],
  ["Chains with mandated promotion", "Venues with high staff turnover"],
  "Credible and free", "Depends on staff genuinely liking the food",
  "Independent restaurants and cafes", "Chain operations with promotional targets",
  ["A chef-recommendation frame where staff opinion is not available"],
  "Presenting the highest-margin dish as the staff favourite",
  "Staff will contradict it in person, and one contradiction undoes the campaign",
  "Ask the staff and publish the answer even when it is inconvenient",
  ind="food_beverage", iscore=7, prio=8, conf=0.84)

C("campaign_territory.food_beverage.the_first_sip.001", "The moment before it is good", "campaign_territory", "food_beverage",
  "The best part of the drink is the second before it starts, and no brand has ever mentioned it.",
  "Anticipation is a larger part of the experience than consumption, and the category photographs only consumption.",
  "Anticipation itself — the pleasure of a moment about to happen.",
  "That the brand understands the experience rather than the product.",
  "The moment before — a brand that owns anticipation rather than consumption.",
  "Build the campaign on the moment before consumption rather than during it.",
  "Anticipation lasts longer than the first sip and is almost entirely unoccupied in category imagery.",
  "An unoccupied moment is ownable in a way the product shot is not.",
  "Beverage advertising has converged on the consumption moment and the pour.",
  "Occupies an unclaimed moment in a visually saturated category.",
  ["Beverage and indulgence categories", "Products with a ritual of preparation"],
  ["Functional and convenience drinks", "Categories where speed is the benefit"],
  "An unoccupied visual territory", "Does not show the product being enjoyed",
  "Coffee, tea and considered beverages", "Functional and energy drinks",
  ["A consumption frame for functional categories"],
  "Adding a slow-motion pour to the anticipation moment",
  "The pour is the category default and pulls the idea straight back into it",
  "Stop before the pour and hold there",
  ind="food_beverage", iscore=8, prio=8, conf=0.85)

C("consumer_insight.food_beverage.local_pride.001", "Pride that has nowhere to go", "consumer_insight", "food_beverage",
  "She is proud of where she is from and international brands keep telling her about somewhere else.",
  "Local pride is a strong and under-used purchase motivation in markets where imported brands dominate the premium tier.",
  "Recognition — seeing your own place treated as worth something.",
  "That local can mean best rather than cheaper.",
  "Local as premium — a brand that puts its own market at the top of the hierarchy.",
  "Position the local origin as the premium claim rather than as the affordable alternative.",
  "Local brands default to a value position, conceding the premium tier to imports without contest.",
  "The position is unavailable to an importer and directly addresses an existing sentiment.",
  "Domestic brands compete on price against imports, which cedes the more profitable tier.",
  "Opens the premium tier to a domestic brand without a product change.",
  ["Domestic brands in import-dominated markets", "Categories with local production advantage"],
  ["Imported brands", "Categories where local production is genuinely inferior"],
  "Opens a more profitable tier", "Requires the product to justify the tier",
  "Domestic premium food and drink", "Imported and value propositions",
  ["A value frame where the product cannot support a premium"],
  "Claiming premium local status while competing on price in the same asset",
  "The two claims cancel and the audience reads the price",
  "Choose the tier and let the price follow it",
  ind="food_beverage", pos=["premium", "traditional"], iscore=8, prio=8, conf=0.86)

flush()
