# -*- coding: utf-8 -*-
"""Phase 4.0 — Fashion 15, Hospitality 10, Real Estate 10, Technology 10,
Healthcare 10, Education 5."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_concept_lib import CONCEPT, flush


def C(kid, name, domain, sub, tension, insight, trigger, belief, territory,
      decision, reasoning, why, problem, impact, use, avoid, adv, lim, suit,
      unsuit, alts, app, apw, apf, ind="*", aud="*", obj="*", pos="*",
      cat="*", ch="*", examples=None, avoid_patterns=None,
      iscore=8, prio=8, conf=0.85):
    CONCEPT(kid, name, domain, sub, tension, insight, trigger, belief, territory,
            decision, reasoning, why, problem, impact,
            use=use, avoid=avoid, adv=adv, lim=lim, suit=suit, unsuit=unsuit,
            alts=alts, aps=[(app, apw, apf)], examples=examples,
            avoid_patterns=avoid_patterns, ind=ind, aud=aud, obj=obj, pos=pos,
            cat=cat, ch=ch, iscore=iscore, prio=prio, conf=conf)


F = "fashion"
# ═══════════════════ FASHION (15) ═══════════════════
C("human_tension.fashion.wardrobe_regret.001", "The clothes she does not wear", "human_tension", F,
  "Half her wardrobe was bought for a version of herself she has not been for years.",
  "Repeat apparel purchase is suppressed by the buyer's own record of buying things she never wore.",
  "Certainty — the rare confidence that this one will actually be worn.",
  "That this purchase will be used rather than stored.",
  "Wear frequency — a brand that sells how often, not how special.",
  "Sell the number of times a garment will be worn rather than the occasion it is for.",
  "The barrier is anticipated regret, and occasion-led messaging increases it by narrowing use.",
  "Frequency answers the buyer's actual objection, which specialness makes worse.",
  "Fashion messaging is occasion-led, which is exactly what produced the unworn wardrobe.",
  "Removes the dominant barrier to considered apparel purchase.",
  ["Considered and investment purchases", "Audiences with wardrobe fatigue"],
  ["Occasion wear", "Trend-led fast fashion"],
  "Addresses the real objection", "Unsuitable for genuine occasion pieces",
  "Everyday and investment apparel", "Occasion and event wear",
  ["An occasion frame for genuine event pieces"],
  "Photographing an everyday garment in a dramatic evening setting",
  "The setting narrows the garment to one occasion, restoring the regret it was meant to remove",
  "Show the garment in the ordinary situations it will actually meet",
  ind=F, iscore=9, prio=9, conf=0.88)

C("consumer_insight.fashion.dressing_for_room.001", "Dressed for the room, not the mirror", "consumer_insight", F,
  "She dresses for the specific people who will be in the room, not for an abstract sense of style.",
  "Apparel decisions are situational and social, which is why aspirational lifestyle imagery converts poorly.",
  "Preparedness — knowing you are dressed correctly for a particular room.",
  "That the brand understands the situations she actually enters.",
  "Situational dressing — a brand organised by room rather than by season.",
  "Organise the proposition around specific social situations rather than seasons or styles.",
  "The buyer selects against a known room, so a season is not a category she thinks in.",
  "Matching the buyer's own organising principle makes selection faster and returns lower.",
  "Fashion merchandising is organised by season and style, which is the seller's logic rather than the buyer's.",
  "Improves conversion and reduces returns by matching the real selection criterion.",
  ["Workwear and social apparel", "Categories with clear situational use"],
  ["Pure trend and statement pieces", "Categories with no situational anchor"],
  "Matches the buyer's own logic", "Requires knowing the audience's situations",
  "Workwear and everyday apparel", "Trend and statement fashion",
  ["A trend-led frame where novelty is the proposition"],
  "Grouping by season while claiming to be situational",
  "The merchandising contradicts the message and the buyer follows the merchandising",
  "Reorganise the range by situation or drop the claim",
  ind=F, iscore=8, prio=8, conf=0.86)

C("campaign_territory.fashion.garment_over_styling.001", "The clothes, unassisted", "campaign_territory", F,
  "She cannot tell whether she liked the garment or the styling around it.",
  "Heavy styling makes evaluation impossible, and buyers who cannot evaluate do not buy considered pieces.",
  "Clarity — being able to see the thing itself.",
  "That the garment can hold a frame without help.",
  "Unassisted product — a brand confident enough to remove the styling.",
  "Remove styling elements until only the garment is carrying the frame.",
  "Styling is a confession that the garment cannot carry attention on its own.",
  "Restraint is legible as confidence and is expensive for a weaker product to imitate.",
  "Fashion imagery adds context until the product becomes one element among many.",
  "Improves evaluability, which is the blocker on considered purchase.",
  ["Considered and investment apparel", "Brands with genuine construction quality"],
  ["Trend pieces sold on mood", "Lifestyle brands selling a world"],
  "Makes the product evaluable", "Exposes a weak product immediately",
  "Quality-led apparel", "Mood and lifestyle-led fashion",
  ["A lifestyle frame where the brand sells a world rather than a garment"],
  "Removing the props and adding an elaborate location instead",
  "The location becomes the styling, and evaluation is blocked again",
  "Reduce the setting as well as the props",
  ind=F, pos=["premium", "luxury"], iscore=8, prio=8, conf=0.86)

C("human_tension.fashion.size_anxiety.001", "The number that decides the day", "human_tension", F,
  "She has learned that the same size fits differently in every shop, and that the fault will feel like hers.",
  "Sizing inconsistency converts a practical problem into a personal judgement, which is why fit anxiety suppresses online purchase.",
  "Relief — the removal of a private verdict.",
  "That a poor fit is the garment's failure rather than hers.",
  "Fit accountability — a brand that takes responsibility for its own sizing.",
  "Make the brand accountable for fit rather than asking the buyer to select correctly.",
  "The anxiety comes from implied personal failure, which better size charts do not remove.",
  "Taking the blame is unusual, cheap, and removes the actual barrier.",
  "Category practice pushes fit responsibility onto the buyer through charts and guides.",
  "Raises online conversion and lowers the emotional cost of returns.",
  ["Online apparel", "Categories with inconsistent sizing"],
  ["Made-to-measure", "Categories with standardised fit"],
  "Removes a real conversion barrier", "Raises return handling cost",
  "Online-first apparel", "Bespoke and made-to-measure",
  ["A precision-fit frame for made-to-measure propositions"],
  "A detailed size guide presented as the solution",
  "A guide restates that getting it right is her job, which is the barrier itself",
  "State plainly that a wrong fit is the brand's problem to fix",
  ind=F, ch="website", iscore=8, prio=9, conf=0.87)

C("idea_pattern.fashion.wear_it_wrong.001", "Permission to wear it wrong", "idea_pattern", F,
  "She likes the piece and is not confident she would wear it correctly.",
  "Prescriptive styling raises the perceived competence required, which deters exactly the buyers who like the piece most.",
  "Permission — the ease of a garment with no right answer.",
  "That there is no wrong way to wear it, so there is no risk in owning it.",
  "Low-competence entry — a brand that removes the styling exam.",
  "Show the garment worn several contradictory ways rather than one correct way.",
  "A single styled look implies a standard the buyer must meet, which adds risk to the purchase.",
  "Removing the implied standard removes the risk without changing the garment.",
  "Fashion imagery presents one authoritative styling, which reads as a requirement.",
  "Widens the addressable buyer set for distinctive pieces.",
  ["Distinctive and statement pieces", "Audiences with low styling confidence"],
  ["Uniform and workwear with a correct form", "Formal categories with rules"],
  "Widens the buyer set", "Weakens a single strong brand look",
  "Distinctive everyday pieces", "Formal and uniform categories",
  ["A single authoritative look for formal categories"],
  "Three styled looks that are all clearly the same styling",
  "Near-identical options read as one option and restore the implied standard",
  "Make the alternatives genuinely contradictory",
  ind=F, iscore=8, prio=8, conf=0.85)

C("campaign_territory.fashion.made_to_last.001", "The garment that outlives the trend", "campaign_territory", F,
  "She is being sold newness by an industry that will call this piece dated within a year.",
  "Buyers increasingly resent planned obsolescence in apparel, and almost no brand competes on longevity because it suppresses repeat purchase.",
  "Trust — the unusual sense of being sold to honestly.",
  "That buying less often is something a brand would actually encourage.",
  "Longevity — the brand that argues against its own repeat purchase.",
  "Argue for keeping the garment longer rather than for replacing it sooner.",
  "The position is structurally unoccupied because it conflicts with volume, which is what makes it credible.",
  "A brand arguing against its own frequency has spent something real, and the audience reads that.",
  "Fashion messaging is built on newness, which is precisely what the audience has begun to resent.",
  "Occupies a credible unoccupied position at the cost of purchase frequency.",
  ["Quality-led and investment apparel", "Brands with genuine durability"],
  ["Fast fashion", "Trend-dependent categories"],
  "A credible unoccupied position", "Directly reduces purchase frequency",
  "Durable and investment apparel", "Fast and trend-led fashion",
  ["A newness frame where the business depends on frequency"],
  "A longevity message on a range that changes every six weeks",
  "The range disproves the claim faster than the campaign can make it",
  "Only take this position if the range is genuinely stable",
  ind=F, pos=["premium", "traditional"], iscore=8, prio=8, conf=0.86)

C("consumer_insight.fashion.second_hand_shift.001", "Bought to be resold", "consumer_insight", F,
  "She is calculating resale value at the moment of purchase, which no brand acknowledges.",
  "Resale consideration now shapes first purchase in apparel, making residual value a live purchase criterion nobody addresses.",
  "Shrewdness — the satisfaction of a purchase that holds value.",
  "That this piece is an asset rather than a cost.",
  "Residual value — a brand that acknowledges the second owner.",
  "Address the resale value of the garment as part of the purchase argument.",
  "The buyer is already performing this calculation, and no competitor is helping her with it.",
  "Acknowledging the second owner is unusual and converts a hidden criterion into a stated benefit.",
  "Brands ignore resale because it appears to cannibalise, which leaves a live criterion unaddressed.",
  "Addresses an active purchase criterion that competitors leave silent.",
  ["Premium apparel with a resale market", "Audiences who trade pieces on"],
  ["Fast fashion with no residual value", "Underwear and non-resale categories"],
  "Addresses an unspoken criterion", "Legitimises a secondary market",
  "Premium and designer apparel", "Fast fashion and non-resale categories",
  ["A pure ownership frame where no resale market exists"],
  "Claiming resale value for a garment with none",
  "Resale prices are public and the claim is disproved in one search",
  "Only make the claim where a real market exists",
  ind=F, iscore=8, prio=8, conf=0.85)

C("human_tension.fashion.occasion_pressure.001", "The event she has nothing for", "human_tension", F,
  "The invitation arrived and the wardrobe answer is no, and there are eleven days.",
  "Occasion purchase is driven by deadline and anxiety, not by desire, which makes aspirational messaging ineffective at the decisive moment.",
  "Resolution — a problem closed rather than a desire raised.",
  "That the problem is solved and she can stop thinking about it.",
  "Problem closure — a brand that ends the search rather than extending it.",
  "Frame the proposition as resolving a deadline rather than as inspiring a choice.",
  "At the decisive moment the buyer wants the search to end, and inspiration prolongs it.",
  "Matching the buyer's actual state converts far better than raising desire she already has.",
  "Occasion communication is inspiration-led, which is the wrong mode for a deadline.",
  "Improves conversion in the highest-intent apparel occasion.",
  ["Occasion and event wear", "Deadline-driven purchase"],
  ["Browsing and discovery contexts", "Wardrobe-building propositions"],
  "Converts high-intent traffic", "Ineffective for discovery",
  "Occasion wear", "Discovery and inspiration contexts",
  ["An inspiration frame for browsing contexts"],
  "An occasion campaign built around an extensive lookbook",
  "Breadth extends the search that the buyer is trying to end",
  "Offer few options and make the decision final",
  ind=F, obj="conversion", iscore=8, prio=8, conf=0.86)

C("campaign_territory.fashion.unbranded_confidence.001", "No logo, on purpose", "campaign_territory", F,
  "She wants the quality without announcing what she paid for it.",
  "A segment of premium buyers actively avoids visible branding, and most premium apparel communication assumes the opposite.",
  "Discretion — the confidence of not needing to be recognised.",
  "That quality can be private.",
  "Quiet ownership — a brand recognised by people who already know.",
  "Remove visible branding and make its absence the proposition.",
  "For this segment a logo lowers value, so branding works against the price it is meant to justify.",
  "The position is only available to brands whose construction is legible without a label.",
  "Premium apparel signals value through visible branding, alienating buyers who read that as insecurity.",
  "Opens a premium segment that logo-led communication cannot reach.",
  ["Quality-led premium apparel", "Audiences avoiding conspicuous branding"],
  ["Logo-driven streetwear", "Brands whose value is the mark itself"],
  "Reaches a discreet premium segment", "Forfeits brand recognition in the wild",
  "Quiet premium apparel", "Logo and streetwear brands",
  ["A logo-led frame where the mark carries the value"],
  "Removing the logo and replacing it with an equally visible signature detail",
  "A recognisable signature is a logo by another name for this buyer",
  "Let construction rather than any mark carry the recognition",
  ind=F, pos=["premium", "luxury"], iscore=8, prio=8, conf=0.86)

C("idea_pattern.fashion.one_garment_many_lives.001", "The same piece, five years apart", "idea_pattern", F,
  "She is shown new clothes on new people and has no evidence any of it lasts.",
  "Longevity claims are unprovable in a single image, which is why durability messaging in apparel rarely persuades.",
  "Evidence — the persuasion of something visibly survived.",
  "That the garment genuinely lasts, because she has seen it having lasted.",
  "Proof by duration — a brand that shows the same piece over time.",
  "Show one garment across a span of years rather than one season.",
  "Duration cannot be asserted convincingly and can be shown, which is the only route to a believed durability claim.",
  "The proof is expensive for a fast competitor to produce, which makes it defensible.",
  "Durability is claimed in adjectives that carry no evidence.",
  "Makes an unprovable claim demonstrable.",
  ["Durable and investment apparel", "Brands with a long-running product"],
  ["Seasonal and trend ranges", "New brands with no history"],
  "Demonstrable rather than asserted", "Requires a genuinely long-lived product",
  "Long-running apparel lines", "Seasonal and new ranges",
  ["An assertion-led frame for a new product with no history"],
  "Styling the older garment to look new",
  "Removing the wear removes the evidence, which was the whole idea",
  "Show the wear and let it be the point",
  ind=F, iscore=8, prio=8, conf=0.85)

C("consumer_insight.fashion.local_designer_doubt.001", "Doubt about the local label", "consumer_insight", F,
  "She assumes the imported piece is better made and has never checked.",
  "In import-dominated markets, domestic apparel carries an unexamined quality assumption that suppresses premium pricing.",
  "Surprise — the small correction of an assumption she did not know she held.",
  "That local can mean better made rather than cheaper.",
  "Direct comparison — a brand that invites the comparison others avoid.",
  "Invite direct comparison with the imported alternative rather than avoiding it.",
  "The assumption survives because it is never tested, and only a direct comparison tests it.",
  "Inviting comparison is a costly signal that a weaker product cannot afford to send.",
  "Domestic brands compete on price, which confirms the quality assumption rather than challenging it.",
  "Challenges the assumption blocking domestic premium pricing.",
  ["Domestic brands with genuine quality", "Import-dominated markets"],
  ["Domestic brands competing on price", "Genuinely lower-specification products"],
  "Challenges the blocking assumption", "Only safe if the comparison is winnable",
  "Domestic premium apparel", "Value-positioned domestic brands",
  ["A price-led frame where quality cannot win the comparison"],
  "Inviting comparison without making the comparison possible",
  "An invitation with no means to accept it reads as bluff",
  "Show the construction detail side by side",
  ind=F, pos="premium", iscore=8, prio=8, conf=0.85)

C("human_tension.fashion.body_change.001", "The body that changed", "human_tension", F,
  "Her size has changed and every brand she trusted now feels like it is for somebody else.",
  "Body change is a common and largely unaddressed trigger for brand switching in apparel.",
  "Being kept — the relief of not being quietly dropped.",
  "That the brand intends to stay with her rather than serve a fixed body.",
  "Continuity across change — a brand that follows the customer rather than the size.",
  "Position the brand as following the customer through change rather than serving one fixed body.",
  "The switch is triggered by feeling excluded, not by a product failure, so product messaging does not prevent it.",
  "Addressing the exclusion directly retains a customer the category loses by default.",
  "Range communication is organised around a standard body, which excludes by omission.",
  "Retains customers at the moment the category usually loses them.",
  ["Brands with genuine size range", "Categories with long customer relationships"],
  ["Single-size and sample-size ranges", "Brands unable to serve the range"],
  "Retains customers at a switching moment", "Requires the range to genuinely exist",
  "Broad-range apparel", "Narrow-range and sample-size brands",
  ["A fixed-fit frame where the range is genuinely narrow"],
  "A size-inclusivity message supported by two additional sizes",
  "The range is checked immediately and the gap between claim and stock is the story",
  "Only make the claim the stock list can support",
  ind=F, iscore=8, prio=8, conf=0.86)

C("campaign_territory.fashion.workwear_dignity.001", "Clothes for the work she actually does", "campaign_territory", F,
  "Her working day is physical and every workwear image shows someone at a desk.",
  "Workwear imagery has converged on office work, leaving most working people unrepresented by the category that serves them.",
  "Recognition — being depicted doing what you actually do.",
  "That the brand has seen the work rather than imagined it.",
  "Actual work — a brand that depicts the job accurately.",
  "Depict the specific physical work the garment is made for.",
  "Accuracy is rare in the category and is immediately legible to anyone who does the job.",
  "A depicted job is verifiable by the people who do it, which no styling can substitute for.",
  "Workwear communication defaults to an office aesthetic that most of its buyers do not occupy.",
  "Reaches an under-represented majority of the category's buyers.",
  ["Functional and trade workwear", "Brands serving physical occupations"],
  ["Office and corporate apparel", "Fashion-led interpretations of workwear"],
  "Reaches the actual buyer", "Narrows the aspirational appeal",
  "Functional workwear", "Fashion workwear and corporate apparel",
  ["An aspirational frame for fashion-led workwear"],
  "Casting a model in unworn workwear on a spotless site",
  "Anyone who does the job reads it as costume within a second",
  "Photograph people who do the work, in clothes that have done it",
  ind=F, iscore=8, prio=8, conf=0.85)

C("idea_pattern.fashion.what_it_is_not.001", "Defined by refusal", "idea_pattern", F,
  "Every brand tells her what it stands for and they all stand for the same four things.",
  "Positive brand values have converged to the point of meaninglessness, while stated refusals remain distinctive.",
  "Clarity — knowing what a brand will not do is more informative than knowing what it wants.",
  "That the brand has made an actual choice.",
  "Stated refusal — a brand defined by what it declines.",
  "State what the brand refuses to make rather than what it stands for.",
  "A refusal costs revenue and is therefore informative, where a value costs nothing.",
  "The cost is what makes it credible and what makes it hard to copy.",
  "Brand values have converged on the same vocabulary across the whole category.",
  "Produces distinctiveness from a statement competitors will not make.",
  ["Brands with a genuine operating constraint", "Saturated value messaging"],
  ["Brands unwilling to forgo the refused revenue", "Broad-range operators"],
  "Distinctive and costly to copy", "Forgoes real revenue",
  "Focused brands with real constraints", "Broad-range operators",
  ["A values frame where no refusal is genuine"],
  "Refusing something the brand was never going to do anyway",
  "A costless refusal is read as posturing and damages the rest of the message",
  "Refuse something that would actually have made money",
  ind=F, iscore=8, prio=8, conf=0.85)

C("consumer_insight.fashion.gift_of_clothing.001", "Clothes as a risky gift", "consumer_insight", F,
  "He wants to buy her clothes and is certain he will get it wrong.",
  "Apparel gifting is suppressed by the giver's low confidence in size and taste, not by price.",
  "Confidence — a gift he cannot get wrong.",
  "That the risk has been removed rather than reduced.",
  "The gift that cannot fail — a brand that removes the giver's risk entirely.",
  "Remove the giver's risk of getting it wrong rather than helping them choose better.",
  "Confidence, not information, is the barrier, and guides supply information.",
  "Removing risk unlocks a purchase that no amount of guidance will.",
  "Apparel gift communication offers size guides, which restate the risk instead of removing it.",
  "Unlocks a gifting occasion the category largely forfeits.",
  ["Gifting seasons", "Categories with size and taste risk"],
  ["Self-purchase", "Accessories with no fit dimension"],
  "Unlocks a forfeited occasion", "Requires a genuinely easy exchange",
  "Apparel gifting", "Self-purchase communication",
  ["A taste-led frame for accessories with no fit risk"],
  "A gifting campaign whose main support is a detailed size chart",
  "The chart makes the risk explicit rather than removing it",
  "Lead with how easily it can be exchanged, and say it plainly",
  ind=F, obj="seasonal", iscore=8, prio=8, conf=0.85)

# ═══════════════════ HOSPITALITY (10) ═══════════════════
H = "hospitality"
C("human_tension.hospitality.arrival_uncertainty.001", "The first ninety seconds", "human_tension", H,
  "She arrives somewhere new and spends the first minute working out whether she has made a mistake.",
  "Guest satisfaction is disproportionately set at arrival, before any service has been delivered.",
  "Reassurance — the specific relief of having chosen correctly.",
  "That the choice was right, confirmed before anything else happens.",
  "The arrival — a brand that owns the moment of doubt.",
  "Build the proposition around the moment of arrival rather than the amenities.",
  "The decisive experience happens before any amenity is used, so amenity messaging arrives too late.",
  "Owning arrival is unavailable to a competitor selling a facilities list.",
  "Hospitality communication sells facilities, which are evaluated long after the impression is set.",
  "Aligns the proposition with where guest satisfaction is actually determined.",
  ["Hotels and venues with a distinctive arrival", "Properties competing on experience"],
  ["Facilities-led resorts", "Transit and functional accommodation"],
  "Owns the decisive moment", "Says nothing about the facilities",
  "Boutique and experience-led hospitality", "Functional and transit accommodation",
  ["A facilities frame where the amenities genuinely differentiate"],
  "An arrival campaign photographed from behind the reception desk",
  "The staff viewpoint is not the guest's, and the anxiety being addressed is the guest's",
  "Photograph from where the guest stands, at the moment they stop",
  ind=H, iscore=8, prio=9, conf=0.87)

C("consumer_insight.hospitality.review_dependence.001", "Booked on strangers' opinions", "consumer_insight", H,
  "She trusts a stranger's review over anything the venue says about itself.",
  "Venue selection runs almost entirely on third-party review, which makes brand-authored claims structurally weak.",
  "Confirmation — the comfort of a claim she can check elsewhere.",
  "That what the venue says matches what guests say.",
  "Corroboration — a brand whose claims match its reviews.",
  "Make claims that the venue's own reviews already substantiate.",
  "Any claim the reviews contradict is discovered within one search, which costs more than the claim gained.",
  "Aligning with existing reviews turns third-party evidence into brand support at no cost.",
  "Venue marketing claims what management wishes were true rather than what guests report.",
  "Converts an uncontrolled channel into corroboration.",
  ["Review-dependent categories", "Venues with a strong existing review profile"],
  ["New venues with no reviews", "Venues with a weak review profile"],
  "Turns reviews into support", "Constrains claims to what guests already say",
  "Established hotels and restaurants", "New openings with no review base",
  ["An aspiration-led frame for a new opening"],
  "Claiming a quality the reviews consistently dispute",
  "The contradiction is one search away and it discredits every other claim",
  "Read the reviews first and claim what they already say",
  ind=H, iscore=8, prio=8, conf=0.87)

C("campaign_territory.hospitality.the_staff_who_stay.001", "The people who have been here years", "campaign_territory", H,
  "Service feels different when the person serving has been there long enough to care.",
  "Staff tenure is a strong and almost never used proxy for service quality in hospitality communication.",
  "Confidence — the sense of a place that people do not leave.",
  "That the experience is stable because the people are.",
  "Tenure — a venue that names how long its people have stayed.",
  "Make staff tenure the substance of the service claim.",
  "Tenure is verifiable, correlates with service quality, and cannot be bought quickly.",
  "A competitor cannot match it without waiting years, which makes it genuinely defensible.",
  "Service claims are made in adjectives that every competitor also uses.",
  "Converts an operational fact into a defensible service claim.",
  ["Venues with genuinely low staff turnover", "Service-led positioning"],
  ["High-turnover operations", "New venues"],
  "Verifiable and hard to copy", "Only available with genuine tenure",
  "Established service-led venues", "High-turnover and new operations",
  ["A facility-led frame where turnover is high"],
  "Featuring long-serving staff in a venue that has just rehired most of its team",
  "Guests notice the unfamiliar faces on the first visit",
  "Only claim tenure the roster actually supports",
  ind=H, iscore=8, prio=8, conf=0.86)

C("human_tension.hospitality.holiday_pressure.001", "The trip that has to be worth it", "human_tension", H,
  "She has waited a year for these days and the pressure to enjoy them is itself unenjoyable.",
  "The scarcity of leisure time turns holidays into performances, and most hospitality marketing intensifies that by promising perfection.",
  "Permission — the relief of a trip that does not have to be exceptional.",
  "That an unremarkable good time is enough.",
  "Lowered stakes — a venue that removes the pressure to make it count.",
  "Remove the pressure to make the trip exceptional rather than raising the promise.",
  "Aspiration raises the stakes on time that is already over-freighted, which increases anxiety.",
  "Lowering stakes is unoccupied in a category that competes entirely on aspiration.",
  "Travel communication escalates promises, which makes the trip harder to enjoy.",
  "Occupies an unclaimed emotional position in a saturated aspirational category.",
  ["Leisure and short-break travel", "Audiences with limited annual leave"],
  ["Once-in-a-lifetime and milestone travel", "Luxury aspiration propositions"],
  "An unoccupied emotional position", "Forfeits aspirational pull",
  "Short-break and repeat leisure", "Milestone and luxury travel",
  ["An aspirational frame for milestone occasions"],
  "Promising a relaxed break in imagery full of scheduled activity",
  "The activity contradicts the promise and restores the pressure",
  "Show unstructured time and very little happening",
  ind=H, iscore=8, prio=8, conf=0.85)

C("idea_pattern.hospitality.what_we_do_not_have.001", "The missing amenity, stated", "idea_pattern", H,
  "Every venue lists what it has and she cannot tell any of them apart.",
  "Amenity lists have converged completely, so what a venue lacks is now more informative than what it offers.",
  "Trust — the credibility of a venue that volunteers a shortcoming.",
  "That the rest of the list is accurate too.",
  "Stated absence — a venue that says what it does not have.",
  "State prominently what the venue does not offer.",
  "In converged amenity lists the absences are the only remaining information.",
  "Volunteering a shortcoming is costly and therefore believed, which lends credibility to the rest.",
  "Amenity lists are identical across competitors and carry no decision value.",
  "Restores information to a message space that has none.",
  ["Venues with a distinctive absence", "Saturated amenity messaging"],
  ["Full-service properties with no notable gaps", "Categories where absences are disqualifying"],
  "Informative where the category is not", "Deters guests who need the missing thing",
  "Boutique and focused venues", "Full-service resorts",
  ["A conventional amenity frame for full-service properties"],
  "Listing an absence nobody expected in the first place",
  "A costless absence is read as a technique and adds nothing",
  "Name an absence guests would genuinely have assumed was there",
  ind=H, iscore=8, prio=8, conf=0.85)

C("consumer_insight.hospitality.group_veto.001", "The one who decides is the one who objects", "consumer_insight", H,
  "The group booking is decided by whoever has the strongest objection, not the strongest preference.",
  "Group venue selection is veto-driven, so messaging that maximises appeal to one person loses to messaging that removes objections.",
  "Ease — the absence of anything to argue about.",
  "That nobody in the group will have a reason to say no.",
  "The unobjectionable choice — a venue that wins by having no vetoes.",
  "Remove the common objections rather than maximising the appeal.",
  "A single veto ends the booking, so appeal is capped by the least enthusiastic member.",
  "Removing objections addresses the actual decision mechanism, which appeal does not.",
  "Group-dining communication maximises appeal, which does not survive one objection.",
  "Improves conversion on group bookings, the highest-value occasion.",
  ["Group dining and events", "Bookings decided collectively"],
  ["Solo and couple dining", "Bookings with a single decision maker"],
  "Matches the real decision mechanism", "Produces a less distinctive proposition",
  "Group and event dining", "Solo and couple occasions",
  ["An appeal-led frame for single-decider occasions"],
  "A group campaign built around a highly distinctive signature dish",
  "Distinctiveness generates the objection that ends the booking",
  "Lead with range and the absence of obstacles",
  ind=H, iscore=8, prio=8, conf=0.85)

C("campaign_territory.hospitality.off_season_honesty.001", "Better when it is empty", "campaign_territory", H,
  "She travels off-season to save money and expects a worse version of the place.",
  "Off-season is sold apologetically as a discount, when for many properties it is genuinely the better experience.",
  "Discovery — the pleasure of an advantage nobody mentioned.",
  "That the quiet season is the good one rather than the cheap one.",
  "The better season — a property that argues its low season is superior.",
  "Argue that the quiet season is the better experience rather than the cheaper one.",
  "Discount framing confirms the guest's assumption that they are getting less.",
  "The argument is only available to properties where it is true, which makes it credible.",
  "Off-season communication is discount-led, which suppresses rate and confirms a worse experience.",
  "Protects rate in the low season and reframes an assumed compromise.",
  ["Seasonal properties genuinely better when quiet", "Destinations with crowding problems"],
  ["Properties dependent on seasonal weather", "Destinations where low season is genuinely worse"],
  "Protects low-season rate", "Only credible where it is true",
  "Crowded destinations with quiet seasons", "Weather-dependent properties",
  ["A discount frame where the low season is genuinely inferior"],
  "Claiming a better experience while running the deepest discount of the year",
  "The discount contradicts the claim and the guest believes the discount",
  "Hold rate if the claim is being made",
  ind=H, obj="seasonal", iscore=8, prio=8, conf=0.85)

C("human_tension.hospitality.business_traveller_time.001", "The traveller who wants to leave", "human_tension", H,
  "He is not on a trip, he is between meetings, and the hotel keeps offering him experiences.",
  "Business travellers optimise for speed of exit, and hospitality messaging sells lingering.",
  "Efficiency — the relief of a place that gets out of the way.",
  "That the stay will cost him no time beyond sleeping.",
  "Frictionless transit — a property that competes on how fast you can leave.",
  "Compete on speed of arrival and departure rather than on things to do.",
  "The guest's objective is elapsed time, so amenities read as obstacles rather than benefits.",
  "Speed is measurable and unclaimed, where experience is unmeasurable and universally claimed.",
  "Business hotel communication borrows leisure messaging, which addresses the wrong objective.",
  "Aligns the proposition with the guest's actual optimisation.",
  ["Business and transit hotels", "Properties near transport hubs"],
  ["Resort and leisure properties", "Destination hotels"],
  "Matches the guest's real objective", "Unappealing to leisure guests",
  "Business and airport hotels", "Resort and destination properties",
  ["An experience frame for leisure properties"],
  "A business hotel campaign featuring the spa and the rooftop bar",
  "It advertises time the guest does not have and does not want to spend",
  "Lead with check-in speed and how close the exit is",
  ind=H, iscore=8, prio=8, conf=0.86)

C("idea_pattern.hospitality.the_neighbourhood_not_the_room.001", "Sell the street, not the suite", "idea_pattern", H,
  "The room is where she will spend the least conscious time of the whole trip.",
  "Guests choose accommodation largely by what surrounds it, while property marketing sells the interior.",
  "Anticipation of a place rather than a room.",
  "That the stay is about where it is rather than what it contains.",
  "Location as product — a property that sells its surroundings.",
  "Make the surrounding area the subject rather than the interior.",
  "The interior is comparable across every competitor while the location is unique by definition.",
  "Location is the one attribute a competitor cannot replicate at any price.",
  "Property marketing shows rooms, which are the most interchangeable thing on offer.",
  "Shifts the proposition to the only genuinely unique attribute.",
  ["Urban and neighbourhood properties", "Locations with genuine character"],
  ["Resorts where the property is the destination", "Isolated properties"],
  "Uses the only unique attribute", "Weak where the location is unremarkable",
  "Urban boutique hotels", "Destination resorts",
  ["An interior-led frame where the property is the destination"],
  "Showing a generic street scene that could be any city",
  "A non-specific location claim is weaker than showing the room",
  "Show the specific street, named",
  ind=H, iscore=8, prio=8, conf=0.85)

C("consumer_insight.hospitality.familiar_over_best.001", "Chosen because it is known", "consumer_insight", H,
  "She returns to the same places not because they are the best but because they require no decision.",
  "Repeat venue choice is driven by decision avoidance rather than satisfaction, which conventional loyalty messaging misreads.",
  "Ease — the absence of a decision to make.",
  "That coming back is the path of least effort.",
  "Default status — a venue that becomes the automatic answer.",
  "Compete to become the default choice rather than the preferred one.",
  "Repeat visits are habitual rather than evaluative, so improving satisfaction does not increase frequency.",
  "Becoming a default is more durable than being preferred, because it survives a better competitor opening.",
  "Loyalty programmes reward frequency without addressing the habit that produces it.",
  "Targets the mechanism that actually drives repeat visits.",
  ["Frequent-visit venues", "Neighbourhood and commuter locations"],
  ["Destination and occasion venues", "One-visit tourist locations"],
  "Durable against better competitors", "Slow to establish",
  "Neighbourhood and daily venues", "Destination and occasion dining",
  ["A preference-led frame for occasion venues"],
  "A loyalty scheme that requires the guest to make a decision each visit",
  "Adding a decision works against the mechanism being used",
  "Remove steps rather than adding rewards",
  ind=H, iscore=8, prio=8, conf=0.85)

flush()
