# -*- coding: utf-8 -*-
"""Phase 4.0 — Real Estate 10, Technology 10, Healthcare 10, Education 5."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_concept_lib import CONCEPT, flush


def C(kid, name, domain, sub, tension, insight, trigger, belief, territory,
      decision, reasoning, why, problem, impact, use, avoid, adv, lim, suit,
      unsuit, alts, app, apw, apf, ind="*", aud="*", obj="*", pos="*",
      cat="*", ch="*", examples=None, avoid_patterns=None,
      iscore=8, prio=8, conf=0.85):
    CONCEPT(kid, name, domain, sub, tension, insight, trigger, belief, territory,
            decision, reasoning, why, problem, impact,
            use=use, avoid=avoid, adv=adv, lim=lim, suit=suit, unsuit=unsuit,
            alts=alts, aps=[(app, apw, apf)], examples=examples,
            avoid_patterns=avoid_patterns, ind=ind, aud=aud, obj=obj, pos=pos,
            cat=cat, ch=ch, iscore=iscore, prio=prio, conf=conf)


R = "real_estate"
# ═══════════════════ REAL ESTATE (10) ═══════════════════
C("human_tension.real_estate.render_distrust.001", "The gap between the drawing and the building", "human_tension", R,
  "She has seen what the last development actually looked like once it was finished.",
  "First-time buyers now discount developer imagery entirely, which makes better imagery a losing strategy.",
  "Relief — being shown something that cannot have been improved.",
  "That what she is shown is what will exist.",
  "Unimproved evidence — a developer who shows the thing rather than a picture of it.",
  "Show the actual built condition rather than an improved depiction of it.",
  "Every developer's imagery is idealised, so the audience discounts idealisation uniformly.",
  "An unimproved image is cheap to produce and impossible for an idealising competitor to match credibly.",
  "Development marketing competes on quality of depiction against an audience that discounts depiction.",
  "Converts scepticism into a differentiator without changing the product.",
  ["Mid-market developments", "Markets with a history of over-promised delivery"],
  ["Pre-construction with nothing built", "Luxury where aspiration is the product"],
  "Credibility in a distrusted category", "Loses aspirational appeal",
  "Mid-market residential development", "Pre-construction and luxury aspiration",
  ["A visualisation frame where nothing is yet built"],
  "An unretouched photograph of a show unit that is not representative",
  "Buyers compare it with the standard unit on viewing and the gap becomes the story",
  "Photograph a standard unit, not the show one",
  ind=R, iscore=9, prio=9, conf=0.88)

C("consumer_insight.real_estate.commute_reality.001", "The journey she will make twice a day", "consumer_insight", R,
  "The location is described in distance and she experiences it in minutes at eight in the morning.",
  "Buyers evaluate location by peak-hour journey time, while listings describe it in kilometres and landmarks.",
  "Certainty — knowing what the daily reality will actually be.",
  "That the commute has been described honestly.",
  "Honest journey time — a listing that states the real number.",
  "State the peak-hour journey time to the places buyers actually travel to.",
  "The buyer converts distance to time anyway and distrusts the conversion, so stating time removes friction.",
  "A stated time is checkable and most competitors will not state one, which makes it distinctive.",
  "Listings describe proximity in terms that hide the experience buyers care about.",
  "Removes a major source of viewing-stage disappointment and wasted viewings.",
  ["Residential sales and lettings", "Commuter-belt properties"],
  ["Prime central locations with no commute", "Holiday and second homes"],
  "Reduces wasted viewings", "Exposes an unfavourable journey",
  "Commuter residential property", "Prime central and holiday property",
  ["A landmark-proximity frame where the commute is negligible"],
  "Quoting an off-peak journey time without saying it is off-peak",
  "The buyer discovers the real number on the first viewing and distrusts everything else",
  "State the peak-hour figure and label it",
  ind=R, iscore=8, prio=9, conf=0.88)

C("campaign_territory.real_estate.the_third_year.001", "How it lives after the newness", "campaign_territory", R,
  "She is being sold the first week and will live there for a decade.",
  "Development marketing sells the moment of moving in, while buyers are increasingly asking how a building ages.",
  "Confidence in the long term rather than excitement about the short one.",
  "That the building will still be good when it is no longer new.",
  "Ageing well — a developer who talks about year three.",
  "Build the proposition around how the building performs after several years.",
  "Buyers have watched previous developments deteriorate, making longevity the live question.",
  "Almost no competitor addresses it, and the ones who can are the ones who built properly.",
  "Development communication is entirely front-loaded on the launch moment.",
  "Addresses the buyer's actual long-horizon question.",
  ["Developers with genuine build quality", "Markets with visible deterioration problems"],
  ["Speculative and short-hold investment products", "Developers without a track record"],
  "Addresses the real question", "Requires a track record to substantiate",
  "Quality-led residential development", "Speculative investment products",
  ["A launch-moment frame for investment-led products"],
  "Claiming durability with no completed building to point at",
  "An unsubstantiated longevity claim is the easiest thing in the category to disbelieve",
  "Show a building the developer completed years ago",
  ind=R, iscore=8, prio=8, conf=0.86)

C("human_tension.real_estate.decision_magnitude.001", "The largest decision she will make alone", "human_tension", R,
  "This is the biggest purchase of her life and everyone advising her is paid on completion.",
  "Property buyers are acutely aware that every party in the transaction is incentivised for it to happen.",
  "Trust — the unusual experience of advice against the sale.",
  "That someone in the process is not simply trying to close it.",
  "Disinterested advice — an agent who will tell you not to buy.",
  "Give the buyer a genuine reason not to proceed where one exists.",
  "Every other voice is aligned to completion, so a discouraging voice is structurally distinctive.",
  "Advice against the sale is costly, which is exactly why it is believed.",
  "Property communication is uniformly encouraging, which the buyer already discounts.",
  "Builds trust in a transaction where trust is the scarcest input.",
  ["Agency and brokerage", "High-value considered transactions"],
  ["Volume sales operations", "Auction and time-pressured sales"],
  "Trust in a low-trust transaction", "Costs some transactions",
  "Advisory-led agency", "Volume and auction sales",
  ["A conventional encouragement frame for auction sales"],
  "Advising against a property the agency does not have on its books",
  "Selective honesty is read as a technique the moment the pattern is visible",
  "Be willing to advise against your own listing",
  ind=R, iscore=8, prio=8, conf=0.86)

C("idea_pattern.real_estate.the_neighbours.001", "Who else lives there", "idea_pattern", R,
  "She is buying a building and will actually be living with the people in it.",
  "Buyers care intensely about who else lives in a development and no listing addresses it.",
  "Belonging — a sense of the people rather than the property.",
  "That she can picture who she will share the building with.",
  "The residents — a development described by who lives in it.",
  "Describe the community rather than the specification.",
  "Neighbours materially shape the experience of living somewhere and are entirely absent from listings.",
  "The information is genuinely useful and no competitor provides it.",
  "Listings describe fabric and specification, which buyers can compare and do not decide on.",
  "Addresses an unmet information need with high decision weight.",
  ["Developments with a distinctive resident profile", "Community-led propositions"],
  ["Investment and buy-to-let products", "Developments with no established community"],
  "Meets a real unmet need", "Risks exclusionary signalling",
  "Owner-occupier developments", "Investment products",
  ["A specification frame for investment products"],
  "Describing the residents in a way that signals who is not welcome",
  "Exclusionary signalling is both a legal risk and a reputational one",
  "Describe shared interests and rhythms rather than demographics",
  ind=R, iscore=7, prio=8, conf=0.83)

C("consumer_insight.real_estate.rent_versus_buy.001", "Renting as a decision, not a failure", "consumer_insight", R,
  "She rents and is told constantly that she is wasting money by people selling property.",
  "Long-term renters are a large segment addressed almost exclusively through shame, which suppresses engagement.",
  "Respect — being addressed as someone who made a choice.",
  "That renting is a legitimate position rather than a delayed purchase.",
  "The considered renter — a brand that treats renting as a decision.",
  "Address renters as having chosen rather than as having failed to buy.",
  "The segment is large and disengaged precisely because every message frames them as deficient.",
  "Respect is unusual in the category and unlocks engagement no incentive achieves.",
  "Property communication treats renting as a temporary failure state.",
  "Opens engagement with a large, systematically alienated segment.",
  ["Lettings and rental propositions", "Markets with long-term rental populations"],
  ["First-time buyer products", "Ownership-focused developments"],
  "Unlocks an alienated segment", "Conflicts with ownership messaging",
  "Rental and lettings", "First-time buyer products",
  ["An ownership frame for buyer-targeted products"],
  "A rental campaign whose call to action is a mortgage calculator",
  "It restates the deficiency framing the idea set out to remove",
  "Keep the proposition entirely within renting",
  ind=R, iscore=8, prio=8, conf=0.85)

C("campaign_territory.real_estate.what_the_photos_hide.001", "Shown from the position you will stand in", "campaign_territory", R,
  "Every photograph is taken from a corner she will never stand in.",
  "Property photography systematically distorts spatial understanding, and buyers have learned to expect the disappointment.",
  "Orientation — being able to understand the space before arriving.",
  "That she knows what the room is actually like.",
  "Honest spatial depiction — a listing that shows the room as experienced.",
  "Photograph rooms from the position a person actually occupies.",
  "Distortion is universal in the category, so accurate depiction is genuinely differentiating.",
  "Accuracy costs nothing and is immediately verifiable at viewing.",
  "Property photography competes on making rooms look larger, which guarantees disappointment.",
  "Reduces wasted viewings and raises trust before contact.",
  ["Residential listings", "Markets with high viewing volumes"],
  ["Genuinely large properties where accuracy flatters", "Off-plan sales"],
  "Fewer wasted viewings", "Rooms will look smaller than competitors'",
  "Residential sales and lettings", "Off-plan and pre-construction",
  ["A conventional wide depiction where the space genuinely is large"],
  "Photographing accurately and then listing an inflated area figure",
  "The two contradict each other and the figure is the checkable one",
  "Make the imagery and the stated area agree",
  ind=R, iscore=8, prio=8, conf=0.86)

C("human_tension.real_estate.family_timing.001", "The move that has to happen by September", "human_tension", R,
  "The purchase is not driven by the property, it is driven by a school term starting.",
  "Family property decisions are governed by external deadlines, which makes certainty of completion more valuable than price.",
  "Certainty — a date that will actually hold.",
  "That the timeline is real and will be met.",
  "Reliable completion — a brand that competes on certainty rather than price.",
  "Compete on certainty of the completion date rather than on price.",
  "The deadline is external and immovable, so certainty is worth more than a discount to this buyer.",
  "Certainty is rare in the category and cannot be matched by a competitor with a poor delivery record.",
  "Property marketing competes on price and specification, ignoring the constraint that actually drives the decision.",
  "Wins deadline-driven buyers without discounting.",
  ["Family purchases with fixed deadlines", "Developers with a strong delivery record"],
  ["Investment purchases with no deadline", "Developers with delivery problems"],
  "Wins without discounting", "Requires a genuine delivery record",
  "Family residential with reliable delivery", "Speculative and delayed projects",
  ["A price-led frame where delivery certainty cannot be offered"],
  "Promising a completion date the project has already missed once",
  "A missed date is public and destroys the only claim being made",
  "Only claim certainty a delivery record supports",
  ind=R, iscore=8, prio=8, conf=0.86)

C("idea_pattern.real_estate.the_one_fact.001", "The single fact that decides it", "idea_pattern", R,
  "She has read forty listings and remembers none of them.",
  "Listings present every attribute equally, so nothing is retained and comparison collapses into price.",
  "Recall — one thing that stays after the browsing stops.",
  "That this property is the one with the particular feature she remembers.",
  "The memorable fact — a listing organised around one thing.",
  "Lead every listing with the single most decisive fact about that property.",
  "Uniform presentation produces no recall, which pushes the decision to price by default.",
  "A single lead fact is retained and gives the property an identity in a uniform grid.",
  "Portal listings are structurally identical, which makes them individually unmemorable.",
  "Creates recall in a format designed to prevent it.",
  ["Portal and grid listings", "Markets with high listing volume"],
  ["Unique properties with no comparison set", "Off-market and private sales"],
  "Creates recall in a uniform format", "Requires editorial judgement per listing",
  "High-volume portal listings", "Off-market and unique properties",
  ["A full-specification frame for unique properties"],
  "Leading with the price as the single fact",
  "Price is the one attribute every listing already leads with",
  "Lead with whatever is true of this property and few others",
  ind=R, ch="facebook", iscore=8, prio=8, conf=0.85)

C("consumer_insight.real_estate.investor_versus_resident.001", "Two buyers, one listing", "consumer_insight", R,
  "The investor wants yield and the resident wants a home, and the listing is written for neither.",
  "Property listings blend investor and owner-occupier language, which weakens the appeal to both.",
  "Precision — being addressed as the kind of buyer you actually are.",
  "That this listing was written for her specifically.",
  "Single-audience listings — a brand that picks which buyer it is talking to.",
  "Write each listing for one buyer type rather than for both.",
  "The two buyers evaluate on disjoint criteria, so blended language optimises for neither.",
  "Choosing one audience raises relevance more than reaching both raises reach.",
  "Listings hedge between yield language and lifestyle language and persuade neither reader.",
  "Raises enquiry quality by addressing one buyer properly.",
  ["Mixed-market properties", "Portals serving both buyer types"],
  ["Single-market properties", "Products with only one plausible buyer"],
  "Higher relevance per listing", "Forfeits half the potential audience",
  "Mixed investor and resident markets", "Single-audience products",
  ["A blended frame where the audience genuinely is mixed"],
  "Writing for the resident and adding a yield figure at the end",
  "The yield figure signals the property is an investment and undermines the home framing",
  "Choose the buyer and remove the other's language entirely",
  ind=R, iscore=8, prio=8, conf=0.85)

T = "technology"
# ═══════════════════ TECHNOLOGY (10) ═══════════════════
C("human_tension.technology.tool_fatigue.001", "One more thing to learn", "human_tension", T,
  "She already has nine tools open and the cost of a tenth is not the price.",
  "Software adoption is blocked by learning cost and context switching, not by feature gaps or price.",
  "Relief — a tool that asks for almost nothing.",
  "That adopting this will not cost her a week.",
  "Adoption cost — a brand that competes on how little it demands.",
  "Compete on how little the tool demands rather than on what it can do.",
  "The buyer's constraint is attention, so more capability raises the barrier rather than lowering it.",
  "Competing on adoption cost is unoccupied in a category that competes entirely on capability.",
  "Software marketing enumerates features, which increases the perceived learning cost.",
  "Removes the real adoption barrier in a crowded tool market.",
  ["Team software in crowded categories", "Products competing for attention not budget"],
  ["Enterprise platforms sold on capability", "Products with no comparable alternative"],
  "Addresses the real barrier", "Under-sells genuine capability",
  "Team tools in saturated categories", "Enterprise capability platforms",
  ["A capability frame where the product is genuinely unique"],
  "A campaign claiming simplicity that opens with a feature grid",
  "The grid demonstrates the learning cost the message denies",
  "Show the one thing it does and stop",
  ind=T, iscore=8, prio=9, conf=0.87)

C("consumer_insight.technology.ai_claim_saturation.001", "Everything claims to be intelligent", "consumer_insight", T,
  "Every product she evaluated this quarter claimed the same capability in the same words.",
  "Capability claims in software have converged so completely that the claim itself now carries no information.",
  "Recognition — a brand that says something checkable.",
  "That this product does one specific thing she can verify.",
  "Specific outcome — a brand that names a result rather than a capability.",
  "State a specific outcome the product produces rather than the capability it uses.",
  "A capability is shared by every competitor while an outcome is particular to the product.",
  "An outcome is testable in a trial, which a capability claim is not.",
  "Category messaging has converged on identical capability language.",
  "Restores information to a saturated claim space.",
  ["Saturated software categories", "Products with a demonstrable outcome"],
  ["Genuinely novel capabilities", "Research and platform products"],
  "Informative where the category is not", "Narrows the perceived scope",
  "Applied software with clear outcomes", "Platform and research products",
  ["A capability frame for genuinely novel technology"],
  "Replacing one capability word with a newer capability word",
  "The new word saturates within a quarter and the problem returns",
  "Name the outcome and the conditions under which it holds",
  ind=T, iscore=9, prio=9, conf=0.88)

C("campaign_territory.technology.built_by_users.001", "Made by people who needed it", "campaign_territory", T,
  "She is buying a tool from people who have never done her job.",
  "Practitioner-built software carries credibility that no amount of user research can substitute for.",
  "Confidence — the sense of being understood without explaining.",
  "That the people who made this have had her problem.",
  "Practitioner origin — a brand built by the people who use it.",
  "Make the makers' own experience of the problem the substance of the proposition.",
  "Buyers discount claims of understanding and accept evidence of having done the job.",
  "The origin story is unavailable to a competitor who does not have it.",
  "Software marketing claims customer understanding without evidence of it.",
  "Converts a founding fact into a credibility asset.",
  ["Practitioner-founded products", "Vertical and specialist software"],
  ["Generalist platforms", "Products built by outside teams"],
  "Credible and unavailable to copy", "Only available where it is true",
  "Vertical practitioner-built software", "Generalist platform products",
  ["A capability frame where the founders are not practitioners"],
  "Claiming practitioner origin based on a single advisory hire",
  "The claim collapses on the first conversation with the team",
  "Only claim it where the founders genuinely did the job",
  ind=T, iscore=8, prio=8, conf=0.86)

C("human_tension.technology.accountability_fear.001", "The person who signs it off", "human_tension", T,
  "If the tool gets it wrong, the mistake will have her name on it.",
  "Enterprise software decisions are governed by personal career risk, which capability messaging does not address.",
  "Safety — a decision she can defend afterwards.",
  "That choosing this is defensible if it goes wrong.",
  "Defensibility — a brand that makes the buyer's decision safe to explain.",
  "Give the buyer the argument they will need if the decision is questioned.",
  "The buyer is managing personal risk, so features do not address their actual calculation.",
  "Supplying the defence is unusual and directly addresses the blocking concern.",
  "Enterprise messaging sells capability to a buyer who is managing exposure.",
  "Unblocks decisions that capability messaging cannot move.",
  ["Enterprise and regulated software", "Decisions with personal accountability"],
  ["Self-serve and individual purchase", "Low-consequence tools"],
  "Addresses the real blocker", "Slower and more conservative in tone",
  "Enterprise and regulated software", "Self-serve consumer tools",
  ["A capability frame for low-risk self-serve products"],
  "Offering reassurance without any evidence the buyer could cite",
  "Reassurance she cannot repeat to her own manager is worthless to her",
  "Give her citable evidence: certifications, audit trails, named references",
  ind=T, iscore=8, prio=9, conf=0.87)

C("idea_pattern.technology.show_the_failure.001", "Show it not working", "idea_pattern", T,
  "Every demonstration she has seen was recorded on a good day with clean data.",
  "Technical buyers discount demonstrations entirely because they know demonstrations are curated.",
  "Trust — the credibility of seeing the edges.",
  "That the product behaves reasonably when things go wrong.",
  "Honest edges — a brand that shows the failure modes.",
  "Show the product handling a failure rather than a successful case.",
  "Technical buyers evaluate on failure behaviour and are never shown it.",
  "Showing failure is costly and unavailable to a product that handles it badly.",
  "Product demonstrations are uniformly curated, which technical audiences discount entirely.",
  "Earns credibility with the audience that actually evaluates the product.",
  ["Developer and technical products", "Products with graceful failure handling"],
  ["Consumer products with no technical audience", "Products with poor failure behaviour"],
  "Credible with technical buyers", "Exposes genuine weaknesses",
  "Developer and infrastructure tools", "Consumer and non-technical products",
  ["A capability demonstration for non-technical audiences"],
  "Showing a failure the product handles perfectly and no other",
  "A staged failure is recognisable as staged and costs more than it earns",
  "Show a failure the product handles imperfectly, and say what happens next",
  ind=T, iscore=8, prio=8, conf=0.86)

C("consumer_insight.technology.switching_cost.001", "The data she cannot get out", "consumer_insight", T,
  "She would switch and everything she has built is inside the thing she wants to leave.",
  "Switching cost, not satisfaction, is what keeps software customers, and prospects know this before they buy.",
  "Freedom — the confidence of a decision that can be undone.",
  "That choosing this does not trap her.",
  "Reversibility — a brand that competes on how easily you can leave.",
  "Compete on how easily a customer can leave rather than on what keeps them.",
  "Prospects price in the risk of being trapped, so removing it lowers the barrier to entry.",
  "Guaranteeing exit is costly and therefore credible, and most competitors will not match it.",
  "Software marketing emphasises integration depth, which reads to prospects as lock-in.",
  "Lowers the barrier to adoption in a category defined by switching fear.",
  ["Products competing against entrenched incumbents", "Data-heavy tools"],
  ["Platforms whose economics depend on lock-in", "Products with no data to export"],
  "Lowers the adoption barrier", "Reduces retention leverage",
  "Challenger tools with export", "Lock-in dependent platforms",
  ["An integration-depth frame for entrenched platforms"],
  "Advertising easy export while making it a support ticket",
  "The first customer who tries publishes the discrepancy",
  "Make the export self-service before making the claim",
  ind=T, iscore=8, prio=8, conf=0.86)

C("campaign_territory.technology.small_team_advantage.001", "Four people who answer the phone", "campaign_territory", T,
  "She has spent two weeks in a support queue at a company with three thousand employees.",
  "Small size is treated as a weakness in software marketing when buyers frequently experience it as the main advantage.",
  "Access — the certainty of reaching someone who can act.",
  "That being small is why the service is better.",
  "Direct access — a brand whose size is the proposition.",
  "Present the small size as the advantage rather than compensating for it.",
  "Buyers who have been through enterprise support queues actively value direct access.",
  "Large competitors structurally cannot match it, which makes the position defensible.",
  "Small vendors imitate enterprise positioning, discarding their only structural advantage.",
  "Converts a perceived weakness into the primary differentiator.",
  ["Small vendors competing with large incumbents", "Support-sensitive categories"],
  ["Vendors requiring enterprise credibility", "Products needing scale assurance"],
  "Turns a weakness into an advantage", "Raises doubt about scale and continuity",
  "Small challenger software", "Enterprise-credibility-dependent products",
  ["An enterprise-scale frame where continuity assurance is the barrier"],
  "Claiming direct access while routing support to a ticket queue",
  "The first support request disproves the entire proposition",
  "Publish a direct route and staff it",
  ind=T, iscore=8, prio=8, conf=0.85)

C("human_tension.technology.jargon_exclusion.001", "The meeting she cannot follow", "human_tension", T,
  "The product is for her team and every page about it is written for engineers.",
  "Non-technical buyers of technical products are routinely excluded by the language, despite often holding the budget.",
  "Inclusion — being addressed as competent without being technical.",
  "That she can evaluate this without a translator.",
  "Plain address — a brand that explains itself to the budget holder.",
  "Write for the non-technical buyer who controls the budget rather than the technical evaluator.",
  "Budget authority frequently sits outside the technical team, which the language excludes.",
  "Addressing the budget holder directly is rare and reaches the actual decision maker.",
  "Technical products are marketed to evaluators rather than to buyers.",
  "Reaches the person who authorises the purchase.",
  ["Technical products with non-technical buyers", "Team and departmental software"],
  ["Developer tools bought by developers", "Products with a technical purchaser"],
  "Reaches the budget holder", "Risks appearing shallow to evaluators",
  "Departmental technical software", "Developer-purchased tools",
  ["A technical frame where the evaluator is also the buyer"],
  "Simplifying the language while keeping the same technical structure",
  "The structure is what excludes her, not only the vocabulary",
  "Reorganise around her decision rather than the product architecture",
  ind=T, iscore=8, prio=8, conf=0.85)

C("idea_pattern.technology.the_thing_it_replaces.001", "The spreadsheet it makes redundant", "idea_pattern", T,
  "She does not have a gap in her workflow, she has a spreadsheet doing this badly.",
  "New software competes against an existing workaround rather than against other vendors.",
  "Recognition — the specific relief of a familiar frustration being named.",
  "That the tool addresses the thing she is actually doing now.",
  "The named workaround — a brand that competes against the spreadsheet.",
  "Name the existing workaround the product replaces rather than the competing vendor.",
  "The real competitor is the incumbent process, which is where the buyer's attention already is.",
  "Naming the workaround demonstrates understanding no feature list conveys.",
  "Software marketing compares against other vendors, which most buyers are not evaluating.",
  "Aligns the message with the buyer's actual point of comparison.",
  ["Products replacing manual processes", "Categories with entrenched workarounds"],
  ["Genuinely new capabilities", "Head-to-head vendor competition"],
  "Matches the buyer's real comparison", "Concedes the vendor comparison",
  "Workflow and process software", "Direct vendor-replacement products",
  ["A competitive-comparison frame for head-to-head displacement"],
  "Naming a workaround the audience does not actually use",
  "A wrong workaround signals the brand has not met this buyer",
  "Name the workaround the audience will recognise immediately",
  ind=T, iscore=8, prio=8, conf=0.86)

C("consumer_insight.technology.trial_abandonment.001", "The trial she never started", "consumer_insight", T,
  "She signed up, opened it once, and never went back, and it was not the product's fault.",
  "Trial abandonment is overwhelmingly caused by the first session having no obvious first action.",
  "Momentum — the satisfaction of having done one useful thing immediately.",
  "That the tool will be useful within minutes rather than eventually.",
  "First value — a brand that promises one useful outcome in the first session.",
  "Promise one specific useful outcome achievable in the first session.",
  "Abandonment happens in the first session, so anything promised later never arrives.",
  "A first-session promise is testable immediately, which converts trial into use.",
  "Trial messaging promises long-term transformation, which the first session cannot deliver.",
  "Raises trial-to-active conversion, the decisive metric for self-serve software.",
  ["Self-serve trials", "Products with a fast first outcome"],
  ["Enterprise implementations", "Products requiring configuration before value"],
  "Raises the decisive metric", "Under-sells the full capability",
  "Self-serve software trials", "Enterprise implementation products",
  ["A capability frame for products with long implementation"],
  "Promising a first-session outcome the product cannot deliver without setup",
  "The unmet promise accelerates abandonment rather than preventing it",
  "Promise the smallest outcome the product genuinely delivers immediately",
  ind=T, ch="website", iscore=8, prio=9, conf=0.87)

HC = "healthcare"
# ═══════════════════ HEALTHCARE (10) ═══════════════════
C("human_tension.healthcare.symptom_uncertainty.001", "Not knowing whether it is serious", "human_tension", HC,
  "She does not know whether this warrants a doctor and is afraid of both answers.",
  "Health-seeking is delayed by uncertainty about whether the concern is legitimate, not by access or cost.",
  "Permission — being told the concern is worth raising.",
  "That asking is reasonable regardless of the answer.",
  "Legitimised concern — a service that makes asking easy rather than making answers dramatic.",
  "Make the act of asking feel reasonable rather than emphasising the seriousness of the condition.",
  "Delay is caused by fear of over-reacting, which severity messaging intensifies.",
  "Legitimising the question addresses the actual barrier to presentation.",
  "Health communication emphasises consequences, which raises the cost of being wrong about asking.",
  "Reduces presentation delay, which is the primary outcome driver.",
  ["Primary care and screening", "Conditions with delayed presentation"],
  ["Emergency communication requiring urgency", "Established patient management"],
  "Reduces delay", "Under-communicates genuine urgency",
  "Primary care and screening services", "Emergency and acute communication",
  ["An urgency frame for genuine emergencies"],
  "A screening campaign led by mortality statistics",
  "Fear raises avoidance in exactly the group least likely to present",
  "Make the first step small and explicitly reversible",
  ind=HC, iscore=9, prio=9, conf=0.88)

C("consumer_insight.healthcare.expertise_intimidation.001", "The questions she did not ask", "consumer_insight", HC,
  "She left the appointment with four unasked questions because there was no room to ask them.",
  "Patients routinely leave consultations without asking what they came to ask, which shapes their view of the provider more than the clinical outcome.",
  "Being heard — the specific relief of having asked everything.",
  "That her questions are expected rather than tolerated.",
  "Room to ask — a provider that makes questions normal.",
  "Make asking questions an expected part of the service rather than an interruption.",
  "Satisfaction and adherence track the sense of having been heard more than clinical outcome.",
  "Addressing it costs nothing clinically and differentiates strongly in a category where all providers claim care.",
  "Provider communication claims expertise, which raises the intimidation that suppresses questions.",
  "Improves satisfaction and adherence, both of which follow being heard.",
  ["Clinics and consultation-led services", "Long-term condition management"],
  ["Emergency care", "Automated and self-service health products"],
  "Improves adherence and satisfaction", "Requires longer appointment times",
  "Consultation-led healthcare", "Emergency and automated services",
  ["An expertise frame for emergency and acute settings"],
  "Inviting questions while advertising the shortest appointment times",
  "The two promises are incompatible and patients believe the timing",
  "Match the appointment length to the invitation",
  ind=HC, iscore=8, prio=8, conf=0.86)

C("campaign_territory.healthcare.what_happens_next.001", "Told what will actually happen", "campaign_territory", HC,
  "She is afraid of the procedure and nobody will tell her what it will be like.",
  "Procedural anxiety comes from uncertainty about the experience rather than from risk, and consent processes address only risk.",
  "Preparedness — knowing what the day will be like.",
  "That she will not be surprised by anything.",
  "The described experience — a provider that narrates the day in advance.",
  "Describe the experience of the procedure rather than its risks and benefits.",
  "Risk disclosure addresses a legal requirement, not the patient's actual anxiety.",
  "Describing the experience is free, differentiating, and directly reduces anxiety.",
  "Patient communication is dominated by consent language that does not address the fear.",
  "Reduces anxiety and non-attendance without changing clinical practice.",
  ["Elective procedures", "Services with high anxiety-driven cancellation"],
  ["Emergency intervention", "Conditions where detail increases distress"],
  "Reduces cancellation", "Longer and more detailed communication",
  "Elective and planned procedures", "Emergency and acute intervention",
  ["A reassurance-led frame where detail increases distress"],
  "Describing the experience in clinical rather than experiential terms",
  "Clinical description restates the consent form and answers the wrong question",
  "Describe what she will see, hear and feel, in order",
  ind=HC, iscore=8, prio=9, conf=0.87)

C("human_tension.healthcare.adherence_guilt.001", "The course she did not finish", "human_tension", HC,
  "She stopped taking it when she felt better and will not mention that at the next appointment.",
  "Non-adherence is under-reported because patients expect to be judged, which makes the clinical picture unreliable.",
  "Honesty made safe — the relief of being able to say it.",
  "That reporting a lapse is useful rather than shameful.",
  "Safe disclosure — a provider that makes the truth easy to tell.",
  "Make reporting a lapse explicitly expected rather than exceptional.",
  "Judged patients under-report, and under-reporting produces the wrong clinical decision.",
  "Normalising the lapse improves data quality, which improves outcomes directly.",
  "Adherence messaging emphasises compliance, which raises the cost of admitting a lapse.",
  "Improves reporting accuracy and therefore clinical decisions.",
  ["Long-term medication management", "Conditions with known adherence problems"],
  ["Single-dose treatments", "Acute intervention"],
  "Improves clinical data quality", "Appears to condone non-adherence",
  "Chronic condition management", "Acute and single-dose treatment",
  ["A compliance frame where adherence is clinically critical and short"],
  "Asking about adherence in language that presumes compliance",
  "A presumptive question produces a presumptive answer",
  "Ask in a way that makes the lapse the expected answer",
  ind=HC, iscore=8, prio=8, conf=0.86)

C("idea_pattern.healthcare.the_smallest_first_step.001", "One step, not the whole path", "idea_pattern", HC,
  "She knows what she should change and the size of the change is why she has not started.",
  "Behaviour-change communication fails by presenting the complete change, which is exactly what prevents starting.",
  "Feasibility — a step small enough to take today.",
  "That starting is possible without committing to everything.",
  "The first step only — a service that asks for almost nothing.",
  "Ask for one small action rather than the complete behaviour change.",
  "The magnitude of the requested change is itself the barrier to starting it.",
  "A small ask converts, and conversion is what the whole programme depends on.",
  "Health behaviour campaigns present the full change, which suppresses initiation.",
  "Raises initiation rate, the gating metric for behaviour change programmes.",
  ["Behaviour change and prevention", "Programmes with low initiation"],
  ["Acute treatment requiring full adherence", "Time-critical interventions"],
  "Raises initiation", "Under-states what is ultimately required",
  "Prevention and lifestyle programmes", "Acute and time-critical treatment",
  ["A full-programme frame where partial adherence is unsafe"],
  "Presenting a small first step followed immediately by the full programme",
  "The full programme reinstates the barrier the small step removed",
  "Show only the first step and let the rest arrive later",
  ind=HC, iscore=8, prio=8, conf=0.86)

C("consumer_insight.healthcare.family_decision.001", "Deciding for someone else", "consumer_insight", HC,
  "She is choosing care for her mother and will carry the decision either way it goes.",
  "Much healthcare decision-making is done on behalf of another person, and communication addresses the patient rather than the decider.",
  "Support — the sense of not deciding alone.",
  "That she has enough to make the decision responsibly.",
  "The proxy decider — a service that addresses the person choosing.",
  "Address the family member making the decision rather than the patient receiving care.",
  "The decision maker is frequently not the patient, and their needs are different.",
  "Addressing the actual decider is rare and directly serves the person who chooses.",
  "Healthcare communication addresses patients, missing the family member who decides.",
  "Reaches the actual decision maker in a large share of cases.",
  ["Elder and paediatric care", "Services chosen by family members"],
  ["Self-directed adult care", "Services with no proxy decision"],
  "Reaches the real decider", "Can sideline patient autonomy",
  "Elder and family-mediated care", "Self-directed adult services",
  ["A patient-led frame where the patient decides"],
  "Addressing the family member in a way that excludes the patient",
  "It undermines the patient's autonomy and the family member notices",
  "Address both, with the decision framed as shared",
  ind=HC, iscore=8, prio=8, conf=0.85)

C("campaign_territory.healthcare.time_given_back.001", "The hours the illness takes", "campaign_territory", HC,
  "The condition is described in symptoms and experienced as lost days.",
  "Patients account for chronic conditions in time lost rather than in clinical measures, which is not how treatment is described.",
  "Recovery of something concrete — days rather than numbers.",
  "That treatment returns time rather than improving a measure.",
  "Time returned — a service that counts in days rather than in clinical values.",
  "Describe the benefit in time recovered rather than in clinical improvement.",
  "Patients experience the condition as lost time, so clinical measures do not describe the benefit they want.",
  "Time is the patient's own accounting unit and is immediately meaningful.",
  "Treatment communication uses clinical measures patients cannot translate.",
  "Makes the benefit legible in the patient's own terms.",
  ["Chronic condition management", "Treatments with functional benefit"],
  ["Acute and life-saving intervention", "Conditions with no functional dimension"],
  "Legible to the patient", "Less precise than a clinical measure",
  "Chronic condition treatment", "Acute and emergency care",
  ["A clinical-measure frame for specialist audiences"],
  "Converting a clinical measure into a time figure with no basis",
  "An invented figure is checked by clinicians and discredits the service",
  "Only state time recovered where evidence supports it",
  ind=HC, iscore=8, prio=8, conf=0.85)

C("human_tension.healthcare.cost_and_care.001", "Wondering what it will cost", "human_tension", HC,
  "She is worried about the treatment and equally worried about the bill, and will only admit to one.",
  "Cost anxiety in healthcare is real and largely unspoken, and providers avoid the subject entirely.",
  "Relief — knowing the number before committing.",
  "That the cost will not be a surprise.",
  "Stated cost — a provider that says the price before being asked.",
  "State costs plainly and in advance rather than leaving them to be discovered.",
  "Unstated cost produces avoidance, and avoidance produces worse outcomes.",
  "Almost no provider states cost upfront, which makes doing so strongly differentiating.",
  "Healthcare communication omits cost, leaving a major anxiety unaddressed.",
  "Reduces avoidance and improves conversion to appointment.",
  ["Private and elective healthcare", "Markets with out-of-pocket payment"],
  ["Fully funded public systems", "Emergency care"],
  "Reduces avoidance", "Invites price comparison",
  "Private and elective healthcare", "Publicly funded and emergency care",
  ["A care-quality frame where cost is not borne by the patient"],
  "Publishing a starting price that few patients actually pay",
  "The final bill contradicts the published figure and the trust is lost",
  "Publish the range most patients fall into",
  ind=HC, iscore=8, prio=8, conf=0.86)

C("idea_pattern.healthcare.who_else_has_this.001", "Not the only one", "idea_pattern", HC,
  "She assumes her condition is rarer and more embarrassing than it is.",
  "Isolation is a major barrier to seeking care, and prevalence information is both reassuring and rarely communicated.",
  "Company — the relief of being ordinary.",
  "That this is common and manageable.",
  "Ordinary condition — a service that makes the condition unremarkable.",
  "State how common the condition is rather than how serious it can become.",
  "Isolation drives avoidance, and severity messaging deepens it.",
  "Prevalence is factual, reassuring and almost never stated.",
  "Health communication emphasises severity, which increases the shame that prevents presentation.",
  "Reduces avoidance in stigmatised conditions.",
  ["Stigmatised and under-presented conditions", "Screening and early intervention"],
  ["Rare conditions where the claim would be false", "Conditions requiring urgent action"],
  "Reduces stigma-driven avoidance", "Can under-communicate seriousness",
  "Common stigmatised conditions", "Rare and urgent conditions",
  ["A severity frame where urgency genuinely matters most"],
  "Stating prevalence for a condition that is genuinely rare",
  "A false reassurance delays presentation in exactly the cases that need speed",
  "Only state prevalence where the figure is genuinely reassuring and true",
  ind=HC, iscore=8, prio=8, conf=0.86)

C("consumer_insight.healthcare.trust_transfer.001", "Recommended by someone she trusts", "consumer_insight", HC,
  "She chose the clinic because a friend went there, not because of anything the clinic said.",
  "Healthcare provider selection runs on personal referral more than any other category, which makes advertising's role indirect.",
  "Confidence in passing it on.",
  "That recommending this provider is safe.",
  "The safe referral — a provider that is easy to recommend.",
  "Make the provider easy to recommend rather than easy to choose.",
  "Referral is the dominant channel, so the target of communication is the referrer.",
  "Equipping the referrer works with the channel that actually decides.",
  "Provider marketing addresses prospective patients directly, bypassing the referral chain.",
  "Improves the channel that drives most provider selection.",
  ["Clinics and provider services", "Referral-dependent categories"],
  ["Emergency services chosen by proximity", "Assigned-provider systems"],
  "Works with the dominant channel", "Slower than direct acquisition",
  "Referral-driven clinics", "Emergency and assigned care",
  ["A direct-acquisition frame where referral is not the channel"],
  "A referral programme that pays the referrer",
  "Payment converts a trusted recommendation into a transaction and devalues it",
  "Make the recommendation easy to give and leave it unpaid",
  ind=HC, iscore=8, prio=8, conf=0.85)

E = "education"
# ═══════════════════ EDUCATION (5) ═══════════════════
C("human_tension.education.parent_anxiety.001", "Choosing for a child who cannot", "human_tension", E,
  "She is choosing a school for a child whose future she cannot see, and will be blamed either way.",
  "Education decisions are made under high anxiety and low feedback, which makes reassurance more valuable than outcome data.",
  "Confidence — the relief of a decision she can stand behind.",
  "That the choice is defensible whatever happens later.",
  "Defensible choice — an institution that makes the decision safe to have made.",
  "Give parents an argument for the choice rather than statistics about outcomes.",
  "Outcomes arrive years later, so the decision is made on confidence rather than evidence.",
  "Supplying the argument addresses how the decision is actually made.",
  "Education marketing leads with outcome statistics that cannot inform a decision made now.",
  "Aligns communication with the actual basis of the decision.",
  ["School and early education choice", "Long-horizon education decisions"],
  ["Vocational training with immediate outcomes", "Adult self-directed learning"],
  "Matches the real decision basis", "Less evidential than outcome data",
  "Schools and early education", "Vocational and adult learning",
  ["An outcome-data frame for short-horizon vocational training"],
  "Leading with university placement rates for a primary school",
  "The horizon is too distant to inform the decision being made now",
  "Describe what the next two years will be like",
  ind=E, iscore=8, prio=9, conf=0.86)

C("consumer_insight.education.adult_learner_shame.001", "Learning it late", "consumer_insight", E,
  "She should already know this and enrolling means admitting she does not.",
  "Adult education enrolment is blocked by the embarrassment of the gap, not by cost or time.",
  "Permission — the ease of a starting point that assumes nothing.",
  "That not knowing this is ordinary.",
  "No assumed knowledge — a provider that makes starting late unremarkable.",
  "Make the absence of prior knowledge the assumed starting position.",
  "The barrier is admission of a gap, which prerequisite language makes worse.",
  "Removing the implied deficiency addresses the actual barrier to enrolment.",
  "Course communication lists prerequisites, which confirms the learner's fear of being behind.",
  "Raises enrolment among the segment most deterred by the gap.",
  ["Adult and returner education", "Foundational and remedial courses"],
  ["Advanced and specialist courses", "Programmes with genuine prerequisites"],
  "Reaches a deterred segment", "May attract under-prepared enrolment",
  "Adult foundational learning", "Advanced specialist programmes",
  ["A prerequisite frame for genuinely advanced courses"],
  "Describing the course as suitable for beginners in the small print",
  "Placement signals it is an exception rather than the assumption",
  "Make the beginner assumption the headline",
  ind=E, iscore=8, prio=8, conf=0.85)

C("campaign_territory.education.the_teachers.001", "The people in the room", "campaign_territory", E,
  "She is choosing an institution and her child will experience four specific teachers.",
  "Education is delivered by individuals, and institutional marketing sells facilities and results instead.",
  "Confidence in people rather than in a building.",
  "That the experience depends on identifiable people who are good at it.",
  "Named teaching — an institution that shows who actually teaches.",
  "Make the teaching staff the substance of the proposition rather than the facilities.",
  "Facilities are comparable across institutions while teachers are not.",
  "Individual staff are unavailable to a competitor and are the actual product.",
  "Education marketing shows buildings and equipment, which are the most interchangeable assets.",
  "Shifts the proposition to the genuine differentiator.",
  ["Schools and colleges with strong teaching staff", "Institutions with stable staff"],
  ["Online and scaled programmes", "Institutions with high staff turnover"],
  "Uses the real differentiator", "Ties the institution to individuals",
  "Teaching-led institutions", "Scaled online programmes",
  ["A facilities frame where teaching is delivered at scale"],
  "Featuring staff who leave before the intake arrives",
  "Parents notice the absence and read it as a bait-and-switch",
  "Feature staff who are contracted for the coming year",
  ind=E, iscore=8, prio=8, conf=0.85)

C("idea_pattern.education.what_they_will_be_able_to_do.001", "Described by capability, not curriculum", "idea_pattern", E,
  "She is shown a syllabus and wants to know what her child will actually be able to do.",
  "Curricula describe content while learners and parents evaluate capability, and the two rarely map onto each other.",
  "Clarity — a concrete picture of the result.",
  "That the course produces a specific ability.",
  "Stated capability — a programme described by what the learner can do afterwards.",
  "Describe the specific capabilities a learner will have rather than the topics covered.",
  "Content lists do not translate into capability, which is what the decision is actually about.",
  "Stating capability is concrete, verifiable after the fact, and unusual in the category.",
  "Education communication describes curriculum, which nobody outside the institution can evaluate.",
  "Makes the offer evaluable to the person choosing.",
  ["Vocational and skills training", "Courses with demonstrable outcomes"],
  ["Broad academic education", "Programmes with diffuse outcomes"],
  "Evaluable by the decision maker", "Commits to a specific outcome",
  "Vocational and skills education", "Broad academic programmes",
  ["A curriculum frame for broad academic education"],
  "Listing capabilities that restate the topic names",
  "A restated topic is not a capability and the reader can tell",
  "Describe a task the learner could perform for someone else",
  ind=E, iscore=8, prio=8, conf=0.85)

C("human_tension.education.cost_versus_uncertainty.001", "Paying now for a payoff she cannot see", "human_tension", E,
  "The fee is certain and immediate and the benefit is uncertain and years away.",
  "Education purchase is an asymmetric bet, and providers respond by inflating the promised outcome rather than reducing the perceived risk.",
  "Safety — the sense of a bet that can be limited.",
  "That the risk of the decision is bounded.",
  "Bounded commitment — a provider that limits what the learner stands to lose.",
  "Reduce the size of the initial commitment rather than raising the promised return.",
  "The buyer is weighing certain cost against uncertain benefit, so a bigger promise does not help.",
  "Reducing the downside addresses the actual asymmetry the buyer is facing.",
  "Education marketing escalates outcome promises, which raises scepticism rather than confidence.",
  "Raises enrolment by addressing the structure of the decision.",
  ["Fee-paying courses", "Programmes with uncertain outcomes"],
  ["Free and subsidised education", "Programmes with guaranteed placement"],
  "Addresses the real asymmetry", "Reduces upfront revenue per learner",
  "Fee-paying adult education", "Subsidised and guaranteed-outcome programmes",
  ["An outcome-promise frame where placement is genuinely guaranteed"],
  "Offering a shorter first module that cannot be completed independently",
  "A first step that requires the rest is not a bounded commitment",
  "Make the first module genuinely useful on its own",
  ind=E, iscore=8, prio=8, conf=0.85)

flush()
