# -*- coding: utf-8 -*-
"""Phase 2.1B — editorial layouts."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_layout_lib import LAY, flush

LUX = dict(pos=["premium","luxury"])

# ══════════════ LUXURY MINIMAL ══════════════
LAY("layout.luxury_minimal.single_subject_void.001","Single subject in void","luxury_minimal",
 "Assert value by giving one object more space than it needs.",
 "Subject occupying 15 to 25 percent of frame, positioned on a third intersection, remainder held as one unbroken field.",
 ["The void","Subject","Brand mark at minimum size"],
 "Registers the emptiness, finds the subject, returns to the emptiness.",
 "The void progressively backfilled during review until the layout returns to category average.",
 "Premium layouts fill available space because empty space looks like unfinished work to a reviewer.",
 "Reduce the subject to 15 to 25 percent of frame and hold the remainder as one unbroken empty field.",
 "Space is expensive, and a brand that declines to use it demonstrates it does not need to.",
 "Concentrating the entire attention budget on one small object is what raises its perceived worth.",
 ["Luxury and premium brand assets","Objective is value perception"],
 ["Retail promotion with offer and price","Formats where chrome consumes the free space"],
 "Strongest available value signal","Carries almost no information",
 "Luxury brand and launch work","Retail and multi-message promotion",
 ["Structured grid where several messages must coexist"],
 [("Backfilling the void with a secondary product during review","Returns the layout to category average and removes the signal the space carried","The reserved field kept genuinely empty, with secondary content moved to another asset")],
 "Converts restraint into perceived value.",9,9,0.9,
 asset=["poster","product_hero"], **LUX)

LAY("layout.luxury_minimal.baseline_alignment.001","Strict baseline alignment","luxury_minimal",
 "Signal precision through alignment a viewer notices only when it is absent.",
 "Every element aligned to a shared baseline grid with optical rather than measured alignment on curved forms.",
 ["Subject","Aligned type","Brand mark"],
 "Reads without interruption; nothing snags the eye.",
 "Measured alignment applied to curved or irregular forms, which looks wrong despite being numerically correct.",
 "Luxury layouts are aligned by measurement, so curved forms appear misaligned even when the numbers are right.",
 "Align every element to a shared baseline grid, correcting optically wherever forms are curved or irregular.",
 "Perceived precision comes from optical alignment, and the eye detects optical error the ruler cannot.",
 "Optical correction removes the subtle wrongness that undermines a precision claim.",
 ["Luxury and precision-led positioning","Type-and-object compositions"],
 ["Deliberately informal or handmade positioning","Fast-turnaround promotional work"],
 "Precision that is felt rather than noticed","Slow, and requires an experienced eye",
 "Luxury and precision categories","Informal and fast-turnaround work",
 ["Measured grid alignment where forms are all rectilinear"],
 [("Aligning a curved form to the measured baseline","Appears misaligned to the eye despite being numerically correct","Optical correction applied to curved and irregular forms")],
 "Produces precision the viewer feels rather than sees.",8,8,0.87,
 **LUX)

LAY("layout.luxury_minimal.monochrome_restraint.001","Monochrome restraint layout","luxury_minimal",
 "Remove colour as a variable so form and material carry the composition.",
 "Single hue family throughout with tonal range restricted to three values, no accent colour anywhere in frame.",
 ["Form","Material","Type","Brand mark"],
 "Reads form and texture directly, unmediated by colour.",
 "One accent colour introduced for interest, which reintroduces the competing cue the restriction removed.",
 "Minimal layouts add an accent to avoid looking austere, which undoes the discipline that produced the effect.",
 "Restrict the frame to one hue family across three tonal values with no accent colour.",
 "Removing colour removes the strongest competing attention cue, leaving composition and material to be read.",
 "Three values give enough separation for hierarchy without reintroducing hue as a variable.",
 ["Editorial and material-led luxury work","Composition or texture is the subject"],
 ["Products sold on colour","Categories where colour variety is the range"],
 "Maximum focus on form and material","Loses colour as a brand cue",
 "Material-led editorial","Colour-led products",
 ["Two-value palette where one brand colour must persist"],
 [("Adding a single accent colour to relieve the monochrome","Reintroduces the cue the restriction removed, so the discipline buys nothing","Interest carried by tone and texture within one hue family")],
 "Concentrates reading on form and material.",8,8,0.86,
 **LUX)

LAY("layout.luxury_minimal.type_as_object.001","Typography as the object","luxury_minimal",
 "Let the wordmark or a single word carry the entire composition.",
 "One word or mark occupying 20 to 35 percent of frame on an unbroken ground, generous margins on every side.",
 ["The word","Ground","Supporting line at minimum size"],
 "Reads the word as a shape, then as language, then stops.",
 "A supporting line set large enough to compete, which turns the object back into a layout.",
 "Type-led luxury layouts add supporting copy until the single word stops being an object.",
 "Set one word or mark at 20 to 35 percent of frame on an unbroken ground with generous margins.",
 "At sufficient scale a word is read as a form before it is read as language, which is what makes it an object.",
 "Generous margins are what separate an object from a headline.",
 ["Wordmark-led luxury and fashion brands","Brand assertion assets"],
 ["Product communication needing the product shown","Information-carrying assets"],
 "Pure brand assertion at maximum confidence","No product exposure whatsoever",
 "Brand assertion and heritage work","Product and information assets",
 ["Type-and-image split where the product must appear"],
 [("Adding a supporting line at competing size","Converts the object back into a layout and loses the assertion","Supporting line held at minimum legible size")],
 "Turns a word into an object of brand assertion.",7,7,0.85,
 ind="fashion", **LUX)

LAY("layout.luxury_minimal.material_edge.001","Material edge composition","luxury_minimal",
 "Show only a fragment of the product so material quality carries the claim.",
 "Product cropped so 20 to 40 percent enters at one frame edge, remainder of frame empty, raking light across the material.",
 ["Material surface","Product edge","Emptiness","Brand mark"],
 "Enters at the material, travels along the edge, rests in the empty field.",
 "Cropping until the product is unidentifiable, which turns restraint into obscurity.",
 "Luxury product assets show the whole object, which invites comparison on features rather than on material.",
 "Crop the product so 20 to 40 percent enters at one frame edge with raking light across the material.",
 "Showing less shifts evaluation from feature comparison to material quality, which is where luxury competes.",
 "A recognisable fragment keeps identification while removing the invitation to compare specifications.",
 ["Luxury products with genuine material quality","Brand and atmosphere assets"],
 ["Products with poor material finish","E-commerce requiring full product view"],
 "Shifts evaluation to material quality","Loses full product identification",
 "Material-led luxury brand work","E-commerce and specification communication",
 ["Full product view where identification is the objective"],
 [("Cropping until the product cannot be identified","Restraint becomes obscurity and the asset communicates nothing","20 to 40 percent kept in frame so the form stays recognisable")],
 "Moves evaluation from features to material.",7,8,0.85,
 **LUX)

LAY("layout.luxury_minimal.asymmetric_calm.001","Asymmetric calm","luxury_minimal",
 "Hold interest in a minimal frame without introducing tension.",
 "Subject placed off-centre with margins in a two-to-one ratio, all elements aligned to one shared edge.",
 ["Subject","Larger margin","Shared alignment edge"],
 "Enters on the subject, drifts into the larger margin, settles.",
 "Margins approaching equal, which produces an off-centre placement that reads as a centring error.",
 "Minimal layouts centre by default, which is stable but leaves nothing for the eye to do.",
 "Place the subject off-centre with margins in a two-to-one ratio and align all elements to one shared edge.",
 "A decisive ratio reads as a choice, while a near-equal one reads as a failed attempt at symmetry.",
 "A shared alignment edge holds the composition together while the ratio supplies the interest.",
 ["Minimal editorial and brand work","Compositions needing interest without tension"],
 ["Authority statements requiring symmetry","Very small formats where the ratio is imperceptible"],
 "Interest without tension","Less absolute authority than symmetry",
 "Minimal editorial work","Authority statements and small formats",
 ["Exact centre placement where authority outranks interest"],
 [("Setting margins at a ratio close to one to one","Reads as a failed centring rather than a decision","A decisive two-to-one margin ratio")],
 "Sustains interest in a minimal frame.",7,7,0.85,
 **LUX)

# ══════════════ MAGAZINE COVER ══════════════
LAY("layout.magazine_cover.masthead_dominance.001","Masthead dominance","magazine_cover",
 "Establish the publication before the story on a shelf or feed.",
 "Masthead occupying the upper 15 to 20 percent at full width, subject beginning immediately beneath with partial overlap permitted.",
 ["Masthead","Cover subject","Cover lines","Issue date"],
 "Reads the masthead, drops to the subject, scans cover lines.",
 "Subject overlapping the masthead so much that the publication name becomes unreadable at shelf distance.",
 "Cover subjects are scaled up until the masthead is obscured, which loses recognition at the distance covers are chosen.",
 "Give the masthead the upper 15 to 20 percent at full width and allow only partial subject overlap.",
 "Covers are selected at distance where the masthead is the recognition cue, and the subject is only assessed afterwards.",
 "Partial overlap retains depth while keeping the name legible at the distance it must work.",
 ["Magazine and publication covers","Editorial brand assets"],
 ["Single-issue special editions where the subject is the draw","Digital-only covers with no shelf context"],
 "Recognition at shelf distance","Constrains subject scale and placement",
 "Newsstand and shelf-competitive covers","Digital-only and special editions",
 ["Subject-dominant cover where the masthead is already established"],
 [("Scaling the subject until it obscures the masthead","Loses publication recognition at the distance covers are actually chosen","Partial overlap only, with the masthead kept legible")],
 "Preserves recognition at selection distance.",8,8,0.87,
 asset="poster")

LAY("layout.magazine_cover.single_subject_gaze.001","Cover subject gaze","magazine_cover",
 "Use a single subject looking at the reader to create direct address.",
 "Subject's eyes on the upper third line, gaze at the lens, face occupying 30 to 40 percent of cover height.",
 ["Eyes","Face","Masthead","Primary cover line"],
 "Locks on the eyes, reads the masthead, scans the cover line.",
 "Gaze directed off-frame, which breaks the address and reduces the cover to an illustration.",
 "Cover portraits are directed for editorial mood, which loses the direct address that sells covers.",
 "Place the subject's eyes on the upper third line with the gaze at the lens and the face at 30 to 40 percent of height.",
 "Direct gaze is processed pre-attentively and creates address, which is what makes a cover feel aimed at the reader.",
 "Eyes on the upper third places them where the eye lands first in a portrait format.",
 ["Personality-led covers","Publications sold on people"],
 ["Object and still-life covers","Publications with an abstract editorial position"],
 "Strongest available cover address","Depends entirely on casting",
 "Personality-led editorial","Object and abstract covers",
 ["Object-led cover where no person is featured"],
 [("Directing the gaze off-frame for an editorial mood","Breaks the address and the cover becomes an illustration rather than an approach","Gaze at the lens with eyes on the upper third line")],
 "Creates direct address between cover and reader.",8,8,0.87,
 asset="poster")

LAY("layout.magazine_cover.cover_line_hierarchy.001","Cover line hierarchy","magazine_cover",
 "Rank cover lines so one clearly leads and the rest support.",
 "One primary line at twice the size of secondaries, at most four secondary lines, all left-aligned to one edge.",
 ["Primary line","Secondary lines","Masthead","Subject"],
 "Reads the primary line, scans secondaries in order, stops.",
 "More than five lines at similar size, which produces a wall of type nobody reads.",
 "Cover lines accumulate as each section demands presence, until none of them is read.",
 "Set one primary line at twice the size of secondaries and cap secondary lines at four.",
 "Cover lines compete with each other, and past five at similar weight the reader stops ranking and skips all of them.",
 "A doubled primary establishes rank instantly, which is what keeps the secondaries readable.",
 ["Multi-story covers","Newsstand-competitive publications"],
 ["Single-story special issues","Minimal editorial covers"],
 "Multiple stories remain readable","Constrains how many sections get cover presence",
 "Multi-story newsstand covers","Single-story and minimal covers",
 ["Single-line cover where one story carries the issue"],
 [("Adding a sixth and seventh cover line for section coverage","Produces a wall of type that is skipped entirely, so no section benefits","Four secondary lines maximum, with one primary at double size")],
 "Keeps multiple stories readable on one cover.",7,8,0.86,
 asset="poster")

LAY("layout.magazine_cover.full_bleed_subject.001","Full bleed cover subject","magazine_cover",
 "Remove the frame so the subject occupies the reader's whole field.",
 "Subject bleeding past every edge with masthead and lines placed only in naturally quiet regions of the image.",
 ["Subject","Masthead","Cover lines"],
 "Enters anywhere in the subject, finds the masthead, then the lines.",
 "Type placed over busy regions and rescued with scrims, which reinstates the frame the bleed removed.",
 "Bleed covers add scrims behind type, which restores the boxed frame the approach was meant to eliminate.",
 "Bleed the subject past every edge and place type only where the image is already quiet.",
 "A visible margin frames the cover as a product, while a bleed presents it as an image the reader is inside.",
 "Placing type in naturally quiet regions preserves the immersion a scrim would break.",
 ["Photography-led editorial covers","Fashion and culture publications"],
 ["Information-dense covers","Publications with many cover lines"],
 "Maximum immersion","Very limited space for cover lines",
 "Photography-led editorial","Information-dense newsstand covers",
 ["Margined cover where cover line volume is high"],
 [("Adding a scrim behind cover lines over a busy region","Reinstates the frame the bleed removed and damages the image","Lines placed only where the image is naturally quiet")],
 "Presents the cover as an image rather than a product.",7,7,0.84,
 ind="fashion", asset="poster")

LAY("layout.magazine_cover.typographic_cover.001","Typographic cover","magazine_cover",
 "Make type the entire cover when the statement outweighs any image.",
 "Type filling 70 percent or more of the cover, masthead integrated into the composition rather than sitting above it.",
 ["Statement","Masthead","Issue detail"],
 "Reads the statement as a shape, then decodes it, then finds the masthead within it.",
 "Masthead placed above the composition as a separate band, which reveals the type as an insert rather than a cover.",
 "Typographic covers place the masthead conventionally above, so the composition reads as an ad rather than a cover.",
 "Fill 70 percent or more of the cover with type and integrate the masthead into the composition itself.",
 "A typographic cover works because the whole surface is one designed object, which a separate masthead band breaks.",
 "Integration makes the masthead part of the statement rather than a label on top of it.",
 ["Statement and special issues","Publications with strong editorial positions"],
 ["Personality-led covers","Publications sold on photography"],
 "Maximum statement impact","No visual subject, no personality draw",
 "Statement and special issues","Personality and photography-led covers",
 ["Subject-led cover where a person or object carries the issue"],
 [("Placing the masthead in a separate band above the type composition","Reveals the type as an insert and the cover loses its integrity as one object","Masthead integrated into the typographic composition")],
 "Makes the whole cover one designed statement.",7,7,0.84,
 asset="poster")

LAY("layout.magazine_cover.digital_thumbnail_safe.001","Thumbnail-safe cover","magazine_cover",
 "Design a cover that still works at app-icon scale.",
 "Masthead and one primary element legible at 10 percent scale, all secondary lines below that threshold accepted as lost.",
 ["Masthead","Primary element","Secondary lines"],
 "At full size reads everything; at thumbnail reads masthead and primary element only.",
 "Designing every element for thumbnail legibility, which forces all type up in scale and destroys the full-size cover.",
 "Digital covers are designed at full size and displayed as thumbnails, where nothing but the image survives.",
 "Guarantee that the masthead and one primary element stay legible at 10 percent scale.",
 "Digital covers appear far more often as thumbnails than at full size, so thumbnail legibility is the primary case.",
 "Protecting two elements rather than all of them keeps the full-size cover intact.",
 ["Digital and app-delivered publications","Covers appearing in feeds and libraries"],
 ["Print-only publications","Covers viewed only at full size"],
 "Works in the format it is mostly seen in","Secondary lines are effectively lost in thumbnails",
 "Digital-first publications","Print-only editions",
 ["Full-size-optimised cover for print-only distribution"],
 [("Scaling every cover line up for thumbnail legibility","Destroys the full-size composition to protect elements nobody reads at thumbnail anyway","Two elements protected, the rest accepted as full-size only")],
 "Works at the scale the cover is mostly seen.",7,8,0.86,
 ch="website", asset="poster")

# ══════════════ SWISS GRID ══════════════
LAY("layout.swiss_grid.modular_column_system.001","Modular column system","swiss_grid",
 "Organise complex content so structure carries the hierarchy.",
 "Twelve-column grid with consistent gutters, every element spanning whole columns, no element breaking the grid.",
 ["Structure","Primary content block","Secondary blocks","Brand mark"],
 "Scans column boundaries first, then reads within the structure they establish.",
 "One element breaking the grid for emphasis, which destroys the systematic reading the grid was providing.",
 "Complex layouts are composed by eye, so no underlying structure emerges and the reader must decode each element.",
 "Build on a twelve-column grid with consistent gutters and align every element to whole column spans.",
 "A visible system lets the reader predict where content will be, which converts decoding into scanning.",
 "Whole-column alignment is what makes the system perceptible rather than merely present.",
 ["Information-dense editorial and reports","Multi-element compositions"],
 ["Single-subject emotional work","Formats too small to sustain twelve columns"],
 "Systematic, predictable, scalable","Cold and impersonal, low emotional register",
 "Information-dense editorial","Emotional single-subject work",
 ["Free composition where the content is one element"],
 [("Breaking the grid for one emphasised element","Destroys the predictability that made the whole layout scannable","Emphasis achieved through column span and scale within the grid")],
 "Converts decoding into scanning.",8,8,0.88,
 ch="website", asset=["poster","banner"])

LAY("layout.swiss_grid.flush_left_ragged_right.001","Flush left ragged right","swiss_grid",
 "Set text so the reading edge is constant and word spacing stays even.",
 "All text flush left with a natural right rag, no justification, no hyphenation across lines.",
 ["Text block","Left reading edge","Headings"],
 "Returns to a constant left edge on every line without searching.",
 "Justified setting in narrow columns, which opens rivers of white space through the text block.",
 "Text is justified for a tidy right edge, which distorts word spacing and creates rivers in narrow columns.",
 "Set all text flush left with a natural rag and no hyphenation or justification.",
 "The eye returns to a fixed left edge on every line, and even word spacing is what keeps reading rhythm intact.",
 "A ragged right costs nothing the reader perceives, while justification costs spacing consistency.",
 ["Any substantial body text","Editorial and long-form layouts"],
 ["Formal documents where justification is mandated","Very wide measures where rivers are unlikely"],
 "Even spacing and consistent reading edge","Right edge appears untidy to some reviewers",
 "Editorial and body text","Mandated justified formats",
 ["Justified setting at wide measure with hyphenation enabled"],
 [("Justifying text in a narrow column","Opens rivers of white space that interrupt reading rhythm","Flush left with a natural rag")],
 "Preserves reading rhythm through even spacing.",8,8,0.9,
 ch="website")

LAY("layout.swiss_grid.objective_photography.001","Objective photography placement","swiss_grid",
 "Place images as information rather than as decoration.",
 "Images cropped to whole grid modules, aligned to column boundaries, with captions set directly beneath at a fixed offset.",
 ["Image","Caption","Grid alignment","Body text"],
 "Reads the image, drops to the caption immediately beneath, returns to text.",
 "Images sized to fit remaining space rather than to grid modules, which breaks the structure.",
 "Images are scaled to fill leftover space, so they read as filler rather than as content.",
 "Crop every image to whole grid modules and place captions directly beneath at a fixed offset.",
 "An image aligned to the system reads as evidence; one fitted to leftover space reads as decoration.",
 "A fixed caption offset makes the image-caption pair a single unit the eye can process together.",
 ["Documentary and editorial photography","Information-led publications"],
 ["Atmosphere-led fashion editorial","Full-bleed emotional imagery"],
 "Images read as information","Removes emotional latitude in image placement",
 "Documentary and information editorial","Atmosphere-led fashion work",
 ["Full-bleed placement where emotional impact outranks structure"],
 [("Scaling images to fill the space left over after text","Images read as filler and the grid stops being perceptible","Images cropped to whole grid modules")],
 "Makes images read as evidence, not decoration.",7,8,0.86,
 ch="website")

LAY("layout.swiss_grid.hierarchy_by_scale.001","Hierarchy by scale alone","swiss_grid",
 "Establish rank using size and weight without decoration.",
 "Three type levels separated by at least a 1.5 ratio, no rules, boxes, colour or ornament used for emphasis.",
 ["Primary level","Secondary level","Tertiary level"],
 "Ranks the three levels instantly without needing to interpret decoration.",
 "Adding a rule or tint to reinforce a level, which introduces a second hierarchy system competing with scale.",
 "Hierarchy is reinforced with boxes, rules and colour, producing several competing systems the reader must reconcile.",
 "Use exactly three type levels separated by at least a 1.5 ratio and add no rules, boxes or colour for emphasis.",
 "One hierarchy system is read instantly; two competing systems must be reconciled before either is understood.",
 "Scale alone is unambiguous, which is why it needs no reinforcement.",
 ["Editorial and systematic layouts","Information-dense content"],
 ["Promotional work needing visual energy","Brand systems built on colour coding"],
 "Unambiguous hierarchy with no decoration","Austere, low visual energy",
 "Systematic editorial","Promotional and colour-coded systems",
 ["Colour-coded hierarchy where categories must be distinguished"],
 [("Adding a rule beneath headings to reinforce hierarchy","Introduces a second system competing with scale, which the reader must reconcile","Hierarchy carried by scale and weight alone")],
 "Delivers unambiguous hierarchy without decoration.",8,8,0.88,
 ch="website")

LAY("layout.swiss_grid.white_space_as_structure.001","White space as structural element","swiss_grid",
 "Use space rather than rules to separate content groups.",
 "Group separation set at twice the internal spacing of any group, with no dividing rules anywhere.",
 ["Content groups","Separating space","Internal spacing"],
 "Perceives groups by proximity without reading any divider.",
 "Adding rules between groups while keeping equal spacing, which makes the rules do work proximity should have done.",
 "Content groups are separated by rules while spacing stays uniform, so the rules carry structure the spacing contradicts.",
 "Set separation between groups at twice the internal spacing and remove all dividing rules.",
 "Proximity is read before any drawn element, so grouping by space is understood faster than grouping by rule.",
 "A two-to-one spacing ratio is unambiguous to the eye without requiring a drawn boundary.",
 ["Information-dense layouts","Editorial and report design"],
 ["Table-based data requiring cell boundaries","Very compressed layouts with no spare space"],
 "Structure without added elements","Requires generous space to read clearly",
 "Editorial and report layouts","Dense tabular data",
 ["Ruled separation where space is genuinely unavailable"],
 [("Adding rules between groups while keeping spacing uniform","The rules and the spacing state different structures, which the reader must reconcile","Separation carried by a two-to-one spacing ratio with no rules")],
 "Creates structure without adding elements.",8,8,0.87,
 ch="website")

LAY("layout.swiss_grid.asymmetric_grid_tension.001","Asymmetric grid","swiss_grid",
 "Introduce dynamism into a systematic layout without abandoning the system.",
 "Columns of unequal width in a fixed repeating ratio, with content aligned to the system throughout.",
 ["Wide column content","Narrow column content","Shared alignment"],
 "Reads the wide column first, then the narrow as commentary.",
 "Varying the column ratio between spreads, which removes the system and leaves only irregularity.",
 "Symmetrical grids produce even, inert layouts, and designers abandon the grid entirely to escape them.",
 "Use columns of unequal width in one fixed repeating ratio and align all content to the system.",
 "A consistent asymmetric ratio is still a system, so it supplies tension and predictability at the same time.",
 "Fixing the ratio is what separates asymmetry from irregularity.",
 ["Editorial with primary and commentary content","Publications needing structure with movement"],
 ["Equal-weight comparison content","Single-column mobile layouts"],
 "Tension within a predictable system","More complex to apply consistently",
 "Editorial with layered content","Equal-weight and single-column layouts",
 ["Symmetrical grid where content carries equal weight"],
 [("Changing the column ratio from spread to spread","Removes the system, leaving irregularity the reader cannot predict","One fixed ratio applied consistently throughout")],
 "Adds movement without abandoning structure.",7,7,0.85,
 ch="website")

# ══════════════ FASHION EDITORIAL ══════════════
LAY("layout.fashion_editorial.full_figure_negative.001","Full figure with negative space","fashion_editorial",
 "Show a garment in full while giving the figure room to assert attitude.",
 "Figure occupying 40 to 55 percent of frame height, positioned off-centre, remaining space held empty above and to one side.",
 ["Figure and stance","Garment silhouette","Negative space","Credit line"],
 "Reads the stance, travels down the garment, rests in the empty field.",
 "Cropping the figure at the ankles or wrists, which truncates the silhouette the garment depends on.",
 "Fashion assets crop tightly for intimacy, which severs the full silhouette that communicates cut and proportion.",
 "Hold the figure at 40 to 55 percent of frame height off-centre with empty space above and to one side.",
 "Garment proportion is only legible when the whole silhouette is present, and crops at joints truncate it.",
 "Negative space around the figure lets the stance read as attitude rather than as a pose in a box.",
 ["Fashion editorial and campaign work","Garments sold on cut and proportion"],
 ["Detail and fabric close-ups","Accessory categories"],
 "Full silhouette with attitude preserved","Low garment detail resolution",
 "Fashion editorial and campaigns","Detail and accessory work",
 ["Detail crop where fabric or construction is the story"],
 [("Cropping the figure at the ankles or wrists","Truncates the silhouette that communicates cut and proportion","Full figure retained within the frame")],
 "Preserves silhouette and attitude together.",8,8,0.87,
 ind="fashion", asset="poster")

LAY("layout.fashion_editorial.movement_capture.001","Movement in editorial frame","fashion_editorial",
 "Show how a garment behaves rather than how it hangs.",
 "Figure captured mid-movement with garment displaced from rest, at least one fabric element in motion blur.",
 ["Garment in motion","Figure","Direction of travel","Credit line"],
 "Follows the moving fabric, arrives at the figure, reads direction.",
 "Freezing the movement completely, which returns the image to a pose and loses the behaviour.",
 "Editorial fashion is shot in held poses, which shows shape but not the drape and weight buyers are uncertain about.",
 "Capture the figure mid-movement with the garment displaced from rest and at least one element in motion blur.",
 "Weight and drape only appear in motion, and they are the properties a remote buyer cannot otherwise assess.",
 "Retained blur proves the movement was real rather than staged as a static shape.",
 ["Fluid garments and fabrics with distinctive drape","Editorial and campaign work"],
 ["Structured tailoring where cut is the story","E-commerce requiring sharp detail"],
 "Communicates fabric behaviour","Lower detail sharpness and less control",
 "Fluid garment editorial","Structured tailoring and e-commerce",
 ["Static pose with one unpressed fold where motion is impractical"],
 [("Freezing the movement completely with high shutter speed","Returns the image to a pose and loses the behaviour it was capturing","At least one fabric element retained in motion blur")],
 "Shows garment behaviour, not just shape.",8,8,0.86,
 ind="fashion", related=["material.fabric.weight_through_fall.001"])

LAY("layout.fashion_editorial.environmental_context.001","Environmental fashion context","fashion_editorial",
 "Place a garment in a world that states who wears it.",
 "Figure occupying under a third of frame with the environment filling the remainder at equal sharpness.",
 ["Environment","Figure","Relationship between them","Credit line"],
 "Reads the environment first, finds the figure within it, connects the two.",
 "Blurring the environment heavily, which removes the context that was the entire reason for the wide frame.",
 "Environmental fashion shoots blur the background for separation, discarding the context they travelled for.",
 "Hold the figure under a third of frame and keep the environment at equal sharpness.",
 "Context communicates the wearer's world, and a blurred context communicates nothing while costing the same to produce.",
 "Equal sharpness makes the environment a subject rather than a backdrop.",
 ["Lifestyle and world-building fashion","Brands sold on a way of living"],
 ["Product-focused e-commerce","Garments needing detail resolution"],
 "Establishes the wearer's world","Very low garment detail",
 "World-building fashion editorial","Product and detail work",
 ["Tight figure framing where the garment is the subject"],
 [("Blurring the environment heavily for subject separation","Removes the context that justified the wide frame in the first place","Environment held at equal sharpness to the figure")],
 "Builds the world the garment belongs to.",7,7,0.85,
 ind="fashion")

LAY("layout.fashion_editorial.detail_crop_series.001","Detail crop series","fashion_editorial",
 "Communicate construction quality through a set of close crops.",
 "Three or four crops at identical scale showing stitch, edge, fastening and fabric, arranged on a uniform grid.",
 ["The set","Individual details","Construction evidence"],
 "Reads the set as one argument, then examines individual crops.",
 "Varying crop distance between frames, which prevents comparison and reduces the set to unrelated images.",
 "Construction detail is shown in one hero crop, which proves one point rather than establishing a standard.",
 "Show three or four details at identical crop distance on a uniform grid.",
 "Quality is a pattern rather than an instance, and a pattern needs several comparable observations.",
 "Identical crop distance is what allows the details to be read as one consistent standard.",
 ["Craft and construction-led fashion","Premium and heritage positioning"],
 ["Silhouette and styling-led work","Fast fashion where construction is not the claim"],
 "Establishes a standard rather than an instance","No silhouette or styling communication",
 "Craft-led fashion","Silhouette and styling work",
 ["Single hero detail where one feature is genuinely distinctive"],
 [("Varying crop distance across the detail set","Prevents comparison, so the set reads as unrelated images rather than one standard","Identical crop distance across every frame")],
 "Establishes construction quality as a pattern.",7,7,0.85,
 ind="fashion", pos=["premium","luxury"])

LAY("layout.fashion_editorial.group_relationship.001","Group figure relationship","fashion_editorial",
 "Show several garments while keeping the group readable as one composition.",
 "Three to five figures at consistent scale on one ground plane, with deliberate spacing and no overlap of faces.",
 ["Group as one shape","Individual figures","Garment variety","Credit line"],
 "Reads the group silhouette, then separates it into individuals.",
 "Overlapping figures so faces are obscured, which reduces the group to a crowd.",
 "Group fashion shots cluster figures for composition, obscuring faces and garments alike.",
 "Place three to five figures at consistent scale on one ground plane with no face overlapping another.",
 "A group reads as one shape first, and any obscured face converts an individual into anonymous mass.",
 "Consistent scale and clear faces keep every garment attributable to a person.",
 ["Collection and range editorial","Group and campaign photography"],
 ["Single hero garment work","Detail-led construction communication"],
 "Shows a collection as a coherent group","Individual garment detail is reduced",
 "Collection editorial","Single hero and detail work",
 ["Sequential single-figure frames where each garment needs full attention"],
 [("Overlapping figures so faces are partly obscured","Reduces the group to an anonymous crowd and the garments lose their wearers","Deliberate spacing with no face overlapping another")],
 "Keeps a collection readable as a group.",7,7,0.84,
 ind="fashion")

# ══════════════ HOSPITALITY EDITORIAL ══════════════
LAY("layout.hospitality_editorial.occupied_wide.001","Occupied wide interior","hospitality_editorial",
 "Show a venue as an experience rather than as inventory.",
 "Wide interior at seated eye height with visible occupancy in the middle distance, practicals lit and in frame.",
 ["Occupancy","Space","Light sources","Brand mark"],
 "Reads the room, finds the people, settles on the light.",
 "Photographing the room empty, which documents facilities and answers none of the questions a guest has.",
 "Venue photography is shot empty for control, producing a listing rather than an invitation.",
 "Shoot wide at seated eye height with visible occupancy in the middle distance and practicals lit.",
 "Guests book an anticipated experience, and an empty room asks them to imagine it, which they will not do.",
 "Occupancy supplies scale, atmosphere and social proof in one frame at no extra cost.",
 ["Hotel, restaurant and venue communication","Booking and visit objectives"],
 ["Property listings requiring unobstructed views","Pre-opening venues with no operation"],
 "Communicates experience and social proof","Harder to schedule, requires consent",
 "Operating venue communication","Listings and pre-opening documentation",
 ["Empty architectural framing where the space itself is the product"],
 [("Photographing the interior empty and immaculate","Documents inventory rather than experience and is interchangeable across the category","The same room occupied at its characteristic hour")],
 "Turns a room into an anticipated experience.",8,8,0.87,
 ind="hospitality", related=["photography.hospitality.characteristic_hour.001"])

LAY("layout.hospitality_editorial.detail_and_wide_pair.001","Detail and wide pairing","hospitality_editorial",
 "Establish a venue with one wide frame and one detail that carries its character.",
 "Wide establishing frame at two thirds with one detail crop at a third, sharing colour temperature and light direction.",
 ["Wide frame","Detail","Shared light","Brand mark"],
 "Reads the wide frame for context, then the detail for character.",
 "Detail shot under different light, which reads as a separate location and breaks the pairing.",
 "Venue sets mix frames shot at different hours, so the set reads as several venues rather than one.",
 "Pair a wide frame at two thirds with one detail at a third, sharing colour temperature and light direction.",
 "Context establishes where, and detail establishes character, but only if both are evidently the same place.",
 "Shared light is what proves the two frames belong to one venue at one moment.",
 ["Venue and hospitality sets","Brand and booking communication"],
 ["Single-asset placements","Menu and product documentation"],
 "Context and character in one set","Requires two frames from the same session",
 "Hospitality editorial sets","Single-asset and menu work",
 ["Single wide frame where a detail cannot be captured in the same light"],
 [("Shooting the detail at a different hour to the wide frame","Reads as a different location and the pairing stops working","Both frames captured in the same light and temperature")],
 "Establishes place and character as one venue.",7,7,0.85,
 ind="hospitality")

LAY("layout.hospitality_editorial.table_level_intimacy.001","Table level intimacy","hospitality_editorial",
 "Place the viewer at the table rather than observing it.",
 "Camera at seated eye height with a near foreground element in soft focus occupying up to a fifth of frame.",
 ["Near foreground","Table subject","Room beyond","Brand mark"],
 "Enters at the soft foreground, moves to the subject, drifts into the room.",
 "Foreground element enlarged until it obstructs the subject rather than framing it.",
 "Dining photography is shot from standing height, which places the viewer as an observer rather than a guest.",
 "Set the camera at seated eye height with a soft near foreground occupying up to a fifth of frame.",
 "Seated height is the position a guest actually occupies, and a near element supplies the obstruction real vision always has.",
 "A soft foreground implies presence at the table rather than documentation of it.",
 ["Restaurant and dining communication","Experience-led hospitality"],
 ["Menu documentation requiring clarity","Architectural interior photography"],
 "Places the viewer at the table","Costs some clarity on the subject",
 "Dining experience communication","Menu and architectural documentation",
 ["Clean overhead framing where item identification is the objective"],
 [("Enlarging the foreground until it obstructs the subject","Converts a depth cue into an obstruction and buries the subject","Foreground held under a fifth of frame and well out of focus")],
 "Places the viewer at the table as a guest.",7,7,0.85,
 ind=["hospitality","food_beverage"])

LAY("layout.hospitality_editorial.arrival_sequence.001","Arrival sequence layout","hospitality_editorial",
 "Present a venue as a journey rather than a set of rooms.",
 "Three frames in fixed order — approach, threshold, interior — each at consistent colour temperature and framing height.",
 ["Sequence order","Individual frames","Continuity of light"],
 "Reads the frames in order as an arrival rather than as separate rooms.",
 "Reordering frames for visual balance, which breaks the sequence and returns the set to a room list.",
 "Venue sets present rooms in arbitrary order, so the viewer receives inventory rather than an experience.",
 "Order three frames as approach, threshold and interior at consistent temperature and framing height.",
 "Arrival is how a guest actually encounters a venue, and sequence is what converts rooms into an experience.",
 "Fixed order plus consistent treatment makes the set read as one continuous journey.",
 ["Hotel and venue brand communication","Carousel and multi-frame formats"],
 ["Single-asset placements","Menu and facility documentation"],
 "Communicates experience rather than inventory","Requires three coordinated frames",
 "Multi-frame hospitality sets","Single-asset and facility documentation",
 ["Single hero interior where only one frame is available"],
 [("Reordering the frames for visual balance","Breaks the arrival sequence and the set reverts to a list of rooms","Fixed order of approach, threshold and interior")],
 "Converts rooms into an arrival experience.",7,7,0.84,
 ind="hospitality", ch="instagram")

LAY("layout.hospitality_editorial.staff_presence.001","Staff presence framing","hospitality_editorial",
 "Include staff so service quality is visible rather than claimed.",
 "One staff member mid-task in the middle distance at under a fifth of frame, guests or space occupying the remainder.",
 ["Space","Staff member mid-task","Guests","Brand mark"],
 "Reads the space, notices the staff member, registers service without being told.",
 "Staff posed looking at camera, which converts service evidence into a staged portrait.",
 "Service quality is asserted in copy while imagery shows empty rooms, so the claim has no support.",
 "Place one staff member mid-task in the middle distance at under a fifth of frame.",
 "Service is a behaviour, and a behaviour shown in progress is evidence where a posed portrait is not.",
 "Mid-task framing keeps the staff member incidental, which is what makes the service read as routine rather than staged.",
 ["Service-led hospitality","Categories where service is the differentiator"],
 ["Self-service formats","Venues where staff presence is not the offer"],
 "Makes service visible rather than claimed","Requires consent and adds scheduling complexity",
 "Service-led hospitality","Self-service and product-led venues",
 ["Space-only framing where service is not the differentiator"],
 [("Posing staff looking at the camera","Converts service evidence into a staged portrait, which proves nothing","Staff captured mid-task without acknowledging the camera")],
 "Makes service quality observable.",7,7,0.84,
 ind="hospitality")

flush()
