# -*- coding: utf-8 -*-
"""Phase 2.1B — advertising (testimonial, offer, announcement) + social layouts."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_layout_lib import LAY, flush

# ══════════════════ TESTIMONIAL LAYOUT ══════════════════
LAY("layout.testimonial.face_quote_pairing.001","Face and quote pairing","testimonial",
 "Attach a claim to a specific identifiable person so it carries credibility.",
 "Portrait occupying the left 40 percent at eye level, quote set in the right 60 percent, attribution directly beneath the quote.",
 ["Face","Quote","Attribution","Brand mark"],
 "Enters on the face, crosses to the quote, drops to the attribution to verify it.",
 "Attribution separated from the quote by other content, which lets the claim read as unattributed marketing copy.",
 "Testimonial assets set the quote large and the person small, which removes the credibility the format exists to borrow.",
 "Give the portrait the left 40 percent at eye level and place the attribution directly beneath the quote with no content between.",
 "A testimonial works by transferring trust from a person, and trust does not transfer from a person too small to read.",
 "Adjacency between quote and attribution is what prevents the claim from being read as brand copy.",
 ["Testimonial and review-led communication","Categories where peer proof outperforms brand claims"],
 ["Regulated categories restricting endorsement","Anonymous or aggregated review data"],
 "Borrows credibility the brand cannot assert","Depends entirely on casting and the quote's authenticity",
 "Peer-proof categories","Regulated endorsement and anonymous reviews",
 ["Aggregated rating display where individual testimony is unavailable"],
 [("Setting the quote large and the person as a small inset","Removes the human source, so the quote reads as brand copy in quotation marks","Portrait at 40 percent of frame, attribution adjacent to the quote")],
 "Transfers credibility from a person to a claim.",8,8,0.87,
 obj=["conversion","awareness"], asset=["poster","social_ad","banner"],
 related=["audience.gen_z.social_proof_mechanics.001"])

LAY("layout.testimonial.result_first.001","Result first, testimony second","testimonial",
 "Lead with visible evidence and use testimony to explain it.",
 "Upper 60 percent shows the result, lower 40 percent carries a short quote and attribution on a plain ground.",
 ["Visible result","Quote","Attribution","Brand mark"],
 "Reads the result, drops to the quote for explanation, checks attribution.",
 "Quote given more space than the result, which returns the asset to a claim without evidence.",
 "Testimonial layouts lead with words, so a sceptical viewer discounts the claim before any evidence appears.",
 "Give the visible result the upper 60 percent and hold the quote and attribution to the lower 40.",
 "Evidence seen before testimony read is evaluated on its own merits, whereas testimony first primes scepticism.",
 "Ordering evidence before explanation removes the opportunity to dismiss the claim unexamined.",
 ["Categories with visible, demonstrable results","Sceptical or informed audiences"],
 ["Purely experiential benefits with no visible result","Services with no photographable outcome"],
 "Evidence lands before scepticism engages","Requires a genuinely photographable result",
 "Demonstrable-result categories","Experiential and service categories",
 ["Face-and-quote pairing where the result cannot be shown"],
 [("Giving the quote more space than the result","Returns the asset to an unevidenced claim, which is what the format was meant to avoid","Result given the larger share, quote confined to the lower 40 percent")],
 "Places evidence ahead of scepticism.",8,8,0.86,
 obj="conversion")

LAY("layout.testimonial.multiple_voices.001","Multiple voices grid","testimonial",
 "Show breadth of endorsement where volume is the argument.",
 "Grid of four to six equal cells, each a face and one short line, identical cell size and consistent crop.",
 ["The number of voices","Individual faces","Individual lines","Aggregate claim"],
 "Registers the count first, samples two or three cells, moves on.",
 "Cells varying in size or crop, which implies some endorsements matter more and undermines the breadth claim.",
 "Multiple testimonials are stacked as a long list, which is read as one testimonial and skipped.",
 "Arrange four to six voices in equal cells with identical crop and one short line each.",
 "Breadth is communicated by simultaneous visibility, not by sequence, and a list is read sequentially or not at all.",
 "Equal cells make the count legible at a glance, which is the entire argument the layout is making.",
 ["Volume of endorsement is the proof","Review-rich categories"],
 ["Single authoritative endorsement","Categories where depth beats breadth"],
 "Communicates breadth instantly","No individual testimony gets read in full",
 "High-volume review categories","Expert or single-authority endorsement",
 ["Single face-and-quote where one endorsement carries more weight"],
 [("Varying cell size to feature the strongest quote","Implies a ranking of endorsements and breaks the breadth argument","Equal cells throughout, with the strongest quote placed first in reading order")],
 "Communicates breadth of endorsement at a glance.",7,7,0.85,
 obj="conversion", ch="website")

LAY("layout.testimonial.before_context.001","Testimony with situational context","testimonial",
 "Ground a testimonial in the situation it came from so it reads as real.",
 "Environmental portrait filling the frame, quote overlaid in a naturally quiet region, attribution at the lower edge.",
 ["Situation","Person","Quote","Attribution"],
 "Reads the environment, finds the person in it, then the quote.",
 "Quote placed over a busy region and rescued with a scrim, which signals the layout had no room for it.",
 "Studio-portrait testimonials read as staged, so the testimony inherits the staging and loses credibility.",
 "Photograph the person in the situation the testimony describes and overlay the quote in a naturally quiet region.",
 "Context is corroboration. A person shown where the claim happened is harder to dismiss than one on a seamless ground.",
 "The environment supplies verification the quote itself cannot provide.",
 ["Authenticity-led testimonial work","Local, trade and community categories"],
 ["Regulated categories requiring controlled presentation","Situations that cannot be photographed"],
 "Situational corroboration for the claim","Less control over framing and legibility",
 "Authenticity-led testimony","Regulated and controlled communication",
 ["Studio portrait where the situation is not photographable"],
 [("Adding a scrim behind the quote over a busy region","Damages the environment that supplied the corroboration","Quote placed only where the image is already quiet")],
 "Corroborates testimony with its own context.",7,7,0.84,
 ind=["hospitality","food_beverage"])

LAY("layout.testimonial.rating_summary.001","Aggregate rating summary","testimonial",
 "Present aggregated review data where individual testimony is unavailable.",
 "Large numeral occupying a third of frame height, star or bar row beneath, sample size stated at half the numeral size.",
 ["Rating numeral","Sample size","Star row","Source"],
 "Reads the numeral, drops to the sample size to weigh it, then to the source.",
 "Sample size omitted or set tiny, which makes the rating unverifiable and reads as concealment.",
 "Ratings are shown without sample size, so an informed viewer cannot judge whether the number means anything.",
 "Set the rating numeral at a third of frame height and state the sample size at no less than half that size.",
 "A rating without a denominator carries no information, and a visibly hidden denominator implies the number is weak.",
 "Prominent sample size converts a claim into a verifiable statistic.",
 ["Aggregated review and rating display","E-commerce and marketplace contexts"],
 ["Low sample sizes that weaken the claim","Categories where individual testimony is stronger"],
 "Verifiable and scannable proof","Only works with a genuinely strong sample",
 "Review-rich e-commerce","Low-volume or new products",
 ["Individual testimonial where sample size is small"],
 [("Setting sample size in small print beneath the rating","Reads as concealment, which makes an informed viewer discount the rating entirely","Sample size at no less than half the numeral height")],
 "Makes a rating verifiable rather than assertive.",7,8,0.87,
 ch="website", obj="conversion")

LAY("layout.testimonial.expert_authority.001","Expert authority layout","testimonial",
 "Borrow authority from a credentialed source rather than a peer.",
 "Portrait at three-quarter length in a professional setting, credential line set immediately beneath the name at equal weight.",
 ["Credential","Name","Portrait","Claim"],
 "Enters on the portrait, reads the name, then the credential that qualifies it.",
 "Credential set smaller than the name, which reverses the source of the authority being borrowed.",
 "Expert endorsements are treated like peer testimonials, which wastes the credential that made the expert worth using.",
 "Set the credential line at equal weight to the name and photograph the expert in their professional setting.",
 "Peer testimony borrows relatability; expert testimony borrows authority, and authority resides in the credential.",
 "Equal weight ensures the credential is read as part of the identity rather than as a footnote.",
 ["Clinical, technical and financial categories","Claims requiring qualification"],
 ["Peer-relatability categories","Youth audiences who discount institutional authority"],
 "Borrows institutional credibility","Reads as distant and less relatable",
 "Clinical and technical categories","Peer-led and youth categories",
 ["Peer testimonial where relatability outperforms authority"],
 [("Setting the credential smaller than the name","Reverses the source of authority, since the credential is what qualifies the claim","Credential and name set at equal weight")],
 "Borrows authority located in a credential.",7,7,0.85,
 ind=["technology","beauty"])

# ══════════════════ OFFER LAYOUT ══════════════════
LAY("layout.offer.price_dominant.001","Price-dominant offer layout","offer",
 "Make the price the message when price is the reason to act.",
 "Price numeral occupying 25 to 35 percent of frame area, product at half that weight, terms at the lower edge.",
 ["Price","Product","Call to action","Terms"],
 "Locks on the price, confirms the product, drops to the action.",
 "Price set as a small corner overlay, which hides the brand's strongest argument.",
 "Value-led assets borrow premium restraint and hide the price, losing the argument without gaining the premium.",
 "Set the price numeral at 25 to 35 percent of frame area with the product at half that visual weight.",
 "For value positioning the price is the proposition, and a hidden proposition reads as embarrassment about it.",
 "A confidently set price reads as a claim rather than a concession.",
 ["Value and budget positioning","Conversion objectives with a genuine price advantage"],
 ["Premium and luxury positioning","Awareness campaigns with no offer"],
 "Converts the real advantage into the message","Anchors the brand on price, making later premium moves harder",
 "Value-led conversion","Premium brand building",
 ["Bundle framing where unit price comparison is unflattering"],
 [("Placing the price as a small corner overlay on a premium-styled layout","Borrows premium codes the brand cannot support while hiding its actual advantage","Price set as a deliberate typographic element at 25 to 35 percent of frame area")],
 "Turns price from apology into proposition.",8,8,0.87,
 pos=["mass","budget"], obj="conversion",
 related=["strategy.price_visibility.mass_market.001"])

LAY("layout.offer.saving_emphasis.001","Saving-emphasis offer layout","offer",
 "Foreground the size of the discount rather than the final price.",
 "Saving figure at largest weight, original price struck through directly above, final price beneath at two thirds the saving size.",
 ["Saving","Original price","Final price","Deadline"],
 "Reads the saving, checks the struck original, confirms the final price.",
 "Original price omitted, which removes the reference that makes the saving meaningful.",
 "Discount assets show only the reduced price, so the viewer has nothing to measure the value against.",
 "Set the saving at largest weight with the struck original price directly above and the final price at two thirds that size.",
 "A saving is a comparison, and a comparison without its reference is only a number.",
 "Vertical adjacency of original and saving makes the arithmetic instant rather than inferred.",
 ["Discount and promotional campaigns","Genuine reductions from a real reference price"],
 ["Everyday-low-price positioning with no reference","Categories where reference pricing is regulated"],
 "Makes value immediately calculable","Requires a defensible reference price",
 "Time-bound promotions","Everyday-low-price and regulated pricing",
 ["Price-dominant layout where no reference price exists"],
 [("Showing only the reduced price without the original","Removes the reference, so the saving cannot be perceived as a saving","Struck original placed directly above the saving figure")],
 "Makes the size of a saving perceivable.",7,8,0.86,
 obj="conversion", pos=["mass","budget"])

LAY("layout.offer.urgency_band.001","Urgency band layout","offer",
 "Add time pressure without letting it overwhelm the offer.",
 "Deadline band occupying the lower 12 to 15 percent of frame at full contrast, offer content above it undisturbed.",
 ["Offer","Deadline band","Product","Call to action"],
 "Reads the offer, registers the band last as a closing condition.",
 "Urgency band expanded until it competes with the offer, leaving the viewer aware of pressure but unclear what is offered.",
 "Urgency is applied as a full-frame treatment, which raises anxiety without communicating what is on offer.",
 "Confine the deadline to a band occupying 12 to 15 percent of frame height at the lower edge.",
 "Urgency modifies an offer rather than replacing it, so it belongs in a subordinate position that is read last.",
 "Reading the deadline last means the offer is understood before the pressure is applied.",
 ["Time-bound promotions with a real deadline","Conversion objectives"],
 ["Evergreen offers with no genuine deadline","Premium positioning damaged by pressure tactics"],
 "Adds pressure without obscuring the offer","False urgency damages trust when detected",
 "Genuine time-bound promotions","Evergreen offers and premium positioning",
 ["Offer-only layout where no genuine deadline exists"],
 [("Expanding urgency treatment across the whole frame","Communicates pressure without communicating the offer, so nothing converts","Urgency confined to a band of 12 to 15 percent at the lower edge")],
 "Applies urgency without obscuring the offer.",7,7,0.85,
 obj="conversion")

LAY("layout.offer.bundle_value.001","Bundle value layout","offer",
 "Show a bundle so the combined value is obvious without arithmetic.",
 "Bundle contents arranged as one grouped shape occupying the centre, individual values listed beside, combined value at largest weight.",
 ["Combined value","Bundle as one shape","Individual items","Individual values"],
 "Reads the group as one object, scans the item values, lands on the combined figure.",
 "Items spread apart so the bundle reads as separate products rather than a single offer.",
 "Bundles are shown as separate products in a row, so the viewer sees several items rather than one offer.",
 "Arrange bundle contents as one grouped shape and set the combined value at the largest weight.",
 "A bundle is a single proposition, and items spread apart are read as a range rather than a package.",
 "Grouping makes the offer one object, which is what allows a single combined value to make sense.",
 ["Bundle and multi-buy offers","Categories where unit price comparison is unflattering"],
 ["Single-product offers","Range communication where separation is the point"],
 "Communicates combined value without arithmetic","Individual products get little exposure",
 "Bundle and package offers","Single-product and range assets",
 ["Grid layout where products should read as a range"],
 [("Spacing bundle items apart for individual clarity","The bundle reads as several products rather than one offer, so combined value stops making sense","Items grouped into a single shape with one combined value")],
 "Makes combined value legible at a glance.",7,7,0.84,
 obj="conversion")

LAY("layout.offer.conditional_clarity.001","Conditional offer clarity","offer",
 "Present an offer with conditions without hiding them.",
 "Offer at dominant weight with the qualifying condition set immediately beneath at no less than 40 percent of the offer's size.",
 ["Offer","Qualifying condition","Product","Call to action"],
 "Reads the offer, immediately reads the condition beneath it.",
 "Condition pushed to a footnote, which produces post-click abandonment and complaint.",
 "Conditional offers hide the condition in small print, which converts clicks that immediately abandon.",
 "Set the qualifying condition immediately beneath the offer at no less than 40 percent of the offer's type size.",
 "A condition discovered after the click is experienced as a trick, and the resulting abandonment costs more than the lost click.",
 "Adjacency and readable size make the condition part of the offer rather than an exclusion from it.",
 ["Conditional and threshold-based offers","Categories with regulatory disclosure duties"],
 ["Unconditional offers","Brand awareness with no offer"],
 "Higher quality conversion and lower complaint","Lower raw click volume",
 "Conditional promotions","Unconditional offers",
 ["Unconditional offer framing where the condition can be removed"],
 [("Placing the qualifying condition in a footnote","Produces clicks that abandon on discovery, which costs more than the clicks were worth","Condition set adjacent to the offer at 40 percent of its size or larger")],
 "Converts qualified intent rather than raw clicks.",8,8,0.88,
 obj="conversion", ch=["website","facebook"])

LAY("layout.offer.gift_with_purchase.001","Gift with purchase layout","offer",
 "Show an added item without letting it outshine the product being sold.",
 "Main product at 60 percent visual weight, gift at 25 percent placed adjacent with a visible connector, value of gift stated once.",
 ["Main product","Gift","Connector","Stated gift value"],
 "Reads the main product, follows the connector to the gift, returns.",
 "Gift given equal or greater weight, which shifts desire onto the item that is not being sold.",
 "Gift-with-purchase assets feature the gift prominently, so buyers want the gift and resent the purchase requirement.",
 "Hold the main product at 60 percent visual weight and the gift at 25, connected by one visible link.",
 "The gift is an incentive rather than the product, and an incentive that outshines the product creates resentment at the requirement.",
 "Proportional weighting keeps desire attached to the item that generates the revenue.",
 ["Gift-with-purchase and sampling promotions","Beauty and consumer goods categories"],
 ["Standalone product communication","Categories where the gift is genuinely the draw"],
 "Adds incentive without displacing desire","Weakens the incentive's own stopping power",
 "Incentive-led promotions","Standalone product assets",
 ["Gift-led layout where the gift is genuinely the acquisition driver"],
 [("Featuring the gift at equal or greater size than the product","Shifts desire onto the free item, so the purchase feels like a toll","Product at 60 percent weight, gift at 25 percent")],
 "Keeps desire attached to the purchased product.",7,7,0.84,
 ind="beauty", obj="conversion")

LAY("layout.offer.tiered_incentive.001","Tiered incentive layout","offer",
 "Encourage larger baskets by showing thresholds and their rewards.",
 "Three horizontal tiers in ascending order, each stating threshold and reward, the target tier given 20 percent more height.",
 ["Target tier","Thresholds","Rewards","Call to action"],
 "Scans upward through tiers, stops at the emphasised one.",
 "All tiers given equal emphasis, which leaves the viewer to compute the best value themselves.",
 "Threshold incentives are listed as equal options, so the shopper must do the arithmetic and usually stops at the first.",
 "Stack three tiers in ascending order and give the target tier 20 percent more height than the others.",
 "Basket-building depends on the shopper seeing a reachable next step, which equal presentation hides.",
 "Emphasising one tier converts an arithmetic problem into a single accept-or-decline decision.",
 ["Basket-building and threshold promotions","E-commerce and retail"],
 ["Single-item purchases","Categories with fixed unit purchase"],
 "Raises average basket value","Adds complexity that can reduce simple conversions",
 "Basket-building promotions","Single-item categories",
 ["Single-threshold framing where only one step exists"],
 [("Presenting all tiers with equal emphasis","Leaves the arithmetic to the shopper, who usually stops at the first threshold","One target tier emphasised through height")],
 "Raises basket value by making the next step visible.",7,7,0.83,
 ch="website", obj="conversion")

# ══════════════════ ANNOUNCEMENT LAYOUT ══════════════════
LAY("layout.announcement.single_statement.001","Single statement announcement","announcement",
 "Deliver one piece of news with nothing competing against it.",
 "One line of type occupying 20 to 30 percent of frame height, centred, on a plain ground with the mark at minimum size.",
 ["The statement","Brand mark"],
 "Reads the line and stops; there is nothing else to find.",
 "A supporting line added beneath, which halves the attention the announcement receives.",
 "Announcements accumulate supporting detail until the news itself is no longer the largest thing in the frame.",
 "Set one line at 20 to 30 percent of frame height on a plain ground and add nothing else but the mark.",
 "News competes with nothing when it arrives alone, and every added element divides the attention it receives.",
 "A single element removes the need for hierarchy entirely, which is why it lands fastest.",
 ["Significant brand news","Openings, launches and milestones"],
 ["Offers requiring terms and conditions","Complex propositions needing explanation"],
 "Maximum impact for a single message","Carries no supporting information at all",
 "Major announcements","Detailed offers and complex propositions",
 ["Two-level announcement where a qualifier is unavoidable"],
 [("Adding a supporting line beneath the statement","Halves the attention the news receives in exchange for detail few will read","The supporting line moved to a second asset")],
 "Delivers news at maximum impact.",8,8,0.88,
 obj="awareness", asset=["poster","social_ad"],
 related=["concept.discipline.one_message_per_asset.001"])

LAY("layout.announcement.date_anchor.001","Date-anchored announcement","announcement",
 "Fix a future event in memory by making the date the visual anchor.",
 "Date set at the largest weight in the upper half, event name beneath at two thirds that size, location and mark at the lower edge.",
 ["Date","Event name","Location","Brand mark"],
 "Reads the date, then what it is for, then where.",
 "Event name set larger than the date, which makes the asset memorable but the timing forgettable.",
 "Event announcements lead with the event name, so viewers remember something is happening but not when.",
 "Set the date at the largest weight in the upper half with the event name beneath at two thirds its size.",
 "The failure mode of event advertising is missed timing, not unawareness, so the date is the load-bearing element.",
 "Leading with the date attaches the news to a point in time, which is what makes it actionable.",
 ["Event, opening and launch date announcements","Time-anchored news"],
 ["Ongoing propositions with no date","Evergreen brand communication"],
 "Timing is retained, not just awareness","Reads as functional rather than atmospheric",
 "Dated events and openings","Evergreen brand work",
 ["Name-led announcement where the date is flexible"],
 [("Setting the event name larger than the date","Produces awareness without timing, so attendance does not follow","Date at largest weight, name at two thirds beneath it")],
 "Makes timing memorable, not just the event.",8,8,0.87,
 obj=["awareness","product_launch"], ind="hospitality")

LAY("layout.announcement.reveal_frame.001","Partial reveal announcement","announcement",
 "Build anticipation by showing part of something without showing all of it.",
 "Subject cropped so 30 to 50 percent is visible at one frame edge, remainder implied by the crop, date or teaser line opposite.",
 ["The partial subject","Teaser line","Date","Brand mark"],
 "Enters at the cropped edge, tries to complete the shape, moves to the line for resolution.",
 "Cropping so tightly that the subject becomes unidentifiable, which produces confusion rather than curiosity.",
 "Teaser campaigns hide the product entirely, so curiosity has nothing to attach to and the audience disengages.",
 "Crop the subject so 30 to 50 percent remains visible at one frame edge and place the teaser line opposite.",
 "Curiosity requires partial information; complete concealment produces indifference rather than interest.",
 "A recognisable fragment gives the mind something to complete, which is what sustains attention until the reveal.",
 ["Pre-launch teaser campaigns","Products with a distinctive recognisable form"],
 ["Immediate conversion objectives","Products with no distinctive silhouette"],
 "Sustains attention across a campaign period","Wastes exposure if the follow-up does not land",
 "Multi-phase launch campaigns","Single-exposure conversion work",
 ["Full reveal where there is no campaign period to sustain"],
 [("Cropping until the subject is unidentifiable","Produces confusion rather than curiosity, and confused viewers disengage","30 to 50 percent kept visible so the form remains recognisable")],
 "Sustains curiosity across a launch period.",7,7,0.83,
 obj="product_launch")

LAY("layout.announcement.list_of_news.001","Multiple announcement list","announcement",
 "Communicate several pieces of news where completeness matters more than impact.",
 "Vertical list of three to five items, each with a bold lead phrase and one supporting line, uniform spacing throughout.",
 ["Item count","Lead phrases","Supporting lines","Brand mark"],
 "Scans lead phrases downward, stopping only at a relevant one.",
 "Varying emphasis between items, which implies a ranking and stops the list being scannable.",
 "Multiple announcements are combined into paragraphs, which are neither read nor scanned.",
 "List three to five items with uniform spacing, each carrying a bold lead phrase and one supporting line.",
 "Scanning depends on regularity, and any variation in emphasis interrupts the scan to demand interpretation.",
 "Uniform lead phrases let a reader find the one relevant item without reading the others.",
 ["Multiple simultaneous announcements","Owned channels and newsletters"],
 ["Paid media with short exposure","Single major news requiring impact"],
 "Complete and scannable","Low impact per item",
 "Owned channels and newsletters","Paid media and major announcements",
 ["Single statement layout where one item is genuinely the news"],
 [("Emphasising the most important item within the list","Breaks the scan pattern and the other items stop being read at all","Uniform treatment, with the priority item placed first")],
 "Makes several announcements scannable.",6,7,0.83,
 ch="website")

LAY("layout.announcement.milestone_number.001","Milestone number announcement","announcement",
 "Communicate an achievement where the number carries the meaning.",
 "Numeral at 35 to 45 percent of frame height, context phrase directly beneath at a fifth its size, mark at the lower edge.",
 ["The numeral","Context phrase","Brand mark"],
 "Reads the number, then the phrase that explains what it counts.",
 "Context phrase set too small to read at distance, leaving an impressive number that means nothing.",
 "Milestone announcements bury the number in a sentence, which removes the impact the milestone was worth announcing for.",
 "Set the numeral at 35 to 45 percent of frame height with the context phrase directly beneath at a fifth its size.",
 "A milestone is a number, and a number set in a sentence is read as prose rather than perceived as a magnitude.",
 "Isolating the numeral converts information into impression, which is what an announcement is for.",
 ["Anniversary, volume and achievement milestones","Trust and scale building"],
 ["Small numbers that undermine the claim","Categories where scale implies impersonality"],
 "Converts a statistic into an impression","Meaningless without a legible context phrase",
 "Scale and longevity milestones","Small-scale or artisanal positioning",
 ["Narrative framing where the number is unimpressive alone"],
 [("Setting the context phrase too small to read at viewing distance","Leaves an impressive number with no meaning attached, which builds nothing","Context phrase at a fifth of the numeral height, directly beneath")],
 "Converts a milestone into a perceived magnitude.",7,7,0.85,
 obj="awareness")

LAY("layout.announcement.partnership_lockup.001","Partnership lockup layout","announcement",
 "Announce a collaboration where neither party may appear subordinate.",
 "Two marks at equal optical weight on one horizontal axis, separated by a neutral connector, announcement line beneath at equal distance from both.",
 ["The pairing","Both marks","Connector","Announcement line"],
 "Reads the pair as one unit before separating it into two brands.",
 "Marks matched by measured size rather than optical weight, which makes the visually heavier mark dominate.",
 "Partnership announcements scale both logos to the same measured width, so the denser mark appears dominant and offends.",
 "Balance both marks to equal optical weight on one axis with a neutral connector between them.",
 "Logos differ in visual density, so equal measured size produces unequal perceived size, which partners notice immediately.",
 "Optical balancing states parity, which is the entire diplomatic requirement of a partnership announcement.",
 ["Co-branding and partnership announcements","Sponsorship communication"],
 ["Single-brand communication","Clear licensor and licensee hierarchies"],
 "States parity, avoiding partner friction","Neither brand gets dominant exposure",
 "Equal partnerships","Licensing with a defined hierarchy",
 ["Primary-and-endorsed lockup where a hierarchy genuinely exists"],
 [("Matching both logos to the same measured width","The visually denser mark appears dominant, which partners read as a slight","Marks balanced by optical weight, not measured dimension")],
 "States partnership parity without friction.",7,7,0.86,
 obj="awareness")

flush()
