# -*- coding: utf-8 -*-
"""Phase 2.1B — social media layouts."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_layout_lib import LAY, flush

SOC = dict(asset="social_ad")

# ══════════════ THUMB STOP COMPOSITION ══════════════
LAY("layout.thumb_stop.single_focal_mass.001","Single focal mass for thumb stop","thumb_stop",
 "Stop a scroll in the fraction of a second before the thumb moves.",
 "One dominant shape occupying 40 to 60 percent of frame with no secondary element above 15 percent.",
 ["Dominant shape","Supporting ground","Brand mark"],
 "Locks on the mass immediately with no search phase.",
 "A second element grown past 15 percent, which forces a search and the scroll continues during it.",
 "Feed assets are composed with several elements of similar weight, so the eye must search and the thumb moves first.",
 "Build one dominant shape at 40 to 60 percent of frame and hold every other element below 15 percent.",
 "Scroll decisions happen before search completes, so any frame requiring a search has already lost.",
 "A single mass is resolved pre-attentively, which is the only processing available in the time the asset gets.",
 ["Paid social in-feed placements","High-scroll-velocity environments"],
 ["Owned channels with committed audiences","Formats with dwell time"],
 "Survives the actual attention window","Carries very little information",
 "Paid in-feed social","Owned long-form channels",
 ["Structured multi-element layout where dwell time is proven"],
 [("Balancing three elements of similar visual weight","Forces a search the scroll does not wait for, so the asset is passed","One dominant mass with everything else below 15 percent")],
 "Wins the pre-attentive scroll decision.",9,9,0.9,
 ch=["instagram","tiktok","facebook"], **SOC)

LAY("layout.thumb_stop.face_direct_gaze.001","Direct gaze for thumb stop","thumb_stop",
 "Use a human face looking at the viewer to interrupt scrolling.",
 "Face occupying 30 to 50 percent of frame with eyes on the upper third line and gaze directed at the lens.",
 ["Eyes","Face","Expression","Message"],
 "Locks on the eyes before anything else is processed.",
 "Gaze directed off-frame, which redirects attention out of the asset instead of into it.",
 "Social assets lead with product, which has no pre-attentive priority and is scrolled past.",
 "Place a face at 30 to 50 percent of frame with the eyes on the upper third line and the gaze on the lens.",
 "Faces and direct gaze are processed before conscious attention, which is the only channel available at scroll speed.",
 "Eyes on the upper third line places them where the eye lands first in a vertical frame.",
 ["Social advertising needing stop rate","Categories where a human presence is credible"],
 ["Product-identification assets","Categories where faces are legally restricted"],
 "Highest available stop rate","Face can overshadow the product entirely",
 "Awareness and consideration social","Product-identification and e-commerce",
 ["Single focal mass where a face is unavailable or inappropriate"],
 [("Directing the gaze off-frame for a more editorial feel","Sends attention out of the asset, which is the opposite of the intent","Gaze directed at the lens with eyes on the upper third line")],
 "Uses pre-attentive face processing to stop scroll.",9,9,0.89,
 ch=["instagram","tiktok"], **SOC)

LAY("layout.thumb_stop.colour_block_interrupt.001","Colour block interrupt","thumb_stop",
 "Interrupt a feed by breaking its prevailing colour temperature.",
 "One saturated field occupying 60 percent or more of frame, subject in the remainder at high luminance contrast.",
 ["Colour field","Subject","Message"],
 "Registers the colour before any shape is resolved.",
 "Choosing a colour already common in the feed, which removes the interruption the layout depends on.",
 "Social assets adopt category-conventional palettes, so they blend into a feed of similar assets.",
 "Fill 60 percent or more of the frame with one saturated field that contrasts the feed's prevailing temperature.",
 "Colour is processed before form, so a temperature break registers earlier than any compositional device.",
 "A large single field cannot be missed at thumbnail scale, where smaller colour accents disappear.",
 ["High-competition feeds","Brands with an ownable colour"],
 ["Premium restraint positioning","Categories where the palette is regulated"],
 "Registers before shape processing","Crude, and can read as cheap in premium contexts",
 "High-competition feed environments","Premium and restrained positioning",
 ["Luminance-contrast approach where saturation would damage the brand"],
 [("Choosing a colour already dominant in the category feed","Removes the interruption entirely, so the asset blends","A field contrasting the feed's prevailing temperature")],
 "Interrupts a feed at the colour-processing stage.",8,8,0.86,
 ch=["instagram","tiktok","facebook"], **SOC)

LAY("layout.thumb_stop.motion_implied.001","Implied motion for thumb stop","thumb_stop",
 "Suggest movement in a still frame so it reads as video and slows the scroll.",
 "Subject captured mid-action with visible directional blur on one element, sharp anchor elsewhere in frame.",
 ["Moving element","Sharp anchor","Direction of travel","Message"],
 "Enters at the sharp anchor, follows the blur along its direction.",
 "Blurring the whole frame, which reads as a technical error rather than as motion.",
 "Static social stills are scrolled past in environments where video sets the expectation of movement.",
 "Capture the subject mid-action with directional blur on one element and keep one sharp anchor in frame.",
 "Feeds mixing video and stills train the eye to pause on movement, and implied motion borrows that pause.",
 "A sharp anchor proves the blur is intentional rather than a focus failure.",
 ["Video-dominant feeds","Categories with natural movement"],
 ["Product detail assets requiring full sharpness","Static categories where motion is implausible"],
 "Borrows the pause that video receives","Reads as an error if the anchor is missing",
 "Video-dominant social feeds","Product detail and specification assets",
 ["Sharp single-mass composition where motion is implausible"],
 [("Applying blur across the whole frame","Reads as a focus error rather than as motion, and errors are scrolled past","One blurred element against a sharp anchor")],
 "Borrows the attention video receives in feed.",7,8,0.84,
 ch=["instagram","tiktok"], **SOC)

LAY("layout.thumb_stop.pattern_break.001","Pattern break for thumb stop","thumb_stop",
 "Use repetition with one interruption so the anomaly is found instantly.",
 "Regular repeat of one element across the frame with exactly one member differing in colour, scale or orientation.",
 ["The anomaly","The pattern","Message"],
 "Locates the anomaly before reading the pattern that made it visible.",
 "Breaking the pattern in more than one place, which dissolves the regularity that made any break findable.",
 "Social assets add variety for interest, which produces noise rather than a findable focal point.",
 "Establish a regular repeat and break it in exactly one place, at the point attention should land.",
 "Anomaly detection is faster than content reading, which makes a single break the quickest focal device available.",
 "One break is unambiguous; several destroy the pattern that made the first one visible.",
 ["Range and multi-item social assets","Categories with repeatable units"],
 ["Single-subject assets with no pattern","Comparison assets requiring equal weight"],
 "Fastest available attention direction","Needs enough units to establish a pattern",
 "Multi-unit social assets","Single-subject and comparison work",
 ["Scale hierarchy where a pattern cannot be built"],
 [("Breaking the pattern in several places for variety","Destroys the regularity that made any break perceptible","Exactly one break, placed where attention should land")],
 "Creates the fastest findable focal point.",7,7,0.85,
 ch=["instagram","facebook"], **SOC)

LAY("layout.thumb_stop.text_as_image.001","Text as the visual","thumb_stop",
 "Stop a scroll with words when the statement is stronger than any available image.",
 "One short statement set at 15 to 25 percent of frame height filling most of the frame, on a plain contrasting ground.",
 ["The statement","Ground","Brand mark"],
 "Reads the statement as a shape before decoding it as language.",
 "More than eight words, past which the block reads as a paragraph and is skipped as work.",
 "Brands with a strong statement bury it beneath a stock image that adds nothing.",
 "Set one statement of eight words or fewer at 15 to 25 percent of frame height on a plain ground.",
 "A short line at scale is processed as a shape first, so it stops the scroll before it is read.",
 "Under eight words the block stays a shape; beyond that it becomes a paragraph and is declined.",
 ["Strong verbal propositions","Categories where imagery is generic"],
 ["Visual products where appearance is the proposition","Low-literacy or multilingual audiences"],
 "Uses a strong line at full strength","No visual product exposure at all",
 "Statement-led brand social","Visual product categories",
 ["Image-led layout where the product's appearance sells it"],
 [("Setting a statement of fifteen words at display size","Reads as a paragraph, which the viewer declines as work","Eight words or fewer, kept at display scale")],
 "Converts a strong line into a visual stop.",7,8,0.85,
 ch=["instagram","facebook"], **SOC)

LAY("layout.thumb_stop.negative_space_isolation.001","Isolation by emptiness","thumb_stop",
 "Stop a scroll by contrast with feed density rather than by adding weight.",
 "Single small subject occupying 10 to 20 percent of frame, remainder held as one uninterrupted empty field.",
 ["The emptiness","Small subject","Brand mark"],
 "Registers the emptiness first, then searches for and finds the small subject.",
 "Adding a second element into the empty field, which removes the density contrast the layout relies on.",
 "Every asset in a feed competes by adding weight, so weight stops being a differentiator.",
 "Reduce the subject to 10 to 20 percent of frame and hold the remainder as one uninterrupted empty field.",
 "In a dense feed, emptiness is the anomaly, so restraint interrupts where addition merely joins in.",
 "Density contrast operates at the same pre-attentive speed as colour, without the crudeness.",
 ["Premium positioning in dense feeds","Categories where restraint signals quality"],
 ["Value and promotional messaging","Feeds already dominated by minimal work"],
 "Interrupts through contrast rather than volume","Very low information capacity",
 "Premium social in dense feeds","Promotional and value messaging",
 ["Colour block interrupt where the feed is already minimal"],
 [("Adding a second element into the empty field","Removes the density contrast that produced the interruption","The field left genuinely uninterrupted")],
 "Interrupts by contrast with feed density.",8,8,0.86,
 ch=["instagram"], pos=["premium","luxury"], **SOC)

# ══════════════ MOBILE FIRST LAYOUT ══════════════
LAY("layout.mobile_first.thumb_zone_action.001","Thumb zone action placement","mobile_first",
 "Place the interactive element where a thumb can reach it without regrip.",
 "Primary action within the lower 40 percent and inset at least 8 percent from each side edge.",
 ["Primary action","Supporting message","Subject"],
 "Reads content above, arrives at the action within natural thumb reach.",
 "Action placed in an upper corner, which requires a regrip and loses a measurable share of taps.",
 "Interactive placements are designed on desktop, where every position is equally reachable by a cursor.",
 "Place the primary action within the lower 40 percent, inset at least 8 percent from each side edge.",
 "One-handed phone use restricts comfortable reach to a lower arc, and anything outside it costs a regrip.",
 "Designing to the reachable arc removes a physical barrier that no amount of visual emphasis can overcome.",
 ["Interactive mobile placements","Objective is tap-through or conversion"],
 ["Static print and out-of-home","Desktop-primary placements"],
 "Removes a physical barrier to action","Constrains composition to reserve the lower band",
 "Interactive mobile formats","Print and desktop-first placements",
 ["Full-frame tap targets where the whole asset is interactive"],
 [("Placing the call to action in an upper corner for visual balance","Requires a regrip that a measurable share of users will not perform","Action placed within the lower 40 percent, inset from the edges")],
 "Removes a physical barrier to conversion.",8,8,0.88,
 ch=["instagram","tiktok","facebook","website"], obj="conversion", **SOC)

LAY("layout.mobile_first.single_column_flow.001","Single column flow","mobile_first",
 "Structure content so it reads in one vertical pass with no lateral movement.",
 "One column at 85 to 90 percent of frame width, elements stacked with uniform vertical rhythm and no side-by-side pairs.",
 ["Reading order","Individual elements","Call to action"],
 "Travels straight down with no lateral correction.",
 "Two elements placed side by side, which forces lateral scanning that a narrow frame cannot support.",
 "Desktop multi-column layouts are compressed for mobile, producing columns too narrow to read.",
 "Use one column at 85 to 90 percent of frame width and stack all elements with uniform vertical rhythm.",
 "A narrow viewport cannot support lateral comparison, so any side-by-side pairing degrades into unreadable columns.",
 "A single column matches the vertical scan a phone already induces.",
 ["Mobile web and in-app content","Any narrow viewport"],
 ["Desktop and tablet landscape","Comparison content requiring adjacency"],
 "Matches the natural mobile scan","Loses adjacency for comparison",
 "Mobile-first content","Comparison and desktop layouts",
 ["Stacked comparison where adjacency is essential but space is short"],
 [("Compressing a two-column desktop layout to phone width","Produces columns too narrow to read, so both are skipped","One column at 85 to 90 percent width with vertical stacking")],
 "Matches the scan a narrow viewport induces.",8,8,0.88,
 ch="website")

LAY("layout.mobile_first.safe_margin_reserve.001","Safe margin reserve","mobile_first",
 "Protect content from device chrome, notches and rounded corners.",
 "All load-bearing content inset at least 6 percent from every edge, with nothing critical in the corner radius zones.",
 ["Protected content","Decorative bleed","Brand mark"],
 "Reads content entirely within the protected region.",
 "Brand mark placed in a corner, where a rounded display or notch clips it on some devices.",
 "Assets are designed to the artboard edge and clipped differently on every device.",
 "Inset all load-bearing content at least 6 percent from every edge and keep corners free of critical elements.",
 "Device chrome varies across handsets, so only an inset margin is safe on all of them.",
 "A uniform reserve removes device-specific testing from the production path.",
 ["All mobile-delivered assets","Multi-device campaigns"],
 ["Print with defined trim","Fixed-format placements with known bounds"],
 "Predictable across every device","Reduces usable canvas by roughly a tenth",
 "Multi-device mobile delivery","Fixed-format and print",
 ["Device-specific artwork where the handset is known"],
 [("Placing the brand mark tight into a corner","Clipped by rounded corners or notches on a share of devices","Mark inset at least 6 percent from both edges")],
 "Guarantees legibility across device variation.",8,9,0.9,
 ch=["instagram","tiktok","facebook","website"])

LAY("layout.mobile_first.progressive_disclosure.001","Progressive disclosure","mobile_first",
 "Sequence information so the first screen carries the decision and detail follows.",
 "First screen holds proposition and action only, with supporting detail beginning below the fold in defined blocks.",
 ["Proposition","Action","Detail blocks"],
 "Decides on the first screen; scrolls only if undecided.",
 "Detail pulled above the fold to appear thorough, which displaces the proposition and lowers conversion.",
 "Mobile pages compress everything above the fold, so the proposition competes with detail nobody has asked for yet.",
 "Restrict the first screen to proposition and action, and begin supporting detail below the fold.",
 "Most viewers decide on the first screen, and detail placed there competes with the decision rather than supporting it.",
 "Detail below the fold serves only viewers who chose to seek it, which is exactly who needs it.",
 ["Mobile landing pages and in-app flows","Conversion objectives"],
 ["Reference and documentation content","Comparison pages requiring simultaneous detail"],
 "Protects the decision on the first screen","Some viewers never see the supporting detail",
 "Mobile conversion pages","Reference and comparison content",
 ["Single-screen layout where the proposition needs no support"],
 [("Pulling specification detail above the fold to look thorough","Displaces the proposition that drives the decision","Detail moved below the fold in defined blocks")],
 "Protects the decision on the first screen.",8,8,0.87,
 ch="website", obj="conversion")

LAY("layout.mobile_first.tap_target_sizing.001","Tap target sizing","mobile_first",
 "Size interactive elements so they can be hit accurately by a thumb.",
 "Every interactive element at least 44 by 44 device-independent pixels with at least 8 pixels of clear space around it.",
 ["Interactive elements","Clear space","Static content"],
 "Locates the target and hits it without a correction tap.",
 "Adjacent targets placed closer than 8 pixels apart, which produces mis-taps and abandonment.",
 "Buttons are sized visually rather than to the physical contact area of a fingertip.",
 "Size every interactive element at least 44 by 44 points with 8 points of clear space around it.",
 "A fingertip contacts a far larger area than a cursor, and a target below that area produces mis-taps.",
 "Clear space prevents adjacent targets from stealing taps intended for their neighbour.",
 ["Any interactive mobile interface","In-app and mobile web"],
 ["Static assets with no interaction","Desktop cursor interfaces"],
 "Removes mis-tap abandonment","Constrains element density",
 "Interactive mobile interfaces","Static and desktop assets",
 ["Larger targets where accuracy matters more than density"],
 [("Placing adjacent buttons with two pixels of separation","Produces mis-taps, and a mis-tap on a destructive action loses the user entirely","At least 8 points of clear space between adjacent targets")],
 "Removes mis-tap abandonment.",8,9,0.92,
 ch="website", obj="conversion")

LAY("layout.mobile_first.vertical_video_bands.001","Vertical video banding","mobile_first",
 "Compose a 9:16 frame in bands that match how it will actually be watched.",
 "Three horizontal bands: hook in the upper 30 percent, subject in the middle 40, lower 30 kept clear of load-bearing content.",
 ["Hook","Subject","Call to action"],
 "Reads top to bottom in one pass with no lateral movement.",
 "Subject centred vertically, which pushes its lower portion behind captions and interface controls.",
 "Landscape compositions are cropped to 9:16, so the crop chooses the composition rather than the designer.",
 "Compose natively in three bands with the hook in the upper 30 percent and the lower 30 kept clear.",
 "Vertical frames are scanned top to bottom in one movement, and platform chrome reliably covers the lower band.",
 "Native banding matches the scan and protects the message from interface overlay simultaneously.",
 ["Story, reel and short vertical video","Instagram and TikTok placements"],
 ["Landscape and square placements","Print formats"],
 "Matches scan direction and survives chrome","Does not adapt to landscape without redesign",
 "Vertical social placements","Landscape and print",
 ["Centre-safe composition where one asset must serve several ratios"],
 [("Cropping a landscape hero to 9:16","Places the subject arbitrarily and usually buries the action under chrome","Native vertical composition in three bands")],
 "Preserves the message under vertical scanning.",9,9,0.9,
 ch=["instagram","tiktok"], **SOC)

LAY("layout.mobile_first.contrast_floor.001","Contrast floor for small screens","mobile_first",
 "Guarantee legibility at the physical size the asset is actually viewed.",
 "Minimum four-to-one luminance ratio between text and its ground, verified in greyscale at 25 percent zoom.",
 ["Primary text","Ground","Secondary text"],
 "Reads text without pausing to resolve it against the ground.",
 "Separating text from ground by hue alone, which collapses at small scale and under compression.",
 "Palettes are approved at full canvas on a monitor, where contrast that fails on a phone still looks adequate.",
 "Hold a minimum four-to-one luminance ratio between text and ground and verify in greyscale at 25 percent zoom.",
 "Hue differences vanish before luminance differences at reduced scale, so hue-only separation fails first.",
 "A greyscale check tests the only channel that survives scale reduction and compression.",
 ["All mobile-delivered text","Social and thumbnail formats"],
 ["Large-format print","Deliberate low-contrast art direction with accepted reach cost"],
 "Text survives real viewing conditions","Constrains subtle tonal palettes",
 "Mobile and social formats","Print and gallery formats",
 ["Shape or silhouette separation where palette is mandated"],
 [("Separating text from ground by hue alone","Hue separation vanishes at phone scale, merging text into the ground","Luminance separation of at least four to one, verified in greyscale")],
 "Guarantees legibility at real viewing size.",8,9,0.92,
 ch=["instagram","tiktok","facebook","website"],
 related=["color.contrast.thumbnail_survival.001"])

# ══════════════ TIKTOK VISUAL HOOK ══════════════
LAY("layout.tiktok_hook.first_frame_complete.001","Self-sufficient first frame","tiktok_hook",
 "Carry the whole proposition in frame one, assuming no second frame is seen.",
 "Subject, hook line and brand cue all present in the opening frame, hook line in the upper 30 percent.",
 ["Hook line","Subject","Brand cue"],
 "Reads the hook, confirms the subject, all within the opening frame.",
 "Opening on an establishing shot before the subject appears, so the scroll decision is made on an empty frame.",
 "Video assets build toward a reveal, but the scroll decision is made long before the build completes.",
 "Place subject, hook line and brand cue in the opening frame with the hook in the upper 30 percent.",
 "Scroll decisions in this channel are made in well under a second, before any build or reveal can resolve.",
 "A self-sufficient first frame converts the decision into an impression rather than losing both.",
 ["TikTok and short vertical video","Paid social with skip behaviour"],
 ["Owned channels with committed audiences","Narrative long-form"],
 "Survives the actual attention window","Removes the possibility of a build",
 "Paid short-form vertical","Owned long-form content",
 ["Narrative build where dwell time is proven"],
 [("Opening on a slow establishing shot","The scroll decision is made before the reveal, losing setup and payoff together","Complete proposition present in frame one")],
 "Aligns the asset with the real attention window.",9,9,0.9,
 ch="tiktok", **SOC)

LAY("layout.tiktok_hook.caption_safe_composition.001","Caption-safe composition","tiktok_hook",
 "Keep the subject clear of the caption and interface zone.",
 "Subject held within the upper 65 percent, with the lower 35 percent reserved for captions, handle and controls.",
 ["Subject","Reserved lower band","On-screen text"],
 "Reads the subject above, ignores the reserved band entirely.",
 "Subject centred vertically, which places its lower third behind captions on every playback.",
 "Vertical video is framed as though the whole 9:16 canvas is visible, which it never is.",
 "Hold the subject within the upper 65 percent and reserve the lower 35 percent for platform interface.",
 "Captions, handles and controls occupy the lower third on every major short-video platform.",
 "Reserving the band means the composition survives playback rather than competing with it.",
 ["TikTok, Reels and Shorts","Any captioned vertical video"],
 ["Landscape video","Platforms without persistent lower chrome"],
 "Subject survives real playback","Loses roughly a third of the canvas",
 "Captioned vertical video","Landscape and chrome-free platforms",
 ["Full-frame composition where captions are burned in above"],
 [("Centring the subject vertically in a 9:16 frame","Places the lower third of the subject behind captions on every view","Subject held within the upper 65 percent")],
 "Protects the subject from platform chrome.",9,9,0.91,
 ch="tiktok", **SOC)

LAY("layout.tiktok_hook.text_overlay_rhythm.001","Text overlay rhythm","tiktok_hook",
 "Pace on-screen text so it can be read at playback speed.",
 "No more than six words visible at once, each block held for at least one second, single position throughout.",
 ["Current text block","Subject","Brand cue"],
 "Reads each block in place without hunting for the next.",
 "Text blocks moving position between beats, which forces a search and loses the reading thread.",
 "On-screen text is designed as graphic layout rather than as timed reading, so viewers cannot keep up.",
 "Show no more than six words at once, hold each block at least one second, and keep the position fixed.",
 "Reading at playback speed requires the eye to stay in one place, because searching costs more time than reading.",
 "A fixed position converts reading into a single fixation per block.",
 ["Text-driven short vertical video","Sound-off viewing environments"],
 ["Long-form video with pause control","Assets with voiceover carrying the message"],
 "Text is actually read at playback speed","Very low words-per-second capacity",
 "Sound-off short vertical video","Long-form and voiceover-led content",
 ["Burned-in captions where the script is dense"],
 [("Moving text blocks around the frame for visual variety","Forces a search between blocks, and the reading thread is lost","One fixed position for every block")],
 "Makes on-screen text readable at playback speed.",8,8,0.87,
 ch="tiktok", **SOC)

LAY("layout.tiktok_hook.pattern_interrupt_open.001","Pattern interrupt opening","tiktok_hook",
 "Break the visual rhythm of the feed in the opening moment.",
 "Opening frame differing sharply from category convention in scale, angle or colour, resolved within two seconds.",
 ["The interruption","Subject","Resolution"],
 "Registers the anomaly, waits for resolution, receives it quickly.",
 "Interruption never resolved, which is read as a mistake and produces a scroll plus a negative brand impression.",
 "Openings follow category convention, so the asset joins the feed's rhythm instead of breaking it.",
 "Open on a frame that breaks category convention in scale, angle or colour, and resolve it within two seconds.",
 "The feed trains an expectation, and a violated expectation holds attention until it is resolved.",
 "Fast resolution converts the interruption into interest rather than confusion.",
 ["Saturated categories on short-form video","Awareness objectives"],
 ["Trust-dependent categories where oddity damages credibility","Regulated categories"],
 "High stop rate through expectation violation","Unresolved interruption damages the brand",
 "Saturated short-form categories","Trust-led and regulated categories",
 ["Conventional opening where credibility outranks stop rate"],
 [("Leaving the interruption unresolved as a mystery","Reads as a mistake, producing a scroll and a negative impression together","Resolution delivered within two seconds")],
 "Holds attention through violated expectation.",7,8,0.83,
 ch="tiktok", **SOC)

LAY("layout.tiktok_hook.creator_frame_mimicry.001","Creator frame mimicry","tiktok_hook",
 "Adopt native creator framing so the asset is not read as an advertisement.",
 "Handheld framing at arm's length, subject slightly off-centre, natural light, no polished production cues.",
 ["Subject","Setting","Message"],
 "Reads it as organic content and proceeds to the message before classifying it as an ad.",
 "Polished lighting or a tripod-locked frame, which reveals the production and triggers ad-skipping.",
 "Brand assets in creator feeds carry production cues that classify them as advertising within a fraction of a second.",
 "Frame handheld at arm's length with the subject slightly off-centre in natural light.",
 "Viewers classify content as advertising from production cues before any message is processed.",
 "Native framing delays classification long enough for the message to land.",
 ["Creator-led and organic-style social","Gen Z and youth audiences"],
 ["Luxury positioning where craft is the product promise","Regulated categories requiring formal presentation"],
 "Delays ad classification","Low perceived premium and less brand control",
 "Creator-style social","Luxury and regulated communication",
 ["Polished production where craft is itself the message"],
 [("Applying studio lighting to a creator-style asset","Reveals the production and triggers ad-skipping before the message lands","Natural light with handheld framing retained")],
 "Delays advertising classification long enough to land.",8,8,0.85,
 ch="tiktok", aud="gen_z", **SOC)

LAY("layout.tiktok_hook.demonstration_open.001","Demonstration opening","tiktok_hook",
 "Open on the action itself rather than on setup or introduction.",
 "First frame shows the product mid-action with the outcome already beginning, no introductory context.",
 ["Action","Product","Emerging outcome"],
 "Enters mid-action and stays to see the outcome complete.",
 "Prefacing the demonstration with a spoken or written introduction, which spends the attention window on setup.",
 "Demonstration videos open with introductions, spending the entire attention window before the demonstration starts.",
 "Open the first frame mid-action with the outcome already beginning and no introductory context.",
 "An action already in progress creates an open loop, and open loops hold attention until they close.",
 "Removing setup spends the whole attention window on the thing worth watching.",
 ["Demonstrable products with visible action","Short-form video"],
 ["Products with no visible action","Brand and atmosphere communication"],
 "Opens an attention loop immediately","No context, so unfamiliar products may confuse",
 "Demonstration categories","Abstract and brand-led communication",
 ["Contextual opening where the product needs explanation"],
 [("Opening with a spoken introduction before the demonstration","Spends the entire attention window on setup, so the demonstration is never seen","First frame placed mid-action with the outcome beginning")],
 "Opens an attention loop in the first frame.",8,8,0.86,
 ch="tiktok", **SOC)

# ══════════════ INSTAGRAM CAROUSEL ══════════════
LAY("layout.carousel.hook_and_payoff.001","Carousel hook and payoff","carousel",
 "Structure a carousel so the first card earns the swipe and the last delivers.",
 "Card one carries a single question or claim, middle cards develop it, final card resolves and carries the action.",
 ["Card one hook","Middle development","Final payoff","Call to action"],
 "Reads card one, swipes on curiosity, arrives at the payoff.",
 "The payoff placed on card one, which removes any reason to swipe and wastes the format entirely.",
 "Carousels are used as galleries of unrelated images, so there is no reason to swipe past the first card.",
 "Place a single question or claim on card one and hold the resolution for the final card.",
 "A carousel is a sequence, and a sequence without an open loop is just a stack of separate posts.",
 "Withholding the payoff creates the only mechanic that makes swiping rational.",
 ["Instagram carousels","Educational and narrative social content"],
 ["Single-image placements","Product galleries where order does not matter"],
 "Drives swipe depth and dwell time","Card one carries no product exposure",
 "Narrative and educational carousels","Product galleries and single images",
 ["Gallery structure where every card stands alone"],
 [("Putting the full answer on card one","Removes any reason to swipe, so the remaining cards are never seen","A question or claim on card one, resolution held to the last")],
 "Creates the mechanic that makes swiping rational.",8,8,0.88,
 ch="instagram", **SOC)

LAY("layout.carousel.continuous_panorama.001","Continuous panorama carousel","carousel",
 "Use a single image split across cards so swiping reveals a continuing scene.",
 "One wide image divided into equal card widths with subject elements deliberately spanning the card boundaries.",
 ["The continuing scene","Boundary-spanning elements","Final card message"],
 "Notices a cut element at the card edge and swipes to complete it.",
 "Splitting the image where nothing crosses the boundary, which removes the reason to swipe.",
 "Panorama carousels split images at convenient points, so each card resolves and no swipe is prompted.",
 "Divide one wide image into equal cards and place subject elements deliberately across the boundaries.",
 "An interrupted shape is completed by the viewer, and swiping is the only way to complete it.",
 "Boundary-spanning elements make the incompleteness visible at the card edge.",
 ["Wide scenes and panoramic subjects","Brand and atmosphere carousels"],
 ["Content where each card must stand alone","Feeds where single cards are reshared"],
 "Strong intrinsic swipe motivation","Individual cards are meaningless in isolation",
 "Panoramic and atmosphere carousels","Standalone card content",
 ["Discrete card structure where cards may be shared separately"],
 [("Splitting the image at points where nothing crosses the edge","Each card resolves on its own, so no swipe is prompted","Subject elements placed deliberately across card boundaries")],
 "Builds swipe motivation into the image itself.",7,8,0.85,
 ch="instagram", **SOC)

LAY("layout.carousel.step_sequence.001","Step sequence carousel","carousel",
 "Teach a process where each card is one step.",
 "One step per card, numbered in a consistent corner position, identical framing and subject scale throughout.",
 ["Step number","Step content","Progress position","Final action"],
 "Checks the number, reads the step, swipes for the next.",
 "Combining two steps on one card, which breaks the one-card-one-step contract and loses the reader's place.",
 "Process carousels vary steps per card, so the reader loses track of progress and abandons.",
 "Place exactly one step per card with the number in a consistent corner and identical framing throughout.",
 "A sequence is followed only while the reader knows where they are, and inconsistent density destroys that.",
 "One step per card makes position in the sequence self-evident at every point.",
 ["Instructional and how-to carousels","Products with a multi-step process"],
 ["Single-action products","Atmosphere and brand carousels"],
 "High completion rate for instruction","Requires as many cards as there are steps",
 "Instructional carousels","Brand and atmosphere content",
 ["Single-card summary where the process is two steps"],
 [("Combining two steps onto one card to save space","Breaks the one-step contract and the reader loses their place","Exactly one step per card, with consistent numbering")],
 "Sustains completion through a taught sequence.",7,8,0.87,
 ch="instagram", **SOC)

LAY("layout.carousel.range_showcase.001","Range showcase carousel","carousel",
 "Present a product range where each card is one item and order implies no ranking.",
 "One product per card at identical scale and framing, consistent ground, with a summary card first or last.",
 ["Summary card","Individual products","Consistent treatment"],
 "Reads the summary, swipes through items at even pace.",
 "Varying product scale between cards, which implies a ranking the range does not have.",
 "Range carousels vary framing per product, so the range reads as a group of unrelated posts.",
 "Show one product per card at identical scale, framing and ground, with a summary card at one end.",
 "Consistency is what makes several cards read as one range rather than as separate items.",
 "Identical treatment removes the accidental ranking that scale variation creates.",
 ["Product range and collection communication","E-commerce and catalogue social"],
 ["Hero launches where one item must lead","Narrative content"],
 "Range reads as a coherent set","Low individual product drama",
 "Range and collection carousels","Hero launches and narrative content",
 ["Hero-and-supporting structure where one item leads"],
 [("Varying scale and framing across product cards","Implies a ranking and fragments the range into unrelated posts","Identical scale, framing and ground on every card")],
 "Makes a range read as one coherent set.",7,7,0.85,
 ch="instagram", **SOC)

LAY("layout.carousel.myth_and_fact.001","Myth and fact carousel","carousel",
 "Correct a category misconception across paired cards.",
 "Odd cards state the myth in a muted treatment, even cards deliver the correction at full contrast.",
 ["Correction cards","Myth cards","Treatment contrast","Final action"],
 "Reads the myth, swipes for the correction, repeats the pattern.",
 "Myth cards styled as attractively as corrections, which makes the misconception the memorable half.",
 "Myth-busting content states myths and facts at equal weight, so the myth is remembered as often as the fact.",
 "Set myth cards in a muted treatment and corrections at full contrast, alternating throughout.",
 "Repetition strengthens whatever is repeated, so a myth given equal treatment is reinforced by the correction.",
 "Treatment contrast ensures the correction is the version that is retained.",
 ["Educational and category-correction content","Categories with common misconceptions"],
 ["Categories with no established misconceptions","Brand and atmosphere work"],
 "Corrects misconceptions durably","Gives visibility to the misconception itself",
 "Educational category content","Brand and atmosphere carousels",
 ["Fact-only presentation where stating the myth risks reinforcing it"],
 [("Styling myth cards as attractively as the corrections","The misconception becomes as memorable as the fact, which defeats the purpose","Myth muted, correction at full contrast")],
 "Ensures the correction is what is retained.",7,7,0.84,
 ch="instagram", **SOC)

LAY("layout.carousel.progress_indicator.001","Carousel progress signalling","carousel",
 "Tell the reader how far through the sequence they are.",
 "A consistent position indicator on every card showing current position and total, at small but legible size.",
 ["Content","Progress indicator","Final action"],
 "Reads content, glances at the indicator, decides whether to continue.",
 "Indicator omitted, which leaves length unknown and raises abandonment in the middle cards.",
 "Carousels give no sense of length, so readers abandon in the middle rather than risk an unbounded sequence.",
 "Place a consistent position indicator on every card showing current position and total.",
 "Willingness to continue depends on knowing how much remains, and an unknown length is assumed to be long.",
 "A visible total converts an open-ended commitment into a bounded one.",
 ["Carousels of four or more cards","Instructional and narrative sequences"],
 ["Two and three card carousels","Panorama carousels where the indicator breaks the image"],
 "Reduces mid-sequence abandonment","Adds a persistent element to every card",
 "Longer instructional carousels","Short and panoramic carousels",
 ["Implicit progress through numbered steps"],
 [("Omitting any indication of sequence length","Readers assume an unbounded sequence and abandon in the middle","A position indicator showing current and total on every card")],
 "Reduces mid-sequence abandonment.",7,7,0.86,
 ch="instagram", **SOC)

# ══════════════ FACEBOOK AD LAYOUT ══════════════
LAY("layout.facebook_ad.text_ratio_discipline.001","Text ratio discipline","facebook_ad",
 "Keep in-image text low enough that delivery is not restricted.",
 "In-image text confined to under 20 percent of frame area, with the remaining message carried in the post copy.",
 ["Image subject","Minimal in-image text","Post copy"],
 "Reads the image, then drops to the post copy for detail.",
 "Filling the image with copy that belongs in the caption, which restricts delivery and raises cost.",
 "Facebook assets are designed as posters with dense in-image text, which suppresses delivery.",
 "Confine in-image text to under 20 percent of frame area and carry the rest in the post copy.",
 "The platform discounts text-heavy images in delivery, so density is paid for in reach as well as legibility.",
 "Splitting message between image and caption uses each surface for what it does best.",
 ["Facebook and Meta paid placements","Delivery efficiency matters"],
 ["Platforms with no text restriction","Organic posts with no delivery consideration"],
 "Protects delivery efficiency","Message must be split across two surfaces",
 "Meta paid placements","Unrestricted platforms",
 ["Text-as-image approach on platforms without the restriction"],
 [("Placing the full message as text inside the image","Restricts delivery and raises effective cost per result","Under 20 percent in-image text with the remainder in post copy")],
 "Protects delivery efficiency on Meta placements.",8,8,0.88,
 ch="facebook", **SOC)

LAY("layout.facebook_ad.feed_square_safe.001","Square-safe feed composition","facebook_ad",
 "Compose so one asset survives square, portrait and landscape crops.",
 "All load-bearing content within a central square inset 10 percent from the shorter dimension on all sides.",
 ["Central protected content","Peripheral bleed","Brand mark"],
 "Reads content from the protected centre regardless of crop.",
 "Placing the brand mark near an edge, where it is cropped out in at least one placement ratio.",
 "One asset is auto-cropped across placements, so the crop chooses the composition in every ratio but one.",
 "Keep all load-bearing content within a central square inset 10 percent from the shorter dimension.",
 "Automatic placement crops from the edges, so only a protected centre survives every ratio.",
 "A single protected region removes the need to produce and traffic separate assets per ratio.",
 ["Multi-placement Meta campaigns","Budget or time does not allow per-ratio assets"],
 ["Single-placement campaigns","Campaigns with per-placement production budget"],
 "One asset survives every crop","Composition is constrained to a centre square",
 "Multi-placement campaigns","Single-placement or fully resourced campaigns",
 ["Native per-placement compositions where budget allows"],
 [("Placing the brand mark near the frame edge","Cropped out entirely in at least one placement ratio","Mark placed inside the protected centre square")],
 "Survives automatic cropping across placements.",8,8,0.88,
 ch="facebook", **SOC)

LAY("layout.facebook_ad.social_proof_badge.001","Social proof badge placement","facebook_ad",
 "Include proof without letting it compete with the offer.",
 "Proof element confined to under 10 percent of frame area in a consistent corner, offer content unaffected.",
 ["Offer","Proof badge","Product","Call to action"],
 "Reads the offer, registers the badge as confirmation, proceeds.",
 "Badge enlarged until it competes with the offer, so the asset advertises the rating rather than the product.",
 "Proof elements are scaled up for credibility until they dominate and the offer is lost.",
 "Confine the proof element to under 10 percent of frame area in a consistent corner position.",
 "Proof confirms a decision rather than creating one, so it belongs in a subordinate, secondary reading position.",
 "A small consistent badge is found when sought and ignored when not.",
 ["Categories where proof influences conversion","Review-rich products"],
 ["New products with no proof to show","Brand awareness with no offer"],
 "Adds credibility without cost to the offer","Small size limits proof impact",
 "Conversion campaigns with real proof","New products and awareness work",
 ["Proof-led layout where the rating genuinely is the proposition"],
 [("Enlarging the proof badge for credibility","The asset advertises the rating rather than the product","Badge held under 10 percent of frame in a consistent corner")],
 "Adds proof without displacing the offer.",7,7,0.85,
 ch="facebook", obj="conversion", **SOC)

LAY("layout.facebook_ad.multi_product_collection.001","Collection ad layout","facebook_ad",
 "Present a hero with shoppable items beneath in a collection format.",
 "Hero image occupying the upper two thirds, four product tiles in a uniform row beneath at identical scale.",
 ["Hero image","Product tiles","Prices","Brand mark"],
 "Reads the hero, scans the tile row, returns to a chosen tile.",
 "Tiles varying in size or crop, which breaks the scan and implies a ranking.",
 "Collection formats reuse arbitrary product crops, so the tile row reads as inconsistent and is skipped.",
 "Give the hero the upper two thirds and place four tiles beneath at identical scale and crop.",
 "The tile row is scanned laterally, and lateral scanning depends on uniformity to stay fast.",
 "Uniform tiles keep the row scannable, which is where collection formats convert.",
 ["Meta collection and catalogue placements","Multi-product e-commerce"],
 ["Single-product campaigns","Brand awareness with no catalogue"],
 "Combines atmosphere with direct shopping","Individual products get small exposure",
 "E-commerce collection placements","Single-product and brand campaigns",
 ["Single hero where one product carries the campaign"],
 [("Using arbitrary product crops in the tile row","Breaks lateral scanning, so the row is skipped and the format wastes its advantage","Identical scale and crop across all four tiles")],
 "Keeps the shoppable row scannable.",7,7,0.85,
 ch="facebook", obj="conversion", **SOC)

LAY("layout.facebook_ad.headline_image_split.001","Headline and image split","facebook_ad",
 "Give a headline its own uncontested territory beside the image.",
 "Vertical split with image on one side and headline block on the other, no overlap and no scrim.",
 ["Headline","Image","Call to action","Brand mark"],
 "Reads the headline block, crosses to the image, returns to the action.",
 "The divide drifting off a clean axis, so neither side reads as dominant.",
 "Headlines are overlaid on busy images and rescued with scrims, damaging both the type and the image.",
 "Split the frame on a clean vertical axis and give the headline its own uncontested territory.",
 "Type over image always costs one of them, and a scrim is an admission the layout had no room for the words.",
 "Separation lets both operate at full strength without compromise.",
 ["Message-led paid social","Headlines carrying substantive argument"],
 ["Product hero assets where the image must dominate","Formats too small to sustain two territories"],
 "Both headline and image at full strength","Halves the available image area",
 "Message-led social advertising","Image-dominant product assets",
 ["Type placed in a naturally quiet image region"],
 [("Overlaying the headline on a busy image with a dark scrim","Damages the image and admits there was never room for the type","A clean split giving the headline its own territory")],
 "Lets headline and image each work fully.",7,8,0.86,
 ch="facebook", **SOC)

LAY("layout.facebook_ad.retargeting_recall.001","Retargeting recall layout","facebook_ad",
 "Re-engage a viewer who has already seen the product.",
 "The exact product image from the original visit at 60 percent of frame, with one changed element signalling new information.",
 ["Recognised product","The changed element","Offer or reason","Call to action"],
 "Recognises the product instantly, notices what changed, reads the reason.",
 "Using a different product image, which breaks recognition and turns retargeting into a first impression.",
 "Retargeting assets use new creative, so the recognition advantage that makes retargeting efficient is discarded.",
 "Reuse the exact product image from the original visit at 60 percent of frame with one changed element.",
 "Retargeting works on recognition, and recognition depends on visual identity with the original encounter.",
 "One changed element supplies a reason to re-engage without destroying the recognition.",
 ["Retargeting and remarketing campaigns","Considered purchase with a research phase"],
 ["Prospecting to cold audiences","Brand awareness campaigns"],
 "Preserves the recognition advantage","Creative fatigue sets in faster",
 "Retargeting campaigns","Cold prospecting",
 ["Fresh creative where the original asset performed poorly"],
 [("Using entirely new creative for retargeting","Discards the recognition that makes retargeting efficient, reverting to a first impression","The original product image retained with one changed element")],
 "Preserves the recognition retargeting depends on.",7,8,0.86,
 ch="facebook", obj="conversion", **SOC)

flush()
