# -*- coding: utf-8 -*-
"""Phase 2.1B — advertising layouts."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_layout_lib import LAY, flush

# ══════════════════ HERO PRODUCT LAYOUT ══════════════════
LAY("layout.hero_product.centred_authority.001", "Centred hero for premium authority", "hero_product",
 "Present a single product as the sole subject when authority is the message.",
 "Product on the exact vertical centre axis at 40 to 55 percent of frame height, symmetrical margins, no props.",
 ["Product","Brand mark","Headline"],
 "Locks on the product immediately and does not travel; the mark is found second.",
 "Product drifts a few percent off the true centre axis, which reads as imprecision rather than intent and undoes the authority.",
 "Premium product assets add props and angles to look considered, which reads as effort and lowers the perceived value.",
 "Place the product on the exact centre axis at 40 to 55 percent of frame height with no supporting props.",
 "Centre is the position of least visual tension, so an object placed there is not arguing for its position.",
 "Symmetry removes competing claims, leaving the product as the only thing the frame asserts.",
 ["Premium or luxury single-product assets","Objective is authority or brand awareness"],
 ["Promotional assets carrying price and urgency","Range communication with several products"],
 "Maximum stability and authority","Static, offers no space for substantial copy",
 "Premium hero and heritage work","Retail promotion and multi-product assets",
 ["Thirds placement where copy needs directed space"],
 [("Near-centre placement missing the axis by a few percent","Reads as an accident rather than a decision, which contradicts the authority being claimed","Exact centre alignment, verified against a guide")],
 "Raises perceived authority through visual stability.", 9, 9, 0.9,
 pos=["premium","luxury"], asset=["poster","product_hero"], obj=["awareness","product_launch"],
 related=["composition.centre.stillness_authority.001","layout.negative_space.premium_hero.001"])

LAY("layout.hero_product.three_quarter_volume.001", "Three-quarter hero for volume", "hero_product",
 "Show a product's form and depth when its shape is part of the purchase decision.",
 "Product rotated 30 to 45 degrees from front, occupying the centre two thirds, with one visible ground shadow.",
 ["Product form","Ground contact shadow","Headline","Brand mark"],
 "Enters on the nearest edge, travels around the form, settles on the shadow that grounds it.",
 "Rotation past 60 degrees, which hides the front face and turns the product into an unrecognisable silhouette.",
 "Products photographed flat-on lose the depth that communicates build quality and physical presence.",
 "Rotate the product 30 to 45 degrees from front and keep one visible ground contact shadow.",
 "A three-quarter view shows two faces at once, which is the minimum needed to read volume rather than outline.",
 "Visible depth plus a contact shadow tells the viewer the object is physical rather than rendered.",
 ["Products with distinctive three-dimensional form","Packaging, devices and containers"],
 ["Flat products such as cards or documents","Assets where the label must read straight on"],
 "Communicates form and physical presence","Label and front-face text partly foreshortened",
 "Dimensional product hero work","Label-led packaging communication",
 ["Straight-on framing where label legibility is the priority"],
 [("Rotating past 60 degrees for a more dynamic look","Hides the front face, so the product becomes hard to recognise on shelf","Rotation held between 30 and 45 degrees")],
 "Communicates build quality through visible volume.", 8, 8, 0.88,
 asset=["product_hero","poster"], related=["camera.lens.long_lens_respect.001"])

LAY("layout.hero_product.in_use_context.001", "Hero in use for benefit clarity", "hero_product",
 "Show the product working when the benefit is not obvious from the object alone.",
 "Product occupying roughly a third of frame, hand or user occupying another third, result visible in the remainder.",
 ["The result","The product","The user's hand","Brand mark"],
 "Enters on the result, traces back to the product that caused it, then to the brand.",
 "Product enlarged until it dominates, which returns the asset to a product shot and hides the benefit.",
 "Products whose benefit is invisible are shown in isolation, leaving the viewer to infer what it does.",
 "Show the product mid-use with the result visible, holding the product to roughly one third of frame.",
 "A benefit that cannot be seen must be demonstrated. Isolation asks the viewer to imagine, which they will not do.",
 "Showing cause and effect in one frame removes the inference step entirely.",
 ["Products with non-obvious benefit","Tools, appliances and applied products"],
 ["Products bought on appearance alone","Assets where packaging recognition is the objective"],
 "Benefit becomes visible rather than claimed","Product identification is weakened",
 "Demonstration-led categories","Shelf-recognition and packaging assets",
 ["Split layout pairing isolated product with a result inset"],
 [("Enlarging the product until it dominates the frame","Returns the asset to a product shot and hides the result that justified the layout","Product held to roughly a third, with the result given equal or greater weight")],
 "Makes an invisible benefit legible.", 8, 8, 0.87,
 obj=["conversion","product_launch"], related=["concept.discipline.earn_the_product_shot.001"])

LAY("layout.hero_product.scale_context.001", "Hero with scale reference", "hero_product",
 "Resolve size ambiguity for products bought remotely.",
 "Product centred with one familiar object or a hand at a consistent plane, occupying at most a quarter of the frame.",
 ["Product","Scale reference","Headline"],
 "Reads the product, checks the reference, returns to the product with size resolved.",
 "Reference object styled so attractively that it competes with the product for attention.",
 "Isolated product photography leaves size to assumption, which is the commonest cause of return in remote purchase.",
 "Include one familiar scale reference occupying no more than a quarter of the frame alongside the product.",
 "Absolute size cannot be inferred from an isolated object, and buyers substitute an assumption that is frequently wrong.",
 "One recognised reference resolves size definitively without a specification table.",
 ["E-commerce and remote purchase","Products whose size is not obvious"],
 ["Products with universally known dimensions","Brand imagery where a reference breaks the world"],
 "Removes the main cause of size-related returns","Adds an element that must be cast and styled",
 "E-commerce product sets","Abstract brand imagery",
 ["Dimensional overlay where a physical reference is inappropriate"],
 [("Styling the reference object to look attractive","It competes with the product and the viewer reads it as a second subject","Reference kept plain and held under a quarter of the frame")],
 "Removes size ambiguity in remote purchase.", 8, 8, 0.89,
 ch="website", obj="conversion", related=["photography.product.scale_reference.001"])

LAY("layout.hero_product.range_hero.001", "Hero within a range", "hero_product",
 "Introduce one product while keeping the range it belongs to visible.",
 "Hero at 60 percent of visual weight front and centre, range members at quarter scale along one edge.",
 ["Hero product","Launch message","Range members","Brand mark"],
 "Locks on the hero, reads the message, then scans the range row and returns.",
 "Range members scaled large enough to compete, which dissolves the launch focus into a catalogue.",
 "Launch assets show new and existing products at similar scale, so nothing reads as new.",
 "Give the hero at least 60 percent of visual weight and hold range members to a quarter of its scale.",
 "A launch is a claim about one item, and equal scale contradicts that claim before the copy can make it.",
 "Decisive scale separation makes the news legible without needing the word new.",
 ["Product launch within an existing range","Objective is launch awareness"],
 ["Range communication where no item leads","Comparison assets requiring equal weight"],
 "Launch news is legible from scale alone","Range members get minimal exposure",
 "Launch assets", "Range and comparison work",
 ["Uniform grid where range awareness is the objective"],
 [("Showing new and existing products at similar scale","Removes the visual claim that anything is new, leaving copy to carry it alone","Hero at 60 percent weight, range at quarter scale")],
 "Makes launch news legible through scale.", 8, 8, 0.87,
 obj="product_launch", asset=["poster","banner"])

LAY("layout.hero_product.floating_isolation.001", "Floating hero for clean isolation", "hero_product",
 "Isolate a product completely when the category demands clinical clarity.",
 "Product suspended with no visible support, soft shadow offset below, uniform ground with no horizon line.",
 ["Product","Offset shadow","Headline"],
 "Enters on the product and stays; the shadow confirms position without drawing attention.",
 "Shadow omitted entirely, which makes the product read as a cut-out pasted onto the background.",
 "Products shown on surfaces inherit the surface's associations, which can contradict a clinical or technical claim.",
 "Suspend the product with no visible support and place one soft offset shadow below it.",
 "Removing the surface removes every association it carried, leaving only the object and its claim.",
 "The offset shadow preserves physical credibility, which a hard cut-out destroys.",
 ["Clinical, technical and pharmaceutical categories","Objective is clarity over atmosphere"],
 ["Lifestyle and hospitality categories needing warmth","Products whose context is part of the story"],
 "Maximum clarity and neutrality","No atmosphere, low emotional engagement",
 "Clinical and technical categories","Lifestyle and atmosphere-led work",
 ["Surface-based placement where context adds meaning"],
 [("Removing the shadow to make the isolation cleaner","The product reads as a pasted cut-out and loses physical credibility","A soft offset shadow retained beneath the suspended product")],
 "Delivers clinical clarity without surface associations.", 7, 7, 0.85,
 ind=["technology","beauty"], asset="product_hero")

LAY("layout.hero_product.texture_macro.001", "Macro hero for material claims", "hero_product",
 "Make a material or formulation claim assessable by showing the material itself.",
 "Single plane of material filling 80 percent or more of frame, product edge or packaging implied at one border.",
 ["Material texture","Product edge","Claim line"],
 "Enters at the sharpest point of texture and explores the surface before finding the edge.",
 "Depth of field so shallow that only a sliver is sharp, leaving the texture unreadable across the frame.",
 "Texture and formulation claims are supported by full-product shots where the texture is below resolvable size.",
 "Fill 80 percent or more of the frame with a single plane of the material and imply the product at one border.",
 "A claim about a material cannot be evaluated on an image where the material occupies a few hundred pixels.",
 "Visible texture converts an asserted property into observable evidence.",
 ["Formulation, texture and material claims","Skincare, food and textile categories"],
 ["Packaging recognition assets","Range communication"],
 "Turns a claim into visible evidence","Loses packaging and brand identification",
 "Formulation-led hero work","Packaging and range communication",
 ["Split composition pairing packaging with a texture inset"],
 [("Using a full-bottle product shot to support a texture claim","The texture falls below resolvable size, so the claim has no visual support","Macro fill of the material itself, packaging carried on a separate asset")],
 "Makes material claims assessable.", 8, 8, 0.88,
 ind=["beauty","food_beverage"], related=["photography.beauty.texture_proximity.001"])

LAY("layout.hero_product.duo_pairing.001", "Paired hero for product relationships", "hero_product",
 "Show two products that are bought or used together without implying one is the hero.",
 "Two products at identical scale on a shared baseline, separated by one product width, no overlap.",
 ["The pair as a unit","Individual products","Relationship line","Brand mark"],
 "Reads the pair as one shape first, then separates it into two items.",
 "Overlapping the products, which creates a depth order the viewer reads as a ranking.",
 "Complementary products are staged with one in front, which implies a hierarchy the brand did not intend.",
 "Place both products at identical scale on a shared baseline separated by one product width.",
 "Any overlap or scale difference is read as a claim about relative importance, whether intended or not.",
 "Equal scale on a shared baseline states partnership rather than precedence.",
 ["Complementary or paired products","Bundle and routine communication"],
 ["Launch assets where one product must lead","Range assets with more than three items"],
 "States partnership without implying a ranking","No single focal point, lower stopping power",
 "Bundle and routine assets","Launches and large ranges",
 ["Hero-plus-supporting where one product genuinely leads"],
 [("Overlapping the two products for a more dynamic composition","Creates a depth order the viewer reads as a ranking of importance","Equal scale, shared baseline, one product width of separation")],
 "Communicates partnership without accidental hierarchy.", 7, 7, 0.85,
 asset=["poster","banner"])

# ══════════════════ PROBLEM SOLUTION LAYOUT ══════════════════
LAY("layout.problem_solution.split_before_after.001", "Split problem and solution", "problem_solution",
 "Show a change of state where the improvement is visible.",
 "Vertical split at exact centre, problem state left, resolved state right, identical framing and lighting both sides.",
 ["The difference between halves","Resolved state","Problem state","Claim line"],
 "Compares the two halves laterally, then settles on the resolved side.",
 "Framing or lighting differing between halves, which lets a viewer attribute the change to the photography.",
 "Before-and-after assets vary lighting or crop between states, so the comparison proves nothing.",
 "Split the frame at exact centre and hold framing, lighting and distance identical across both halves.",
 "A comparison is only evidence if every variable except the claimed one is held constant.",
 "Identical treatment on both sides makes the difference attributable to the product alone.",
 ["Demonstrable physical change","Cleaning, repair, grooming and maintenance categories"],
 ["Subjective or gradual improvements","Categories where regulation restricts comparative claims"],
 "Strong, self-evident proof","Invites scrutiny and regulatory attention",
 "Demonstrable change categories","Subjective benefit and regulated claims",
 ["Sequential frames where the change unfolds over time"],
 [("Using flattering light on the after side only","Lets the viewer attribute the change to lighting, which destroys the proof","Identical lighting, framing and distance on both halves")],
 "Provides self-evident proof of change.", 8, 8, 0.88,
 obj="conversion", asset=["poster","banner","social_ad"])

LAY("layout.problem_solution.tension_release.001", "Tension above, release below", "problem_solution",
 "Lead with a recognised frustration and resolve it in the same frame.",
 "Upper 40 percent carries the problem state, lower 60 percent the resolution, divided by a single horizontal break.",
 ["Problem state","Resolution","Product","Call to action"],
 "Enters at the top on the problem, drops through the break, lands on the resolution.",
 "Problem given more space than the resolution, which leaves the asset feeling negative.",
 "Solution-led advertising opens with the answer, so viewers with no recognised problem have no reason to engage.",
 "Give the problem the upper 40 percent and the resolution the lower 60, separated by one horizontal break.",
 "Recognition precedes interest. A viewer who has not recognised the problem has no use for the solution.",
 "Vertical order matches reading direction, so the sequence arrives in the intended order without instruction.",
 ["Categories where the problem is felt but unspoken","Objective is consideration or conversion"],
 ["Aspirational and luxury positioning","Categories where naming the problem is unflattering to the buyer"],
 "High relevance for problem-aware audiences","Negative framing risks brand association with the problem",
 "Problem-aware categories","Luxury and aspirational positioning",
 ["Benefit-led framing where the problem is unflattering"],
 [("Giving the problem more space than the resolution","Leaves the overall impression negative and attaches the problem to the brand","Resolution given the larger share, at roughly 60 percent")],
 "Creates relevance before offering the answer.", 8, 8, 0.86,
 obj=["conversion","awareness"], related=["concept.construction.tension_first.001"])

LAY("layout.problem_solution.sequential_steps.001", "Sequential steps layout", "problem_solution",
 "Show a process where the number of steps is itself the reassurance.",
 "Three or four equal panels in one row or column, each numbered, with identical framing and consistent subject scale.",
 ["Step count","Individual steps","Final result","Brand mark"],
 "Counts the panels first, then reads them in numbered order.",
 "Panels varying in size or framing, which breaks the reading order and implies some steps matter more.",
 "Processes are described in copy, so the viewer must read to learn whether the product is easy to use.",
 "Divide the frame into three or four equal numbered panels with identical framing in each.",
 "Ease of use is inferred from step count before any copy is read, and equal panels make the count instant.",
 "Numbering plus uniformity removes ambiguity about order and relative importance simultaneously.",
 ["Products with a multi-step process","Ease of use is a purchase driver"],
 ["Single-action products","Assets with room for only one message"],
 "Communicates simplicity before copy is read","Consumes the whole frame, no room for atmosphere",
 "Process-led categories","Single-message brand assets",
 ["Single-frame in-use shot where the process is one action"],
 [("Varying panel size to add visual interest","Breaks the reading order and implies some steps matter more than others","Equal panels with consistent framing and explicit numbering")],
 "Communicates ease of use before copy is read.", 7, 8, 0.87,
 obj=["conversion","product_launch"], asset=["poster","social_ad"])

LAY("layout.problem_solution.magnified_detail.001", "Magnified detail proof", "problem_solution",
 "Prove a claim about something too small to see at normal distance.",
 "Wide context shot occupying two thirds, with one circular or rectangular magnified inset at up to a quarter frame width.",
 ["Magnified detail","Context shot","Claim line","Brand mark"],
 "Enters on the inset, moves out to place it in context, returns to the inset.",
 "Inset placed without a visual link to its source point, leaving the viewer unable to locate what is magnified.",
 "Micro-level claims are asserted in copy because the evidence is below the resolution of a normal shot.",
 "Pair a context shot with one magnified inset at up to a quarter of frame width, visually linked to its source point.",
 "A claim about invisible detail needs the detail shown, and a single frame cannot hold both scales.",
 "The link line or matching shape lets the viewer place the magnified evidence without explanation.",
 ["Micro-level or material claims","Technical, textile and skincare categories"],
 ["Claims visible at normal scale","Formats too small to hold two levels of detail"],
 "Makes microscopic evidence legible","Adds visual complexity and a second focal point",
 "Technical and material proof","Simple single-message assets",
 ["Full-frame macro where context is not needed"],
 [("Placing the inset without linking it to its source","The viewer cannot tell what part is magnified, so the evidence proves nothing","A link line or matching shape connecting inset to source point")],
 "Makes invisible evidence assessable.", 7, 7, 0.85,
 ind=["technology","beauty","fashion"])

LAY("layout.problem_solution.negative_positive_pair.001", "Cross and tick pairing", "problem_solution",
 "Contrast a wrong and a right approach where the difference is behavioural rather than physical.",
 "Two equal panels side by side, incorrect approach marked at upper left, correct at upper right, identical subject in both.",
 ["Correct panel","Incorrect panel","Marks","Explanatory line"],
 "Scans both panels, resolves the marks, settles on the correct side.",
 "The incorrect panel styled more attractively, which makes the wrong approach more memorable than the right one.",
 "Educational advertising explains the correct approach in copy, which is read by almost nobody.",
 "Pair two equal panels with the incorrect approach left and correct right, using the same subject in both.",
 "Contrast is understood faster than instruction, and left-to-right order matches the reading direction of correction.",
 "Identical subjects isolate the behavioural difference as the only variable.",
 ["Educational and usage communication","Categories with common user error"],
 ["Brand and atmosphere work","Categories where showing error damages the brand"],
 "Teaches faster than instructional copy","Gives visual space to the wrong approach",
 "Educational and usage assets","Brand and atmosphere campaigns",
 ["Correct-only demonstration where showing error is risky"],
 [("Making the incorrect panel more visually appealing","The wrong approach becomes the memorable one, which inverts the lesson","Correct panel given the stronger treatment and the final reading position")],
 "Teaches correct usage without instructional copy.", 7, 7, 0.84,
 obj=["awareness","retention"])

LAY("layout.problem_solution.absence_presence.001", "Absence and presence framing", "problem_solution",
 "Communicate a benefit by showing what is missing rather than what is added.",
 "Single frame with a conspicuous empty region where the problem would be, product placed at the edge of that region.",
 ["The absence","Product","Claim line","Brand mark"],
 "Notices the emptiness first, searches for a cause, finds the product at its edge.",
 "Filling the empty region with supporting content, which erases the absence the layout depends on.",
 "Products that remove something are advertised by showing what they add, which misses the actual benefit.",
 "Reserve one conspicuous empty region representing the removed problem and place the product at its edge.",
 "Removal benefits are invisible by nature, and the only way to show a removal is to show the gap it leaves.",
 "An unexplained emptiness creates a question the product answers, which is stronger than a stated claim.",
 ["Products whose benefit is removal or prevention","Cleaning, odour, noise and blemish categories"],
 ["Additive benefits","Assets requiring dense information"],
 "Communicates removal, which additive layouts cannot","Requires interpretation and can be misread",
 "Removal and prevention categories","Additive benefit categories",
 ["Before-and-after split where the removal is physically visible"],
 [("Filling the empty region with supporting copy","Erases the absence the entire layout depends on","The region left genuinely empty, with copy moved elsewhere")],
 "Makes a removal benefit visible.", 7, 7, 0.82,
 obj=["awareness","conversion"])

# ══════════════════ COMPARISON LAYOUT ══════════════════
LAY("layout.comparison.side_by_side_parity.001", "Side by side comparison", "comparison",
 "Compare two options where the difference must be judged by the viewer.",
 "Two equal columns with a shared baseline, identical scale and lighting, one dividing rule at exact centre.",
 ["The difference","Both options","Column labels","Conclusion line"],
 "Scans laterally between columns at each row, then reads down.",
 "Unequal column widths, which is read as a recommendation and destroys the appearance of fair comparison.",
 "Comparison assets favour one side through scale or styling, which readers detect and discount.",
 "Give both options identical column width, scale and lighting, divided by one rule at exact centre.",
 "A comparison that visibly favours one side is read as advertising rather than evidence, and discounted accordingly.",
 "Visible fairness is what makes the conclusion credible when it arrives.",
 ["Feature or specification comparison","Considered purchase categories"],
 ["Categories where naming a competitor is legally risky","Emotional or aspirational positioning"],
 "Credible because visibly fair","Gives equal exposure to the alternative",
 "Considered purchase and specification categories","Emotional and aspirational categories",
 ["Single-option demonstration where comparison is legally restricted"],
 [("Making the favoured column wider or brighter","Readers detect the bias and discount the whole comparison","Identical column width, scale and lighting on both sides")],
 "Makes a comparison credible through visible fairness.", 8, 8, 0.87,
 obj="conversion", asset=["poster","banner"])

LAY("layout.comparison.stacked_tiers.001", "Stacked tier comparison", "comparison",
 "Present three or more tiers where position implies rank.",
 "Horizontal bands stacked vertically, recommended tier given 20 percent more height and a distinct ground.",
 ["Recommended tier","Tier names","Differences between tiers","Price"],
 "Enters on the emphasised tier, then scans up and down to place it against the others.",
 "Every tier given identical emphasis, which leaves the viewer to do the ranking work themselves.",
 "Tiered offerings are presented as equal options, so the viewer must construct the comparison unaided.",
 "Stack tiers vertically and give the recommended tier 20 percent more height and a distinct ground.",
 "Choice paralysis rises with equal options, and a visible recommendation reduces the decision to accept or reject.",
 "Extra height and a changed ground mark the recommendation without needing a badge or label.",
 ["Tiered pricing or product ranges","Three to five options"],
 ["Two options, where side by side is clearer","More than six options"],
 "Reduces choice paralysis","Steers the decision, which some categories should not do",
 "Tiered pricing and subscription offers","Neutral catalogue presentation",
 ["Side-by-side columns for exactly two options"],
 [("Presenting all tiers with identical emphasis","Leaves the viewer to construct the ranking, which raises abandonment","One tier emphasised through height and ground")],
 "Reduces choice paralysis in tiered offers.", 7, 8, 0.86,
 ch="website", obj="conversion")

LAY("layout.comparison.overlay_transition.001", "Overlay slider comparison", "comparison",
 "Compare two states of the same subject in one frame rather than two.",
 "Single frame divided by one diagonal or vertical seam, identical subject and framing on both sides of the seam.",
 ["The seam","Both states","Subject","Claim line"],
 "Locks on the seam, then travels outward in both directions.",
 "Subject shifting position between the two sides, which breaks the illusion of a single frame.",
 "Side-by-side comparison doubles the space needed and halves the size of each state.",
 "Divide one frame with a single seam and hold the subject in identical position on both sides.",
 "Comparing within one frame keeps both states at full size, and the seam makes the difference unmissable.",
 "A shared frame removes the mental work of aligning two separate images.",
 ["Surface, colour or condition change on a fixed subject","Space-constrained formats"],
 ["Comparisons involving different objects","Changes in shape or position"],
 "Full-size comparison in a single frame","Requires perfectly registered source images",
 "Fixed-subject state comparison","Different-object comparison",
 ["Two-panel split where the subjects genuinely differ"],
 [("Allowing the subject to shift between the two sides","Breaks the single-frame illusion and the comparison reads as two images","Subject held in identical position, registered precisely")],
 "Compares two states at full size in one frame.", 7, 7, 0.84,
 asset=["social_ad","banner"])

LAY("layout.comparison.feature_matrix.001", "Feature matrix layout", "comparison",
 "Compare several options across several attributes without narrative.",
 "Grid with options as columns and attributes as rows, alternating row tint, no more than five columns and eight rows.",
 ["Column headers","Row of the decisive attribute","Cell marks","Recommendation"],
 "Scans headers, drops to the attribute that matters most, reads laterally across it.",
 "Exceeding five columns or eight rows, past which the grid stops being readable at a glance.",
 "Complex comparisons are written as prose, which nobody reads and nobody can scan.",
 "Build a grid of at most five option columns and eight attribute rows with alternating row tint.",
 "Comparison across two dimensions is a table by nature, and forcing it into prose removes the ability to scan.",
 "Alternating tint keeps lateral reading accurate, which is where matrix comprehension usually fails.",
 ["Multi-attribute comparison","Technical and considered purchase categories"],
 ["Emotional purchase categories","Formats below tablet size"],
 "Scannable multi-dimensional comparison","Cold and information-dense, no emotional engagement",
 "Technical purchase support","Brand and emotional campaigns",
 ["Highlighted single-attribute comparison where one attribute decides"],
 [("Adding a ninth and tenth attribute row for completeness","Past eight rows the grid can no longer be scanned, so all comparison stops","Rows limited to the eight attributes that actually influence the decision")],
 "Makes multi-attribute comparison scannable.", 7, 7, 0.85,
 ch="website", ind="technology")

LAY("layout.comparison.us_versus_category.001", "Brand versus category norm", "comparison",
 "Contrast a brand against the category default without naming a competitor.",
 "Left two thirds shows the generic category approach in muted treatment, right third shows the brand at full contrast.",
 ["Brand side","Category side","Contrast between them","Claim line"],
 "Enters on the muted field, moves right into the brand region, stays there.",
 "The category side rendered attractively, which makes the norm look preferable to the alternative.",
 "Differentiation claims are stated in copy, which asks the viewer to accept an assertion without evidence.",
 "Give the category norm two thirds in muted treatment and the brand one third at full contrast.",
 "Naming a competitor is legally risky, but showing the category norm is not, and the contrast makes the claim self-evident.",
 "Muting the larger area makes the smaller branded area dominant despite its size, which states the argument structurally.",
 ["Differentiation and positioning claims","Saturated categories"],
 ["Categories with fewer than three competitors","Regulated comparative claims"],
 "Differentiation shown rather than asserted","Gives visual space to the category norm",
 "Saturated category positioning","Regulated comparative advertising",
 ["Direct feature comparison where naming competitors is permitted"],
 [("Rendering the category side attractively for visual balance","Makes the norm look preferable, which inverts the argument","Category side muted, brand side at full contrast")],
 "Shows differentiation rather than asserting it.", 8, 8, 0.85,
 obj="awareness", related=["differentiation.universal.sameness_test.001"])

LAY("layout.comparison.scale_of_difference.001", "Scale comparison layout", "comparison",
 "Communicate a quantitative difference where the number alone is abstract.",
 "Two objects or bars at true relative scale sharing one baseline, with the ratio stated once in type.",
 ["Size difference","The two quantities","Stated ratio","Brand mark"],
 "Reads the size difference immediately, then finds the number that confirms it.",
 "Scaling by height only when area is what the eye reads, which exaggerates the difference several times over.",
 "Quantitative claims are stated numerically, and numbers without a physical referent are not felt.",
 "Render the two quantities at true relative scale on one shared baseline and state the ratio once.",
 "A number is understood but a size difference is perceived, and perception is what produces conviction.",
 "True scaling keeps the claim honest, which matters because exaggerated scaling is easily detected.",
 ["Quantitative superiority claims","Capacity, duration and concentration claims"],
 ["Qualitative differences","Differences too small to see at true scale"],
 "Makes a number physically felt","Only works when the difference is large enough to see",
 "Quantitative claims with a large margin","Small or qualitative differences",
 ["Stated numbers with a supporting icon where the difference is small"],
 [("Scaling by height alone when the shapes read as areas","Doubling height quadruples apparent area, exaggerating the claim several times","Scaling by the dimension the eye actually reads, usually area")],
 "Turns an abstract number into a perceived difference.", 7, 7, 0.86,
 obj="conversion")

flush()
