# -*- coding: utf-8 -*-
"""Phase 2.1 expansion — batch 2: visual craft intelligence."""
import io, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_lib import K, flush

P = "photography"; C = "camera"; L = "lighting"; CO = "composition"; CL = "color"; M = "material"

# ═══════════════════ CAMERA LANGUAGE ═══════════════════
K("camera.lens.long_lens_respect.001", "Long lens as respect and distance", C, "lens_psychology",
  stages=["visual_direction","production"], pos=["premium","luxury"],
  problem="Premium product work is shot wide because it fits more in, which flattens the subject into a catalogue record.",
  decision="Use a long focal length from a greater distance so perspective compresses and the subject sits calmly in its plane.",
  reasoning="Compression removes the sense of an observer leaning in. The subject appears observed rather than inspected, which reads as respect.",
  why="Reduced perspective distortion keeps proportions true, and true proportions are what a viewer reads as quality.",
  use=["Premium or luxury product and portrait work","Objective is desirability rather than information"],
  avoid=["Small spaces where working distance is impossible","Contexts requiring environmental storytelling around the subject"],
  adv="Calm, respectful, premium reading of the subject", lim="Requires physical distance and isolates subject from context",
  suit="Studio and controlled premium product work", unsuit="Environmental storytelling and cramped locations",
  alts=["Standard focal length where context must remain legible"],
  aps=[("Wide lens close to the subject to fit product and environment together",
        "Exaggerates the nearest edge and distorts proportion, which reads as cheap",
        "Longer focal length from further back, with environment implied rather than included")],
  profile=[("kind","photography"),("lens_psychology","Compression reads as composure and distance as respect; the viewer observes rather than intrudes."),("framing_psychology","Subject sits in its own plane, separate from the world behind it."),("depth_of_field","Shallow by consequence, isolating without needing an effect.")],
  impact="Raises perceived quality through undistorted proportion.", iscore=8, prio=8, conf=0.88)

K("camera.lens.wide_lens_immersion.001", "Wide lens as immersion and place", C, "lens_psychology",
  stages=["visual_direction","production"], ind=["hospitality","food_beverage"],
  problem="Venue and place work shot long removes the sense of being inside the space, which is the only thing the imagery is selling.",
  decision="Use a wide focal length from inside the space so the viewer occupies the room rather than observing it.",
  reasoning="Wide perspective expands near-to-far relationships, which reproduces how a body experiences being somewhere.",
  why="Occupancy of the frame is what converts a room from inventory into an experience the viewer can anticipate.",
  use=["Hospitality, venue and place-led work","Objective is anticipation of an experience"],
  avoid=["Product hero work where proportion accuracy is the point","Portrait work where facial distortion is unacceptable"],
  adv="Viewer feels inside the space", lim="Distorts anything near the frame edge, including faces and products",
  suit="Interiors and place storytelling", unsuit="Product hero and portrait work",
  alts=["Standard focal length where both product and place must stay accurate"],
  aps=[("Wide lens used on a face or a product placed near the frame edge",
        "Stretches the nearest features and reads as an error rather than a choice",
        "Keeping people and products near the optical centre, or switching focal length")],
  profile=[("kind","photography"),("lens_psychology","Expansion reads as presence; the viewer is inside rather than outside."),("framing_psychology","Near and far are exaggerated, which produces the feeling of a body in a room."),("camera_angle","Eye level from a seated or standing height the guest would actually occupy.")],
  impact="Converts a room into an anticipated experience.", iscore=8, prio=8, conf=0.85)

K("camera.angle.eye_level_equality.001", "Eye level as equality", C, "angle",
  stages=["visual_direction"], ind=["fashion","food_beverage"],
  problem="Camera height is chosen for convenience, which accidentally assigns a power relationship the brief never asked for.",
  decision="Place the camera at the subject's own eye height when the brand wants to be read as a peer.",
  reasoning="Height encodes status. Looking down diminishes, looking up elevates, and level implies equality, regardless of anything else in frame.",
  why="Peer positioning removes the hierarchy that makes advertising feel like being spoken down to.",
  use=["Brands positioned as peers rather than authorities","Gen Z and community-led communication"],
  avoid=["Luxury positioning built on aspiration and distance","Authority categories such as clinical or financial"],
  adv="Reads as equal and trustworthy", lim="Removes the aspirational lift some categories need",
  suit="Peer-positioned and community brands", unsuit="Aspirational luxury and authority categories",
  alts=["Slight low angle where the brand should read as aspirational"],
  aps=[("Shooting down at a subject because the tripod was already at that height",
        "Assigns an unintended power relationship that undermines a peer positioning",
        "Camera set deliberately to the subject's own eye height")],
  profile=[("kind","photography"),("camera_angle","Level with the subject's eyes asserts equality before any content is read."),("framing_psychology","The viewer is addressed as a peer rather than an audience.")],
  impact="Aligns implied power relationship with brand positioning.", iscore=7, prio=8, conf=0.87)

K("camera.angle.overhead_control.001", "Overhead as order and control", C, "angle",
  stages=["visual_direction"], ind="food_beverage", asset=["social_ad","poster"],
  problem="Overhead food photography is used as a default style rather than for what the angle actually communicates.",
  decision="Reserve the overhead angle for arrangements where the relationship between items is the message, not the food itself.",
  reasoning="Overhead removes depth and volume, converting a scene into a diagram. That serves composition and abundance but not appetite.",
  why="Using it only where relationships matter keeps appetite work in angles that preserve volume and texture.",
  use=["Multi-item spreads where arrangement is the story","Abundance and variety messaging"],
  avoid=["Single-dish appetite work needing volume and texture","Drinks where height and layering are the appeal"],
  adv="Clear, orderly, strong for abundance", lim="Removes depth and volume, weakening appetite response",
  suit="Spreads, sharing and variety messaging", unsuit="Single hero dishes and layered drinks",
  alts=["Three-quarter angle where volume and texture must read"],
  aps=[("Overhead applied to a single hero dish or a tall drink",
        "Flattens the volume that produces the appetite response",
        "Three-quarter or near-level angle preserving height and depth")],
  profile=[("kind","photography"),("camera_angle","Directly above removes volume and converts a scene into a plan."),("framing_psychology","The viewer surveys rather than reaches for the subject.")],
  impact="Matches angle to the appetite mechanism it serves.", iscore=7, prio=7, conf=0.84)

# ═══════════════════ LIGHTING INTELLIGENCE ═══════════════════
K("lighting.soft.single_source_calm.001", "Single soft source for calm authority", L, "soft_directional",
  stages=["visual_direction","production"], pos=["premium","luxury"],
  problem="Premium work is over-lit from several directions to remove all shadow, which also removes the form that makes a surface read as real.",
  decision="Light with one large soft source at roughly 45 degrees and let a single soft shadow fall unfilled.",
  reasoning="One source produces one logic. Multiple sources create competing shadow directions the eye reads as artificial even when it cannot name why.",
  why="A single unfilled shadow gives the object weight and place, which is what separates a photograph from a render.",
  use=["Premium product and portrait work","Objective is quality perception"],
  avoid=["High-energy promotional work needing visible dynamism","Categories where shadow implies poor hygiene, such as clinical"],
  adv="Calm, real, premium surface reading", lim="Low energy, can read as static in high-tempo channels",
  suit="Premium product and brand work", unsuit="Promotional and high-energy formats",
  alts=["Two-source setup where a rim is needed to separate subject from ground"],
  aps=[("Filling every shadow to remove contrast entirely",
        "Removes the form and weight that make the surface read as physically present",
        "One key source with a single shadow allowed to fall unfilled")],
  profile=[("kind","lighting"),("emotional_perception","Calm, composed, unhurried; the subject appears settled rather than presented."),("commercial_usage","Standard for premium skincare, spirits, watches and considered-purchase categories."),("technical_character","One large source at about 45 degrees, no fill on the shadow side, single shadow direction.")],
  impact="Produces premium surface reading with physical weight.", iscore=9, prio=9, conf=0.9)

K("lighting.hard.direct_energy.001", "Hard light for energy and edge", L, "hard_direct",
  stages=["visual_direction","production"], aud="gen_z", ch=["instagram","tiktok"],
  problem="Youth-facing work is softened to look premium, which removes the edge the audience reads as contemporary.",
  decision="Use a small hard source producing defined shadow edges and specular highlights, without fill.",
  reasoning="Hard light carries the visual signature of direct sun and flash, which this audience associates with unmediated reality.",
  why="Defined shadow edges survive compression and small screens, where soft gradation flattens into mush.",
  use=["Gen Z and youth-facing social work","Fashion and streetwear categories"],
  avoid=["Mature premium categories where softness signals quality","Skin-focused beauty where texture must be flattered"],
  adv="Contemporary, high-energy, survives compression", lim="Unflattering on skin, reads as cheap in premium contexts",
  suit="Social fashion and youth categories", unsuit="Premium beauty and mature audiences",
  alts=["Soft light where skin quality is the product claim"],
  aps=[("Applying hard direct light to a skincare product claim about smoothness",
        "Emphasises the exact texture the product claims to reduce",
        "Soft directional light where the claim concerns skin surface")],
  profile=[("kind","lighting"),("emotional_perception","Immediate, unfiltered, energetic; reads as a real moment rather than a set-up."),("commercial_usage","Standard for streetwear, youth beverage, music and event communication."),("technical_character","Small hard source, defined shadow edge, specular highlights, minimal fill.")],
  impact="Signals contemporary energy and survives small-screen compression.", iscore=8, prio=8, conf=0.86)

K("lighting.backlight.appetite_translucency.001", "Backlight for appetite and translucency", L, "backlight",
  stages=["visual_direction","production"], ind="food_beverage",
  problem="Food and drink lit from the front looks documented rather than desirable, because the material never shows what it is made of.",
  decision="Place the key light behind the subject at roughly three quarters back so translucent materials glow from within.",
  reasoning="Appetite response is driven by evidence of moisture, freshness and internal structure, all of which only appear when light passes through the material.",
  why="Transmitted light reveals structure that reflected light hides, which is the physical basis of appetite appeal.",
  use=["Drinks, sauces, fruit and any translucent food","Appetite is a primary objective"],
  avoid=["Opaque packaged goods where nothing transmits","Work needing full label legibility"],
  adv="Strong appetite response and material honesty", lim="Front detail and labels fall dark without fill",
  suit="Drinks and fresh food hero work", unsuit="Packaging and label-led communication",
  alts=["Three-quarter front light where the label must dominate"],
  aps=[("Flat frontal lighting on a drink or a sauce",
        "Shows the outside of the material and none of the internal structure that triggers appetite",
        "Key placed behind at three quarters, with a small front fill for label legibility")],
  profile=[("kind","lighting"),("emotional_perception","Fresh, alive, desirable; the material appears to hold light rather than block it."),("commercial_usage","Standard for beverage, fresh produce, honey, oil and sauce categories."),("technical_character","Key behind at about 3/4 back, low front fill, flag to protect lens from flare.")],
  impact="Produces the physical basis of appetite response.", iscore=9, prio=9, conf=0.89)

K("lighting.ambient.available_light_honesty.001", "Available light as honesty signal", L, "available_light",
  stages=["visual_direction"], aud="gen_z", ind=["food_beverage","hospitality","fashion"],
  problem="Venue and lifestyle work is lit to studio standard, which removes the evidence that the moment was real.",
  decision="Work with the venue's own light at its characteristic hour and add only enough fill to hold shadow detail.",
  reasoning="Audiences read lighting provenance accurately. Studio light in a real place signals staging, which contradicts an authenticity claim.",
  why="Available light carries the colour and direction of an actual time and place, which cannot be convincingly faked.",
  use=["Authenticity-led hospitality and lifestyle work","Gen Z and community-facing communication"],
  avoid=["Product hero work requiring controlled surface rendering","Venues whose own light is genuinely poor"],
  adv="Reads as real and unstaged", lim="Low control, dependent on time of day and weather",
  suit="Venue, lifestyle and social content", unsuit="Controlled product hero photography",
  alts=["Augmented available light where the venue's own light is insufficient"],
  aps=[("Full studio lighting deployed inside a venue for an authenticity campaign",
        "The lighting contradicts the claim, and audiences detect the contradiction before the message",
        "The venue's own light at its best hour, with minimal fill")],
  profile=[("kind","lighting"),("emotional_perception","Unstaged and present; the viewer reads the moment as having actually happened."),("commercial_usage","Standard for hospitality, lifestyle and creator-led social content."),("technical_character","Existing sources only, small bounce or negative fill, no visible added key.")],
  impact="Supports authenticity claims that studio lighting contradicts.", iscore=8, prio=8, conf=0.85)

# ═══════════════════ COMPOSITION INTELLIGENCE ═══════════════════
K("composition.centre.stillness_authority.001", "Centred composition for authority", CO, "centred",
  stages=["visual_direction","design"], pos=["premium","luxury"], asset=["poster","product_hero"],
  problem="Centred composition is avoided as naive, which removes the strongest available signal of confidence.",
  decision="Place the subject on the exact centre axis with symmetrical margin when the brand should read as certain.",
  reasoning="Centre is the position of least tension. An object placed there is not competing for its place, which reads as assurance.",
  why="Symmetry removes visual argument, so nothing in the frame contradicts the claim of authority.",
  use=["Premium and luxury single-subject work","Objective is authority or heritage"],
  avoid=["Dynamic or energetic communication","Frames needing space for substantial copy"],
  adv="Maximum stability and authority", lim="Static, no implied movement or direction",
  suit="Premium hero and heritage work", unsuit="Energetic promotion and copy-heavy layouts",
  alts=["Off-centre placement where movement or copy space is needed"],
  aps=[("Near-centre placement that misses the true axis by a small margin",
        "Reads as an accident rather than a decision, which undermines the authority it was meant to assert",
        "Exact centre, or a decisive offset with clear intent")],
  profile=[("kind","composition"),("structure","Single subject on the vertical centre axis with equal left and right margin."),("attention_effect","Attention settles immediately and does not travel, which reads as certainty."),("failure_pattern","Almost-centred placement, which reads as imprecision rather than intent.")],
  impact="Asserts authority through visual stability.", iscore=8, prio=8, conf=0.88)

K("composition.diagonal.movement_energy.001", "Diagonal structure for movement", CO, "diagonal",
  stages=["visual_direction","design"], ind=["fashion","food_beverage"], obj=["conversion","awareness"],
  problem="Energy is attempted through colour and quantity, which produces noise rather than direction.",
  decision="Build the frame on a single dominant diagonal so the eye travels along one axis at speed.",
  reasoning="The eye follows continuous lines. A diagonal is the only orientation that implies motion, because neither horizontal nor vertical does.",
  why="One diagonal produces speed without clutter, so the energy comes from structure rather than from added elements.",
  use=["High-energy promotion and fashion movement","Objective is urgency or dynamism"],
  avoid=["Premium calm and heritage positioning","Frames requiring careful copy placement"],
  adv="Genuine energy from structure, not from clutter", lim="Destabilising, unsuitable for calm or premium tone",
  suit="Promotional and movement-led work", unsuit="Premium calm and information-dense layouts",
  alts=["Centred or grid structure where calm is required"],
  aps=[("Adding many elements to create energy",
        "Produces visual noise, which raises effort and lowers attention rather than adding speed",
        "One dominant diagonal with fewer elements")],
  profile=[("kind","composition"),("structure","A single dominant diagonal from one corner region toward the opposite."),("attention_effect","The eye accelerates along the axis, producing a reading of motion."),("failure_pattern","Competing diagonals, which cancel into visual noise.")],
  impact="Creates energy structurally rather than by addition.", iscore=7, prio=7, conf=0.83)

K("composition.negative_space.value_signal.001", "Negative space as value signal", CO, "negative_space",
  stages=["visual_direction","design"], pos=["premium","luxury"],
  problem="Empty space is treated as wasted inventory and filled with secondary content until the frame reads as ordinary.",
  decision="Reserve at least half the frame as genuinely empty and defend it against secondary content.",
  reasoning="Space is expensive. A brand that leaves it empty demonstrates it does not need to fill it, which is the signal of confidence.",
  why="Emptiness concentrates the whole attention budget on one element, which raises that element's perceived worth.",
  use=["Premium and luxury single-message assets","Objective is value perception"],
  avoid=["Retail promotion carrying offer, price and urgency","Formats where platform chrome already consumes free space"],
  adv="Strong value signal and unambiguous focus", lim="Carries far less information per asset",
  suit="Premium brand and launch work", unsuit="Retail and multi-message promotion",
  alts=["Structured grid where several messages genuinely must coexist"],
  aps=[("Filling reserved space with a secondary product or supporting line",
        "Returns the frame to category average and removes the signal the space was carrying",
        "Leaving the reserved area genuinely empty and moving secondary content to another asset")],
  profile=[("kind","composition"),("structure","Subject occupying under half the frame, remainder held empty."),("attention_effect","Attention concentrates rather than distributes, raising perceived value."),("failure_pattern","Progressive backfilling of the empty area during stakeholder review.")],
  impact="Converts restraint into perceived value.", iscore=8, prio=9, conf=0.9,
  related=["layout.negative_space.premium_hero.001"])

K("composition.layering.depth_credibility.001", "Foreground layering for depth credibility", CO, "layering",
  stages=["visual_direction"], ind=["hospitality","food_beverage"],
  problem="Scenes rendered on a single plane read as staged sets, because real spaces always have something between the viewer and the subject.",
  decision="Place one deliberately out-of-focus element in the near foreground, occupying no more than a fifth of the frame.",
  reasoning="Real viewing always includes obstruction. Its complete absence signals a constructed set, which undermines an authenticity claim.",
  why="A single soft foreground element supplies depth and the impression of an unposed vantage point at almost no cost to clarity.",
  use=["Venue, lifestyle and in-situ work","Authenticity is part of the claim"],
  avoid=["Product hero work requiring unobstructed clarity","Packaging and label communication"],
  adv="Depth and the impression of a real vantage point", lim="Costs some clarity and can crowd a small format",
  suit="Environmental and lifestyle work", unsuit="Product hero and packaging",
  alts=["Clean single-plane framing where product clarity is paramount"],
  aps=[("Foreground element large enough to compete with the subject",
        "Converts a depth cue into an obstruction and buries the message",
        "Foreground held under a fifth of the frame and well out of focus")],
  profile=[("kind","composition"),("structure","Near soft element, sharp subject plane, implied depth behind."),("attention_effect","Depth is inferred immediately, which reads as a real vantage point."),("failure_pattern","Oversized foreground competing with the subject for attention.")],
  impact="Adds credible depth to environmental work.", iscore=7, prio=7, conf=0.84)

# ═══════════════════ COLOR INTELLIGENCE ═══════════════════
K("color.restraint.premium_palette.001", "Restrained palette for premium perception", CL, "premium_palette",
  stages=["visual_direction","design"], pos=["premium","luxury"],
  problem="Premium work adds colour to feel considered, and each addition lowers the perception it was meant to raise.",
  decision="Limit the palette to two neutrals and one accent drawn from the product itself, and use the accent on under a tenth of the frame.",
  reasoning="Colour variety reads as effort to attract. Restraint reads as confidence that attraction is unnecessary.",
  why="An accent taken from the product ties every colour decision back to the object, so nothing looks arbitrary.",
  use=["Premium and luxury positioning","Single-subject brand and launch work"],
  avoid=["Youth and value categories where energy is the signal","Categories where colour variety is the product, such as cosmetics ranges"],
  adv="Coherent, confident, premium reading", lim="Low visual energy and lower stopping power in busy feeds",
  suit="Premium brand and hero work", unsuit="Range communication and youth categories",
  alts=["Monochrome treatment where even one accent is too much"],
  aps=[("Introducing a second accent colour to add interest",
        "Splits the palette's logic so neither accent reads as deliberate",
        "One accent drawn from the product, used sparingly")],
  profile=[("kind","color"),("brand_perception","Confident, established, unhurried; a brand that does not need to attract."),("emotional_association","Calm and control before any content is decoded."),("cultural_note","In Vietnam, restrained palettes read as imported premium; warmth may be needed for local heritage brands.")],
  impact="Raises premium perception through palette discipline.", iscore=8, prio=9, conf=0.88)

K("color.warmth.hospitality_welcome.001", "Warm neutrals for welcome", CL, "warm_neutral",
  stages=["visual_direction","design"], ind=["hospitality","food_beverage"],
  problem="Venue work adopts cool contemporary palettes that read as designed rather than as welcoming.",
  decision="Build from warm neutrals in the amber to clay range and keep cool tones below a quarter of the frame.",
  reasoning="Warm tones are read as skin, firelight and cooked food. The association is physiological and arrives before any interpretation.",
  why="Warmth produces approach behaviour, which is precisely the response a venue needs.",
  use=["Hospitality, cafe and restaurant communication","Objective is visit intent"],
  avoid=["Clinical or technology categories where cool signals precision","Premium minimal positioning built on coolness"],
  adv="Immediate approachability and welcome", lim="Reads as less contemporary and less precise",
  suit="Venue and food communication", unsuit="Technology and clinical categories",
  alts=["Cool neutral palette where precision is the brand claim"],
  aps=[("Cool grey and blue palette applied to a neighbourhood cafe",
        "Signals a designed environment rather than a welcoming one, which suppresses approach",
        "Warm neutral base with cool tones held to accent proportions")],
  profile=[("kind","color"),("brand_perception","Welcoming, human, established in its neighbourhood."),("emotional_association","Approach and comfort, triggered before content is read."),("cultural_note","Warm palettes align with Vietnamese hospitality convention; cool minimalism can read as unfriendly.")],
  impact="Produces approach behaviour toward venues.", iscore=8, prio=8, conf=0.86)

K("color.contrast.thumbnail_survival.001", "Contrast for thumbnail survival", CL, "contrast",
  stages=["design","production"], ch=["instagram","tiktok","facebook"], asset=["social_ad","thumbnail"],
  problem="Palettes are approved at full size and deployed at thumbnail scale, where low-contrast schemes collapse into a single tone.",
  decision="Hold at least a four-to-one luminance ratio between subject and background, and verify the frame in greyscale before approval.",
  reasoning="At thumbnail scale hue differences disappear before luminance differences do, so a palette separated only by hue merges.",
  why="A greyscale check tests the only channel that survives scale reduction and compression.",
  use=["Social advertising and video thumbnails","Any asset viewed below 200 pixels wide"],
  avoid=["Print and large format where scale is guaranteed","Deliberately low-contrast art direction with a reach trade-off accepted"],
  adv="Message survives real viewing scale", lim="Constrains subtle tonal palettes",
  suit="Social and thumbnail formats", unsuit="Print, out-of-home and gallery formats",
  alts=["Shape and silhouette separation where a low-contrast palette is mandated"],
  aps=[("Separating subject from background by hue alone",
        "Hue separation vanishes at thumbnail scale and under compression, merging the subject into the ground",
        "Luminance separation of at least four to one, verified in greyscale")],
  profile=[("kind","color"),("brand_perception","Legible and confident at any scale."),("emotional_association","Clarity; the viewer is not asked to work."),("cultural_note","Applies universally; scale reduction is a physical constraint rather than a cultural one.")],
  impact="Preserves legibility at real viewing scale.", iscore=8, prio=9, conf=0.92)

K("color.saturation.category_signal.001", "Saturation as category positioning", CL, "saturation",
  stages=["visual_direction"],
  problem="Saturation is set by taste rather than by what the level signals about price and audience.",
  decision="Set saturation deliberately by tier: low for premium, moderate for mainstream, high for youth and value.",
  reasoning="Saturation correlates with price expectation across categories. High saturation signals volume and accessibility; restraint signals scarcity.",
  why="Matching saturation to tier keeps the visual promise consistent with the actual price, which protects trust.",
  use=["Any positioning decision where price tier is known"],
  avoid=["Brands deliberately disrupting category colour convention as their differentiator"],
  adv="Coherence between visual promise and price", lim="Reinforces convention rather than challenging it",
  suit="Establishing brands and category-consistent positioning", unsuit="Deliberate category disruption",
  alts=["Inverted saturation as a disruption strategy where the brand can sustain it"],
  aps=[("High saturation applied to a luxury product",
        "Signals volume and accessibility, which contradicts a scarcity-based price",
        "Saturation lowered to match the tier the price actually occupies")],
  profile=[("kind","color"),("brand_perception","Price tier is read from saturation before the price is seen."),("emotional_association","High saturation reads as energy and availability; low reads as scarcity and control."),("cultural_note","Vietnamese mass-market convention tolerates higher saturation than Western equivalents.")],
  impact="Aligns colour energy with price positioning.", iscore=7, prio=8, conf=0.82)

# ═══════════════════ MATERIAL INTELLIGENCE ═══════════════════
K("material.glass.edge_reading.001", "Reading glass through its edges", M, "glass",
  stages=["visual_direction","production"], cat=["skincare","fragrance","alcohol"],
  problem="Glass is lit frontally, which fills it with reflections of the studio and destroys the transparency being sold.",
  decision="Light glass from behind through a large diffuse surface so form is described by dark refracted edges rather than by highlights.",
  reasoning="Glass has almost no surface of its own to light. It is legible only through what passes through it and bends at its boundaries.",
  why="Edge definition from transmitted light describes the shape without adding reflections that hide the contents.",
  use=["Glass packaging in skincare, fragrance and spirits","Contents must read through the container"],
  avoid=["Opaque or frosted containers","Work where a printed label must dominate"],
  adv="True transparency and readable contents", lim="Labels fall dark and need separate treatment",
  suit="Clear glass hero work", unsuit="Label-led packaging communication",
  alts=["Three-quarter front light where the label is the message"],
  aps=[("Frontal lighting on clear glass",
        "Fills the bottle with studio reflections and hides the liquid the product is sold on",
        "Large diffuse source behind, with dark edge definition describing the form")],
  impact="Renders glass so contents remain the subject.", iscore=8, prio=8, conf=0.9)

K("material.fabric.weight_through_fall.001", "Showing fabric weight through fall", M, "fabric",
  stages=["visual_direction","production"], ind="fashion",
  problem="Garments are photographed pressed flat or over-steamed, which erases the drape that communicates quality and price.",
  decision="Photograph fabric in motion or suspended so it falls under its own weight, and keep at least one visible fold unpressed.",
  reasoning="Weight and hand are the properties buyers use to infer quality, and both are only visible in how a fabric falls.",
  why="Fall is unfakeable: a heavy silk and a light polyester cannot be made to hang alike, so the image carries real information.",
  use=["Fashion and textile communication","Quality or price justification is an objective"],
  avoid=["Structured garments where the cut, not the drape, is the story","Flat technical documentation"],
  adv="Communicates quality without a claim", lim="Harder to control and to keep on-brand exactly",
  suit="Fashion campaign and editorial work", unsuit="Technical specification imagery",
  alts=["Detail macro on weave where drape is not available"],
  aps=[("Garment pressed and pinned flat to remove every wrinkle",
        "Removes the fall that carries the quality information, leaving only colour and shape",
        "Fabric allowed to hang or move, with one unpressed fold retained")],
  impact="Communicates fabric quality without asserting it.", iscore=8, prio=8, conf=0.87)

K("material.skin.texture_honesty.001", "Retaining skin texture", M, "skin",
  stages=["visual_direction","production"], ind="beauty",
  problem="Skin is retouched until it is featureless, which removes the evidence that a skincare claim could ever be assessed.",
  decision="Retain visible pore structure and natural surface variation, and correct only transient blemishes.",
  reasoning="A claim about skin cannot be evaluated on a surface that has no skin left in it. Removing texture removes the proof.",
  why="Retained texture makes improvement legible, which is what converts a claim into evidence.",
  use=["Skincare and beauty efficacy communication","Audience is sceptical or mature"],
  avoid=["Fantasy or heavily stylised beauty work","Categories where the claim is colour rather than condition"],
  adv="Credible, assessable efficacy claim", lim="Less idealised, requires better casting and lighting",
  suit="Efficacy-led skincare", unsuit="Stylised colour cosmetics",
  alts=["Macro detail on a treated area where full-face texture is not available"],
  aps=[("Retouching skin to a uniform featureless surface",
        "Removes the only evidence by which the product's claim could be judged",
        "Pore structure retained, with only transient marks corrected")],
  impact="Makes efficacy claims assessable rather than asserted.", iscore=9, prio=9, conf=0.9)

flush()
