# -*- coding: utf-8 -*-
"""Phase 2.1 expansion — batch 1: strategic intelligence."""
import io, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_lib import K, flush

# ═══════════════════ INDUSTRY INTELLIGENCE ═══════════════════
K("industry.beauty.communication_model.001", "How beauty communicates", "industry", "beauty",
  ktype="framework", stages=["strategy"], ind="beauty",
  problem="Beauty briefs arrive asking for a product shot, when the category is actually sold on self-perception rather than on the object.",
  decision="Treat the product as evidence of a change in self-perception, and give the perception two thirds of the communication weight.",
  reasoning="Purchase is triggered by an imagined future self, not by a container. Categories that sell transformation reward imagery of the person the buyer wants to be.",
  why="The product still appears and is still identifiable, but it inherits meaning from the state it is shown producing.",
  use=["Beauty or personal care brand communication", "Objective is awareness, launch or repositioning"],
  avoid=["Ingredient-claim advertising under regulatory review", "Pure e-commerce listing imagery"],
  adv="Emotional attachment and premium tolerance", lim="Slower, less literal product communication",
  suit="Brand and launch campaigns", unsuit="Regulated efficacy claims and marketplace listings",
  alts=["Ingredient-led scientific framing where the formulation is genuinely novel"],
  aps=[("Product bottle centred on a plain surface with no human context",
        "Communicates that a container exists, which the buyer already assumed",
        "The product held, used or placed inside a recognisable moment of self-regard")],
  human=("Visible change in skin or appearance", "Confidence in how she is perceived", "To be read as someone who takes care of herself"),
  impact="Shifts evaluation from price to self-perception.", iscore=9, prio=9, conf=0.88,
  related=["strategy.identity_preservation.mature_skincare.001"])

K("industry.food_beverage.communication_model.001", "How food and beverage communicates", "industry", "food_beverage",
  ktype="framework", stages=["strategy"], ind="food_beverage",
  problem="Food briefs default to appetite appeal alone, which sells a single occasion and builds no reason to return.",
  decision="Pair one appetite signal with one social or ritual signal in the same frame, never appetite alone.",
  reasoning="Appetite drives the first purchase; belonging drives the second. Imagery carrying only appetite has to win the sale again every time.",
  why="Two signals in one frame let the work do acquisition and retention work simultaneously without splitting the budget.",
  use=["Food, beverage or hospitality brand communication", "Objective includes repeat purchase or loyalty"],
  avoid=["Pure menu or price promotion", "Packaged goods shelf imagery with no consumption context"],
  adv="Drives trial and repeat from one asset", lim="More complex frame, harder to execute cleanly",
  suit="Brand campaigns and launches", unsuit="Price-led promotional formats",
  alts=["Provenance storytelling where sourcing is genuinely differentiated"],
  aps=[("Isolated dish photographed with no human presence or context",
        "Reads as menu documentation rather than as a reason to choose this place",
        "The dish inside the moment it is actually eaten, with a hand, table or room present")],
  human=("Something good to eat now", "A pause worth taking", "To belong to a place worth returning to"),
  impact="Improves repeat visit intent alongside trial.", iscore=8, prio=9, conf=0.85,
  related=["strategy.ritual_framing.local_hospitality.001"])

K("industry.fashion.communication_model.001", "How fashion communicates", "industry", "fashion",
  ktype="framework", stages=["strategy"], ind="fashion",
  problem="Fashion briefs request garment clarity, which produces catalogue imagery in channels where identity, not fit, drives the click.",
  decision="Lead with the wearer's stance and let garment detail be readable rather than dominant.",
  reasoning="Clothing is bought as a claim about the self. A garment shown without a person makes that claim impossible to read.",
  why="Stance is legible at thumbnail scale and survives compression, so the identity claim arrives before the product does.",
  use=["Fashion or accessories brand communication", "Social, editorial or campaign channels"],
  avoid=["Product detail pages requiring literal fit and construction clarity", "Size and specification communication"],
  adv="Stronger identity association and recall", lim="Reduced literal product information",
  suit="Brand campaigns and social advertising", unsuit="E-commerce catalogue systems",
  alts=["Movement-led capture where garment behaviour is itself the story"],
  aps=[("Garment photographed flat or on an invisible mannequin",
        "Removes the identity claim, leaving only price and fabric to compete on",
        "A wearer with a specific readable attitude, garment shown in use")],
  human=("Clothing that fits the occasion", "To feel like the intended version of themselves", "To be read as distinctive"),
  impact="Shifts evaluation from price to identity.", iscore=9, prio=9, conf=0.86,
  related=["strategy.self_expression.fashion_social.001"])

K("industry.hospitality.communication_model.001", "How hospitality communicates", "industry", "hospitality",
  ktype="framework", stages=["strategy"], ind="hospitality",
  problem="Hospitality briefs ask for beautiful interiors, which sell a room rather than the experience of being in it.",
  decision="Show the space occupied at its most characteristic hour rather than empty and immaculate.",
  reasoning="Guests book an anticipated experience, not a floor plan. An empty room asks the viewer to imagine themselves in it, which is work they will not do.",
  why="Occupancy supplies scale, atmosphere and social proof in one frame, and removes the imaginative labour.",
  use=["Hotel, restaurant, cafe or venue communication", "Objective is booking, trial or brand building"],
  avoid=["Property listing photography with legal accuracy requirements", "Facility specification documentation"],
  adv="Higher booking intent and emotional preference", lim="Harder to schedule and control, requires real people",
  suit="Brand and booking campaigns", unsuit="Real estate listings and compliance documentation",
  alts=["Detail-led craft storytelling where the room itself is the product"],
  aps=[("Immaculate empty interior shot at wide angle",
        "Reads as an estate agent listing and gives the viewer no experience to want",
        "The same space at its characteristic hour with real occupancy and real light")],
  human=("Somewhere to stay or eat", "Anticipation of a good time", "To be the kind of person who chooses well"),
  impact="Raises booking intent by showing experience rather than inventory.", iscore=8, prio=8, conf=0.84)

# ═══════════════════ STRATEGY INTELLIGENCE ═══════════════════
K("strategy.scientific_luxury.beauty_efficacy.001", "Scientific luxury for efficacy-led beauty", "strategy", "scientific_luxury",
  ktype="decision_rule", stages=["strategy","concept"], ind="beauty", cat="skincare",
  pos=["premium","luxury"], obj=["product_launch","awareness"],
  problem="Efficacy claims in premium beauty are either buried under lifestyle imagery or presented so clinically that the product loses desirability.",
  decision="Build the campaign on visible material precision — one controlled surface, one exact texture — rather than on laboratory iconography.",
  reasoning="Buyers infer efficacy from evident precision, not from beakers. Laboratory props signal a category, while precision signals a standard.",
  why="Precision is readable in a single frame and cannot be faked cheaply, so it functions as proof without a claim.",
  use=["Premium or luxury skincare with a real formulation story", "Objective is launch or repositioning"],
  avoid=["Mass-market pricing where warmth outperforms precision", "Categories where regulation forbids implied claims"],
  adv="Communicates efficacy without a regulated claim", lim="Colder tone, lower warmth and approachability",
  suit="Premium launches with genuine formulation news", unsuit="Mass-market and family positioning",
  alts=["Identity-preservation framing where the audience is mature","Ritual framing where usage habit is the story"],
  aps=[("Test tubes, pipettes and white lab coats staged around the product",
        "Signals the generic idea of science rather than this product's standard, and every competitor owns it equally",
        "One exact material behaviour of the actual formula, shown at close range")],
  human=("Measurable improvement in skin condition", "Confidence that the money bought something real", "To be seen as informed rather than gullible"),
  impact="Communicates efficacy while retaining desirability.", iscore=8, prio=8, conf=0.85,
  related=["differentiation.beauty.category_cliches.001"])

K("strategy.first_visit_conversion.hospitality.001", "Converting the first visit in hospitality", "strategy", "first_visit_conversion",
  ktype="decision_rule", stages=["strategy","concept"], ind="hospitality", obj=["product_launch","conversion"],
  problem="New venues advertise atmosphere to audiences who have not yet decided the place is for them, so the atmosphere reads as someone else's.",
  decision="Show one specific person who is visibly the target guest, in the venue, doing the thing the venue is for.",
  reasoning="A first visit is a social risk. The decisive question is whether people like me go there, which atmosphere alone cannot answer.",
  why="A recognisable guest answers the belonging question in the first second, before the room is even assessed.",
  use=["New venue launch or relaunch", "Audience has no prior relationship with the brand"],
  avoid=["Established venues where the audience already knows the answer", "Luxury positioning built on exclusivity and distance"],
  adv="Removes the social risk barrier to first visit", lim="Narrows apparent appeal to the depicted guest type",
  suit="Launch and trial campaigns", unsuit="Broad-reach brand campaigns for established venues",
  alts=["Craft and provenance framing where the offer itself is the draw"],
  aps=[("Empty styled interior presented as atmosphere",
        "Leaves the belonging question unanswered, which is the actual barrier to a first visit",
        "One recognisable target guest using the space as intended")],
  human=("Somewhere new to go", "Confidence it will not be awkward", "To be seen choosing somewhere good"),
  impact="Lifts first-visit conversion by resolving social risk.", iscore=8, prio=8, conf=0.82)

K("strategy.occasion_ownership.food_beverage.001", "Own an occasion, not a product", "strategy", "occasion_ownership",
  ktype="decision_rule", stages=["strategy","concept"], ind="food_beverage", obj=["awareness","product_launch"],
  problem="Food and beverage brands compete on product attributes that competitors can match within a season.",
  decision="Claim one specific consumption occasion and repeat it across every asset until the occasion recalls the brand.",
  reasoning="Product attributes are copyable; an occupied occasion is not, because the second brand to claim it looks derivative.",
  why="Repetition against a fixed occasion builds a retrieval cue, so the brand is recalled at the moment of relevant need.",
  use=["Food or beverage brand building over multiple assets", "Category has high attribute parity"],
  avoid=["Single-asset promotions", "Genuinely novel product where the attribute is the news"],
  adv="Builds a defensible mental position", lim="Requires sustained repetition before it pays back",
  suit="Multi-asset campaigns with continuity", unsuit="One-off tactical promotions",
  alts=["Attribute-led positioning where a genuine product advantage exists"],
  aps=[("Rotating the consumption occasion between assets to show versatility",
        "Spreads the memory investment across many cues so none of them becomes retrievable",
        "One occasion repeated with executional variety but positional consistency")],
  human=("Something that fits this moment", "Rightness rather than novelty", "To be the person who knows what goes with what"),
  impact="Builds a retrievable brand position in memory.", iscore=8, prio=8, conf=0.83,
  related=["concept.discipline.single_organising_idea.001"])

K("strategy.price_visibility.mass_market.001", "Making price a strength in mass positioning", "strategy", "price_visibility",
  ktype="decision_rule", stages=["strategy"], pos=["mass","budget"], obj=["conversion"],
  problem="Mass-market brands hide price in the way premium brands do, which loses their strongest argument and gains none of the premium.",
  decision="Place price as a designed element with equal weight to the product, not as a corner overlay.",
  reasoning="For value positioning the price IS the proposition. Treating it as an afterthought signals embarrassment about the brand's actual advantage.",
  why="A confidently set price reads as a claim rather than a concession, which is the difference between cheap and good value.",
  use=["Mass or budget positioning with a genuine price advantage", "Conversion objective"],
  avoid=["Premium or luxury positioning where price visibility damages perception", "Awareness campaigns with no offer"],
  adv="Converts the brand's real advantage into its main message", lim="Anchors the brand on price, making later premium moves harder",
  suit="Value-led conversion campaigns", unsuit="Premium brand building",
  alts=["Quantity or bundle framing where unit price comparison is unflattering"],
  aps=[("Small price text in the lower corner of an otherwise premium-styled layout",
        "Borrows premium codes the brand cannot support while hiding its real advantage",
        "Price set as a deliberate typographic element with weight equal to the product")],
  impact="Converts price from apology into proposition.", iscore=7, prio=7, conf=0.8)

# ═══════════════════ AUDIENCE PSYCHOLOGY ═══════════════════
K("audience.women_25_35.aspiration_drivers.001", "Aspiration drivers for women 25-35", "audience", "women_25_35",
  ktype="framework", stages=["strategy"], ind=["beauty","fashion"], aud="women_25_35",
  problem="This segment is addressed either as students or as mothers, when the defining tension is the gap between current and intended self.",
  decision="Choose the emotional trigger of becoming rather than of maintaining, and show the intended self as already arrived.",
  reasoning="This life stage is defined by active identity construction. Maintenance framing, which works at 35-50, reads as premature and dull here.",
  why="Depicting the intended self as present rather than promised removes the delay between purchase and payoff.",
  use=["Audience resolves to women_25_35", "Beauty, fashion or lifestyle categories"],
  avoid=["Audience is women_35_50, where continuity outperforms aspiration", "Categories sold on reassurance rather than change"],
  adv="High motivational pull and share intent", lim="Can read as pressure if the gap shown is too wide",
  suit="Brand and launch work in identity categories", unsuit="Trust-led or clinical categories",
  alts=["Peer-proof framing where the category is high-risk"],
  aps=[("Depicting the audience as aspiring toward a distant unattainable ideal",
        "Widens the gap until it reads as criticism, which produces avoidance rather than desire",
        "The intended self shown as already present and ordinary")],
  human=("Products that work for a busy life", "To feel she is becoming who she intends to be", "To be read as someone with her own direction"),
  impact="Raises motivational pull in identity-led categories.", iscore=8, prio=8, conf=0.84)

K("audience.premium_consumers.value_justification.001", "How premium buyers justify spend", "audience", "premium_consumers",
  ktype="framework", stages=["strategy"], aud="premium_consumers", pos=["premium","luxury"],
  problem="Premium campaigns assert quality without giving the buyer the argument they will use to justify the purchase to themselves.",
  decision="Supply one concrete, repeatable justification — a material, a process, a duration — that the buyer can restate in a sentence.",
  reasoning="Premium purchase involves private justification. A buyer who cannot articulate why it cost more experiences the spend as indulgence and regrets it.",
  why="A restatable reason converts an emotional decision into a defensible one, which protects satisfaction after purchase.",
  use=["Premium or luxury positioning", "Considered purchase with a real price gap"],
  avoid=["Impulse categories", "Positioning built purely on status signalling"],
  adv="Higher satisfaction and lower post-purchase regret", lim="Requires a genuine substantiable difference",
  suit="Premium products with real製 process or material advantage", unsuit="Badge-value products with no functional story",
  alts=["Scarcity framing where genuine limitation exists"],
  aps=[("Asserting quality through adjectives and premium styling alone",
        "Gives the buyer nothing to repeat, so the price gap stays unexplained and the purchase feels indulgent",
        "One concrete verifiable fact about material, process or duration")],
  human=("A product that lasts and performs", "Confidence the extra spend was reasoned", "To be seen as discerning rather than extravagant"),
  impact="Improves post-purchase satisfaction and advocacy.", iscore=8, prio=8, conf=0.85)

K("audience.mass_market.trust_signals.001", "Trust signals for mass-market audiences", "audience", "mass_market_consumers",
  ktype="framework", stages=["strategy"], aud="mass_market_consumers", pos=["mass","budget"],
  problem="Mass-market work borrows premium visual codes, which raises price expectation and produces distrust when the price is revealed.",
  decision="Match visual production level to the price point deliberately, and lead with familiarity rather than aspiration.",
  reasoning="A mismatch between apparent production value and price triggers suspicion about what has been compromised elsewhere.",
  why="Coherence between look and price reads as honesty, which is the primary trust currency in value categories.",
  use=["Mass or budget positioning", "Price is a stated part of the offer"],
  avoid=["Premium positioning", "Categories where aspiration is the purchase driver"],
  adv="Higher trust and conversion at the price point", lim="Lower perceived quality ceiling, harder to trade up later",
  suit="Value-led categories and everyday purchase", unsuit="Premium and aspirational categories",
  alts=["Trade-up ladder framing where a premium tier genuinely exists"],
  aps=[("Luxury visual codes applied to a value-priced product",
        "Creates a price expectation the product cannot meet, which reads as a trick",
        "Production values matched honestly to the price point")],
  human=("Reliable products at a fair price", "Confidence they are not being overcharged", "To be seen as sensible with money"),
  impact="Raises trust and conversion in value categories.", iscore=7, prio=8, conf=0.83)

K("audience.gen_z.social_proof_mechanics.001", "Social proof mechanics for Gen Z", "audience", "gen_z_proof",
  ktype="framework", stages=["strategy","concept"], aud="gen_z", ch=["instagram","tiktok"],
  problem="Brand-authored claims carry almost no weight with this audience, but campaigns keep making them in brand voice.",
  decision="Route the central claim through a peer or a visible artefact of use rather than through brand assertion.",
  reasoning="Trust is allocated to sources with nothing to gain. A brand asserting its own quality is structurally the least credible source available.",
  why="A peer or a worn artefact carries the same information with a credibility the brand cannot manufacture.",
  use=["Gen Z audience on social channels", "Claim is subjective or experiential"],
  avoid=["Regulated claims requiring brand accountability", "Luxury where distance is part of the value"],
  adv="Substantially higher claim acceptance", lim="Less control over message precision",
  suit="Social-first campaigns", unsuit="Regulated or compliance-sensitive communication",
  alts=["Demonstration framing where the product proves itself visually"],
  aps=[("Brand-voice superlatives delivered directly to camera",
        "Comes from the one source the audience discounts by default",
        "The same claim carried by a peer, a visible result, or an artefact of real use")],
  human=("Products that actually work", "Pride in discovering rather than being sold", "To be seen as having independent taste"),
  impact="Raises claim credibility in social channels.", iscore=8, prio=8, conf=0.84,
  related=["audience.gen_z.authenticity_signals.001"])

# ═══════════════════ DIFFERENTIATION ═══════════════════
K("differentiation.hospitality.category_cliches.001", "Hospitality cliches and replacements", "differentiation", "hospitality",
  ktype="anti_pattern", stages=["concept"], ind="hospitality",
  problem="Hospitality imagery converges on empty perfection, which is indistinguishable between a boutique hotel and a chain.",
  decision="Reject the empty-interior, folded-towel and sunset-terrace defaults in favour of the venue at its characteristic occupied hour.",
  reasoning="These images document facilities. Facilities are parity; the experience of the place is not.",
  why="Occupancy and specific hour supply atmosphere, scale and social proof that an empty room cannot.",
  use=["Hotel, restaurant or venue concept development", "Differentiation is an objective"],
  avoid=["Property listing photography with accuracy obligations"],
  adv="Distinctive and bookable imagery", lim="Harder to produce, needs real people and timing",
  suit="Brand and booking campaigns", unsuit="Listings and compliance documentation",
  alts=["Detail-led craft storytelling where the room itself is genuinely the product"],
  aps=[("Empty immaculate room photographed wide",
        "Documents inventory rather than experience, and is interchangeable across the category",
        "The same room at its characteristic hour, occupied, with real light"),
       ("Folded towels, rose petals and turndown staging",
        "Signals generic hospitality service rather than this venue's character",
        "One detail that only this venue would have")],
  impact="Produces bookable, attributable venue imagery.", iscore=8, prio=9, conf=0.86)

K("differentiation.universal.sameness_test.001", "The interchangeability test", "differentiation", "sameness_test",
  ktype="evaluation_rule", stages=["evaluation"],
  problem="Teams approve work that is competent and interchangeable, because competence is easy to assess and distinctiveness is not.",
  decision="Reject any concept whose executed frame could carry a direct competitor's logo without contradiction.",
  reasoning="Interchangeability is the one differentiation failure that can be tested objectively rather than argued about.",
  why="It converts a subjective debate about distinctiveness into a single answerable question.",
  use=["Concept review before production", "Any category with high visual saturation"],
  avoid=["Categories where legal or format constraints force convention"],
  adv="Objective, fast and hard to argue with", lim="Detects sameness but does not generate the alternative",
  suit="Concept gate before production spend", unsuit="Constrained formats with mandated conventions",
  alts=["Attribution testing where research budget exists"],
  aps=[("Approving work because it is well crafted and on brief",
        "Craft and compliance are necessary but do not produce attribution",
        "Applying the logo-swap test before craft is assessed")],
  impact="Prevents category-average work reaching production.", iscore=9, prio=10, conf=0.9)

K("differentiation.universal.whitespace_discovery.001", "Finding the category white space", "differentiation", "whitespace",
  ktype="framework", stages=["concept"],
  problem="Differentiation is attempted by execution craft after the concept is fixed, which is too late to change what the work is about.",
  decision="Map the four most common category territories before concepting, and build only in the ones nobody occupies.",
  reasoning="Distinctiveness is decided at territory level. Two brands in the same territory remain confusable however differently they execute it.",
  why="Choosing an empty territory makes distinctiveness structural rather than dependent on execution quality.",
  use=["Concept development in a saturated category", "Brand attribution is a stated objective"],
  avoid=["Categories with fewer than three active competitors","Regulated categories with mandated conventions"],
  adv="Structural rather than cosmetic differentiation", lim="Requires competitor review time before concepting",
  suit="Brand campaigns in saturated categories", unsuit="Tactical work with no strategic latitude",
  alts=["Execution-led differentiation where territory choice is fixed by the client"],
  aps=[("Differentiating through craft while occupying the same territory as competitors",
        "Better execution of the same idea still produces confusable work",
        "Territory selection before concepting, craft applied afterwards")],
  impact="Makes differentiation structural rather than cosmetic.", iscore=9, prio=9, conf=0.87)

# ═══════════════════ CONCEPT INTELLIGENCE ═══════════════════
K("concept.construction.visual_metaphor.001", "Choosing a visual metaphor", "concept", "visual_metaphor",
  ktype="decision_rule", stages=["concept"],
  problem="Metaphors are chosen for their beauty rather than for whether the audience can decode them in one second of attention.",
  decision="Select a metaphor decodable within one second by someone who does not know the brand, and discard any that need explanation.",
  reasoning="Advertising is decoded in passing. A metaphor requiring interpretation transfers no meaning in the time actually available.",
  why="One-second decodability guarantees the idea survives the real viewing conditions rather than the presentation room.",
  use=["Concept development for any paid media", "Audience has no prior brand familiarity"],
  avoid=["Long-form or owned channels where dwell time is genuinely longer","Audiences with deep existing brand knowledge"],
  adv="Idea survives real viewing conditions", lim="Excludes sophisticated metaphors that reward attention",
  suit="Paid media and social advertising", unsuit="Brand films and owned long-form content",
  alts=["Layered metaphor for channels with proven dwell time"],
  aps=[("A metaphor that lands only after the tagline is read",
        "Reverses the intended order, so the image does no work and the line carries everything",
        "A metaphor readable before any text, with the line confirming rather than explaining")],
  impact="Ensures the central idea transfers in real viewing conditions.", iscore=8, prio=8, conf=0.85,
  related=["concept.construction.tension_first.001"])

K("concept.construction.three_territories.001", "Develop three territories before choosing", "concept", "territories",
  ktype="framework", stages=["concept"],
  problem="A single concept is developed and defended, so the first workable idea becomes the final idea by default rather than by comparison.",
  decision="Generate three distinct territories and select against stated criteria before any is executed.",
  reasoning="Without alternatives there is no comparison, and without comparison selection is advocacy for whatever was thought of first.",
  why="Three territories force the tension to be examined from different angles, which usually improves even the option originally favoured.",
  use=["Any campaign concept development","Objective includes differentiation"],
  avoid=["Tactical executions inside an approved campaign platform","Genuine emergency turnaround"],
  adv="Better selection and a stronger final idea", lim="Costs additional development time before execution",
  suit="Campaign and platform development", unsuit="Tactical work inside an existing platform",
  alts=["Single-territory development where the platform is already fixed"],
  aps=[("Presenting one concept with two deliberately weaker options beside it",
        "Produces the appearance of choice while removing its substance",
        "Three territories each independently defensible against the same criteria")],
  impact="Improves concept selection quality.", iscore=8, prio=9, conf=0.88,
  related=["differentiation.universal.whitespace_discovery.001"])

K("concept.discipline.one_message_per_asset.001", "One message per asset", "concept", "message_discipline",
  ktype="principle", stages=["concept","design"],
  problem="Stakeholder consensus adds messages to a single asset until none of them is legible in the time the asset actually gets.",
  decision="Carry exactly one message per asset, and split additional messages across additional assets in the set.",
  reasoning="Attention per asset is roughly fixed. Adding a second message halves the first rather than adding to it.",
  why="Splitting messages across a set preserves the full attention budget for each one.",
  use=["Any multi-asset campaign","Paid media with short exposure"],
  avoid=["Long-form owned content","Technical or specification communication"],
  adv="Each message actually lands", lim="Requires more assets to say the same total amount",
  suit="Paid campaigns and social sets", unsuit="Brochures and specification material",
  alts=["Sequenced messaging across a media plan"],
  aps=[("Adding a secondary message to satisfy a stakeholder",
        "Splits a fixed attention budget so neither message clears the threshold",
        "A second asset carrying the second message at full weight")],
  impact="Preserves message legibility under real exposure.", iscore=8, prio=9, conf=0.9)

K("concept.discipline.earn_the_product_shot.001", "Earn the product shot", "concept", "product_placement",
  ktype="principle", stages=["concept"],
  problem="The product is placed first and the idea is built around it, which produces work that announces rather than persuades.",
  decision="Introduce the product only after the frame has established a reason to care, and never as the first thing read.",
  reasoning="A product shown before a reason to want it is visual noise. Order of reading determines whether it is information or interruption.",
  why="Establishing the tension first converts the product from an announcement into a resolution.",
  use=["Awareness and launch campaigns","Categories with high attribute parity"],
  avoid=["Direct response where the offer is the message","Genuine product news where the object itself is the story"],
  adv="Product arrives as an answer rather than an assertion", lim="Delays product identification, risky in low-attention formats",
  suit="Brand and launch campaigns", unsuit="Performance advertising and retail formats",
  alts=["Product-first framing where the design is itself the news"],
  aps=[("Opening the frame with the product centred and largest",
        "Asks for desire before supplying a reason for it",
        "A reason to care established first, with the product resolving it")],
  impact="Converts product presence from announcement into payoff.", iscore=8, prio=8, conf=0.84,
  related=["concept.construction.tension_first.001"])

flush()
