# -*- coding: utf-8 -*-
"""Phase 2.1 expansion — batch 4: depth across craft domains."""
import io, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_lib import K, flush

C="camera"; L="lighting"; CL="color"; CO="composition"; M="material"; TY="typography"
CH="channel"; CR="critic"; P="photography"; LA="layout"; A="audience"; S="strategy"; VD="visual_direction"

# ── CAMERA ──
K("camera.framing.close_crop_intimacy.001","Close crop as intimacy",C,"framing",stages=["visual_direction"],
  problem="Wide framing is used to show context, which places the viewer at an observing distance the brief did not ask for.",
  decision="Crop tight enough that the subject exceeds the frame edges when the brand should feel personally addressed.",
  reasoning="Crop encodes social distance. A frame that cannot contain the subject implies proximity closer than public space.",
  why="Implied proximity converts a broadcast into an address, which raises attention without raising volume.",
  use=["Personal, intimate or confessional brand voice","Beauty and personal care"],
  avoid=["Product identification work where the whole object must read","Context-dependent storytelling"],
  adv="Personal address and high attention",lim="Loses context and product identification",
  suit="Intimate brand voice work",unsuit="Product identification and context storytelling",
  alts=["Medium framing where both intimacy and context are needed"],
  aps=[("Wide framing used for an intimate personal claim","Places the viewer at public distance, contradicting the intimacy of the message","Crop tightened until the subject exceeds the frame edges")],
  profile=[("kind","photography"),("framing_psychology","Exceeding the frame implies the viewer is inside personal space rather than observing.")],
  impact="Converts broadcast into personal address.",iscore=7,prio=8,conf=0.85)

K("camera.angle.low_angle_monument.001","Low angle as monument",C,"angle",stages=["visual_direction"],
  pos=["premium","luxury"],asset=["poster","product_hero"],
  problem="Products are shot from above because it is the natural working height, which makes them read as available rather than important.",
  decision="Drop the camera below the product's midpoint so the object rises within the frame.",
  reasoning="Anything the viewer looks up at is read as larger and more significant, a reading that operates below conscious attention.",
  why="Elevation is granted by geometry alone, requiring no props, scale cues or copy.",
  use=["Premium product hero work","Objective is significance or authority"],
  avoid=["Approachable everyday positioning","Food where a downward angle serves appetite"],
  adv="Grants significance with no added elements",lim="Can read as pompous on everyday products",
  suit="Premium hero work",unsuit="Everyday and value categories",
  alts=["Eye level where approachability matters more than status"],
  aps=[("Shooting down at a premium product from standing height","Renders it as available inventory rather than as something significant","Camera dropped below the product's midpoint")],
  profile=[("kind","photography"),("camera_angle","Below the subject's midpoint, so the object rises and the viewer looks up.")],
  impact="Grants significance through geometry alone.",iscore=7,prio=7,conf=0.86)

K("camera.depth.selective_focus_attention.001","Selective focus as attention direction",C,"depth_of_field",stages=["visual_direction","production"],
  problem="Depth of field is set for technical correctness rather than used to state what matters in the frame.",
  decision="Hold exactly one plane sharp and let everything else fall off, choosing that plane as the message.",
  reasoning="Sharpness is the strongest attention cue available. Distributing it across several planes distributes the message with it.",
  why="A single sharp plane removes the viewer's need to decide where to look, which is the main cost of a cluttered frame.",
  use=["Frames with competing elements","Single-message assets"],
  avoid=["Group or range work where all items matter equally","Technical documentation requiring full sharpness"],
  adv="Unambiguous attention direction",lim="Everything outside the plane is sacrificed",
  suit="Single-subject and single-message work",unsuit="Range and documentation imagery",
  alts=["Deep focus where every element carries information"],
  aps=[("Stopping down to hold everything sharp in a busy frame","Every element competes equally, so the viewer must do the sorting the image should have done","One plane held sharp, chosen as the message")],
  profile=[("kind","photography"),("depth_of_field","One plane sharp, everything else surrendered deliberately.")],
  impact="Removes the viewer's burden of choosing where to look.",iscore=8,prio=8,conf=0.88)

K("camera.stability.handheld_presence.001","Handheld as presence",C,"stability",stages=["visual_direction"],
  aud="gen_z",ch=["instagram","tiktok"],
  problem="Locked-off tripod framing signals a production, which contradicts campaigns claiming spontaneity.",
  decision="Shoot handheld with visible micro-movement when the claim is spontaneity or presence.",
  reasoning="Camera stability is read as production budget. Absolute stillness implies a crew, a plan and therefore a message.",
  why="Slight instability implies a person holding the camera, which is what an authenticity claim requires.",
  use=["Authenticity and spontaneity claims","Social and creator-led content"],
  avoid=["Premium product work requiring precision","Formats where movement causes compression artefacts"],
  adv="Reads as present and unstaged",lim="Less precise framing, compression cost in video",
  suit="Social and authenticity-led content",unsuit="Premium product photography",
  alts=["Locked framing with handheld cutaways where precision is needed"],
  aps=[("Perfectly locked tripod framing on a spontaneity claim","The stability reveals the production, contradicting the claim being made","Handheld with retained micro-movement")],
  profile=[("kind","photography"),("framing_psychology","Micro-movement implies a person present rather than a rig deployed.")],
  impact="Aligns camera behaviour with an authenticity claim.",iscore=7,prio=7,conf=0.82)

# ── LIGHTING ──
K("lighting.rim.separation_without_clutter.001","Rim light for separation",L,"rim",stages=["visual_direction","production"],
  problem="Subjects merge into dark backgrounds, and the fix applied is usually to brighten the background, which flattens the depth.",
  decision="Add a hard rim from behind at roughly 135 degrees to draw a bright edge, rather than lifting the background.",
  reasoning="Separation requires a luminance boundary at the subject's edge. Lifting the background reduces the very contrast that produced the depth.",
  why="A rim creates the boundary exactly where it is needed and nowhere else, preserving the dark ground.",
  use=["Dark or low-key compositions","Subject tone close to background tone"],
  avoid=["High-key work where no separation problem exists","Matte subjects that produce no specular edge"],
  adv="Separation with depth preserved",lim="Adds a light source and can read as theatrical",
  suit="Low-key product and portrait work",unsuit="High-key and matte-subject work",
  alts=["Background gradient where a rim would be too theatrical"],
  aps=[("Raising background brightness to separate a dark subject","Removes the contrast that created depth, flattening the frame","A hard rim from behind, background left dark")],
  profile=[("kind","lighting"),("emotional_perception","Definition and presence; the subject asserts its own edge."),("commercial_usage","Standard in spirits, automotive and low-key portrait work."),("technical_character","Hard source behind at about 135 degrees, no fill on the ground.")],
  impact="Separates subject while preserving depth.",iscore=7,prio=8,conf=0.88)

K("lighting.ratio.contrast_as_tone.001","Lighting ratio sets emotional tone",L,"ratio",stages=["visual_direction"],
  problem="Lighting ratio is set by exposure convenience, which assigns an emotional tone nobody chose.",
  decision="Set the key-to-fill ratio deliberately: near 2:1 for approachable, 8:1 or beyond for dramatic and premium.",
  reasoning="Contrast between lit and unlit sides is read as emotional intensity before any content is interpreted.",
  why="Choosing the ratio first makes tone a decision rather than a by-product of the exposure.",
  use=["Any lit photography where tone matters","Brand tone is defined in the brief"],
  avoid=["Documentary work where available light governs"],
  adv="Tone becomes an explicit controllable decision",lim="Constrains lighting to serve tone over convenience",
  suit="Controlled studio and location lighting",unsuit="Available-light documentary",
  alts=["Available light where authenticity outranks tonal control"],
  aps=[("Setting fill by what looks correct on the monitor","Assigns an emotional tone by accident that may contradict the brief","Ratio chosen from the required tone, then exposed to it")],
  profile=[("kind","lighting"),("emotional_perception","Low ratio reads open and approachable; high ratio reads serious and premium."),("commercial_usage","Low ratio for family and value; high ratio for luxury, spirits and automotive."),("technical_character","Key-to-fill measured, not judged by eye.")],
  impact="Makes emotional tone an explicit lighting decision.",iscore=8,prio=8,conf=0.89)

K("lighting.practical.in_frame_sources.001","Practical sources as atmosphere",L,"practical",stages=["visual_direction"],
  ind=["hospitality","food_beverage"],
  problem="Venue lighting is replaced with film lighting, which produces a well-lit room that no longer looks like that room.",
  decision="Keep the venue's own visible fixtures lit in frame and shape around them rather than replacing them.",
  reasoning="Visible practical sources explain the light. Light with no visible source reads as imposed, and the viewer registers the imposition.",
  why="A visible source makes the lighting self-justifying, which is what lets an interior read as real.",
  use=["Interiors with characterful existing fixtures","Atmosphere-led venue work"],
  avoid=["Venues with poor or unflattering fixtures","Product work needing controlled surface rendering"],
  adv="Atmosphere reads as belonging to the place",lim="Constrained by the venue's actual fixtures",
  suit="Venue and interior work",unsuit="Controlled product photography",
  alts=["Augmenting practicals with matched colour temperature where they are insufficient"],
  aps=[("Turning off venue fixtures and lighting the room entirely with film lights","Produces a well-lit space that no longer resembles the venue being sold","Practicals kept lit and in frame, with shaping added around them")],
  profile=[("kind","lighting"),("emotional_perception","Belonging; the light is evidently of that place rather than brought to it."),("commercial_usage","Standard for restaurant, bar and boutique hotel photography."),("technical_character","Practicals exposed correctly, additions matched to their colour temperature.")],
  impact="Keeps interior atmosphere native to the venue.",iscore=8,prio=8,conf=0.86)

# ── COLOR ──
K("color.monochrome.focus_discipline.001","Monochrome for focus",CL,"monochrome",stages=["visual_direction","design"],
  problem="Colour is used to add interest, which spreads attention across a frame that needed it concentrated.",
  decision="Reduce the frame to a single hue family and let form, tone and texture carry the interest.",
  reasoning="Removing colour variation removes the strongest competing attention cue, leaving structure to be read.",
  why="With hue removed as a variable, the viewer reads composition and material directly.",
  use=["Composition or material is the message","Premium and editorial positioning"],
  avoid=["Products sold on colour","Categories where colour variety is the range"],
  adv="Maximum focus on form and material",lim="Loses colour as a brand and appetite cue",
  suit="Editorial and material-led work",unsuit="Colour-led products and ranges",
  alts=["Two-hue palette where a single brand colour must persist"],
  aps=[("Adding a second colour to relieve a monochrome frame","Reintroduces the competing cue the restriction removed","Interest supplied by tone and texture instead")],
  profile=[("kind","color"),("brand_perception","Disciplined and editorial; confident enough to remove a tool."),("emotional_association","Calm concentration rather than stimulation."),("cultural_note","Reads as premium in most markets, but can read as austere or funereal where white dominates.")],
  impact="Concentrates attention on form and material.",iscore=7,prio=7,conf=0.84)

K("color.accent.single_point_direction.001","Single accent as attention pointer",CL,"accent",stages=["design"],
  problem="Brand colour is applied across many elements, so it stops indicating anything.",
  decision="Apply the accent colour to exactly one element per asset, chosen as the thing the viewer should look at first.",
  reasoning="An accent works by scarcity. Applied to several elements it becomes a theme, which points nowhere.",
  why="Scarcity converts colour into a pointer, doing hierarchy work at no cost in space.",
  use=["Assets with a clear primary element","Brand has a defined accent colour"],
  avoid=["Brand systems built on multi-colour identity","Assets with no single primary element"],
  adv="Free hierarchy through colour scarcity",lim="Requires disciplined restraint across the set",
  suit="Single-message assets",unsuit="Multi-colour brand systems",
  alts=["Weight or scale for hierarchy where colour is unavailable"],
  aps=[("Applying brand colour to the logo, the headline and the button","Distributes the cue until none of them is pointed at","One element carrying the accent, chosen deliberately")],
  profile=[("kind","color"),("brand_perception","Deliberate and controlled."),("emotional_association","Immediate direction without effort."),("cultural_note","Red carries strong festive and prosperity association in Vietnam; accent choice should account for it.")],
  impact="Turns colour into a hierarchy instrument.",iscore=8,prio=8,conf=0.87)

K("color.cultural.vietnam_market_reading.001","Colour meaning in the Vietnamese market",CL,"cultural",stages=["visual_direction","design"],
  ktype="framework",
  problem="Palettes proven in Western markets are applied unchanged in Vietnam, where several colours carry different associations.",
  decision="Verify red, white and gold against local association before using them as primary brand colours.",
  reasoning="Red signals prosperity and celebration rather than urgency; white carries mourning association; gold reads as auspicious rather than merely expensive.",
  why="Checking the three highest-variance colours prevents the most common and most damaging misreading.",
  use=["Any campaign for the Vietnamese market","Brands adapting global assets locally"],
  avoid=["Purely export-facing communication"],
  adv="Avoids the most damaging local misreadings",lim="Constrains global palette consistency",
  suit="Vietnam and SEA market work",unsuit="Global campaigns with mandated palettes",
  alts=["Market-specific palette variant within a global system"],
  aps=[("Using white as the dominant palette for a celebratory local launch","Carries mourning association in the market, which contradicts the occasion","Warm or red-led palette appropriate to celebration locally")],
  profile=[("kind","color"),("brand_perception","Local fluency; the brand appears to know its market."),("emotional_association","Correct association rather than the imported one."),("cultural_note","Red for prosperity, gold for auspiciousness, white with mourning association in traditional contexts.")],
  impact="Prevents culturally incorrect palette decisions.",iscore=9,prio=9,conf=0.88)

# ── COMPOSITION ──
K("composition.framing.frame_within_frame.001","Frame within frame for focus",CO,"frame_within_frame",stages=["visual_direction"],
  ind=["hospitality","fashion"],
  problem="Environmental shots include so much context that the subject is never clearly indicated.",
  decision="Use an existing architectural or natural opening to surround the subject rather than adding a graphic device.",
  reasoning="An enclosing shape directs attention inward without adding elements, using structure already present in the scene.",
  why="It supplies both focus and context in one move, which a graphic overlay cannot do without breaking immersion.",
  use=["Environmental and venue work","Context must remain while focus is required"],
  avoid=["Clean studio product work","Frames already tightly composed"],
  adv="Focus and context together, no added elements",lim="Depends on the location offering a usable opening",
  suit="Environmental storytelling",unsuit="Studio product work",
  alts=["Selective focus where no architectural frame exists"],
  aps=[("Adding a graphic border to focus attention in an environmental shot","Breaks immersion and announces the image as designed","An opening already present in the scene used as the frame")],
  profile=[("kind","composition"),("structure","Subject enclosed by an opening already present in the scene."),("attention_effect","Attention is funnelled inward while context is retained."),("failure_pattern","A frame element so dominant it becomes the subject.")],
  impact="Delivers focus without sacrificing context.",iscore=7,prio=7,conf=0.84)

K("composition.balance.asymmetric_tension.001","Asymmetric balance for interest",CO,"asymmetric",stages=["visual_direction","design"],
  problem="Symmetry is used for safety, producing frames that are stable and inert.",
  decision="Balance a large quiet area against a small dense one rather than matching mass on both sides.",
  reasoning="Visual weight is a product of size and density. A small dense element can balance a large empty one, which holds tension symmetry removes.",
  why="Retained tension keeps the eye moving, which sustains attention past the first instant.",
  use=["Editorial and brand work needing sustained interest","Formats with room to breathe"],
  avoid=["Authority statements requiring absolute stability","Very small formats where tension reads as error"],
  adv="Sustained visual interest",lim="Less immediately authoritative than symmetry",
  suit="Editorial and campaign work",unsuit="Authority statements and small formats",
  alts=["Symmetry where stability outranks interest"],
  aps=[("Matching mass on both sides of the frame for safety","Produces stability at the cost of any reason to keep looking","Large quiet area balanced against a small dense one")],
  profile=[("kind","composition"),("structure","Unequal masses balanced by density rather than by size."),("attention_effect","The eye continues to move, sustaining attention."),("failure_pattern","Imbalance without intent, which reads as a mistake.")],
  impact="Sustains attention beyond the first instant.",iscore=7,prio=7,conf=0.83)

K("composition.repetition.rhythm_and_break.001","Repetition with one break",CO,"repetition",stages=["visual_direction","design"],
  problem="Repeating elements are used for pattern, which is orderly and gives the eye nowhere to land.",
  decision="Establish a regular repeat and break it exactly once, placing the break where attention should land.",
  reasoning="The eye locates anomalies faster than it reads content. A single break in an established pattern is the fastest attention cue available.",
  why="One break is unambiguous; several break the pattern that made the first one visible.",
  use=["Range and multi-item assets","One item must lead within a set"],
  avoid=["Single-subject assets with no pattern","Comparison work requiring equal weight"],
  adv="Fastest available attention direction",lim="Requires enough items to establish a pattern",
  suit="Multi-item and range assets",unsuit="Single-subject and comparison work",
  alts=["Scale hierarchy where a pattern cannot be established"],
  aps=[("Breaking the pattern in several places for variety","Destroys the regularity that made any break visible","Exactly one break, placed where attention should land")],
  profile=[("kind","composition"),("structure","Regular repeat with a single deliberate interruption."),("attention_effect","Attention locks onto the anomaly before reading anything else."),("failure_pattern","Multiple breaks, which dissolve the pattern.")],
  impact="Directs attention faster than any content cue.",iscore=7,prio=7,conf=0.85)

# ── MATERIAL ──
K("material.metal.reflection_control.001","Controlling metal reflection",M,"metal",stages=["visual_direction","production"],
  problem="Metal is lit with point sources, which fills the surface with mirrored studio detail instead of describing its form.",
  decision="Light metal with large soft gradients so the surface reflects a controlled tonal ramp rather than identifiable objects.",
  reasoning="Metal shows what is in front of it. Its form is described by the gradient it reflects, not by light landing on it.",
  why="A smooth reflected gradient reads as polished form, while a mirrored studio reads as a mistake.",
  use=["Metal packaging, watches, hardware and appliances","Surface finish is part of the claim"],
  avoid=["Matte or brushed surfaces that scatter rather than mirror"],
  adv="True description of finish and form",lim="Requires large sources and careful set control",
  suit="Polished metal product work",unsuit="Matte and textured surfaces",
  alts=["Polarised capture where reflections cannot be controlled on set"],
  aps=[("Small hard sources aimed at a polished metal surface","Mirrors the studio into the product and hides its form","Large soft gradients reflected as a controlled tonal ramp")],
  impact="Describes metal form through controlled reflection.",iscore=8,prio=8,conf=0.89)

K("material.liquid.viscosity_evidence.001","Showing liquid viscosity",M,"liquid",stages=["visual_direction","production"],
  ind=["beauty","food_beverage"],
  problem="Liquids are shown static in a container, which communicates colour but nothing about the property buyers actually assess.",
  decision="Capture the liquid in motion — a pour, a drip, a lifted trail — so viscosity and body are visible.",
  reasoning="Viscosity exists only in movement. A static liquid conceals the single property that separates a rich formula from a thin one.",
  why="Motion supplies unfakeable physical evidence, since a thin liquid cannot be made to behave like a thick one.",
  use=["Serums, oils, sauces, syrups and honey","Texture or richness is part of the claim"],
  avoid=["Sealed packaging communication","Products where thinness is the benefit"],
  adv="Unfakeable evidence of formula body",lim="Difficult to execute and to keep clean",
  suit="Texture-led liquid products",unsuit="Sealed packaging work",
  alts=["Macro of surface tension at rest where motion is impractical"],
  aps=[("Serum shown static inside a sealed bottle for a richness claim","Conceals viscosity, the only property that could support the claim","A controlled pour or lifted trail showing how the liquid actually behaves")],
  impact="Provides physical evidence for texture claims.",iscore=8,prio=8,conf=0.87)

K("material.paper.tactility_signal.001","Paper texture as tactility",M,"paper",stages=["visual_direction","production"],
  pos=["premium","luxury"],
  problem="Premium packaging is photographed flat-on under even light, which erases the surface texture that justifies the price.",
  decision="Rake light across the paper at a shallow angle so fibre, emboss and edge thickness cast visible micro-shadow.",
  reasoning="Tactile quality is inferred from micro-shadow. Even frontal light removes every shadow and with it every tactile cue.",
  why="Raking light makes the surface legible as a material rather than as a colour, which is what carries the price.",
  use=["Premium packaging and print collateral","Material quality justifies the price"],
  avoid=["Flat digital reproduction","Packaging where printed graphics are the message"],
  adv="Communicates tactile quality visually",lim="Raking light can exaggerate defects and dust",
  suit="Premium packaging and print",unsuit="Graphic-led packaging communication",
  alts=["Macro edge detail where a full raking setup is impractical"],
  aps=[("Flat frontal lighting on an embossed premium box","Removes the micro-shadow that carries the tactile signal, leaving flat colour","Light raked across the surface at a shallow angle")],
  impact="Makes tactile quality visible.",iscore=7,prio=8,conf=0.86)

# ── TYPOGRAPHY ──
K("typography.sans.contemporary_neutrality.001","Neutral sans for contemporary trust",TY,"sans",stages=["design"],
  ind=["technology","beauty"],pos=["innovative","premium"],
  problem="Distinctive display faces are chosen for personality in categories where the brand needs to read as competent first.",
  decision="Use a neutral grotesque for the primary voice where credibility outranks personality, and carry distinctiveness in layout instead.",
  reasoning="Highly expressive letterforms draw attention to the typesetting, which in trust-dependent categories reads as decoration over substance.",
  why="Neutral letterforms let the content and structure carry the brand, which is more durable than a face that dates.",
  use=["Technology and efficacy-led categories","Credibility is the primary requirement"],
  avoid=["Heritage and craft positioning","Categories where personality is the differentiator"],
  adv="Credible, durable, ages slowly",lim="Low distinctiveness from type alone",
  suit="Technology and clinical categories",unsuit="Heritage and craft brands",
  alts=["Distinctive display face where personality is the differentiator"],
  aps=[("A highly expressive display face used for a clinical efficacy claim","Draws attention to the styling and away from the evidence, which reads as compensating","A neutral grotesque, with distinctiveness carried by layout")],
  profile=[("kind","typography"),("personality","Competent, current, unobtrusive."),("hierarchy","Weight and size carry the hierarchy since the face contributes little contrast."),("vietnamese_note","Grotesques generally carry well-drawn Vietnamese diacritics; verify the tone marks are drawn rather than composed.")],
  impact="Puts credibility ahead of typographic personality.",iscore=7,prio=7,conf=0.84)

K("typography.scale.headline_minimum_social.001","Minimum headline scale for social",TY,"scale",stages=["design","production"],
  ch=["instagram","tiktok","facebook"],asset="social_ad",ktype="production_rule",
  problem="Headlines sized for desktop review become unreadable at the physical size the asset is actually viewed at.",
  decision="Set social headlines at no less than a twentieth of the frame height and check them at 25 percent zoom before approval.",
  reasoning="Social assets are viewed at roughly a tenth of their design canvas size. Type that is comfortable on a monitor is marginal on a phone.",
  why="A fixed proportional floor and a zoom check both fail early, before the asset is in market.",
  use=["All social advertising","Any asset viewed primarily on mobile"],
  avoid=["Print and large format","Desktop-first placements"],
  adv="Headlines remain legible at real viewing size",lim="Fewer words fit per asset",
  suit="Mobile-first social",unsuit="Print and desktop formats",
  alts=["Shorter headline where the size floor cannot accommodate the copy"],
  aps=[("Approving headline size at full canvas on a desktop monitor","Overstates legibility by roughly ten times relative to real viewing","Proportional floor of one twentieth frame height, checked at 25 percent zoom")],
  profile=[("kind","typography"),("personality","Legibility before expression."),("hierarchy","Headline floor set proportionally, not in absolute points.")],
  impact="Keeps headlines legible at actual viewing size.",iscore=8,prio=9,conf=0.92)

# ── CHANNEL ──
K("channel.ooh.distance_legibility.001","Out-of-home distance legibility",CH,"ooh",stages=["design","production"],
  ch="billboard",ktype="production_rule",
  problem="Out-of-home artwork is designed at desk distance and carries detail no viewer will ever be close enough to resolve.",
  decision="Restrict out-of-home to one image, one line of no more than seven words, and the brand mark.",
  reasoning="Roadside exposure is a few seconds at distance. Anything beyond three elements exceeds what can be read in that window.",
  why="A hard element limit forces the message down to what the format can actually deliver.",
  use=["Billboard and roadside placements","Viewing distance exceeds ten metres"],
  avoid=["Transit placements with dwell time","Digital formats with sequencing"],
  adv="Message survives the real exposure window",lim="Very low information capacity",
  suit="Roadside and highway placements",unsuit="Transit and dwell-time environments",
  alts=["Sequenced messaging across multiple sites"],
  aps=[("Adding a supporting line and a website to a billboard","Exceeds what can be read at speed, so nothing is retained","One image, one short line, one mark")],
  impact="Fits the message to the real exposure window.",iscore=8,prio=8,conf=0.9)

K("channel.ecommerce.listing_clarity.001","E-commerce listing clarity",CH,"ecommerce",stages=["design","production"],
  ch="website",obj="conversion",ktype="production_rule",
  problem="Brand campaign imagery is reused on product listings, where atmosphere obstructs the identification the buyer needs.",
  decision="Lead the listing with an unobstructed product on a plain ground, and place atmospheric imagery only in later positions.",
  reasoning="A listing visit is an identification task, not a persuasion task. The buyer has already chosen to look and now needs to see.",
  why="Separating the identification image from the atmosphere images serves both jobs instead of compromising each.",
  use=["E-commerce product listings","Conversion is the objective"],
  avoid=["Brand campaign placements","Awareness objectives"],
  adv="Higher conversion through fast identification",lim="First image carries no brand atmosphere",
  suit="Product listings and marketplaces",unsuit="Brand campaigns",
  alts=["Atmospheric hero where the listing platform allows a gallery lead-in"],
  aps=[("Using an atmospheric campaign image as the first listing image","Obstructs the identification the buyer came to perform, raising bounce","Clean unobstructed product first, atmosphere in later gallery positions")],
  impact="Serves identification and persuasion separately.",iscore=8,prio=8,conf=0.88)

# ── CRITIC ──
K("critic.evaluation.audience_relevance.001","Audience relevance evaluation",CR,"audience_relevance",stages=["evaluation"],
  ktype="evaluation_rule",
  problem="Work is evaluated by the team commissioning it, whose reference set differs systematically from the target audience.",
  decision="Score audience relevance by naming the specific moment in the target's life the asset speaks to, and reject any asset where that moment cannot be named.",
  reasoning="Relevance is specific or absent. An asset that speaks to everybody speaks to nobody in particular.",
  why="Naming the moment converts an assumption about relevance into a claim that can be challenged.",
  use=["Concept and asset review","A defined target audience exists"],
  avoid=["Broad-reach awareness with no defined target"],
  adv="Surfaces the team's own reference bias",lim="Depends on the audience being genuinely defined",
  suit="Targeted campaign review",unsuit="Undifferentiated mass reach",
  alts=["Audience research where the moment cannot be named internally"],
  aps=[("Approving work because the team finds it relatable","Substitutes the team's reference set for the audience's, which differ systematically","Naming the specific audience moment the asset speaks to")],
  impact="Surfaces reference bias in internal review.",iscore=8,prio=9,conf=0.87)

K("critic.evaluation.production_feasibility.001","Production feasibility evaluation",CR,"feasibility",stages=["evaluation"],
  ktype="evaluation_rule",
  problem="Concepts are approved before anyone confirms they can be produced at the available budget, so compromise happens after commitment.",
  decision="Score feasibility before concept approval by naming the single hardest element to produce and confirming it is achievable.",
  reasoning="Compromise after approval degrades the idea invisibly, because the approved version is no longer the one being made.",
  why="Naming the hardest element early surfaces the constraint while the concept can still be changed rather than diluted.",
  use=["Concept approval gates","Any campaign with fixed production budget"],
  avoid=["Pure exploratory concepting with no production intent"],
  adv="Prevents post-approval dilution",lim="Can suppress ambition if applied too early",
  suit="Pre-production concept gates",unsuit="Early exploration",
  alts=["Parallel feasibility track for ambitious concepts"],
  aps=[("Approving a concept and discovering the key element is unaffordable in pre-production","The idea is diluted after commitment, so the approved version is never the one produced","Naming and confirming the hardest element before approval")],
  impact="Prevents invisible dilution after approval.",iscore=8,prio=8,conf=0.86)

# ── AUDIENCE + STRATEGY depth ──
K("audience.families.decision_dynamics.001","Household decision dynamics",A,"families",stages=["strategy"],
  ktype="framework",ind=["food_beverage","hospitality"],
  problem="Family-targeted work addresses one decision maker, when the purchase is usually vetoed or triggered by another household member.",
  decision="Identify the veto holder separately from the buyer and give each one visible reassurance in the frame.",
  reasoning="Household purchases pass two gates. Communication addressing only the buyer loses to the unaddressed veto.",
  why="Two visible reassurances clear both gates in one asset rather than requiring a second campaign.",
  use=["Family and household categories","Purchase involves more than one person"],
  avoid=["Individual discretionary purchases","B2B communication"],
  adv="Clears both decision gates in one asset",lim="Divides the frame's attention between two audiences",
  suit="Family food, hospitality and household categories",unsuit="Individual discretionary purchase",
  alts=["Sequenced messaging addressing each party separately"],
  aps=[("Addressing only the purchasing adult in family communication","Leaves the veto holder unaddressed, and the veto is where the purchase actually fails","Visible reassurance for both the buyer and the veto holder")],
  human=("Something the whole household will accept","Confidence the choice will not be criticised","To be seen as looking after everyone well"),
  impact="Clears both household decision gates.",iscore=8,prio=8,conf=0.83)

K("strategy.seasonal.tet_cultural_alignment.001","Tet campaigns require cultural alignment",S,"seasonal",stages=["strategy","concept"],
  obj="seasonal",
  problem="Seasonal campaigns for Tet apply Western holiday conventions, which read as decoration rather than as participation.",
  decision="Anchor Tet work in reunion and reciprocity rather than in gift-giving abundance, and treat red and gold as meaning rather than as palette.",
  reasoning="Tet is organised around return, family obligation and renewal. Abundance framing borrowed from Christmas misses the actual emotional centre.",
  why="Aligning with the real emotional structure lets the brand participate in the occasion instead of decorating around it.",
  use=["Tet and Lunar New Year campaigns in Vietnam","Brands seeking cultural participation rather than seasonal presence"],
  avoid=["Markets that do not observe the occasion","Categories with no plausible role in the ritual"],
  adv="Genuine cultural participation and higher acceptance",lim="Requires real understanding, and errors are conspicuous",
  suit="Vietnamese seasonal campaigns",unsuit="Non-observing markets",
  alts=["Neutral seasonal presence where the brand has no authentic role"],
  aps=[("Red and gold applied as decoration over a standard product campaign","Reads as borrowing the occasion's colours without participating in its meaning","Work built on reunion and reciprocity, with colour following meaning")],
  human=("Gifts and provisions for the occasion","Belonging to family and continuity","To be seen fulfilling obligation well"),
  impact="Converts seasonal presence into cultural participation.",iscore=9,prio=9,conf=0.85)

K("visual_direction.scientific_precision.technology.001","Precision world for technology",VD,"scientific_precision",stages=["visual_direction"],
  ind="technology",pos=["innovative","premium"],
  problem="Technology products are shown in warm lifestyle settings that soften exactly the precision the category is bought for.",
  decision="Build a controlled world with exact geometry, hard edges and no incidental objects.",
  reasoning="Precision in the frame is read as precision in the engineering. Incidental warmth implies the product needs help being liked.",
  why="Visible control substitutes for specification, communicating capability without a claim.",
  use=["Technology and precision-engineered products","Capability is the purchase driver"],
  avoid=["Consumer categories sold on warmth and companionship","Family technology positioning"],
  adv="Communicates capability without specification copy",lim="Cold and low in emotional warmth",
  suit="Precision technology",unsuit="Family and companion technology",
  alts=["Warm human context where the product is sold on companionship"],
  aps=[("Placing a precision device in a soft styled domestic scene","Softens the precision signal the category is bought on","Exact geometry and controlled edges with no incidental objects")],
  impact="Communicates engineering capability visually.",iscore=7,prio=7,conf=0.83)

K("photography.product.scale_reference.001","Give the product a scale reference",P,"scale",stages=["visual_direction","production"],
  problem="Products are photographed isolated, leaving buyers unable to judge size, which is the commonest cause of return.",
  decision="Include one familiar object or a hand in at least one asset in every set so absolute size is unambiguous.",
  reasoning="Isolated products have no absolute scale. Buyers substitute an assumption, and the assumption is frequently wrong.",
  why="One recognised reference resolves size definitively without a specification table.",
  use=["Any product with non-obvious size","E-commerce and considered purchase"],
  avoid=["Products with universally known dimensions","Assets where a hand would break the visual world"],
  adv="Removes the main cause of size-related returns",lim="Adds an element that must be styled and cast",
  suit="E-commerce and product sets",unsuit="Abstract brand imagery",
  alts=["Dimensional overlay where a physical reference is inappropriate"],
  aps=[("Every asset in the set showing the product isolated","Leaves size to assumption, which drives size-related returns","One asset in the set carrying a hand or familiar object as reference")],
  profile=[("kind","photography"),("framing_psychology","A hand implies use as well as scale, which adds a second signal for free.")],
  impact="Removes size ambiguity in remote purchase.",iscore=8,prio=8,conf=0.9)

flush()
