# -*- coding: utf-8 -*-
"""Phase 2.1 expansion — batch 3: layout, typography, channel, critic, craft."""
import io, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_lib import K, flush

LA = "layout"; TY = "typography"; CH = "channel"; CR = "critic"; VD = "visual_direction"; P = "photography"

def lay(kid, name, sub, purpose, structure, hierarchy, eye, failure, **kw):
    kw["profile"] = [("kind", "layout"), ("purpose", purpose), ("structure", structure),
                     ("visual_hierarchy", hierarchy), ("eye_movement", eye), ("failure_pattern", failure)]
    K(kid, name, LA, sub, **kw)

# ═══════════════════ LAYOUT INTELLIGENCE ═══════════════════
lay("layout.editorial_split.headline_parity.001", "Editorial split for headline parity", "editorial_split",
    "Give a headline equal standing with the image when the words carry half the argument.",
    "Frame divided on a vertical axis, image on one side, type block on the other, no overlap.",
    ["Headline", "Image subject", "Supporting line", "Brand mark"],
    "Enters on the type block, crosses to the image, returns to the sub-line.",
    "The divide drifts off the intended axis, so neither side reads as dominant and the layout looks undecided.",
    stages=["design"], asset=["poster","banner"], pos=["premium","mass"],
    problem="A strong headline is overlaid on an image where neither survives, because both are competing for the same pixels.",
    decision="Split the frame on a clean vertical axis and give the headline its own uncontested territory.",
    reasoning="Type over image always costs one of them. Separation lets both operate at full strength.",
    why="Uncontested territory means the headline needs no scrim, outline or drop shadow to stay legible.",
    use=["Headline carries substantive argument","Poster or banner formats with room to divide"],
    avoid=["Product hero work where the image must dominate","Formats too small to sustain two territories"],
    adv="Both headline and image work at full strength", lim="Reduces image area by roughly half",
    suit="Message-led posters and banners", unsuit="Product hero and small formats",
    alts=["Type over a deliberately empty area of the image where the image must dominate"],
    aps=[("Headline overlaid on a busy image with a dark scrim added for legibility",
          "The scrim damages the image and admits the layout never had room for the type",
          "A clean split giving the headline its own territory")],
    impact="Lets headline and image each operate at full strength.", iscore=8, prio=8, conf=0.88)

lay("layout.rule_of_thirds.product_placement.001", "Thirds placement for product assets", "thirds",
    "Place a product off-centre so the frame holds both subject and breathing room.",
    "Subject on a third intersection, remaining two thirds held as controlled space.",
    ["Product", "Negative space", "Headline", "Brand mark"],
    "Enters at the product, travels into the open space, settles on the mark.",
    "The product creeps toward centre during revisions until the layout loses its direction.",
    stages=["design"], asset=["poster","product_hero","social_ad"],
    problem="Products are centred by default, which produces stability but leaves no directed space for anything else.",
    decision="Place the product on a third intersection and hold the opposing space empty for type or air.",
    reasoning="Off-centre placement creates direction. The eye moves from subject into space, which gives copy somewhere to live.",
    why="Directed space is usable space; centred symmetry leaves only equal margins, which type cannot occupy without unbalancing it.",
    use=["Assets combining product and copy","Objective needs both subject and message"],
    avoid=["Pure authority statements where symmetry is the point","Square formats where thirds read as accidental"],
    adv="Creates usable directed space for copy", lim="Less absolute authority than centred symmetry",
    suit="Product-plus-copy layouts", unsuit="Symmetrical authority statements",
    alts=["Exact centre where authority outranks copy space"],
    aps=[("Product drifting to near-centre through successive revisions",
          "Loses the direction the thirds placement created while gaining none of centre's authority",
          "Holding the third intersection deliberately and defending it in review")],
    impact="Creates directed space that copy can occupy.", iscore=7, prio=8, conf=0.86)

lay("layout.stacked_vertical.story_format.001", "Stacked vertical for story formats", "stacked_vertical",
    "Sequence a message top to bottom in a 9:16 frame where the eye already scans vertically.",
    "Three horizontal bands: hook, subject, resolution, with the lower band kept clear of chrome.",
    ["Hook line", "Product or subject", "Call to action"],
    "Top to bottom in one pass, with no lateral movement required.",
    "Content placed in the lowest band is covered by platform interface and never seen.",
    stages=["design"], ch=["instagram","tiktok"], asset="social_ad",
    problem="Landscape compositions are cropped to 9:16, which places the subject wherever the crop happens to leave it.",
    decision="Compose natively in three vertical bands and keep the lowest band clear of load-bearing content.",
    reasoning="Vertical formats are scanned top to bottom in a single movement. A layout designed laterally fights that motion.",
    why="Native vertical banding matches the scan direction and keeps the message clear of interface overlay.",
    use=["Story and reel formats","Instagram and TikTok placements"],
    avoid=["Landscape and square placements","Print formats"],
    adv="Matches native scan direction, survives platform chrome", lim="Does not adapt to landscape without redesign",
    suit="Vertical social placements", unsuit="Landscape and print",
    alts=["Square-safe centre composition where one asset must serve several ratios"],
    aps=[("Cropping a landscape hero to 9:16 for story placement",
          "Places the subject arbitrarily and usually pushes the call to action under platform chrome",
          "Native vertical composition in three bands")],
    impact="Preserves message under native vertical scanning.", iscore=8, prio=9, conf=0.9,
    related=["layout.mobile_first.social_hierarchy.001"])

lay("layout.grid_catalogue.multi_product.001", "Grid layout for multi-product assets", "grid",
    "Present several products so comparison is possible without any one dominating.",
    "Regular grid with equal cell size, uniform spacing and consistent product scale.",
    ["Range as a whole", "Individual products", "Category label", "Brand mark"],
    "Scans row by row, returning to any product that breaks the pattern.",
    "Inconsistent product scale between cells, which reads as a size difference the range does not have.",
    stages=["design"], asset=["poster","banner"], obj=["awareness","conversion"],
    problem="Multi-product assets arrange items by aesthetic balance, which accidentally implies a hierarchy of importance.",
    decision="Use a regular grid with identical cell size and scale every product to the same visual weight.",
    reasoning="Any variation in cell size or product scale is read as a claim about relative importance, whether intended or not.",
    why="Uniformity removes the accidental claim so the range reads as a range rather than as a ranking.",
    use=["Range or collection communication","Comparison is the objective"],
    avoid=["Hero product launches where one item must lead","Storytelling formats"],
    adv="Clean comparison without accidental hierarchy", lim="Low emotional engagement, reads as catalogue",
    suit="Range and collection assets", unsuit="Single-hero launches",
    alts=["Hero-plus-supporting layout where one product genuinely leads"],
    aps=[("Varying product scale across grid cells for visual interest",
          "Implies an importance ranking the brand did not intend and buyers will read",
          "Uniform scale, with interest supplied by the products themselves")],
    impact="Enables comparison without implying a ranking.", iscore=7, prio=7, conf=0.85)

lay("layout.full_bleed.immersion.001", "Full bleed for immersion", "full_bleed",
    "Remove the frame so the viewer is inside the scene rather than looking at a picture of it.",
    "Image extends past every edge with no margin, type placed within the image's own quiet areas.",
    ["Scene", "Headline in a naturally quiet region", "Brand mark at minimum size"],
    "Enters anywhere, wanders the scene, finds type last.",
    "Type placed in a busy region and rescued with a scrim, which reintroduces the frame that bleed removed.",
    stages=["design"], ind=["hospitality","fashion"], asset=["poster","banner"],
    problem="Bordered layouts announce themselves as advertising before any content is read.",
    decision="Extend the image past every edge and place type only where the image is naturally quiet.",
    reasoning="A visible margin frames the content as a message. Removing it lets the scene be experienced instead of received.",
    why="Immersion lowers the viewer's advertising defences, which is when atmosphere can actually do its work.",
    use=["Atmosphere and place-led communication","Hospitality and fashion brand work"],
    avoid=["Information-dense assets needing structured space","Formats where safe margins are mandated"],
    adv="Immersive, low advertising signal", lim="Very limited structured space for copy",
    suit="Atmosphere-led brand work", unsuit="Information-dense retail assets",
    alts=["Margined layout where copy volume requires structure"],
    aps=[("Placing type over a busy image region and adding a scrim to make it legible",
          "Reinstates the frame the bleed was removing and damages the image",
          "Type placed only in regions the image already leaves quiet")],
    impact="Lowers advertising defences so atmosphere can work.", iscore=7, prio=7, conf=0.83)

lay("layout.hero_supporting.launch_hierarchy.001", "Hero and supporting for launches", "hero_supporting",
    "Introduce one new product while showing the range it joins.",
    "Hero at roughly 60 percent of the frame, supporting items at a quarter scale along one edge.",
    ["Hero product", "Launch message", "Supporting range", "Brand mark"],
    "Locks on the hero, reads the message, then scans the supporting row.",
    "Supporting items scaled large enough to compete, which dissolves the launch focus.",
    stages=["design"], obj="product_launch", asset=["poster","banner"],
    problem="Launch assets show the new product beside existing range at similar scale, so nothing reads as new.",
    decision="Give the hero at least 60 percent of the visual weight and hold supporting items to a quarter of its scale.",
    reasoning="A launch is a claim about one item. Equal scale contradicts the claim before the copy can make it.",
    why="Decisive scale separation makes the news legible without needing the word new.",
    use=["Product launches within an existing range","Objective is launch awareness"],
    avoid=["Range communication where no item leads","Comparison assets"],
    adv="Launch news is legible without stating it", lim="Supporting range gets minimal exposure",
    suit="Launch assets", unsuit="Range and comparison work",
    alts=["Uniform grid where the objective is range awareness"],
    aps=[("New and existing products shown at similar scale",
          "Removes the visual claim that anything is new, leaving the copy to do it alone",
          "Hero at 60 percent weight with supporting items at quarter scale")],
    impact="Makes launch news legible through scale alone.", iscore=8, prio=8, conf=0.87)

# ═══════════════════ TYPOGRAPHY INTELLIGENCE ═══════════════════
K("typography.vietnamese.diacritic_clearance.001", "Vietnamese diacritic clearance", TY, "vietnamese",
  ktype="production_rule", stages=["design","production"],
  problem="Latin-first typesetting is applied to Vietnamese, where stacked diacritics collide with the line above or are clipped by tight leading.",
  decision="Increase leading by at least 20 percent over the Latin default and verify that stacked marks on characters such as e-circumflex-acute clear the ascender line.",
  reasoning="Vietnamese stacks a tone mark above a vowel modifier, producing glyphs taller than any Latin equivalent the leading was set for.",
  why="Explicit clearance prevents the collisions and clipping that make otherwise correct typesetting look careless to a Vietnamese reader.",
  use=["Any asset containing Vietnamese text","Bilingual layouts sharing one type system"],
  avoid=["Latin-only assets where the default leading is sufficient"],
  adv="Correct, professional Vietnamese typesetting", lim="Costs vertical space and reduces copy capacity",
  suit="All Vietnamese-language work", unsuit="Latin-only communication",
  alts=["A typeface designed with Vietnamese diacritics in its vertical metrics"],
  aps=[("Applying Latin leading defaults to Vietnamese headlines",
        "Stacked tone marks collide with the descenders above or are clipped, which reads as amateur work",
        "Leading increased by at least a fifth with stacked marks verified against the ascender line")],
  profile=[("kind","typography"),("personality","Correctness in diacritics is read as respect for the reader."),("hierarchy","Headline leading needs proportionally more increase than body text."),("vietnamese_note","Test the sequence with e-circumflex-acute and o-horn-tilde, the tallest common stacks.")],
  impact="Prevents diacritic collision and clipping.", iscore=9, prio=10, conf=0.95)

K("typography.serif.heritage_authority.001", "Serif for heritage and authority", TY, "serif",
  stages=["design"], pos=["luxury","premium","traditional"],
  problem="Heritage positioning is executed in contemporary sans faces, which contradicts the claim of longevity.",
  decision="Use a high-contrast serif for the primary voice when the brand claims heritage, longevity or authority.",
  reasoning="Serif forms carry the visual memory of printing and institutions. That association arrives before the words are read.",
  why="Letterform history does the positioning work at no cost in space or copy length.",
  use=["Heritage, luxury and authority positioning","Print and premium digital"],
  avoid=["Technology and innovation positioning","Small-size interface text where contrast strokes break up"],
  adv="Instant heritage and authority signal", lim="Reads as conservative, weak at small sizes",
  suit="Luxury and heritage brand work", unsuit="Technology and interface contexts",
  alts=["Low-contrast serif where small-size legibility matters"],
  aps=[("Geometric sans applied to a brand claiming a century of history",
        "The letterforms contradict the claim, so the copy has to argue against its own typesetting",
        "A serif whose contrast and proportion match the era being claimed")],
  profile=[("kind","typography"),("personality","Established, authoritative, printed; carries institutional memory."),("hierarchy","Serif headline with a neutral sans for supporting text keeps hierarchy clear."),("vietnamese_note","Confirm the serif has properly drawn Vietnamese diacritics rather than composed fallbacks.")],
  impact="Aligns letterform history with positioning claim.", iscore=7, prio=8, conf=0.86)

K("typography.hierarchy.three_level_limit.001", "Three levels of hierarchy maximum", TY, "hierarchy",
  ktype="principle", stages=["design"],
  problem="Layouts accumulate five or six type sizes as stakeholders add emphasis, until nothing is emphasised.",
  decision="Limit any single asset to three type levels and separate each by at least a 1.5 ratio in size or weight.",
  reasoning="Hierarchy is relational. Beyond three levels the differences fall below the threshold at which a reader can rank them at a glance.",
  why="Three clearly separated levels are read instantly, which is all the time a paid asset actually gets.",
  use=["Any advertising layout","Formats with short exposure"],
  avoid=["Long-form editorial with genuine structural depth","Technical documentation"],
  adv="Instant, unambiguous reading order", lim="Forces content reduction rather than accommodation",
  suit="Advertising and social assets", unsuit="Editorial and documentation",
  alts=["Colour or position to separate content where a fourth level is unavoidable"],
  aps=[("Adding a fourth and fifth type size to emphasise additional content",
        "Compresses the differences until the reader cannot rank any of them quickly",
        "Three levels held, with surplus content moved to another asset")],
  profile=[("kind","typography"),("personality","Disciplined and confident; the layout knows what matters."),("hierarchy","Three levels, each separated by at least 1.5 in size or a full weight step.")],
  impact="Produces instantly readable hierarchy.", iscore=8, prio=9, conf=0.9,
  related=["concept.discipline.one_message_per_asset.001"])

# ═══════════════════ CHANNEL INTELLIGENCE ═══════════════════
K("channel.tiktok.first_frame_hook.001", "TikTok first-frame hook", CH, "tiktok",
  ktype="production_rule", stages=["design","production"], ch="tiktok", asset="social_ad",
  problem="Assets built for feed browsing are placed in a channel where the decision to stay is made almost immediately.",
  decision="Carry the complete proposition in the first frame, assuming no second frame will be seen.",
  reasoning="Scroll decisions in this channel are made in well under a second, before any build or reveal can complete.",
  why="A self-sufficient first frame converts the scroll decision into an impression rather than losing both.",
  use=["TikTok and short vertical video placements","Paid social with skip behaviour"],
  avoid=["Owned channels with committed audiences","Long-form and narrative formats"],
  adv="Survives the actual attention window", lim="Removes the possibility of a build or reveal",
  suit="Paid short-form vertical", unsuit="Owned long-form content",
  alts=["Narrative build for channels with proven dwell time"],
  aps=[("Opening with a slow establishing shot before the product appears",
        "The scroll decision is made before the reveal, so neither the setup nor the payoff is seen",
        "Complete proposition present in frame one, with any build as a bonus")],
  impact="Aligns the asset with the channel's real attention window.", iscore=9, prio=9, conf=0.9)

K("channel.instagram.feed_versus_story.001", "Feed and story are different jobs", CH, "instagram",
  ktype="decision_rule", stages=["design"], ch="instagram", asset="social_ad",
  problem="One asset is resized across feed and story, so it is composed for neither and underperforms in both.",
  decision="Compose feed assets for lateral scanning at 4:5 or 1:1 and story assets vertically at 9:16 as separate designs.",
  reasoning="Feed is browsed with sideways comparison against neighbouring posts; story is consumed full-screen with no neighbours.",
  why="Designing to each viewing mode preserves the composition rather than surrendering it to a crop.",
  use=["Instagram campaigns using both placements","Budget allows two compositions"],
  avoid=["Single-placement campaigns","Severely constrained production budgets"],
  adv="Each placement performs as designed", lim="Two compositions rather than one",
  suit="Multi-placement Instagram campaigns", unsuit="Single-placement or minimal-budget work",
  alts=["Centre-safe composition where one asset must serve both"],
  aps=[("Auto-cropping a 1:1 feed asset to 9:16 for story",
          "Leaves large empty bands or cuts the subject, and the crop chooses the composition",
          "Two native compositions, or a deliberately centre-safe single design")],
  impact="Preserves composition across placements.", iscore=8, prio=8, conf=0.88)

K("channel.print.ink_and_scale.001", "Print demands different contrast", CH, "print",
  ktype="production_rule", stages=["production"], ch="print",
  problem="Screen-approved artwork goes to print, where dark tones fill in and fine reversed type closes up.",
  decision="Hold shadow detail above 10 percent tone and set reversed type at no less than medium weight before releasing to print.",
  reasoning="Ink spread on paper closes small gaps that a backlit screen keeps open, so screen approval systematically overstates print legibility.",
  why="Building the margin in at design time avoids a reprint, which costs far more than the design constraint does.",
  use=["Any print or out-of-home delivery","Artwork approved on screen"],
  avoid=["Screen-only campaigns"],
  adv="Predictable, legible printed output", lim="Constrains the darkest and finest design choices",
  suit="Print and out-of-home", unsuit="Screen-only delivery",
  alts=["Proofing on the actual stock where the design cannot be constrained"],
  aps=[("Approving fine reversed type on a rich black on screen",
          "Ink spread closes the counters and the type becomes a solid mark on press",
          "Reversed type at medium weight or heavier with shadow detail held above 10 percent")],
  impact="Prevents legibility loss between screen and press.", iscore=8, prio=8, conf=0.9)

# ═══════════════════ CRITIC INTELLIGENCE ═══════════════════
K("critic.evaluation.strategic_fit.001", "Strategic fit evaluation", CR, "strategic_fit",
  ktype="evaluation_rule", stages=["evaluation"],
  problem="Work is assessed on craft and taste, and the question of whether it serves the business objective is assumed rather than asked.",
  decision="Score strategic fit by asking which stated objective the asset advances, and reject any asset that cannot name one.",
  reasoning="Craft quality and strategic fit are independent. Beautiful work can serve the wrong objective perfectly.",
  why="Forcing the objective to be named converts a vague approval into a testable claim.",
  use=["Concept and asset review","Any campaign with stated objectives"],
  avoid=["Exploratory work with no fixed objective yet"],
  adv="Separates craft assessment from strategic assessment", lim="Requires objectives to be stated precisely first",
  suit="Campaign review gates", unsuit="Early exploratory phases",
  alts=["Objective-setting workshop where objectives are not yet defined"],
  aps=[("Approving work because the team likes it",
        "Substitutes internal taste for the audience's response to a business problem",
        "Naming the objective the asset advances before any craft discussion")],
  impact="Prevents well-crafted work serving the wrong objective.", iscore=9, prio=9, conf=0.9)

K("critic.evaluation.generic_ai_feeling.001", "Detecting generic AI output", CR, "generic_detection",
  ktype="evaluation_rule", stages=["evaluation"],
  problem="Generated imagery is technically clean and compositionally average, and reviewers approve it because nothing is visibly wrong.",
  decision="Reject any generated asset that contains no specific, unrepeatable detail — a named place, a worn object, an asymmetry.",
  reasoning="Generative systems regress toward the category mean. Absence of specific detail is the signature of that regression.",
  why="Specificity is the one property averaging cannot produce, so its presence is a reliable test.",
  use=["Review of any generated imagery","Brand attribution is an objective"],
  avoid=["Deliberately abstract or graphic work with no representational content"],
  adv="Catches the dominant AI failure mode objectively", lim="Cannot assess strategic quality, only distinctiveness",
  suit="Generated asset review", unsuit="Abstract and graphic work",
  alts=["Side-by-side comparison against competitor work"],
  aps=[("Approving generated work because it is clean and correctly composed",
        "Cleanliness and correctness are exactly what averaging produces, so they are not evidence of quality",
        "Requiring one specific unrepeatable detail before approval")],
  impact="Catches the dominant generative failure mode.", iscore=9, prio=10, conf=0.9,
  related=["differentiation.universal.sameness_test.001"])

K("critic.evaluation.brand_consistency.001", "Brand consistency across an asset set", CR, "brand_consistency",
  ktype="evaluation_rule", stages=["evaluation"],
  problem="Individual assets are reviewed in isolation, so a set that drifts across five different visual worlds passes five separate approvals.",
  decision="Review the full asset set together and reject any asset that could belong to a different campaign.",
  reasoning="Consistency is a property of the set, and a property of a set cannot be assessed one member at a time.",
  why="Reviewing together makes drift visible, which single-asset review structurally cannot.",
  use=["Any multi-asset campaign","Brand attribution is an objective"],
  avoid=["Single-asset work","Deliberate multi-territory testing"],
  adv="Catches drift that single-asset review cannot see", lim="Requires the whole set before any approval",
  suit="Campaign set review", unsuit="Rolling single-asset production",
  alts=["Defined visual system with tolerances where sets cannot be reviewed together"],
  aps=[("Approving each asset as it is produced",
        "Drift accumulates below the threshold of any single review, and the set fragments",
        "Reviewing the complete set together against one organising idea")],
  impact="Preserves campaign coherence across an asset set.", iscore=8, prio=9, conf=0.88,
  related=["concept.discipline.single_organising_idea.001"])

# ═══════════════════ VISUAL DIRECTION ═══════════════════
K("visual_direction.warm_belonging.local_hospitality.001", "Lived-in world for local venues", VD, "warm_belonging",
  stages=["visual_direction"], ind=["food_beverage","hospitality"], pos=["mass","traditional"],
  problem="Local venues are art-directed toward a magazine ideal, which signals that regulars are not the intended audience.",
  decision="Build a lived-in world showing genuine use — worn surfaces, occupied seats, imperfect arrangement.",
  reasoning="Local trade is won on belonging. Immaculate styling signals a place designed for someone else.",
  why="Evidence of use is evidence that people already come, which is the strongest available social proof.",
  use=["Independent venues and local hospitality","Objective is trial or repeat visit"],
  avoid=["Luxury hospitality where flawlessness is the product","Opening-day communication before any use exists"],
  adv="Strong belonging and social proof", lim="Reads as less premium and less aspirational",
  suit="Neighbourhood and independent venues", unsuit="Luxury hotels and fine dining",
  alts=["Immaculate styling where flawlessness is genuinely the offer"],
  aps=[("Styling a neighbourhood cafe to look like a design magazine",
        "Signals the place is not for the regulars it depends on",
        "Genuine use retained, with composition doing the ordering rather than styling")],
  impact="Builds local belonging and social proof.", iscore=8, prio=8, conf=0.85)

K("visual_direction.editorial_attitude.fashion_social.001", "Editorial attitude for fashion social", VD, "editorial_attitude",
  stages=["visual_direction"], ind="fashion", ch=["instagram","tiktok"],
  problem="Fashion social work is styled for beauty rather than attitude, producing images that are admired and scrolled past.",
  decision="Direct for a single readable attitude in the subject's posture and expression, and let styling support it rather than lead.",
  reasoning="Attitude is the only element that survives thumbnail scale intact. Styling detail does not.",
  why="A readable stance gives the viewer something to identify with in the fraction of a second available.",
  use=["Fashion social and campaign work","Objective is stop rate or brand attribution"],
  avoid=["Product detail and e-commerce imagery","Categories sold on construction rather than identity"],
  adv="High stop rate and identity association", lim="Requires strong casting and direction",
  suit="Fashion social advertising", unsuit="E-commerce product imagery",
  alts=["Movement-led direction where garment behaviour carries the interest"],
  aps=[("Beautiful but expressionless studio portraits",
        "Nothing to identify with, so the image is admired for a moment and forgotten",
        "One specific readable attitude carried in posture and expression")],
  impact="Raises stop rate through identity legibility.", iscore=8, prio=8, conf=0.86)

K("visual_direction.clinical_precision.efficacy_beauty.001", "Clinical precision world", VD, "clinical_precision",
  stages=["visual_direction"], ind="beauty", cat="skincare", pos=["premium","luxury"],
  problem="Efficacy-led skincare is directed with lifestyle warmth, which softens exactly the precision the claim depends on.",
  decision="Build a precise, controlled world with hard edges, exact placement and no incidental props.",
  reasoning="Precision in the frame is read as precision in the formulation. Incidental warmth reads as compensation for weak evidence.",
  why="Visible control provides a proxy for laboratory rigour without laboratory props.",
  use=["Efficacy-led skincare with a real formulation claim","Sceptical or informed audiences"],
  avoid=["Comfort and sensory-led positioning","Mass-market family categories"],
  adv="Efficacy reads as credible without an explicit claim", lim="Cold, low warmth and approachability",
  suit="Clinical and scientific skincare", unsuit="Comfort and sensory categories",
  alts=["Warm sensory direction where the product is sold on experience"],
  aps=[("Adding soft fabric, flowers and warm props around a clinical product",
        "Softens the precision the efficacy claim rests on and moves the product toward category average",
        "Exact placement and controlled edges with no incidental props")],
  impact="Makes efficacy claims credible through visible control.", iscore=8, prio=8, conf=0.85,
  related=["strategy.scientific_luxury.beauty_efficacy.001"])

# ═══════════════════ PHOTOGRAPHY (industry craft) ═══════════════════
K("photography.beauty.texture_proximity.001", "Proximity for skincare texture", P, "texture_proximity",
  stages=["visual_direction","production"], ind="beauty", cat="skincare",
  problem="Skincare products are shot at product-catalogue distance, where the texture that carries the claim is not resolvable.",
  decision="Shoot at close working distance so the formula's own texture — viscosity, particle, sheen — is visible at full asset size.",
  reasoning="Skincare claims are claims about a material. A material that cannot be seen cannot support a claim.",
  why="Visible texture converts an asserted property into observable evidence.",
  use=["Skincare and formulation-led beauty","Texture or formulation is part of the claim"],
  avoid=["Packaging and range communication","Products whose claim is colour rather than texture"],
  adv="Turns a claim into visible evidence", lim="Loses packaging and brand identification",
  suit="Formulation-led hero work", unsuit="Range and packaging communication",
  alts=["Split composition pairing packaging with a texture inset"],
  aps=[("Full-bottle product shot used to support a texture claim",
        "The texture is below resolvable size, so the claim has no visual support",
        "Close working distance on the formula itself, with packaging carried on another asset")],
  profile=[("kind","photography"),("framing_psychology","Proximity implies intimacy and invites inspection, which suits an evidence claim."),("depth_of_field","Shallow, isolating one plane of texture so the eye knows where to look.")],
  impact="Converts formulation claims into visible evidence.", iscore=8, prio=8, conf=0.87)

K("photography.food.moment_before_eating.001", "The moment before eating", P, "moment_before",
  stages=["visual_direction","production"], ind="food_beverage",
  problem="Food is photographed either untouched or already eaten, and neither state produces appetite.",
  decision="Capture the moment of interruption — a poured stream mid-fall, a lifted portion, steam still rising — rather than a settled arrangement.",
  reasoning="Appetite is anticipatory. A settled plate is a record; an interrupted moment implies the eating is about to happen.",
  why="Implied imminence recruits the viewer into the moment rather than leaving them observing it.",
  use=["Food and beverage appetite work","Objective is trial or visit intent"],
  avoid=["Menu documentation requiring clear item identification","Packaging communication"],
  adv="Strong anticipatory appetite response", lim="Harder to execute, less clear item identification",
  suit="Appetite-led brand and venue work", unsuit="Menu and packaging documentation",
  alts=["Clean settled composition where item identification is the priority"],
  aps=[("Perfectly arranged untouched plate photographed from above",
        "Reads as documentation rather than as food about to be eaten",
        "One interrupted action — pour, lift or steam — captured mid-movement")],
  profile=[("kind","photography"),("framing_psychology","Interruption implies the viewer arrived mid-moment, which recruits rather than presents."),("camera_angle","Near the eye height of someone seated at the table.")],
  impact="Produces anticipatory appetite rather than documentation.", iscore=9, prio=9, conf=0.88)

K("photography.hospitality.characteristic_hour.001", "Shoot the characteristic hour", P, "characteristic_hour",
  stages=["visual_direction","production"], ind="hospitality",
  problem="Venues are shot when they are empty and convenient, which is never the hour that defines them.",
  decision="Shoot at the hour the venue is most itself, accepting real occupancy and the venue's own light.",
  reasoning="Every venue has one hour that defines its character. Any other hour documents the room but misses the place.",
  why="The characteristic hour supplies light, occupancy and atmosphere simultaneously, none of which can be staged convincingly.",
  use=["Hospitality and venue communication","Objective is booking or visit intent"],
  avoid=["Architectural documentation requiring unobstructed views","Pre-opening venues with no operation yet"],
  adv="Authentic atmosphere and social proof together", lim="Difficult scheduling, low control, requires consent",
  suit="Operating venues with a defined character", unsuit="Pre-opening and architectural documentation",
  alts=["Staged occupancy at the correct hour where real trade cannot be photographed"],
  aps=[("Shooting an empty venue at midday for scheduling convenience",
        "Captures the room at the one hour that describes nothing about its character",
        "The venue's defining hour with real occupancy and its own light")],
  profile=[("kind","photography"),("framing_psychology","Occupied space implies the viewer could be one of the people in it."),("camera_angle","Seated eye height, the position a guest would actually occupy.")],
  impact="Captures the character a room alone cannot show.", iscore=8, prio=8, conf=0.86,
  related=["lighting.ambient.available_light_honesty.001"])

K("photography.fashion.movement_over_pose.001", "Movement over pose", P, "movement",
  stages=["visual_direction","production"], ind="fashion",
  problem="Fashion is shot in held poses, which shows the garment's shape but not its behaviour, and behaviour is what buyers are uncertain about.",
  decision="Capture the garment in motion so weight, drape and recovery are visible in the frame.",
  reasoning="Buyers cannot assess how a garment moves from a still pose, and movement is the main uncertainty in remote purchase.",
  why="Motion answers the uncertainty directly and simultaneously produces the energy that stops a scroll.",
  use=["Fashion campaign and social work","Fabrics with distinctive drape or weight"],
  avoid=["Structured tailoring where cut, not movement, is the story","Flat technical documentation"],
  adv="Answers the buyer's real uncertainty while adding energy", lim="Lower shape clarity, harder to art direct precisely",
  suit="Fluid garments and social fashion", unsuit="Structured tailoring and technical imagery",
  alts=["Held pose with a visible unpressed fold where motion is impractical"],
  aps=[("Static held pose used for a fabric sold on its drape",
        "Shows silhouette but not behaviour, leaving the buyer's actual question unanswered",
        "Motion captured so weight and recovery are visible")],
  profile=[("kind","photography"),("framing_psychology","Movement implies a moment rather than a session, which reads as less staged."),("depth_of_field","Deep enough to hold the whole garment as it travels.")],
  impact="Answers the buyer's uncertainty about garment behaviour.", iscore=8, prio=8, conf=0.85,
  related=["material.fabric.weight_through_fall.001"])

flush()
