# -*- coding: utf-8 -*-
"""Phase 2.1 expansion — batch 5: closing gaps."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_lib import K, flush

K("strategy.trial_barrier.beauty_switching.001", "Lowering the switching barrier in beauty", "strategy", "trial_barrier",
  stages=["strategy","concept"], ind="beauty", obj=["conversion","product_launch"],
  problem="Beauty campaigns argue that a product is better, when the barrier is not belief but the risk of abandoning a routine that already works.",
  decision="Frame the product as an addition to an existing routine rather than a replacement for it.",
  reasoning="Switching risks a working regimen for an unproven one. Addition carries almost no risk and needs no abandonment.",
  why="Removing the abandonment requirement removes the real barrier without weakening the product claim.",
  use=["Beauty categories with established routines","Objective is trial or switching"],
  avoid=["All-in-one products where addition is not possible","First-purchase categories with no incumbent routine"],
  adv="Removes the actual barrier to trial", lim="Positions the product as supplementary rather than central",
  suit="Serums, treatments and additive steps", unsuit="Replacement products and all-in-one formats",
  alts=["Direct comparison where the product is demonstrably superior on a measurable axis"],
  aps=[("Arguing the product is better than the one already in use",
        "Asks the buyer to abandon a working routine on a promise, which is the risk they are avoiding",
        "Positioning the product as one added step alongside what already works")],
  human=("Better skin without starting over","Confidence she is not risking what already works","To be seen as informed rather than impulsive"),
  impact="Removes the abandonment risk that blocks trial.", iscore=8, prio=8, conf=0.85)

K("strategy.repeat_visit.hospitality_ritual.001", "Building repeat visit through ritual", "strategy", "repeat_visit",
  stages=["strategy"], ind="hospitality", obj="retention",
  problem="Venues invest all communication in acquisition, then rely on the product alone to produce the second visit.",
  decision="Name and repeat one specific returning behaviour — a regular order, a usual table, a standing time — across retention communication.",
  reasoning="A second visit is habit formation, and habits need a named cue. Quality alone produces satisfaction but not a trigger.",
  why="Naming the behaviour supplies the cue, which is the missing component between satisfaction and return.",
  use=["Operating venues with an existing customer base","Retention or frequency objectives"],
  avoid=["Pre-opening venues with no behaviour to name","One-off destination venues"],
  adv="Converts satisfaction into a repeatable habit", lim="Requires sustained repetition and real regulars",
  suit="Neighbourhood venues seeking frequency", unsuit="Destination and one-visit venues",
  alts=["Loyalty mechanics where a behavioural cue cannot be established"],
  aps=[("Spending the entire budget on acquisition and none on the return cue",
        "Produces satisfied first-time guests with nothing prompting a second visit",
        "One named returning behaviour repeated in retention communication")],
  human=("A reliable place nearby","The comfort of somewhere familiar","To be recognised as a regular"),
  impact="Converts satisfaction into repeat frequency.", iscore=8, prio=8, conf=0.83)

K("differentiation.technology.category_cliches.001", "Technology cliches and replacements", "differentiation", "technology",
  ktype="anti_pattern", stages=["concept"], ind="technology",
  problem="Technology imagery converges on floating devices, blue gradients and abstract network graphics that describe no product and no benefit.",
  decision="Reject floating-device, blue-gradient and abstract-network defaults in favour of the product mid-use by a specific person.",
  reasoning="These images signal the idea of technology rather than this product's capability, so every competitor owns them equally.",
  why="Use in context supplies benefit, scale and audience simultaneously, none of which an isolated device conveys.",
  use=["Technology and device concept development","Differentiation or benefit clarity is an objective"],
  avoid=["Component and B2B specification communication","Pre-release products that cannot be shown in use"],
  adv="Communicates benefit and audience together", lim="Requires casting, location and a real use case",
  suit="Consumer technology campaigns", unsuit="Component and specification communication",
  alts=["Detail macro on genuinely novel engineering where use cannot be shown"],
  aps=[("Device floating on a blue gradient with abstract network lines",
        "Signals the category rather than the product, and is available to every competitor equally",
        "The device mid-use by a specific person in a specific place"),
       ("Exploded-view renders used as hero imagery",
        "Communicates engineering interest to people who are buying an outcome",
        "The outcome the engineering produces, shown as it is experienced")],
  impact="Replaces category signalling with benefit communication.", iscore=8, prio=9, conf=0.85)

K("layout.asymmetric_split.editorial_tension.001", "Asymmetric split for editorial tension", "layout", "asymmetric_split",
  stages=["design"], asset=["poster","banner"], pos=["premium","innovative"],
  problem="Split layouts default to an even division, which is orderly and states no priority between image and message.",
  decision="Divide the frame at roughly one third to two thirds rather than in half, and give the larger share to whichever carries the argument.",
  reasoning="An even split says the two halves matter equally, which is almost never true and wastes the chance to state a priority.",
  why="An uneven division states the priority structurally, so the hierarchy is read before anything is decoded.",
  use=["Image-and-message layouts where one clearly leads","Editorial and campaign formats"],
  avoid=["Genuine parity between image and headline","Comparison layouts requiring equal weight"],
  adv="States priority structurally, with visual tension", lim="Wrong assignment inverts the intended hierarchy",
  suit="Editorial and campaign posters", unsuit="Comparison and parity layouts",
  alts=["Even split where image and message genuinely carry equal weight"],
  aps=[("Dividing the frame exactly in half by default",
        "States a parity that is rarely true and forfeits a free hierarchy signal",
        "A one-third to two-thirds division with the larger share given to the argument")],
  profile=[("kind","layout"),("purpose","State priority between image and message through proportion alone."),
           ("structure","Vertical division at approximately one third to two thirds."),
           ("visual_hierarchy",["Dominant side content","Subordinate side content","Brand mark"]),
           ("eye_movement","Enters on the larger field, crosses once to the smaller, settles."),
           ("failure_pattern","Division drifting toward half, which dissolves the stated priority.")],
  impact="Converts proportion into a hierarchy statement.", iscore=7, prio=7, conf=0.84)

K("channel.website.hero_scan_behaviour.001", "Website hero scan behaviour", "channel", "website",
  ktype="production_rule", stages=["design"], ch="website",
  problem="Website heroes are designed as posters, but visitors scan them in an F-pattern and leave before a centred composition resolves.",
  decision="Place the primary message in the upper left third and keep the first screen readable without scrolling.",
  reasoning="Web scanning begins top-left and moves right then down. A centred composition places the message outside the first fixation.",
  why="Aligning to the scan path means the message is read in the first fixation rather than the third.",
  use=["Website and landing page heroes","Desktop and tablet placements"],
  avoid=["Social feed placements with different scan behaviour","Print formats"],
  adv="Message lands in the first fixation", lim="Constrains composition to an off-centre structure",
  suit="Web heroes and landing pages", unsuit="Social and print formats",
  alts=["Centred composition where the page is a single-purpose splash"],
  aps=[("Centring the hero message like a poster",
        "Places the message outside the first fixation, so bounce happens before it is read",
        "Primary message in the upper left third, within the first screen")],
  impact="Aligns the hero to actual web scan behaviour.", iscore=8, prio=8, conf=0.88)

K("critic.evaluation.commercial_strength.001", "Commercial strength evaluation", "critic", "commercial_strength",
  ktype="evaluation_rule", stages=["evaluation"],
  problem="Creative review assesses whether work is good, and rarely asks whether a viewer could act on it if persuaded.",
  decision="Score commercial strength by confirming the asset makes the next action obvious, and reject any asset where it is not.",
  reasoning="Persuasion without a legible next action produces sentiment rather than behaviour, which is not what the budget bought.",
  why="Requiring the next action to be named separates work that moves people from work that merely pleases them.",
  use=["Any asset with a commercial objective","Performance and conversion campaigns"],
  avoid=["Pure brand awareness with no available action","Sponsorship and presence formats"],
  adv="Connects creative quality to commercial outcome", lim="Can push toward literal calls to action in brand work",
  suit="Conversion and consideration campaigns", unsuit="Pure awareness and presence",
  alts=["Brand metric evaluation where no immediate action exists"],
  aps=[("Approving persuasive work that leaves the next action unstated",
        "Generates intent with nowhere to go, so the intent decays before it converts",
        "Confirming the next action is obvious before approval")],
  impact="Connects creative quality to commercial behaviour.", iscore=8, prio=9, conf=0.87)

flush()
