# -*- coding: utf-8 -*-
"""Batch 4C — font pairing intelligence."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_typo_lib import TYPO, flush
LUX = dict(pos=["premium","luxury"])

def P(kid, name, sub, **kw):
    TYPO(kid, name, sub, **kw)

# ═══════════ LUXURY PAIRING ═══════════
P("typography.luxury_pairing.didone_grotesque.001","Didone display with neutral grotesque","luxury_pairing",
 purpose="Pair a refined display face with a neutral text face so refinement survives at every size.",
 visual_effect="High-contrast display against even-weight text creates strong optical difference between levels.",
 signal="Cultivated at the top, practical underneath — taste without impracticality.",
 hierarchy_rule="Didone at display only; grotesque carries every level from headline down.",
 spacing_rule="Didone tracked 20 to 40 units at display; grotesque at zero tracking for text.",
 failure="Using the Didone below 24 points, where hairlines vanish and the pairing looks broken rather than refined.",
 problem="Luxury brands set every level in one display serif, so text sizes lose the hairlines the face depends on.",
 decision="Pair a Didone for display above 24 points with a neutral grotesque for all text levels.",
 reasoning="Display faces are drawn for large sizes and text faces for small ones, and no single face does both well.",
 why="Splitting the roles by size lets each face operate in the range it was drawn for.",
 use=["Fashion and beauty luxury brands","Assets with both display and text levels"],
 avoid=["Single-level assets with no text","Small-format assets with no display size"],
 adv="Refinement at display, legibility at text", lim="Requires licensing two families",
 suit="Fashion and beauty luxury systems", unsuit="Single-level and small-format assets",
 alts=["A single transitional serif where two families cannot be licensed"],
 aps=[("Setting body copy in the Didone for brand consistency","Hairlines vanish at text size and the setting reads as broken rather than refined","Grotesque for text, Didone confined to display")],
 impact="Keeps refinement legible across the whole size range.", iscore=8, prio=8, conf=0.88,
 ind=["fashion","beauty"], **LUX)

P("typography.luxury_pairing.old_style_humanist.001","Old style serif with humanist sans","luxury_pairing",
 purpose="Pair heritage display with warm text so provenance reads without becoming stiff.",
 visual_effect="Angled stress in the serif against calligraphic sans forms produces a consistently human page.",
 signal="Made by people over a long time — heritage without institutional coldness.",
 hierarchy_rule="Old style at headline and pull quotes; humanist sans at body, captions and labels.",
 spacing_rule="Serif leading at 1.45; sans body at 1.55, since the two faces need different vertical room.",
 failure="Pairing the old style with a geometric sans, whose mechanical forms contradict the handmade claim.",
 problem="Craft brands pair heritage serifs with geometric sans, and the mechanical text face contradicts the provenance.",
 decision="Pair an old style serif for display with a humanist sans for text, never a geometric one.",
 reasoning="Both faces derive from handwriting, so their shared origin keeps the page consistent in what it claims.",
 why="Consistency of origin across the pairing is what makes a provenance claim hold at every level.",
 use=["Craft, artisanal and provenance-led brands","Food, spirits and handmade goods"],
 avoid=["Technology and precision categories","Brands positioned on modernity"],
 adv="Coherent provenance across all levels", lim="Reads as dated in contemporary categories",
 suit="Craft and heritage brands", unsuit="Technology and modern positioning",
 alts=["A single humanist family where two faces are too much variation"],
 aps=[("Pairing an old style serif with a geometric sans","The mechanical text face contradicts the handmade claim the display face is making","A humanist sans whose calligraphic origin matches the serif")],
 impact="Keeps a provenance claim consistent at every level.", iscore=7, prio=8, conf=0.87)

P("typography.luxury_pairing.single_family_optical.001","One family across optical sizes","luxury_pairing",
 purpose="Achieve display and text quality without introducing a second family.",
 visual_effect="Optical cuts of one family differ in proportion but share letterform identity across sizes.",
 signal="Disciplined — one voice, correctly modulated rather than swapped.",
 hierarchy_rule="Display cut above 32 points, text cut below 18, intermediate range uses the nearer cut.",
 spacing_rule="No manual tracking at all, since each optical cut carries its own correct spacing.",
 failure="Applying manual tracking on top of an optical cut, which double-corrects and produces uneven rhythm.",
 problem="Luxury systems license two families when one family with optical cuts would serve both roles better.",
 decision="Use one family with optical size cuts, applying the display cut above 32 points and the text cut below 18.",
 reasoning="Optical cuts solve the display-versus-text problem within one identity, which a pairing solves by fragmenting it.",
 why="A single letterform identity across all levels produces the strongest coherence available.",
 use=["Luxury systems with a single-family identity","Brands licensing a full optical family"],
 avoid=["Brands requiring tonal contrast between levels","Families with no optical cuts"],
 adv="Maximum coherence with correct optical behaviour", lim="No tonal contrast between levels",
 suit="Single-family luxury identities", unsuit="Systems needing serif and sans contrast",
 alts=["Serif and sans pairing where tonal contrast is required"],
 aps=[("Applying manual tracking on top of an optical display cut","Double-corrects the spacing the cut already carries, producing uneven rhythm","No manual tracking when the correct optical cut is used")],
 impact="Delivers coherence without a second family.", iscore=7, prio=8, conf=0.88, **LUX)

P("typography.luxury_pairing.serif_smallcaps_labels.001","Serif small caps for luxury labels","luxury_pairing",
 purpose="Set labels and eyebrows in a way that matches a serif display without shouting.",
 visual_effect="Small caps sit at x-height, producing a label that reads as formal without the crowding of full caps.",
 signal="Formal and quiet — a label rather than an announcement.",
 hierarchy_rule="Small caps occupy the eyebrow and label levels only; never headline or body.",
 spacing_rule="Tracked 60 to 100 units, since small caps are drawn tighter than their optical size requires.",
 failure="Using scaled-down capitals instead of true small caps, whose strokes are visibly too thin.",
 problem="Luxury labels use scaled capitals, whose strokes thin visibly and reveal the substitution.",
 decision="Use true drawn small caps for labels tracked 60 to 100 units, never scaled-down capitals.",
 reasoning="Scaling capitals reduces stroke weight proportionally, so they no longer match the surrounding text colour.",
 why="Drawn small caps carry correct stroke weight for their size, which is what makes them invisible as a device.",
 use=["Luxury labels, eyebrows and running heads","Families offering true small caps"],
 avoid=["Families without drawn small caps","Vietnamese text where cap-height marks crowd"],
 adv="Formal labels with correct page colour", lim="Requires a family with true small caps",
 suit="Luxury editorial and packaging", unsuit="Families lacking small caps",
 alts=["Tracked lowercase where small caps are unavailable"],
 aps=[("Using scaled-down capitals in place of true small caps","Strokes thin visibly against surrounding text, revealing the substitution as an error","True drawn small caps at the correct optical weight")],
 impact="Produces formal labels with correct page colour.", iscore=7, prio=7, conf=0.86,
 viet="Small caps crowd Vietnamese tone marks against the cap line; add 15 percent leading or use tracked lowercase.", **LUX)

P("typography.luxury_pairing.contrast_ratio_discipline.001","Pairing contrast discipline","luxury_pairing",
 purpose="Choose a pairing that is clearly different rather than nearly the same.",
 visual_effect="Two faces from clearly different classifications read as a deliberate pair rather than a mismatch.",
 signal="Intentional — the difference was chosen rather than tolerated.",
 hierarchy_rule="Display and text faces must differ in classification, not merely in weight or width.",
 spacing_rule="Each face keeps its own default tracking; matching tracking across classifications distorts one of them.",
 failure="Pairing two humanist sans faces, which differ enough to look wrong and not enough to look chosen.",
 problem="Pairings are chosen from similar faces, which read as an error rather than as a decision.",
 decision="Pair faces from clearly different classifications, rejecting any pairing within the same class.",
 reasoning="Small differences read as mistakes because the eye cannot tell whether they were intended.",
 why="Clear classification difference makes the pairing legible as a decision.",
 use=["Any two-face typographic system","Brand system definition"],
 avoid=["Single-family systems","Systems using optical cuts of one family"],
 adv="Pairing reads as deliberate", lim="Limits the pool of acceptable combinations",
 suit="Two-face brand systems", unsuit="Single-family and optical-cut systems",
 alts=["Single family with weight variation where no clear pairing exists"],
 aps=[("Pairing two humanist sans faces with slightly different proportions","Differs enough to look wrong and not enough to look chosen","Faces from clearly different classifications")],
 impact="Makes a pairing read as a decision.", iscore=7, prio=8, conf=0.88)

P("typography.luxury_pairing.mark_and_text_separation.001","Wordmark and text face separation","luxury_pairing",
 purpose="Keep a wordmark distinct from the text system so it stays a mark.",
 visual_effect="A wordmark set in a face used nowhere else remains recognisable as an identity element.",
 signal="Owned — the mark belongs to the brand rather than to the layout.",
 hierarchy_rule="The wordmark is outside the hierarchy entirely and never shares a face with any text level.",
 spacing_rule="Wordmark spacing is fixed at construction and never adjusted per layout.",
 failure="Setting the wordmark in the body face, after which it reads as a word rather than as a mark.",
 problem="Wordmarks are set in the brand text face, so they stop being distinguishable as identity elements.",
 decision="Set the wordmark in a face used nowhere else in the system, with spacing fixed at construction.",
 reasoning="A mark is recognised by consistent unique form, which is destroyed by reuse across the layout.",
 why="Exclusivity of the face is what lets a wordmark function as a signature.",
 use=["Brand identity systems","Any brand with a typographic wordmark"],
 avoid=["Wordless symbol identities","Systems deliberately using one face throughout"],
 adv="Mark stays recognisable as identity", lim="Adds a third face to the system",
 suit="Typographic brand identities", unsuit="Symbol-only identities",
 alts=["Customised letterforms drawn from the text face where a third face is excessive"],
 aps=[("Setting the wordmark in the standard body face","The mark reads as an ordinary word and loses its function as a signature","A face reserved exclusively for the mark")],
 impact="Keeps the wordmark functioning as a signature.", iscore=7, prio=7, conf=0.86)

# ═══════════ EDITORIAL PAIRING ═══════════
P("typography.editorial_pairing.serif_body_sans_furniture.001","Serif body with sans furniture","editorial_pairing",
 purpose="Separate reading text from navigational apparatus by face.",
 visual_effect="Serif body against sans headings and captions makes apparatus visually distinct from argument.",
 signal="Organised — the reader can tell content from navigation without thinking.",
 hierarchy_rule="Serif for body and pull quotes; sans for headings, captions, bylines and footnotes.",
 spacing_rule="Serif body at 1.55 leading; sans furniture at 1.4, since it is scanned rather than read.",
 failure="Using the serif for captions too, after which apparatus and content become visually indistinguishable.",
 problem="Editorial sets everything in one face, so readers cannot distinguish apparatus from argument while scanning.",
 decision="Set body and pull quotes in serif and all navigational furniture in sans.",
 reasoning="Scanning and reading are different tasks, and a face change marks which elements serve which.",
 why="The visual split lets a scanner skip content and a reader skip apparatus without effort.",
 use=["Long-form editorial and reports","Publications with substantial apparatus"],
 avoid=["Short articles with no furniture","Single-face brand systems"],
 adv="Content and apparatus separate at a glance", lim="Requires two licensed families",
 suit="Long-form editorial", unsuit="Short-form and single-face systems",
 alts=["Weight and size separation within one family"],
 aps=[("Setting captions in the same serif as the body","Apparatus and content become indistinguishable, so scanning requires reading","Sans for all navigational furniture")],
 impact="Separates apparatus from argument visually.", iscore=7, prio=8, conf=0.88, ch="website")

P("typography.editorial_pairing.sans_body_serif_display.001","Sans body with serif display","editorial_pairing",
 purpose="Combine contemporary reading comfort with editorial authority at headline level.",
 visual_effect="Serif headlines above sans body give each article an authoritative entry with a modern column.",
 signal="Current but serious — a publication of now that takes itself seriously.",
 hierarchy_rule="Serif at headline and standfirst; sans from body downward including subheads.",
 spacing_rule="Serif headline leading at 1.1; sans body at 1.55 with measure held to 60 to 75 characters.",
 failure="Using serif for subheads as well, which fragments the column into competing authority signals.",
 problem="Digital publications use sans throughout, so articles open without the authority a serif headline supplies.",
 decision="Set headline and standfirst in serif and everything from body downward in sans.",
 reasoning="Serif at display supplies authority; sans at text supplies the screen legibility serif loses at small size.",
 why="Splitting by size takes the strength of each classification where it actually applies.",
 use=["Digital publications and long-form web","Editorial with screen-first delivery"],
 avoid=["Print-first publications where serif body performs well","Single-face brand systems"],
 adv="Authority at entry, legibility in the column", lim="Two families to license and load",
 suit="Screen-first editorial", unsuit="Print-first and single-face systems",
 alts=["Serif throughout for print-first publications"],
 aps=[("Using the serif for subheads as well as headlines","Fragments the column into competing authority signals and the hierarchy blurs","Serif confined to headline and standfirst")],
 impact="Combines editorial authority with screen legibility.", iscore=7, prio=8, conf=0.87, ch="website")

P("typography.editorial_pairing.tonal_consistency_check.001","Tonal consistency in a pairing","editorial_pairing",
 purpose="Ensure two faces make the same claim about the publication.",
 visual_effect="Faces sharing era and formality register read as one voice at two volumes.",
 signal="Coherent — the publication has one personality across its levels.",
 hierarchy_rule="Both faces must be usable at three levels each without either reading as out of place.",
 spacing_rule="Leading values differ by no more than 0.15 between the two faces at the same level.",
 failure="Pairing a contemporary geometric with a historical serif, which reads as two publications sharing a page.",
 problem="Pairings are chosen for visual contrast alone, ignoring whether both faces make the same tonal claim.",
 decision="Pair faces from compatible eras and formality registers, rejecting pairings that differ in tonal claim.",
 reasoning="Contrast in classification is desirable, but contrast in tonal claim splits the brand's voice.",
 why="A shared register keeps the pairing reading as one publication rather than as a collision.",
 use=["Editorial and brand system definition","Any two-face system"],
 avoid=["Deliberate collision aesthetics","Single-face systems"],
 adv="One coherent voice across levels", lim="Rules out visually striking but tonally mismatched pairs",
 suit="Editorial and brand systems", unsuit="Deliberate collision aesthetics",
 alts=["Deliberate tonal collision where disruption is the brand position"],
 aps=[("Pairing a 1920s geometric with an 18th-century serif for contrast","Reads as two publications sharing a page rather than one voice at two volumes","Faces sharing era and formality register")],
 impact="Keeps a two-face system reading as one voice.", iscore=7, prio=8, conf=0.86)

P("typography.editorial_pairing.x_height_matching.001","X-height matching in pairings","editorial_pairing",
 purpose="Make two faces sit together without one appearing larger than the other.",
 visual_effect="Faces with similar x-heights at the same point size appear the same size to the reader.",
 signal="Precise — the pairing was measured rather than assumed.",
 hierarchy_rule="Where two faces share a level, their point sizes are adjusted so x-heights match optically.",
 spacing_rule="Baseline alignment is set by x-height rather than by point size when faces are mixed inline.",
 failure="Matching point sizes across faces with different x-heights, leaving one visibly larger.",
 problem="Mixed-face settings match point size, so a face with a larger x-height appears bigger and breaks the level.",
 decision="Match x-heights optically when two faces share a level, adjusting point size rather than assuming parity.",
 reasoning="Perceived size is governed by x-height, not by point size, which is a measure of the em rather than the letter.",
 why="Optical matching makes two faces occupy the same level rather than appearing to occupy two.",
 use=["Inline mixed-face settings","Two-face systems sharing a level"],
 avoid=["Single-face systems","Faces used only at separate levels"],
 adv="Faces sit together correctly", lim="Requires per-pair adjustment rather than a global rule",
 suit="Mixed-face inline settings", unsuit="Single-face and level-separated systems",
 alts=["Keeping faces strictly on separate levels so matching is unnecessary"],
 aps=[("Setting two faces at the same point size within one line","The face with the larger x-height appears bigger and the level visibly breaks","Point sizes adjusted so x-heights match optically")],
 impact="Makes two faces occupy one level correctly.", iscore=7, prio=7, conf=0.88)

P("typography.editorial_pairing.three_face_limit.001","Three face maximum","editorial_pairing",
 purpose="Keep a system coherent by limiting how many faces it contains.",
 visual_effect="Beyond three faces the page stops reading as one system and becomes a collection.",
 signal="Systematic — variety is produced within constraints rather than by adding families.",
 hierarchy_rule="Maximum three faces: display, text and optionally one accent for a specific recurring role.",
 spacing_rule="Each face keeps its own default spacing; no attempt is made to harmonise them numerically.",
 failure="Adding a fourth face for one special use, after which every subsequent exception seems justified.",
 problem="Systems accumulate faces for special cases until the page reads as several brands at once.",
 decision="Limit any typographic system to three faces, with the third reserved for one specific recurring role.",
 reasoning="Coherence depends on repetition, and each added face reduces how often any of them repeats.",
 why="A hard ceiling prevents the incremental accumulation that dissolves systems.",
 use=["Brand and editorial system definition","Multi-asset campaigns"],
 avoid=["Single-asset experimental work","Deliberate maximalist aesthetics"],
 adv="System stays coherent under pressure", lim="Some special cases must be solved within existing faces",
 suit="Brand and editorial systems", unsuit="Experimental and maximalist work",
 alts=["Weight and width variation to solve special cases within existing faces"],
 aps=[("Adding a fourth face for one special use case","Every subsequent exception then seems equally justified and the system dissolves","The special case solved within one of the three existing faces")],
 impact="Prevents systems dissolving through accumulation.", iscore=7, prio=8, conf=0.88)

P("typography.editorial_pairing.weight_pairing_balance.001","Weight balance across a pairing","editorial_pairing",
 purpose="Keep two faces producing the same page colour at the same level.",
 visual_effect="Faces of nominally equal weight can differ visibly in density, making one look heavier.",
 signal="Even — the page has consistent texture regardless of which face is set.",
 hierarchy_rule="Weight names are ignored; weights are chosen so both faces produce matching page colour.",
 spacing_rule="Tracking adjusted per face to equalise page colour, typically 5 to 15 units on the lighter face.",
 failure="Matching weight names rather than page colour, leaving one face visibly heavier at the same level.",
 problem="Pairings match weight names, but a regular in one family can be visibly heavier than a regular in another.",
 decision="Match page colour rather than weight names, adjusting tracking 5 to 15 units to equalise density.",
 reasoning="Weight naming is not standardised across foundries, so equal names do not produce equal density.",
 why="Matching optical density is what makes two faces read as one level rather than two.",
 use=["Any two-face system","Mixed-face body and heading settings"],
 avoid=["Single-family systems","Faces used at clearly separate levels"],
 adv="Consistent page texture", lim="Requires visual comparison rather than a numeric rule",
 suit="Two-face systems", unsuit="Single-family systems",
 alts=["Single family where matching cannot be achieved"],
 aps=[("Assuming regular in one family matches regular in another","Weight naming is not standardised, so one face reads visibly heavier at the same level","Weights chosen by comparing page colour directly")],
 impact="Produces consistent page texture across faces.", iscore=7, prio=7, conf=0.87)

# ═══════════ TECHNOLOGY PAIRING ═══════════
P("typography.technology_pairing.grotesque_mono.001","Grotesque with monospace accent","technology_pairing",
 purpose="Signal technical credibility without setting everything in monospace.",
 visual_effect="Monospace against proportional text marks code and data as a different kind of content.",
 signal="Technical and precise — the brand knows the difference between prose and code.",
 hierarchy_rule="Grotesque carries all prose levels; monospace is reserved for code, identifiers and data only.",
 spacing_rule="Monospace at 90 percent of body size so its wider letterforms match surrounding text colour.",
 failure="Setting body copy in monospace for a technical look, which slows reading by roughly a fifth.",
 problem="Technology brands set prose in monospace for a technical aesthetic, which measurably slows reading.",
 decision="Use a grotesque for all prose and reserve monospace at 90 percent size for code and identifiers only.",
 reasoning="Monospace exists to make character position predictable, which is useless in prose and costly to read.",
 why="Reserving it for code makes the face carry meaning rather than decoration.",
 use=["Technology, developer and data products","Documentation and interfaces"],
 avoid=["Consumer categories with no technical content","Long-form prose"],
 adv="Technical signal where it carries meaning", lim="Requires a second licensed family",
 suit="Developer and technical products", unsuit="Consumer prose categories",
 alts=["Weight or colour marking for code where a monospace family is unavailable"],
 aps=[("Setting body prose in monospace for a technical aesthetic","Reading slows by roughly a fifth for a decorative signal","Monospace reserved for code and identifiers, prose in a grotesque")],
 impact="Marks technical content meaningfully.", iscore=8, prio=8, conf=0.89, ind="technology", ch="website")

P("typography.technology_pairing.variable_font_system.001","Variable font as a pairing substitute","technology_pairing",
 purpose="Get pairing-level range from one file without a second family.",
 visual_effect="Continuous weight and width axes provide contrast a two-face pairing would otherwise supply.",
 signal="Efficient and modern — the system is built for the medium it ships in.",
 hierarchy_rule="Levels defined by named instances on the weight axis, not by arbitrary interpolated values.",
 spacing_rule="Tracking defined per named instance, since optical spacing needs change across the weight axis.",
 failure="Using arbitrary interpolated weights, which makes the system impossible to reproduce consistently.",
 problem="Web systems load several static families, costing page weight for contrast one variable file could supply.",
 decision="Use one variable family with named instances per level rather than loading multiple static families.",
 reasoning="A variable file carries the whole range at a fraction of the payload of several static weights.",
 why="Named instances keep the system reproducible while the axis supplies the contrast.",
 use=["Web and product interfaces","Performance-sensitive delivery"],
 avoid=["Print-only work","Environments without variable font support"],
 adv="Full range at low payload", lim="Requires modern rendering support",
 suit="Web and app interfaces", unsuit="Print and legacy environments",
 alts=["Two static weights where variable support is unavailable"],
 aps=[("Using arbitrary interpolated weight values across a system","The system cannot be reproduced consistently and drifts between assets","Named instances defined once per hierarchy level")],
 impact="Delivers pairing-level range at low payload.", iscore=7, prio=7, conf=0.86, ch="website", ind="technology")

P("typography.technology_pairing.ui_and_marketing_split.001","Interface and marketing face split","technology_pairing",
 purpose="Let marketing express personality while the product stays neutral.",
 visual_effect="A distinctive marketing face against a neutral interface face separates persuasion from use.",
 signal="Honest — the brand does not perform while you are working.",
 hierarchy_rule="Marketing face for campaign and site display; interface face for every in-product level.",
 spacing_rule="Interface face at zero tracking throughout; marketing face tracked per level as design requires.",
 failure="Carrying the expressive marketing face into the product, where its personality becomes friction.",
 problem="Brands use one expressive face everywhere, and the personality becomes friction during actual product use.",
 decision="Use a distinctive face for marketing and a neutral face for every in-product interface level.",
 reasoning="Marketing is read once with attention; interfaces are read repeatedly under task load.",
 why="Splitting by context lets each face serve a different reading mode without compromise.",
 use=["Software products with marketing surfaces","Brands with distinct acquisition and use contexts"],
 avoid=["Single-surface brands","Products where the interface is itself the brand experience"],
 adv="Personality without task friction", lim="Two systems to maintain and document",
 suit="Software with separate marketing and product", unsuit="Single-surface brands",
 alts=["One neutral face throughout where consistency outranks expression"],
 aps=[("Carrying an expressive marketing face into the product interface","Personality becomes friction under repeated task load, which lowers usability","A neutral face for every in-product level")],
 impact="Separates persuasion from repeated use.", iscore=7, prio=8, conf=0.87, ind="technology", ch="website")

P("typography.technology_pairing.data_display_numerals.001","Numeral treatment across a technology pairing","technology_pairing",
 purpose="Keep figures comparable wherever they appear in a technical system.",
 visual_effect="Tabular figures in data contexts and proportional figures in prose keep both readable.",
 signal="Rigorous — numbers are treated as data rather than as words.",
 hierarchy_rule="Figure style is set by context, not by level: tabular in data, proportional in prose.",
 spacing_rule="No tracking on tabular figures anywhere, since tracking destroys column alignment.",
 failure="Using one figure style throughout, which either breaks columns or produces uneven prose.",
 problem="Technical systems set one figure style everywhere, so either tables misalign or prose spaces unevenly.",
 decision="Set figure style by context: tabular lining in data and proportional in running prose.",
 reasoning="Tables need equal widths for vertical comparison; prose needs proportional widths for even colour.",
 why="Context-driven selection serves both requirements without compromising either.",
 use=["Technical and financial products","Any system with both data and prose"],
 avoid=["Prose-only content","Data-only displays"],
 adv="Both tables and prose read correctly", lim="Requires context-aware styling rules",
 suit="Mixed data and prose systems", unsuit="Single-context content",
 alts=["Tabular throughout where data dominates the system"],
 aps=[("Using tabular figures throughout including running prose","Even digit widths leave visible gaps in prose, producing uneven page colour","Proportional figures in prose, tabular in data")],
 impact="Serves both tables and prose correctly.", iscore=7, prio=8, conf=0.88, ind="technology", ch="website")

P("typography.technology_pairing.loading_performance_budget.001","Font payload budget","technology_pairing",
 purpose="Keep typographic ambition within a performance budget.",
 visual_effect="Fewer weights loaded means faster first paint and no flash of unstyled text.",
 signal="Considerate — the brand values the user's connection as well as their eye.",
 hierarchy_rule="Hierarchy must be achievable within four loaded weights total across all faces.",
 spacing_rule="Spacing rules must not depend on weights outside the loaded set.",
 failure="Designing a hierarchy requiring seven weights, which either loads slowly or falls back visibly.",
 problem="Type systems are designed without a payload budget, so they load slowly or fall back mid-render.",
 decision="Design every hierarchy to work within four loaded weights across all faces combined.",
 reasoning="Each additional weight is a separate file, and font payload delays the first meaningful paint.",
 why="A hard weight budget forces hierarchy decisions that survive real network conditions.",
 use=["Web and app delivery","Performance-sensitive markets"],
 avoid=["Print and offline delivery","Environments with guaranteed fast connections"],
 adv="Fast first paint with no fallback flash", lim="Constrains hierarchy expressiveness",
 suit="Web delivery", unsuit="Print and offline media",
 alts=["Variable font where more range is genuinely required"],
 aps=[("Designing a hierarchy requiring seven separate weight files","Either loads slowly or falls back visibly mid-render, which looks broken","A hierarchy built within four loaded weights")],
 impact="Keeps typography fast under real conditions.", iscore=7, prio=8, conf=0.88, ch="website", ind="technology")

P("typography.technology_pairing.fallback_stack_matching.001","Fallback stack matching","technology_pairing",
 purpose="Prevent layout shift when a web font fails or loads late.",
 visual_effect="A fallback with matched metrics keeps line breaks identical while the web font loads.",
 signal="Robust — the layout holds even when the network does not.",
 hierarchy_rule="Every level declares a fallback whose x-height and width are within 5 percent of the web font.",
 spacing_rule="Size-adjust and letter-spacing overrides tuned per fallback so metrics match during swap.",
 failure="Declaring a generic sans-serif fallback, which reflows the entire layout when the web font arrives.",
 problem="Fallback stacks name generic families whose metrics differ, causing visible reflow on font load.",
 decision="Declare a metrically matched fallback for every level with x-height and width within 5 percent.",
 reasoning="Layout shift on font swap is caused by metric mismatch, not by the swap itself.",
 why="Matched metrics make the swap invisible because line breaks do not change.",
 use=["Web delivery with custom fonts","Performance and stability sensitive sites"],
 avoid=["System-font-only designs","Print and offline media"],
 adv="No layout shift on font load", lim="Requires per-face fallback tuning",
 suit="Custom web font delivery", unsuit="System-font and offline designs",
 alts=["System font stack only, where custom fonts are not essential"],
 aps=[("Declaring a generic sans-serif fallback with no metric matching","The entire layout reflows when the web font arrives, which reads as instability","A metrically matched fallback with size-adjust tuning")],
 impact="Removes layout shift on font load.", iscore=7, prio=8, conf=0.89, ch="website", ind="technology")

# ═══════════ BEAUTY PAIRING ═══════════
P("typography.beauty_pairing.serif_display_clean_sans.001","Serif display with clean sans for beauty","beauty_pairing",
 purpose="Combine desirability at headline with clinical clarity in claims.",
 visual_effect="A refined serif headline above a clean sans claim separates seduction from evidence.",
 signal="Desirable and credible — the brand offers both feeling and proof.",
 hierarchy_rule="Serif at headline; sans at claims, ingredients and directions without exception.",
 spacing_rule="Serif headline tracked 20 units; sans claims at zero tracking with 1.5 leading.",
 failure="Setting ingredient lists in the display serif, where small sizes make them look decorative rather than factual.",
 problem="Beauty brands set claims in the display serif, so factual content reads as decoration.",
 decision="Set headline in a refined serif and every claim, ingredient and direction in a clean sans.",
 reasoning="Desirability and evidence are different claims, and setting both in one face blurs which is being made.",
 why="Face separation lets a sceptical reader locate the evidence without reading the seduction.",
 use=["Beauty and personal care","Products making efficacy claims"],
 avoid=["Pure fragrance and mood-led categories","Single-claim minimal packaging"],
 adv="Desire and evidence both legible", lim="Two families to license and manage",
 suit="Efficacy-led beauty", unsuit="Mood-led fragrance",
 alts=["Single humanist family where evidence and desire share a register"],
 aps=[("Setting ingredient lists in the display serif","Small sizes make factual content look decorative, so sceptical readers discount it","Claims and ingredients in a clean sans")],
 impact="Keeps evidence legible alongside desire.", iscore=8, prio=8, conf=0.88, ind="beauty")

P("typography.beauty_pairing.clinical_sans_only.001","Sans-only for clinical beauty","beauty_pairing",
 purpose="Signal that the product is bought on evidence rather than on feeling.",
 visual_effect="A single neutral sans across all levels produces an even, laboratory-like page.",
 signal="Evidence-led — the brand is selling a result rather than a mood.",
 hierarchy_rule="One sans at three levels separated by weight; no serif anywhere in the system.",
 spacing_rule="Leading at 1.5 throughout with tracking at zero, giving uniform page colour.",
 failure="Introducing a serif accent for warmth, which reintroduces the mood register the system excluded.",
 problem="Clinical beauty brands add serif accents for warmth, which contradicts the evidence positioning.",
 decision="Use one neutral sans across every level and exclude serif entirely from the system.",
 reasoning="Serif letterforms carry historical and emotional association that dilutes an evidence claim.",
 why="Uniform sans keeps every level in the same evidentiary register.",
 use=["Clinical and dermatological beauty","Efficacy-led positioning"],
 avoid=["Luxury and sensory beauty","Heritage and craft positioning"],
 adv="Consistent evidence register", lim="Cold, with no sensory warmth available",
 suit="Clinical beauty", unsuit="Sensory and luxury beauty",
 alts=["Serif and sans pairing where sensory appeal is part of the proposition"],
 aps=[("Adding a serif accent to a clinical beauty system for warmth","Reintroduces the mood register the system excluded, diluting the evidence claim","One neutral sans throughout")],
 impact="Keeps the whole system in an evidence register.", iscore=7, prio=8, conf=0.87, ind="beauty")

P("typography.beauty_pairing.ingredient_legibility.001","Ingredient list legibility","beauty_pairing",
 purpose="Make required ingredient information genuinely readable.",
 visual_effect="A face with open apertures at 6 to 7 points keeps long chemical names distinguishable.",
 signal="Transparent — the brand is not hiding what is in the product.",
 hierarchy_rule="Ingredient lists are a distinct level with their own face selection driven by legibility alone.",
 spacing_rule="Tracking increased 10 to 20 units and leading at 1.4, since dense chemical names need separation.",
 failure="Using the brand display face at 5 points, which makes required information legally present but unreadable.",
 problem="Ingredient lists use the brand face at minimum size, making required information technically present but unreadable.",
 decision="Set ingredient lists in an open-aperture face at 6 points minimum, tracked 10 to 20 units looser.",
 reasoning="Long unfamiliar words cannot be recognised by word shape, so every character must be individually legible.",
 why="Character-level legibility is the only mechanism available where word recognition cannot help.",
 use=["Beauty and personal care packaging","Regulated ingredient disclosure"],
 avoid=["Display and marketing surfaces","Products with no ingredient requirement"],
 adv="Genuinely readable disclosure", lim="Requires more packaging area",
 suit="Regulated packaging", unsuit="Marketing and display surfaces",
 alts=["QR-linked full disclosure where pack area is genuinely insufficient"],
 aps=[("Setting ingredients in the display face at 5 points","Required information becomes legally present but practically unreadable","An open-aperture face at 6 points minimum, tracked looser")],
 impact="Makes required disclosure genuinely readable.", iscore=7, prio=8, conf=0.89, ind="beauty")

P("typography.beauty_pairing.script_restraint.001","Script face restraint in beauty","beauty_pairing",
 purpose="Use a script face without making the product look dated.",
 visual_effect="A script confined to one word creates a focal accent against otherwise neutral setting.",
 signal="Personal — one handwritten moment inside an otherwise composed system.",
 hierarchy_rule="Script occupies one element only, never a full line and never more than one word per asset.",
 spacing_rule="Script never tracked, since letter connections break when spacing is altered.",
 failure="Tracking a connecting script, which breaks the joins and reveals it as a font rather than handwriting.",
 problem="Beauty brands set whole headlines in script faces, which reads as dated and reduces legibility sharply.",
 decision="Confine script faces to a single word per asset and never apply tracking to them.",
 reasoning="Script legibility falls steeply with length, and tracking destroys the connections that make it script.",
 why="One word keeps the personal signal while staying within the length script can carry.",
 use=["Beauty accents and signatures","Products with a personal or artisanal story"],
 avoid=["Clinical positioning","Any text over one word"],
 adv="Personal accent without legibility cost", lim="Extremely limited application",
 suit="Beauty and artisanal accents", unsuit="Clinical and long-form settings",
 alts=["Italic in the text family where a script is too decorative"],
 aps=[("Applying tracking to a connecting script face","Breaks the letter joins and reveals it as a font rather than as handwriting","Script left at default spacing, confined to one word")],
 impact="Adds a personal accent without legibility cost.", iscore=6, prio=7, conf=0.85, ind="beauty")

P("typography.beauty_pairing.pack_and_campaign_consistency.001","Pack and campaign face consistency","beauty_pairing",
 purpose="Make the product recognisable from campaign to shelf.",
 visual_effect="The same display face on pack and in campaign creates a direct recognition link.",
 signal="Consistent — the thing advertised is evidently the thing on the shelf.",
 hierarchy_rule="Display face is shared between pack and campaign; text faces may differ by surface.",
 spacing_rule="Display tracking matched between pack and campaign, adjusted only for reproduction size.",
 failure="Using a different display face on pack, which breaks the recognition link the campaign paid to build.",
 problem="Campaign and packaging use different faces, so the shelf does not cash in the recognition the campaign built.",
 decision="Share the display face between pack and campaign with matched tracking adjusted only for size.",
 reasoning="Shelf recognition depends on visual continuity with the advertising the shopper saw.",
 why="A shared display face is the cheapest continuity signal available across surfaces.",
 use=["FMCG and retail beauty","Campaigns driving to physical retail"],
 avoid=["Direct-to-consumer with no retail presence","Products sold only through marketplaces"],
 adv="Campaign spend converts at shelf", lim="Constrains pack design freedom",
 suit="Retail-distributed beauty", unsuit="Marketplace-only distribution",
 alts=["Colour and mark continuity where the pack face is fixed by regulation"],
 aps=[("Using a different display face on packaging than in campaign","Breaks the recognition link, so campaign spend does not convert at shelf","The same display face across both surfaces")],
 impact="Converts campaign recognition at shelf.", iscore=7, prio=8, conf=0.87, ind="beauty")

P("typography.beauty_pairing.claim_qualifier_pairing.001","Claim and qualifier pairing","beauty_pairing",
 purpose="Attach regulatory qualifiers to claims so both are read together.",
 visual_effect="A qualifier in the same face one weight lighter reads as part of the claim rather than a footnote.",
 signal="Compliant and candid — the qualification is presented rather than hidden.",
 hierarchy_rule="Qualifier is a sub-level of its claim, never a separate footnote level elsewhere on the pack.",
 spacing_rule="Qualifier set at 60 percent of claim size directly beneath, with no more than 0.25 line separation.",
 failure="Placing qualifiers in a footnote block, which regulators and consumers both read as evasion.",
 problem="Efficacy qualifiers are relegated to footnotes, which reads as evasion and attracts regulatory attention.",
 decision="Set each qualifier at 60 percent of its claim size directly beneath it in the same face.",
 reasoning="A qualifier separated from its claim fails its purpose, since the claim is read without it.",
 why="Adjacency in the same face makes the qualification part of the claim rather than an exception to it.",
 use=["Regulated efficacy claims","Beauty and healthcare packaging"],
 avoid=["Unqualified claims","Non-regulated categories"],
 adv="Compliant and credible", lim="Consumes space beside every claim",
 suit="Regulated claim communication", unsuit="Unregulated categories",
 alts=["Single combined claim sentence that needs no separate qualifier"],
 aps=[("Placing efficacy qualifiers in a footnote block","Reads as evasion to consumers and regulators alike, attracting scrutiny","Qualifier set directly beneath its claim at 60 percent size")],
 impact="Makes qualification part of the claim.", iscore=7, prio=8, conf=0.88, ind=["beauty","healthcare"])

# ═══════════ HOSPITALITY PAIRING ═══════════
P("typography.hospitality_pairing.warm_serif_humanist.001","Warm serif with humanist sans","hospitality_pairing",
 purpose="Combine welcome with practicality across a venue's typographic surfaces.",
 visual_effect="An old style serif for names against a humanist sans for detail keeps both warm and readable.",
 signal="Hospitable — the place is welcoming and also organised.",
 hierarchy_rule="Serif for venue name, section headings and dish names; sans for descriptions, prices and practical detail.",
 spacing_rule="Serif at 1.3 leading for headings; sans at 1.5 for descriptions with prices right-aligned in tabular figures.",
 failure="Setting prices in the serif, whose proportional figures misalign in a price column.",
 problem="Menus set everything in one decorative serif, so prices misalign and descriptions become hard to scan.",
 decision="Set names and headings in an old style serif and all descriptions and prices in a humanist sans.",
 reasoning="Names are read once for pleasure; prices and descriptions are scanned and compared.",
 why="Splitting by reading task lets each face serve the behaviour it actually meets.",
 use=["Restaurant, cafe and hotel collateral","Menus and wayfinding"],
 avoid=["Fine dining with a deliberately minimal single-face system","Digital-only ordering interfaces"],
 adv="Warmth with scannable practical detail", lim="Two families across print and digital",
 suit="Hospitality collateral", unsuit="Minimal single-face systems",
 alts=["Single humanist family where two faces are too much for a small venue"],
 aps=[("Setting prices in the decorative serif with proportional figures","Prices misalign in the column and cannot be compared by eye","Prices in the sans using tabular figures, right-aligned")],
 impact="Combines welcome with scannable detail.", iscore=7, prio=8, conf=0.87, ind="hospitality")

P("typography.hospitality_pairing.menu_scan_structure.001","Menu face selection for scanning","hospitality_pairing",
 purpose="Let a diner find a dish quickly in low light.",
 visual_effect="Open apertures at 10 to 12 points remain legible under the low light restaurants actually use.",
 signal="Practical — the menu was designed for the room it is read in.",
 hierarchy_rule="Three levels: section, dish name, description, with dish name at 1.3 times description size.",
 spacing_rule="Leading at 1.5 with 1 line between dishes and 2 lines between sections.",
 failure="Choosing a face for elegance and testing it in daylight, where the low-light failure is invisible.",
 problem="Menus are designed and approved in daylight, then used in dim rooms where the face becomes unreadable.",
 decision="Choose an open-aperture face at 10 to 12 points minimum and proof the menu at the venue's actual light level.",
 reasoning="Low light reduces effective contrast, which closes counters and merges similar characters.",
 why="Proofing in the real light level is the only way to catch a failure daylight hides.",
 use=["Restaurant and bar menus","Dimly lit venue collateral"],
 avoid=["Brightly lit fast-service environments","Digital menus with adjustable brightness"],
 adv="Legible in the room it is used in", lim="Constrains face choice and increases page count",
 suit="Dim-lit dining", unsuit="Bright fast-service and digital menus",
 alts=["Larger type in the display face where the face cannot be changed"],
 aps=[("Approving a menu face under daylight office lighting","The low-light failure is invisible during approval and only appears in service","Proofing at the venue's actual light level before approval")],
 impact="Makes menus legible in real service conditions.", iscore=7, prio=8, conf=0.88, ind="hospitality")

P("typography.hospitality_pairing.signage_and_print_split.001","Signage and print face split","hospitality_pairing",
 purpose="Use different faces for reading distance and reading duration.",
 visual_effect="A generous open face on signage against a finer face in print serves two viewing distances.",
 signal="Coherent — the brand adapts to context without changing identity.",
 hierarchy_rule="Signage uses two levels maximum in the open face; print uses three in the finer face.",
 spacing_rule="Signage tracked 20 to 30 units looser; print at default tracking.",
 failure="Using the fine print face on signage, where distance blur closes its counters.",
 problem="Venues use one face across signage and print, so either signage blurs or print looks crude.",
 decision="Use an open-counter face for signage tracked 20 to 30 units looser and a finer face for print.",
 reasoning="Distance introduces optical blur that closes counters, which print viewing distance does not.",
 why="Selecting by viewing distance lets each surface use the face that survives its conditions.",
 use=["Venues with both signage and printed collateral","Hotels and multi-space venues"],
 avoid=["Print-only or signage-only applications","Single-face brand mandates"],
 adv="Each surface legible in its own conditions", lim="Two families to maintain",
 suit="Multi-surface hospitality", unsuit="Single-surface applications",
 alts=["One open-counter face across both, accepting slightly crude print"],
 aps=[("Using the fine print face on wayfinding signage","Distance blur closes the counters and the sign becomes unreadable beyond ten metres","An open-counter face for signage, tracked looser")],
 impact="Keeps every surface legible in its own conditions.", iscore=7, prio=7, conf=0.86, ind="hospitality")

P("typography.hospitality_pairing.bilingual_menu_pairing.001","Bilingual menu pairing","hospitality_pairing",
 purpose="Present two languages on one menu without either looking secondary.",
 visual_effect="Both languages in one family at the same size read as equally intended.",
 signal="Locally rooted and internationally open — neither audience is an afterthought.",
 hierarchy_rule="Both languages share every level; the second language never drops a level or a weight.",
 spacing_rule="Leading governed by the Vietnamese requirement, roughly 20 percent above the Latin default, applied to both.",
 failure="Setting the second language smaller or lighter, which tells that audience they are secondary.",
 problem="Bilingual menus set the second language smaller, which reads as a hierarchy of welcome.",
 decision="Set both languages in one family at identical size and weight with leading governed by Vietnamese.",
 reasoning="Relative type size on a menu is read as relative importance of the reader, not of the language.",
 why="Equal setting removes an unintended message about which guests are primary.",
 use=["Bilingual Vietnamese and English menus","Tourist and international venues"],
 avoid=["Single-language venues","Menus with severe space constraints"],
 adv="Neither audience reads as secondary", lim="Roughly doubles menu length",
 suit="Bilingual hospitality", unsuit="Single-language and space-constrained menus",
 alts=["Separate menus per language where one bilingual menu will not fit"],
 aps=[("Setting the English translation smaller and lighter than Vietnamese","Reads as a hierarchy of welcome rather than of language","Both languages at identical size and weight")],
 impact="Removes an unintended hierarchy of welcome.", iscore=7, prio=8, conf=0.88, ind="hospitality",
 viet="Set leading from the Vietnamese requirement and apply it to both blocks so the two languages stay visually matched.")

P("typography.hospitality_pairing.handwritten_specials.001","Handwritten specials and printed menu","hospitality_pairing",
 purpose="Signal freshness through a genuinely temporary typographic register.",
 visual_effect="A handwritten or script element beside printed type marks content as changing daily.",
 signal="Fresh — this part changes, and the brand wants you to notice.",
 hierarchy_rule="The handwritten register is reserved for genuinely temporary content only, never for fixed menu items.",
 spacing_rule="Handwritten elements keep their own natural spacing and are never tracked or justified.",
 failure="Setting permanent menu items in the handwritten face, which removes the freshness signal entirely.",
 problem="Venues set entire menus in handwritten faces, so the signal that marks daily specials is spent everywhere.",
 decision="Reserve the handwritten register for genuinely changing content and set fixed items in the printed face.",
 reasoning="A freshness signal works by contrast, and applying it everywhere removes the contrast it depends on.",
 why="Restricting the register keeps its meaning intact for the content that actually changes.",
 use=["Venues with daily specials","Markets and seasonal menus"],
 avoid=["Fixed menus with no changing content","Fine dining with a formal register"],
 adv="Genuine freshness signal", lim="Requires the content to actually change",
 suit="Venues with daily changing offers", unsuit="Fixed menus and formal dining",
 alts=["Colour or position marking where a second face is unavailable"],
 aps=[("Setting the entire menu in a handwritten face","Spends the freshness signal on permanent content, so daily specials no longer stand out","Handwritten reserved for genuinely changing items")],
 impact="Preserves the freshness signal for changing content.", iscore=6, prio=7, conf=0.84, ind="hospitality")

P("typography.hospitality_pairing.room_number_wayfinding.001","Numeral face for wayfinding","hospitality_pairing",
 purpose="Make room and floor numbers readable at a glance while carrying luggage.",
 visual_effect="Lining figures with distinct 6, 8 and 9 forms remain distinguishable at distance and angle.",
 signal="Effortless — the guest never has to stop and squint.",
 hierarchy_rule="Numerals form their own level, set larger than any accompanying text on the same sign.",
 spacing_rule="Tracked 30 to 50 units, since figures at distance need more separation than letters do.",
 failure="Using oldstyle figures on wayfinding, whose varying heights are harder to read at a glance.",
 problem="Wayfinding uses the brand text face with oldstyle figures, which are slower to read at distance.",
 decision="Use lining figures at the largest level on wayfinding, tracked 30 to 50 units looser.",
 reasoning="Oldstyle figures vary in height, which aids prose rhythm and hinders rapid numeric recognition.",
 why="Uniform figure height makes numbers recognisable in a single fixation.",
 use=["Hotel and venue wayfinding","Room, floor and gate numbering"],
 avoid=["Running prose containing numbers","Editorial and menu settings"],
 adv="Faster numeric recognition at distance", lim="Looks mechanical in prose contexts",
 suit="Wayfinding and numbering", unsuit="Prose and editorial settings",
 alts=["Oldstyle figures in prose, lining reserved for signage"],
 aps=[("Using oldstyle figures on room number signage","Varying figure heights slow recognition at distance and at a glance","Lining figures, tracked looser, at the largest level")],
 impact="Speeds numeric recognition in wayfinding.", iscore=7, prio=7, conf=0.87, ind="hospitality")

flush()
