# -*- coding: utf-8 -*-
"""Batch 4E - industry typography."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_typo_lib import TYPO, flush

def P(kid, name, sub, **kw):
    TYPO(kid, name, sub, **kw)

# ---------- BEAUTY ----------
P("typography.beauty_typography.efficacy_vs_indulgence.001","Choosing between efficacy and indulgence registers","beauty_typography",
 purpose="Pick a typographic register that matches what the product is actually bought for.",
 visual_effect="Even sans setting reads as tested; high-contrast serif setting reads as pleasurable.",
 signal="Either proof or pleasure, and the reader decides which within one fixation.",
 hierarchy_rule="Efficacy registers lead with the claim; indulgence registers lead with the product name.",
 spacing_rule="Efficacy at 1.5 leading and zero tracking; indulgence at 1.7 leading with 40 units on the display line.",
 failure="Mixing both registers in one asset, which leaves the reader unsure what is being sold.",
 problem="Beauty assets borrow from both registers at once, so neither the proof nor the pleasure claim lands.",
 decision="Commit to one register per product and set claim-led efficacy or name-led indulgence throughout.",
 reasoning="The two registers ask for different purchase reasoning, and a reader can only be in one at a time.",
 why="Commitment lets the typography do the positioning work the copy alone cannot.",
 use=["Beauty and personal care campaigns","Products with a clear efficacy or sensory position"],
 avoid=["Hybrid products deliberately spanning both","Retailer templates fixing the layout"],
 adv="Positioning legible before the copy is read", lim="Requires the position to be decided first",
 suit="Clearly positioned beauty products", unsuit="Deliberately hybrid propositions",
 alts=["A neutral register where the position is genuinely undecided"],
 aps=[("Combining a high-contrast serif name with a clinical claim block in equal weight","The reader cannot tell whether proof or pleasure is the reason to buy","One register applied consistently across the asset")],
 impact="Makes beauty positioning legible before reading.", iscore=8, prio=9, conf=0.88, ind="beauty")

P("typography.beauty_typography.percentage_claim_setting.001","Setting percentage efficacy claims","beauty_typography",
 purpose="Make a numeric efficacy claim read as measured rather than as advertising.",
 visual_effect="Tabular lining figures with a restrained size ratio read as data rather than as a promotion.",
 signal="Measured - the number came from a study rather than from a copywriter.",
 hierarchy_rule="The figure and its unit share one level; the study qualifier sits directly beneath at 60 percent.",
 spacing_rule="Tabular figures at zero tracking, with the qualifier no more than 0.25 line beneath.",
 failure="Setting the percentage several times larger than everything else, which reads as a discount.",
 problem="Efficacy percentages are set at promotional scale, so a clinical result reads as a sales number.",
 decision="Set efficacy figures in tabular lining at no more than 2.5 times body size with the qualifier beneath.",
 reasoning="Extreme scale is the grammar of price promotion, which undermines a claim meant to read as evidence.",
 why="Restrained scale plus an adjacent qualifier is what makes a number read as a finding.",
 use=["Clinical and efficacy-led beauty","Regulated claim communication"],
 avoid=["Price and discount communication","Mood-led fragrance"],
 adv="Numbers read as evidence", lim="Less immediately attention-grabbing",
 suit="Efficacy-led beauty", unsuit="Promotional price messaging",
 alts=["Promotional scale where the number genuinely is a price"],
 aps=[("Setting a clinical percentage at five times body size","The finding reads as a discount announcement and its credibility drops","Tabular figures at 2.5 times body with the study qualifier beneath")],
 impact="Keeps efficacy numbers reading as findings.", iscore=8, prio=9, conf=0.89, ind="beauty")

P("typography.beauty_typography.shade_name_treatment.001","Shade and variant name treatment","beauty_typography",
 purpose="Make variant names findable on shelf and in a grid without dominating the pack.",
 visual_effect="A consistently placed variant name at a fixed level lets a shopper compare across a range.",
 signal="Organised - the range was designed as a range.",
 hierarchy_rule="Variant name occupies the same level and position on every pack in the range.",
 spacing_rule="Fixed distance beneath the product name across the whole range, regardless of name length.",
 failure="Sizing the variant name to fit each pack, which moves it and breaks cross-pack comparison.",
 problem="Variant names are sized per pack to fit, so their position shifts and shoppers cannot compare a range.",
 decision="Fix the variant name at one level and one position across every pack, truncating rather than resizing.",
 reasoning="Range comparison is a scanning task that depends on the compared element sitting in a constant place.",
 why="Positional constancy is what makes a range scannable at shelf and in a grid.",
 use=["Beauty ranges with multiple variants","Colour cosmetics and shade systems"],
 avoid=["Single-variant products","Ranges with radically different pack formats"],
 adv="Range becomes scannable", lim="Long variant names must be shortened",
 suit="Multi-variant beauty ranges", unsuit="Single-product lines",
 alts=["Colour coding where names cannot be standardised"],
 aps=[("Resizing the variant name per pack so each fits its available area","The name moves between packs and cross-range comparison breaks","One fixed level and position, with names shortened to fit")],
 impact="Makes a beauty range scannable.", iscore=7, prio=8, conf=0.87, ind="beauty")

P("typography.beauty_typography.ritual_language_pacing.001","Pacing ritual and routine copy","beauty_typography",
 purpose="Set application instructions so they read as a ritual rather than as a manual.",
 visual_effect="Numbered steps with generous spacing read as a sequence to enjoy rather than a procedure to complete.",
 signal="Considered - the routine is part of the product rather than an obligation.",
 hierarchy_rule="Step number, action and detail form three sub-levels within one step block.",
 spacing_rule="1.6 leading within a step and two line spaces between steps, with the measure under 40 characters.",
 failure="Setting steps as a dense numbered list, which reads as an instruction manual.",
 problem="Application steps are set as dense instruction lists, which frames the routine as a chore.",
 decision="Set each step as a spaced block at 1.6 leading with two line spaces between steps.",
 reasoning="Reading pace is part of the proposition when the routine itself is being sold.",
 why="Generous pacing makes the sequence read as something to do slowly rather than to get through.",
 use=["Skincare routines and ritual-led beauty","Products where the routine is the experience"],
 avoid=["Single-application products","Packs with severe space constraints"],
 adv="The routine reads as part of the product", lim="Consumes considerable vertical room",
 suit="Ritual-led skincare", unsuit="Single-step products and tight packs",
 alts=["A compact numbered list where space genuinely does not allow"],
 aps=[("Setting application steps as a dense numbered list","The routine reads as a chore to complete rather than an experience to have","Each step as a spaced block with generous leading")],
 impact="Frames the routine as part of the product.", iscore=7, prio=7, conf=0.85, ind="beauty")

# ---------- FOOD AND BEVERAGE ----------
P("typography.food_typography.appetite_weight_choice.001","Weight selection for appetite appeal","food_typography",
 purpose="Choose a weight that matches how the food itself reads.",
 visual_effect="Heavier rounder forms read as abundant; lighter finer forms read as delicate and refined.",
 signal="Either indulgence or refinement, matching what the food actually is.",
 hierarchy_rule="Display weight is chosen from the product's own character, then all other levels follow from it.",
 spacing_rule="Heavy display tracked minus 20 units; light display tracked plus 30 units.",
 failure="Setting a delicate dish in a heavy rounded display face, which promises abundance the plate does not deliver.",
 problem="Food typography is chosen for legibility alone, so the weight contradicts what the product actually is.",
 decision="Select display weight from the product's own character, heavy for abundance and light for refinement.",
 reasoning="Weight is read as physical mass, so it sets an expectation about the food before the image is processed.",
 why="Matching weight to product keeps the typographic promise and the product consistent.",
 use=["Food and beverage packaging and campaigns","Menu and restaurant identity"],
 avoid=["Regulated nutrition panels","Categories where weight is fixed by a retailer template"],
 adv="Typography and product make the same promise", lim="Constrains display face selection",
 suit="Food and beverage branding", unsuit="Regulated panels and fixed templates",
 alts=["A neutral weight where the range spans both characters"],
 aps=[("Setting a delicate tasting menu in a heavy rounded display face","Promises abundance the plate does not deliver, so the product disappoints on arrival","A light display weight tracked open")],
 impact="Aligns the typographic promise with the product.", iscore=7, prio=8, conf=0.87, ind="food_beverage")

P("typography.food_typography.nutrition_panel_legibility.001","Nutrition panel typography","food_typography",
 purpose="Set a required nutrition panel so it is readable at arm's length on shelf.",
 visual_effect="Tabular figures with a clear grid make values comparable across products in the same aisle.",
 signal="Straightforward - the brand expects the panel to be read.",
 hierarchy_rule="The panel is a separate typographic system with its own face, size and spacing rules.",
 spacing_rule="Tabular figures at zero tracking, 1.3 leading, with hairline rules only where the grid needs them.",
 failure="Setting the panel in the brand display face, which makes required values slower to compare.",
 problem="Nutrition panels are set in the brand face, which slows the numeric comparison the panel exists for.",
 decision="Set nutrition panels in tabular figures at 1.3 leading using a face chosen for numeric clarity.",
 reasoning="Panels are read as a comparison table, and comparison depends on figure alignment rather than brand voice.",
 why="Treating the panel as its own system serves the reading task it actually meets.",
 use=["Food and beverage packaging","Regulated nutrition disclosure"],
 avoid=["Front-of-pack brand communication","Unregulated categories"],
 adv="Values are comparable at shelf", lim="Introduces a face outside the brand system",
 suit="Regulated food packaging", unsuit="Front-of-pack branding",
 alts=["The brand face with tabular figures enabled where it offers them"],
 aps=[("Setting the nutrition panel in the brand display face","Proportional figures misalign in the value column and comparison slows","Tabular figures in a face chosen for numeric clarity")],
 impact="Makes required panels usable at shelf.", iscore=7, prio=8, conf=0.89, ind="food_beverage")

P("typography.food_typography.origin_claim_typography.001","Provenance and origin claim setting","food_typography",
 purpose="Make an origin claim read as verifiable rather than as decorative.",
 visual_effect="A restrained specific claim set at label scale reads as a fact rather than as a badge.",
 signal="Verifiable - this is information rather than an ornament.",
 hierarchy_rule="Origin claims sit at the label level, never at display, and never inside a decorative device.",
 spacing_rule="Label level tracked 60 units in small caps or tracked lowercase, at 1.4 leading.",
 failure="Placing the origin inside a ribbon or seal device, which makes a true fact look invented.",
 problem="Origin claims are set inside badge devices, which makes verifiable facts look like decorative invention.",
 decision="Set origin claims at label level in tracked small caps without any surrounding badge device.",
 reasoning="Badge devices are associated with self-awarded marks, so they reduce the credibility of a real claim.",
 why="Plain setting lets a true provenance claim be read as information.",
 use=["Provenance-led food and drink","Regional and appellation products"],
 avoid=["Categories where badges carry regulatory meaning","Products with no genuine origin claim"],
 adv="Provenance reads as verifiable", lim="Less visually prominent than a badge",
 suit="Provenance-led food", unsuit="Regulated certification marks",
 alts=["An official certification mark where one legitimately exists"],
 aps=[("Placing a genuine origin claim inside a decorative ribbon device","The claim reads as a self-awarded badge and its credibility drops","Plain tracked small caps at label level")],
 impact="Keeps provenance claims credible.", iscore=7, prio=8, conf=0.87, ind="food_beverage")

P("typography.food_typography.price_visibility_balance.001","Price prominence in food communication","food_typography",
 purpose="Show price at the size the offer actually justifies.",
 visual_effect="Price at the second level reads as information; price at the first level reads as the entire proposition.",
 signal="Either value-led or product-led, depending on which level the price occupies.",
 hierarchy_rule="Price occupies the primary level only when price is the proposition, otherwise the second.",
 spacing_rule="Price at second level is 60 percent of display size with its own gap above.",
 failure="Setting price at display scale for a premium product, which reframes it as a value offer.",
 problem="Price is set at maximum scale by default, which reframes premium products as value offers.",
 decision="Place price at the second level unless price is genuinely the proposition, at 60 percent of display.",
 reasoning="The largest element is read as the reason to buy, whatever the copy elsewhere claims.",
 why="Level assignment is what tells the reader whether they are being sold a product or a price.",
 use=["Food and beverage retail and promotion","Menu and offer communication"],
 avoid=["Genuine price-led promotions","Formats where price display is regulated"],
 adv="Price stated without reframing the offer", lim="Lower immediate price salience",
 suit="Product-led food communication", unsuit="Genuine value promotions",
 alts=["Price at primary level where the discount genuinely is the offer"],
 aps=[("Setting price at display scale on a premium product asset","Reframes a premium product as a value offer regardless of the copy","Price at the second level at 60 percent of display size")],
 impact="Stops price from reframing the offer.", iscore=7, prio=8, conf=0.88, ind="food_beverage")

# ---------- FASHION ----------
P("typography.fashion_typography.subordinate_to_image.001","Keeping type subordinate to the image","fashion_typography",
 purpose="Let the garment carry the message while type stays as identification.",
 visual_effect="Small type at the edge of a full-bleed image keeps attention on the product.",
 signal="Confident - the clothes do not need explaining.",
 hierarchy_rule="Two elements maximum: brand mark and one line, both below 5 percent of the shorter edge.",
 spacing_rule="Type held at the margin with at least 8 percent edge distance and no element crossing the subject.",
 failure="Enlarging the headline to compete with the image, which turns fashion into retail promotion.",
 problem="Fashion assets scale type up for message clarity, which converts an image-led category into a promotional one.",
 decision="Limit fashion assets to a mark and one line, each below 5 percent of the shorter edge.",
 reasoning="Fashion communicates through the garment, so type competing with the image weakens the actual message.",
 why="Subordination is what keeps the category's primary communication channel clear.",
 use=["Fashion campaign and lookbook imagery","Image-led brand communication"],
 avoid=["Fashion retail promotion","E-commerce product listings"],
 adv="The garment stays the message", lim="Very little can be said in words",
 suit="Image-led fashion campaigns", unsuit="Retail promotion and e-commerce",
 alts=["A separate text panel where information genuinely must be carried"],
 aps=[("Enlarging the campaign headline to compete with the image","Converts image-led fashion into retail promotion and weakens the garment","A mark and one line, both held small at the margin")],
 impact="Keeps the garment as the primary message.", iscore=8, prio=9, conf=0.89, ind="fashion")

P("typography.fashion_typography.season_code_setting.001","Season and collection code typography","fashion_typography",
 purpose="Mark a collection so it is identifiable without dating the imagery.",
 visual_effect="A small tracked code reads as a catalogue reference rather than as an expiry date.",
 signal="Archival - the collection is placed in a sequence rather than given a shelf life.",
 hierarchy_rule="The season code sits at the smallest level, below every other element in the layout.",
 spacing_rule="Tracked 100 units at the smallest level with the largest available edge distance.",
 failure="Setting the season prominently, which makes the asset read as expired the moment the season passes.",
 problem="Season codes are set prominently, so campaign imagery visibly expires and cannot be reused.",
 decision="Set the season code at the smallest level tracked 100 units, below every other element.",
 reasoning="Prominent dating gives an asset a visible expiry, which shortens the life of expensive imagery.",
 why="A quiet code preserves both identification and the asset's usable life.",
 use=["Fashion collections and lookbooks","Seasonal retail communication"],
 avoid=["Time-limited promotional communication","Products where recency is the selling point"],
 adv="Imagery stays usable beyond its season", lim="Season is harder to identify at a glance",
 suit="Fashion collection imagery", unsuit="Time-limited promotions",
 alts=["Prominent dating where urgency is the point"],
 aps=[("Setting the season code at headline scale","The asset reads as expired the moment the season passes, wasting the production spend","The code at the smallest level, tracked wide")],
 impact="Extends the usable life of campaign imagery.", iscore=7, prio=7, conf=0.86, ind="fashion")

P("typography.fashion_typography.ecommerce_listing_clarity.001","Fashion e-commerce listing typography","fashion_typography",
 purpose="Set listing text so a shopper can compare items in a grid.",
 visual_effect="Fixed-height name and price blocks keep grid rows aligned regardless of name length.",
 signal="Efficient - the grid is built for comparing rather than for admiring.",
 hierarchy_rule="Three fixed levels per card: brand, product name, price, each with a reserved height.",
 spacing_rule="Name truncated to two lines at 1.35 leading; price on its own line at a fixed offset.",
 failure="Letting product names wrap freely, which misaligns prices across the grid and breaks comparison.",
 problem="Listing cards let names wrap freely, so prices sit at different heights and the grid cannot be compared.",
 decision="Reserve a fixed height for each card level, truncating names at two lines so prices align across the row.",
 reasoning="Grid comparison depends on the compared value appearing at the same height in every card.",
 why="Fixed heights guarantee alignment regardless of how long any individual name is.",
 use=["Fashion e-commerce grids","Any comparison-driven product listing"],
 avoid=["Editorial lookbooks","Single-product pages"],
 adv="Prices compare across the row", lim="Long product names are truncated",
 suit="E-commerce listing grids", unsuit="Editorial and single-product layouts",
 alts=["Variable card heights where comparison is not the primary task"],
 aps=[("Letting product names wrap to any number of lines in a listing grid","Prices sit at different heights across the row and cannot be compared at a glance","A reserved two-line height for names with truncation")],
 impact="Makes listing grids comparable.", iscore=7, prio=8, conf=0.88, ind="fashion", ch="website")

P("typography.fashion_typography.designer_credit_hierarchy.001","Designer and collaborator credit setting","fashion_typography",
 purpose="Credit collaborators at a level that matches their contractual prominence.",
 visual_effect="Credits at a consistent level read as a masthead rather than as competing brand marks.",
 signal="Professional - contributions are acknowledged in an established order.",
 hierarchy_rule="All credits share one level and one face, ordered by contribution rather than sized by it.",
 spacing_rule="Credits at the smallest level, 1.4 leading, separated by a fixed en-space rather than by size.",
 failure="Sizing each credit by negotiated importance, which turns a credit line into competing logos.",
 problem="Credits are sized by negotiated prominence, which converts an acknowledgement into competing brand marks.",
 decision="Set all credits at one level and one face, expressing precedence through order rather than size.",
 reasoning="Order already encodes precedence, so size adds a second signal that fragments the line.",
 why="A single level keeps the credit line readable as one masthead.",
 use=["Fashion campaign credits","Collaboration and co-branded work"],
 avoid=["Co-branded lockups with contractual size requirements","Single-contributor work"],
 adv="Credits read as one masthead", lim="Cannot satisfy contractual size demands",
 suit="Editorial and campaign credits", unsuit="Contractual co-branding lockups",
 alts=["A formal co-brand lockup where sizes are contractually fixed"],
 aps=[("Sizing each credit according to negotiated importance","The credit line becomes competing logos and stops reading as an acknowledgement","One level for all credits, with precedence carried by order")],
 impact="Keeps credit lines readable as one element.", iscore=6, prio=7, conf=0.84, ind="fashion")

# ---------- HOSPITALITY ----------
P("typography.hospitality_typography.menu_price_alignment.001","Price column alignment in menus","hospitality_typography",
 purpose="Let a diner compare prices without reading every description.",
 visual_effect="Right-aligned tabular prices in a fixed column can be scanned vertically in one pass.",
 signal="Straightforward - the menu does not hide what things cost.",
 hierarchy_rule="Prices occupy their own column outside the description flow at every level of the menu.",
 spacing_rule="Tabular figures, right-aligned, at zero tracking, with no leader dots between name and price.",
 failure="Running prices inline after descriptions, which forces reading every item to compare cost.",
 problem="Prices are placed inline after descriptions, so comparing cost requires reading the entire menu.",
 decision="Place prices in a right-aligned tabular column separate from descriptions, without leader dots.",
 reasoning="Price comparison is a vertical scanning task, which inline placement makes impossible.",
 why="A dedicated column lets the scan happen in one pass.",
 use=["Restaurant, bar and cafe menus","Any priced list"],
 avoid=["Tasting menus with a single price","Deliberately price-suppressed fine dining"],
 adv="Prices compare in one vertical pass", lim="Makes price more salient than some venues want",
 suit="Priced menus", unsuit="Fixed-price and price-suppressed menus",
 alts=["Inline prices where the venue deliberately de-emphasises cost"],
 aps=[("Running prices inline at the end of each description","Comparing cost requires reading every description in full","A right-aligned tabular price column")],
 impact="Makes menu prices comparable at a glance.", iscore=7, prio=8, conf=0.89, ind="hospitality")

P("typography.hospitality_typography.dish_description_measure.001","Measure for dish descriptions","hospitality_typography",
 purpose="Set descriptions at a width that can be read in a glance rather than studied.",
 visual_effect="A measure under 45 characters lets a description be taken in without a return sweep.",
 signal="Effortless - the menu can be read while talking.",
 hierarchy_rule="Description measure is narrower than the menu column, leaving the price column clear.",
 spacing_rule="Measure under 45 characters at 1.5 leading, with descriptions capped at two lines.",
 failure="Running descriptions the full page width, which requires several return sweeps per dish.",
 problem="Menu descriptions run the full page width, so each dish requires several return sweeps to read.",
 decision="Hold description measure under 45 characters at 1.5 leading and cap descriptions at two lines.",
 reasoning="Menus are read intermittently between conversation, so each item must be readable in one pass.",
 why="A short measure keeps each dish within a single uninterrupted glance.",
 use=["Restaurant and bar menus","Any list read intermittently"],
 avoid=["Tasting menus with extended narrative descriptions","Digital menus with expandable detail"],
 adv="Each dish readable in one glance", lim="Descriptions must be written short",
 suit="Standard restaurant menus", unsuit="Narrative tasting menus",
 alts=["A wider measure where the menu is genuinely read attentively"],
 aps=[("Running dish descriptions across the full page width","Each dish requires several return sweeps and the menu becomes tiring to scan","A measure under 45 characters capped at two lines")],
 impact="Makes each menu item readable in one glance.", iscore=7, prio=8, conf=0.88, ind="hospitality")

P("typography.hospitality_typography.booking_call_to_action.001","Booking call to action typography","hospitality_typography",
 purpose="Make the booking action findable without breaking a hospitable tone.",
 visual_effect="A clearly separated action block reads as helpful rather than as a hard sell.",
 signal="Welcoming - the venue makes booking easy rather than urgent.",
 hierarchy_rule="The booking action is the third level, separated by the layout's second-largest gap.",
 spacing_rule="Its own gap above at 1.5 base units, with the action text at body size in a heavier weight.",
 failure="Setting the booking action at display scale, which makes a hospitality brand read as a discount site.",
 problem="Booking actions are set at promotional scale, which contradicts the hospitable tone of everything around them.",
 decision="Set the booking action at body size in a heavier weight, separated by its own generous gap.",
 reasoning="Findability comes from isolation rather than from size, and isolation keeps the tone intact.",
 why="Separation makes the action easy to locate without adopting a promotional register.",
 use=["Hospitality websites and campaigns","Restaurant and hotel booking flows"],
 avoid=["Time-limited promotional offers","High-pressure conversion contexts"],
 adv="Findable without a promotional tone", lim="Lower click salience than a large button",
 suit="Hospitality booking", unsuit="Urgency-driven promotions",
 alts=["A prominent button where a genuine time limit applies"],
 aps=[("Setting the booking action at display scale","A hospitality brand reads as a discount site and the tone collapses","Body size in a heavier weight with its own generous gap")],
 impact="Keeps the booking action findable and hospitable.", iscore=7, prio=8, conf=0.87, ind="hospitality", ch="website")

P("typography.hospitality_typography.venue_name_scale.001","Venue name scale on collateral","hospitality_typography",
 purpose="Size a venue name for recognition across every piece of collateral.",
 visual_effect="A constant proportion of the shorter edge keeps the name recognisable from card to signage.",
 signal="Established - the venue is the same entity on every surface.",
 hierarchy_rule="The venue name occupies a fixed proportion of the shorter edge on every format.",
 spacing_rule="Name at 12 to 18 percent of the shorter edge with fixed tracking scaled proportionally.",
 failure="Sizing the name to fill available space on each format, which changes its proportion between pieces.",
 problem="Venue names are sized per piece to fill space, so the name looks different on every format.",
 decision="Set the venue name at 12 to 18 percent of the shorter edge on every format, scaled proportionally.",
 reasoning="Recognition depends on constant proportion, not on constant physical size.",
 why="Proportional sizing keeps the name the same object from business card to facade.",
 use=["Hospitality collateral systems","Multi-format venue identity"],
 avoid=["Single-format applications","Formats with regulated signage dimensions"],
 adv="Name recognisable across every format", lim="May under-fill some formats",
 suit="Multi-format hospitality identity", unsuit="Single-format and regulated signage",
 alts=["Per-format sizing where formats differ radically in aspect"],
 aps=[("Sizing the venue name to fill each format's available space","The name's proportion changes between pieces and recognition weakens","A fixed proportion of the shorter edge on every format")],
 impact="Keeps a venue name recognisable across formats.", iscore=7, prio=7, conf=0.86, ind="hospitality")

# ---------- TECHNOLOGY ----------
P("typography.technology_typography.interface_neutrality.001","Neutrality in interface typography","technology_typography",
 purpose="Choose an interface face that does not compete with the content it displays.",
 visual_effect="A face with unremarkable letterforms lets the user's own content carry the personality.",
 signal="Deferential - the tool does not perform while you work.",
 hierarchy_rule="Interface hierarchy uses weight and size only, never a change of face.",
 spacing_rule="Zero tracking throughout with 1.5 leading, so density stays predictable across dynamic content.",
 failure="Using a distinctive display face in the interface, which becomes tiring across repeated sessions.",
 problem="Interfaces use distinctive brand faces, whose personality becomes fatiguing under repeated daily use.",
 decision="Use a neutral face for every interface level, expressing hierarchy through weight and size only.",
 reasoning="Interface type is read hundreds of times, and any character in the letterforms accumulates as noise.",
 why="Neutrality is what lets an interface stay comfortable at the frequency it is actually used.",
 use=["Software interfaces and dashboards","Tools used repeatedly"],
 avoid=["Marketing surfaces","Single-session promotional experiences"],
 adv="Comfortable under repeated use", lim="No brand personality in the product",
 suit="Repeatedly used software", unsuit="Marketing surfaces",
 alts=["A distinctive face in marketing surfaces only"],
 aps=[("Using the distinctive brand display face throughout the product interface","Personality accumulates as noise across daily sessions and becomes fatiguing","A neutral face with hierarchy from weight and size")],
 impact="Keeps interfaces comfortable under daily use.", iscore=8, prio=9, conf=0.89, ind="technology", ch="website")

P("typography.technology_typography.error_message_setting.001","Error and system message typography","technology_typography",
 purpose="Set system messages so they are read rather than dismissed.",
 visual_effect="A message set at body size in the interface face reads as information rather than as an alarm.",
 signal="Calm - something needs attention, not panic.",
 hierarchy_rule="System messages occupy the body level with weight rather than size carrying the emphasis.",
 spacing_rule="Body size at 1.5 leading with a measure under 60 characters and its own gap above.",
 failure="Setting errors in red capitals, which readers learn to dismiss without reading.",
 problem="Error messages are set as alarms in capitals and colour, so users learn to dismiss them unread.",
 decision="Set system messages at body size in the interface face, using weight rather than colour or capitals.",
 reasoning="Alarm styling produces habituation, after which the message is dismissed before it is read.",
 why="Ordinary setting keeps the message inside the reading flow where it will actually be processed.",
 use=["Software interfaces","Any system communicating state to a user"],
 avoid=["Safety-critical warnings requiring maximum salience","Regulated alert formats"],
 adv="Messages are read rather than dismissed", lim="Lower immediate salience",
 suit="Ordinary system messaging", unsuit="Safety-critical alerts",
 alts=["High-salience alert styling for genuine safety warnings"],
 aps=[("Setting every error message in red capitals","Users habituate and dismiss the message before reading it","Body size in the interface face with weight for emphasis")],
 impact="Makes system messages actually get read.", iscore=8, prio=8, conf=0.88, ind="technology", ch="website")

P("typography.technology_typography.dashboard_number_hierarchy.001","Numeric hierarchy in dashboards","technology_typography",
 purpose="Rank metrics so the important number is found first.",
 visual_effect="One dominant figure with supporting values beneath directs attention before any label is read.",
 signal="Decisive - the dashboard knows which number matters.",
 hierarchy_rule="One primary metric per view at twice the size of supporting metrics, with labels below values.",
 spacing_rule="Tabular figures at zero tracking, with the label at 40 percent of the value size directly beneath.",
 failure="Setting every metric at the same size, which makes the user read all of them to find one.",
 problem="Dashboards set every metric at equal size, so users read all of them to find the one that matters.",
 decision="Give each view one primary metric at twice the supporting size with labels beneath the values.",
 reasoning="A dashboard is scanned for exceptions, which requires one entry point rather than uniform weight.",
 why="A single dominant figure gives the scan somewhere to start.",
 use=["Dashboards and analytics interfaces","Monitoring and reporting views"],
 avoid=["Comparison tables where metrics are genuinely equal","Raw data exports"],
 adv="Scan has a clear entry point", lim="Requires deciding which metric leads",
 suit="Dashboard and monitoring views", unsuit="Equal-weight comparison tables",
 alts=["Uniform sizing in tables where all values are genuinely equivalent"],
 aps=[("Setting every dashboard metric at the same size","Users read all metrics to find the one that matters, which defeats the scan","One primary metric at twice the supporting size")],
 impact="Gives dashboard scanning an entry point.", iscore=7, prio=8, conf=0.88, ind="technology", ch="website")

P("typography.technology_typography.documentation_scannability.001","Documentation typography for scanning","technology_typography",
 purpose="Set documentation so a reader can find one answer without reading the page.",
 visual_effect="Frequent headings, short paragraphs and distinct code blocks make a page navigable by eye.",
 signal="Usable - the document expects to be searched rather than read.",
 hierarchy_rule="A heading every 150 words maximum, with three heading levels distinguished by size and weight.",
 spacing_rule="1.6 leading with a 1.5 line gap above headings and code blocks set apart by a full line.",
 failure="Writing long unbroken sections, which forces a reader to read the whole page to find one detail.",
 problem="Documentation is set as continuous prose, so finding one answer requires reading the entire page.",
 decision="Place a heading at least every 150 words with three distinguished levels and separated code blocks.",
 reasoning="Documentation is entered mid-page from search, so structure must be visible from any starting point.",
 why="Frequent headings give every entry point a nearby orientation marker.",
 use=["Technical documentation","Reference and help content"],
 avoid=["Narrative long-form content","Marketing prose"],
 adv="Answers findable without full reading", lim="Fragments continuous argument",
 suit="Reference documentation", unsuit="Narrative long-form",
 alts=["Continuous prose where the document is genuinely read start to finish"],
 aps=[("Writing documentation as long unbroken prose sections","A reader entering from search must read the whole page to find one detail","A heading at least every 150 words")],
 impact="Makes documentation searchable by eye.", iscore=7, prio=8, conf=0.88, ind="technology", ch="website")

# ---------- REAL ESTATE ----------
P("typography.real_estate_typography.specification_clarity.001","Property specification typography","real_estate_typography",
 purpose="Set property specifications so buyers can compare listings quickly.",
 visual_effect="A fixed label and value grid lets a buyer compare area, rooms and price across listings.",
 signal="Transparent - the numbers are presented for comparison.",
 hierarchy_rule="Specifications form a fixed grid where every listing carries the same fields in the same order.",
 spacing_rule="Tabular figures right-aligned with labels left-aligned at 1.4 leading in a two-column grid.",
 failure="Writing specifications as prose sentences, which prevents comparison across listings.",
 problem="Property specifications are written as prose, so buyers cannot compare listings without reading each in full.",
 decision="Present specifications as a fixed label and value grid with tabular figures in a consistent field order.",
 reasoning="Property selection is a comparison task across many listings, not a reading task within one.",
 why="A consistent grid makes the comparison possible in a single vertical scan.",
 use=["Property listings and brochures","Any comparison-driven catalogue"],
 avoid=["Single-property luxury presentations","Narrative property storytelling"],
 adv="Listings compare in one scan", lim="Removes narrative from the specification",
 suit="Multi-listing property communication", unsuit="Single-property luxury presentation",
 alts=["Narrative description where only one property is presented"],
 aps=[("Writing property specifications as prose sentences","Buyers must read each listing in full to compare, which they will not do","A fixed label and value grid with tabular figures")],
 impact="Makes property listings comparable.", iscore=7, prio=8, conf=0.88, ind="real_estate")

P("typography.real_estate_typography.price_and_area_pairing.001","Pairing price with area","real_estate_typography",
 purpose="Present price and area together so the derived value is visible.",
 visual_effect="Price and area on adjacent lines at the same level let the reader compute value without effort.",
 signal="Confident - the brand is comfortable with the comparison being made.",
 hierarchy_rule="Price and area share one level and one alignment, with area directly beneath price.",
 spacing_rule="Both in tabular figures at zero tracking, separated by no more than 0.3 line.",
 failure="Separating price and area to different parts of the layout, which reads as concealment.",
 problem="Price and area are placed apart in the layout, which reads as an attempt to obscure value per unit.",
 decision="Place price and area at the same level on adjacent lines in matching tabular figures.",
 reasoning="Buyers compute value per unit regardless, and separation only signals that the brand would rather they did not.",
 why="Adjacency makes the calculation easy and the presentation credible.",
 use=["Property listings and marketing","Categories where unit value is calculated"],
 avoid=["Properties where area is genuinely not comparable","Regulated formats fixing field placement"],
 adv="Value presentation reads as confident", lim="Makes an unfavourable ratio equally visible",
 suit="Property listings", unsuit="Non-comparable and regulated formats",
 alts=["Separated presentation where the properties are genuinely not comparable"],
 aps=[("Placing price and area in different parts of the layout","Reads as an attempt to obscure unit value, which buyers calculate anyway","Price and area adjacent at the same level")],
 impact="Makes value presentation read as confident.", iscore=7, prio=8, conf=0.87, ind="real_estate")

P("typography.real_estate_typography.location_hierarchy.001","Location naming hierarchy","real_estate_typography",
 purpose="Name a location at the level of specificity the buyer searches by.",
 visual_effect="District at the primary level with street beneath matches how buyers actually narrow a search.",
 signal="Locally fluent - the listing speaks the buyer's search vocabulary.",
 hierarchy_rule="District leads, street follows at the second level, and the full address sits at the smallest level.",
 spacing_rule="District at display size, street at 50 percent, full address at label level tracked 40 units.",
 failure="Leading with the full street address, which is more precise than the buyer's search and less recognisable.",
 problem="Listings lead with a full street address, which is more specific than how buyers actually search.",
 decision="Lead with the district, place the street at the second level and the full address at the smallest.",
 reasoning="Buyers narrow by area before street, so the leading element should match the first filter they apply.",
 why="Matching the hierarchy to the search sequence makes the listing findable in the buyer's own terms.",
 use=["Property listings and portals","Location-led property marketing"],
 avoid=["Single named landmark properties","Markets where street identity outranks district"],
 adv="Matches how buyers actually search", lim="Less precise at first glance",
 suit="District-driven property markets", unsuit="Landmark and street-led markets",
 alts=["Street-led naming in markets where the street is the recognised unit"],
 aps=[("Leading a listing with the full street address","More specific than the buyer's first search filter and less recognisable","District at the primary level with street beneath")],
 impact="Matches listings to how buyers search.", iscore=7, prio=7, conf=0.86, ind="real_estate")

P("typography.real_estate_typography.floorplan_annotation.001","Floor plan annotation typography","real_estate_typography",
 purpose="Label a floor plan so rooms and dimensions read at the plan's actual reproduction size.",
 visual_effect="Consistent label size across rooms keeps the plan readable regardless of room area.",
 signal="Technical and reliable - the drawing can be trusted.",
 hierarchy_rule="Room name and dimension form one two-line label at a single size across the whole plan.",
 spacing_rule="Labels at 7 points minimum after reduction, tracked plus 15 units, with dimensions in tabular figures.",
 failure="Scaling labels to fit each room, which makes small rooms unreadable at reproduction size.",
 problem="Floor plan labels are scaled to fit each room, so labels in small rooms fall below legible size.",
 decision="Use one label size across the whole plan at 7 points minimum after reduction, with leader lines where needed.",
 reasoning="Legibility is set by the reproduction size, not by the room the label happens to sit in.",
 why="A single size guarantees every label survives reduction, with leaders solving the fit problem.",
 use=["Floor plans in property marketing","Technical drawings for consumer use"],
 avoid=["Architectural working drawings","Interactive plans with zoom"],
 adv="Every label survives reduction", lim="Requires leader lines in small rooms",
 suit="Consumer-facing floor plans", unsuit="Working drawings and zoomable plans",
 alts=["Numbered rooms with a separate key where leaders would crowd the plan"],
 aps=[("Scaling floor plan labels to fit each room's area","Labels in small rooms fall below legible size after reduction","One label size throughout with leader lines where needed")],
 impact="Keeps floor plans readable after reduction.", iscore=7, prio=7, conf=0.87, ind="real_estate")

# ---------- HEALTHCARE ----------
P("typography.healthcare_typography.dosage_instruction_clarity.001","Dosage instruction typography","healthcare_typography",
 purpose="Set dosage information so it cannot be misread under stress or poor light.",
 visual_effect="Large open-aperture type with generous spacing keeps numbers and units unambiguous.",
 signal="Safe - the information was set to be understood, not to fit.",
 hierarchy_rule="Dose, frequency and duration each occupy their own line at the same level.",
 spacing_rule="Minimum 10 points, 1.6 leading, tracked plus 10 units, with numerals in tabular lining.",
 failure="Compressing dosage into one line to save space, where frequency and duration can be confused.",
 problem="Dosage information is compressed into one line to fit, which allows frequency and duration to be confused.",
 decision="Give dose, frequency and duration separate lines at 10 points minimum with 1.6 leading.",
 reasoning="Misreading dosage causes harm, so the setting must be optimised for comprehension over compactness.",
 why="Separate lines remove the ambiguity that compression introduces.",
 use=["Pharmaceutical and healthcare packaging","Patient-facing instructions"],
 avoid=["Professional-only technical documentation","Space-limited unit packaging"],
 adv="Dosage cannot be misread", lim="Requires considerably more packaging area",
 suit="Patient-facing healthcare", unsuit="Professional technical documentation",
 alts=["An enclosed leaflet where pack area is genuinely insufficient"],
 aps=[("Compressing dose, frequency and duration into one line to save space","Frequency and duration can be confused, which causes real harm","Each on its own line at 10 points with generous leading")],
 impact="Removes ambiguity from dosage information.", iscore=9, prio=9, conf=0.92, ind="healthcare")

P("typography.healthcare_typography.reassurance_register.001","A reassuring rather than clinical register","healthcare_typography",
 purpose="Set patient communication so it calms rather than alarms.",
 visual_effect="Humanist letterforms at generous size read as spoken rather than as issued.",
 signal="Human - a person is talking to you rather than a system processing you.",
 hierarchy_rule="Two levels only in patient communication, since more levels read as institutional documentation.",
 spacing_rule="Body at 12 points minimum, 1.6 leading, with a measure under 55 characters.",
 failure="Using a condensed grotesque at small size, which reads as bureaucratic and increases anxiety.",
 problem="Patient communication uses condensed institutional typography, which increases anxiety in already stressed readers.",
 decision="Set patient communication in a humanist face at 12 points minimum with two levels and 1.6 leading.",
 reasoning="Readers under stress process less, so both the letterform character and the size affect comprehension.",
 why="A humanist face at generous size reads as addressed to a person rather than issued by an institution.",
 use=["Patient-facing healthcare communication","Clinics, hospitals and health services"],
 avoid=["Professional clinical documentation","Regulated formats with fixed specifications"],
 adv="Lower anxiety and better comprehension", lim="Consumes more space than institutional setting",
 suit="Patient communication", unsuit="Professional clinical documents",
 alts=["Standard institutional setting for professional audiences"],
 aps=[("Setting patient information in a condensed grotesque at 8 points","Reads as bureaucratic and raises anxiety in readers who already process less","A humanist face at 12 points with generous leading")],
 impact="Reduces anxiety in patient communication.", iscore=8, prio=9, conf=0.89, ind="healthcare")

P("typography.healthcare_typography.warning_hierarchy.001","Warning and contraindication hierarchy","healthcare_typography",
 purpose="Rank warnings so the most serious is found first.",
 visual_effect="A ranked warning block puts the most serious contraindication at the top in the heaviest weight.",
 signal="Ordered by risk - the most important thing is first.",
 hierarchy_rule="Warnings are ordered by severity, with severity carried by weight and position rather than by colour.",
 spacing_rule="The most serious warning takes the largest gap above; subsequent warnings at 0.5 base units.",
 failure="Listing warnings in the order they were written, which buries the most serious one mid-block.",
 problem="Warnings appear in authoring order, so the most serious contraindication can sit in the middle of a block.",
 decision="Order warnings by severity with the most serious first in the heaviest weight and the largest gap above.",
 reasoning="Readers scan the first item of a block, so position determines which warning is actually received.",
 why="Ranking by severity puts the highest-consequence information where it will be read.",
 use=["Pharmaceutical and healthcare communication","Any safety warning set"],
 avoid=["Regulated formats prescribing warning order","Single-warning products"],
 adv="The most serious warning is received", lim="Cannot override regulated ordering",
 suit="Multi-warning healthcare communication", unsuit="Regulated fixed-order formats",
 alts=["The regulated order where one is prescribed"],
 aps=[("Listing warnings in the order they were drafted","The most serious contraindication can sit mid-block where it is not scanned","Warnings ordered by severity, most serious first")],
 impact="Puts the most serious warning where it is read.", iscore=8, prio=9, conf=0.89, ind="healthcare")

P("typography.healthcare_typography.accessibility_minimums.001","Accessibility minimums in healthcare typography","healthcare_typography",
 purpose="Set healthcare text for readers with reduced vision.",
 visual_effect="Larger sizes with open apertures and high contrast remain readable with common vision loss.",
 signal="Inclusive - the material was set for the people who actually receive it.",
 hierarchy_rule="Every level sits above the accessibility minimum, so hierarchy is built upward from that floor.",
 spacing_rule="Body at 12 points minimum, 1.6 leading, contrast at 7 to 1, with no text over imagery.",
 failure="Setting the minimum only for body text and letting captions and labels fall below it.",
 problem="Accessibility minimums are applied to body text while captions and labels fall below the threshold.",
 decision="Set the accessibility minimum as the floor for every level, building hierarchy upward from it.",
 reasoning="Healthcare audiences skew toward reduced vision, so the smallest level determines who can use the material.",
 why="Treating the minimum as a floor rather than a body-text rule makes the whole document usable.",
 use=["Healthcare and patient communication","Public health and older audiences"],
 avoid=["Professional clinical materials","Digital formats with user-controlled sizing"],
 adv="The whole document is usable", lim="Reduces information density substantially",
 suit="Patient and public health materials", unsuit="Professional and resizable digital formats",
 alts=["A large-print edition where standard sizing is contractually fixed"],
 aps=[("Applying the size minimum to body text while captions fall below it","The smallest level determines usability, so the document still fails its audience","The minimum treated as a floor for every level")],
 impact="Makes healthcare materials usable by their audience.", iscore=8, prio=9, conf=0.9, ind="healthcare")

flush()
