# -*- coding: utf-8 -*-
"""Batch 4F - Vietnamese typography."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_typo_lib import TYPO, flush

def P(kid, name, sub, **kw):
    TYPO(kid, name, sub, **kw)

# ---------- DIACRITIC READABILITY ----------
P("typography.vietnamese_diacritics.stacked_mark_clearance.001","Clearance for stacked tone marks","vietnamese_diacritics",
 purpose="Give a tone mark sitting above an already-accented vowel the vertical room it needs.",
 visual_effect="Sufficient clearance keeps the two marks separable, so the tone and the vowel both read.",
 signal="Correctly set - the text was made for Vietnamese rather than adapted to it.",
 hierarchy_rule="Every level's leading is set from the worst-case stacked character, not from the Latin average.",
 spacing_rule="Ascender-to-mark clearance of at least 15 percent of cap height at every level.",
 failure="Setting leading from Latin ascenders, where the stacked mark on a character collides with the line above.",
 problem="Leading is set from Latin ascender height, which sits below where a stacked Vietnamese mark actually reaches.",
 decision="Set leading from the tallest stacked character in the text, allowing 15 percent of cap height above it.",
 reasoning="A circumflex with a grave above it reaches materially higher than any Latin ascender in the same face.",
 why="Measuring from the actual worst case is the only way to guarantee clearance across arbitrary copy.",
 use=["Any Vietnamese text setting","Bilingual layouts containing Vietnamese"],
 avoid=["Latin-only text","Text where Vietnamese appears only in a controlled short string"],
 adv="No collision on any character combination", lim="Consumes more vertical room than Latin setting",
 suit="Vietnamese and bilingual text", unsuit="Latin-only settings",
 alts=["A face designed with compressed mark heights where vertical room is fixed"],
 aps=[("Setting Vietnamese leading from Latin ascender height","Stacked marks collide with descenders from the line above on common characters","Leading measured from the tallest stacked character")],
 impact="Removes stacked-mark collision from Vietnamese text.", iscore=9, prio=9, conf=0.92,
 viet="This is the primary Vietnamese setting constraint; every other vertical decision derives from it.")

P("typography.vietnamese_diacritics.mark_distinguishability.001","Keeping tone marks distinguishable","vietnamese_diacritics",
 purpose="Keep the acute, grave and hook marks distinct at small sizes.",
 visual_effect="Marks with clear angular difference stay separable where similar shapes merge into one form.",
 signal="Legible - the tone can be read, not guessed from context.",
 hierarchy_rule="The smallest level in Vietnamese text sets the face selection for the whole system.",
 spacing_rule="Body at 11 points minimum in Vietnamese, one point above the Latin equivalent.",
 failure="Choosing a face whose acute and grave marks are near-vertical, which makes them merge at body size.",
 problem="Faces are chosen on Latin merit, but their tone marks are too similar to distinguish at Vietnamese body size.",
 decision="Select the face by comparing acute, grave and hook marks at the smallest size the system uses.",
 reasoning="Tone marks change word meaning, so a merged mark is a semantic error rather than an aesthetic one.",
 why="Testing at the smallest size catches the failure that a display-size review always hides.",
 use=["Vietnamese font selection","Any system with Vietnamese body text"],
 avoid=["Display-only Vietnamese usage","Latin-only systems"],
 adv="Tone is read rather than inferred", lim="Rules out otherwise attractive faces",
 suit="Vietnamese body text systems", unsuit="Display-only Vietnamese",
 alts=["Increasing size where the face cannot be changed"],
 aps=[("Approving a face for Vietnamese by reviewing it at display size","Marks that separate at 60 points merge at 10 points, where the text actually lives","Comparing the marks at the smallest size in the system")],
 impact="Keeps tone marks semantically readable.", iscore=9, prio=9, conf=0.91,
 viet="Acute and grave are the pair most often confused; check them together at the smallest level.")

P("typography.vietnamese_diacritics.capital_mark_placement.001","Marks on Vietnamese capitals","vietnamese_diacritics",
 purpose="Set Vietnamese capitals so marks above the cap line are not clipped.",
 visual_effect="Capitals with marks need clearance above the cap line that Latin capital settings never reserve.",
 signal="Complete - nothing is cut off.",
 hierarchy_rule="Any level using capitals in Vietnamese carries extra leading rather than tighter tracking.",
 spacing_rule="Cap-height leading raised by 25 percent, with tracking left at the all-caps value.",
 failure="Tightening leading on Vietnamese capitals to fit, which clips the marks against the element above.",
 problem="Vietnamese capital settings inherit Latin cap leading, so marks above the cap line are clipped.",
 decision="Raise leading by 25 percent for Vietnamese capital settings rather than reducing tracking to fit.",
 reasoning="Marks on capitals occupy space above the cap line that Latin capital leading does not reserve.",
 why="Adding vertical room solves the actual constraint, while tightening tracking does not address it at all.",
 use=["Vietnamese headlines and labels in capitals","Signage and wayfinding in Vietnamese"],
 avoid=["Lowercase Vietnamese settings","Latin-only capital settings"],
 adv="Marks are never clipped", lim="Capital settings consume more vertical room",
 suit="Vietnamese capitals", unsuit="Latin-only capitals",
 alts=["Mixed case rather than capitals where vertical room is fixed"],
 aps=[("Tightening leading on a Vietnamese capital headline to fit the space","Marks above the cap line are clipped by the element above, which reads as broken","Leading raised 25 percent, or the headline set in mixed case")],
 impact="Prevents mark clipping in Vietnamese capitals.", iscore=8, prio=9, conf=0.9,
 viet="Capitals with stacked marks are the tightest case; verify against the actual set string.")

P("typography.vietnamese_diacritics.display_size_mark_weight.001","Mark weight at display sizes","vietnamese_diacritics",
 purpose="Keep tone marks visible when a light weight is used at display size.",
 visual_effect="Thin marks at display size can disappear against a busy background where the letterform survives.",
 signal="Whole - the word is complete rather than approximately spelled.",
 hierarchy_rule="Weight selection for Vietnamese display is governed by mark visibility, not by letterform preference.",
 spacing_rule="Marks need at least 25 percent of the stem weight to remain visible over imagery.",
 failure="Using a hairline weight for a Vietnamese display line over an image, where marks vanish entirely.",
 problem="Light display weights are chosen for Latin elegance, and their tone marks disappear over imagery.",
 decision="Choose Vietnamese display weight so marks carry at least 25 percent of the stem weight.",
 reasoning="Marks are drawn thinner than stems, so a weight that works for letterforms can lose the marks entirely.",
 why="Setting the weight from the mark rather than the stem keeps the word complete.",
 use=["Vietnamese display typography over imagery","Campaign headlines in Vietnamese"],
 avoid=["Vietnamese text on flat backgrounds at body size","Latin-only display"],
 adv="Words stay complete over imagery", lim="Excludes the lightest weights",
 suit="Vietnamese display over images", unsuit="Latin-only and flat-background settings",
 alts=["A scrim or panel behind the type where a light weight is required"],
 aps=[("Setting a Vietnamese display line in a hairline weight over an image","Tone marks vanish against the image and the words are effectively misspelled","A weight where marks carry at least 25 percent of stem weight")],
 impact="Keeps Vietnamese display words complete.", iscore=8, prio=9, conf=0.9,
 viet="Check marks against the busiest region of the image, not against an average.")

# ---------- FONT COMPATIBILITY ----------
P("typography.vietnamese_compatibility.glyph_coverage_verification.001","Verifying Vietnamese glyph coverage","vietnamese_compatibility",
 purpose="Confirm a face actually contains every Vietnamese character before it is adopted.",
 visual_effect="A face with partial coverage substitutes glyphs from a fallback, producing visibly mismatched characters.",
 signal="Reliable - the same face renders every word.",
 hierarchy_rule="Coverage is verified once for the whole system before any level is specified.",
 spacing_rule="Spacing decisions are invalid until coverage is confirmed, since substituted glyphs carry other metrics.",
 failure="Adopting a face on its Latin appearance, then discovering fallback substitution in production copy.",
 problem="Faces are adopted on Latin appearance, and partial Vietnamese coverage only appears once real copy is set.",
 decision="Verify coverage of all 134 Vietnamese precomposed characters before adopting any face.",
 reasoning="Partial coverage triggers per-character fallback, which mixes two faces inside a single word.",
 why="Verifying before adoption prevents a failure that is expensive to discover after the system is specified.",
 use=["Vietnamese font selection","Any system serving Vietnamese content"],
 avoid=["Latin-only systems","Systems using a face with documented full coverage"],
 adv="No mid-word fallback substitution", lim="Excludes many otherwise suitable faces",
 suit="Vietnamese typographic systems", unsuit="Latin-only systems",
 alts=["A documented Vietnamese-supporting family where the preferred face fails"],
 aps=[("Adopting a face based on its Latin specimen alone","Partial coverage substitutes fallback glyphs mid-word once real Vietnamese copy is set","Verification of full precomposed character coverage first")],
 impact="Prevents fallback substitution inside Vietnamese words.", iscore=9, prio=9, conf=0.92,
 viet="Test with a string containing every tone on every vowel, not with a sample sentence.")

P("typography.vietnamese_compatibility.fallback_face_matching.001","Vietnamese fallback face matching","vietnamese_compatibility",
 purpose="Make an unavoidable fallback as invisible as possible.",
 visual_effect="A fallback matched in x-height and weight keeps a substituted character from standing out.",
 signal="Consistent - the reader does not see the seam.",
 hierarchy_rule="The fallback declaration applies at every level so no level substitutes differently.",
 spacing_rule="Fallback x-height within 5 percent and weight within one step of the primary face.",
 failure="Declaring a generic fallback, which substitutes a visibly different character inside a word.",
 problem="Fallback declarations name generic families, so a substituted Vietnamese character is visibly foreign in the word.",
 decision="Declare a specific fallback matched within 5 percent on x-height and one weight step.",
 reasoning="A substitution is only noticeable when the substituted glyph differs visibly from its neighbours.",
 why="Matching the fallback makes the substitution invisible even when it happens.",
 use=["Web delivery of Vietnamese content","Systems where full coverage cannot be guaranteed"],
 avoid=["Print with embedded fonts","Systems using a fully covering face"],
 adv="Substitution becomes invisible", lim="Requires identifying a matched fallback per face",
 suit="Vietnamese web delivery", unsuit="Print and fully covering systems",
 alts=["A fully covering primary face, which removes the need entirely"],
 aps=[("Declaring a generic sans-serif Vietnamese fallback","A substituted character is visibly foreign inside the word","A specific fallback matched on x-height and weight")],
 impact="Makes unavoidable substitution invisible.", iscore=8, prio=8, conf=0.89, ch="website",
 viet="Match on x-height first; weight difference is more forgiving than size difference inside a word.")

P("typography.vietnamese_compatibility.web_font_subsetting.001","Subsetting Vietnamese web fonts","vietnamese_compatibility",
 purpose="Keep Vietnamese font payload manageable without losing characters.",
 visual_effect="A correctly subset file loads faster while still rendering every character in the content.",
 signal="Efficient - the site is fast without being incomplete.",
 hierarchy_rule="Every loaded weight carries the same subset, so no level loses coverage.",
 spacing_rule="Subset ranges must include all precomposed Vietnamese blocks, not only the base Latin range.",
 failure="Subsetting to the basic Latin range, which strips the Vietnamese characters the content requires.",
 problem="Web fonts are subset to basic Latin for performance, which strips the Vietnamese characters entirely.",
 decision="Include all precomposed Vietnamese ranges in every subset and apply the same subset to every weight.",
 reasoning="Vietnamese characters sit outside basic Latin, so a default subset removes exactly what the content needs.",
 why="Subsetting to the content's actual character set delivers the performance benefit without breaking rendering.",
 use=["Vietnamese web delivery","Performance-sensitive multilingual sites"],
 avoid=["Latin-only sites","Print and offline delivery"],
 adv="Fast loading with complete rendering", lim="Larger files than a Latin-only subset",
 suit="Vietnamese web delivery", unsuit="Latin-only and offline delivery",
 alts=["A full unsubset file where build tooling cannot subset reliably"],
 aps=[("Subsetting a web font to the basic Latin range for performance","Strips exactly the Vietnamese characters the content requires and forces fallback everywhere","A subset including all precomposed Vietnamese ranges")],
 impact="Keeps Vietnamese rendering intact under subsetting.", iscore=8, prio=8, conf=0.9, ch="website")

P("typography.vietnamese_compatibility.display_face_availability.001","Vietnamese support in display faces","vietnamese_compatibility",
 purpose="Choose a display face that supports Vietnamese rather than retrofitting marks.",
 visual_effect="A face with drawn Vietnamese marks looks integrated where composed marks look attached.",
 signal="Authentic - the face was drawn for this language.",
 hierarchy_rule="Display face selection is constrained by Vietnamese support before any aesthetic comparison.",
 spacing_rule="Drawn marks carry correct optical placement; composed marks require manual adjustment per character.",
 failure="Adding marks manually to an unsupporting display face, which produces uneven placement across characters.",
 problem="Display faces without Vietnamese support are adopted and marks are added manually, producing uneven results.",
 decision="Restrict display face selection to faces with drawn Vietnamese marks rather than composing them manually.",
 reasoning="Mark placement varies per letterform, so composed marks are correct on some characters and wrong on others.",
 why="Drawn marks carry the per-character placement the designer of the face already solved.",
 use=["Vietnamese display and headline typography","Brand identity in Vietnamese markets"],
 avoid=["Latin-only display usage","Custom lettering drawn specifically for one word"],
 adv="Marks are correctly placed on every character", lim="Substantially narrows display face choice",
 suit="Vietnamese display typography", unsuit="Latin-only display",
 alts=["Custom lettering where one fixed word is being set"],
 aps=[("Adding tone marks manually to a display face lacking Vietnamese support","Placement is correct on some characters and visibly wrong on others","A face with drawn Vietnamese marks")],
 impact="Keeps mark placement correct across all characters.", iscore=8, prio=8, conf=0.89,
 viet="Custom lettering is acceptable only for a fixed wordmark, never for variable copy.")

# ---------- LOCAL AUDIENCE READABILITY ----------
P("typography.vietnamese_readability.body_size_floor.001","Vietnamese body size floor","vietnamese_readability",
 purpose="Set Vietnamese body text large enough for its marks to resolve.",
 visual_effect="One point above the Latin equivalent keeps tone marks resolvable at reading distance.",
 signal="Readable - the text was sized for the language it is in.",
 hierarchy_rule="The Vietnamese floor raises every level, preserving the ratios between them.",
 spacing_rule="Body at 11 points minimum in print and 17 pixels on screen, with 1.6 leading.",
 failure="Using the Latin body size for Vietnamese, where marks fall below the resolution the reader can separate.",
 problem="Vietnamese body text uses Latin sizing, so tone marks fall below the size at which they can be separated.",
 decision="Set Vietnamese body at 11 points in print and 17 pixels on screen, raising every level proportionally.",
 reasoning="Marks are a fraction of cap height, so they cross the legibility threshold before the letterforms do.",
 why="Raising the floor keeps the smallest meaningful element above the threshold.",
 use=["Vietnamese body text in print and on screen","Bilingual documents"],
 avoid=["Display-only Vietnamese","Latin-only settings"],
 adv="Marks resolve at reading distance", lim="Reduces the content that fits a given area",
 suit="Vietnamese running text", unsuit="Latin-only and display-only settings",
 alts=["A face with proportionally larger marks where the size cannot be raised"],
 aps=[("Setting Vietnamese body text at the Latin size","Tone marks fall below the size at which the reader can separate them","11 points in print or 17 pixels on screen")],
 impact="Keeps Vietnamese body text legible.", iscore=8, prio=9, conf=0.9,
 viet="The floor is set by mark resolution, not by letterform legibility, which is why it exceeds the Latin value.")

P("typography.vietnamese_readability.line_break_word_integrity.001","Line breaking in Vietnamese","vietnamese_readability",
 purpose="Break Vietnamese lines at syllable boundaries rather than inside compound words.",
 visual_effect="Breaks at the correct boundary keep multi-syllable words readable across a line ending.",
 signal="Fluent - the text was broken by someone who reads the language.",
 hierarchy_rule="Line-break rules apply at every level, including display where breaks are most visible.",
 spacing_rule="Hyphenation is disabled entirely; breaks occur at spaces between syllables only.",
 failure="Enabling Latin hyphenation, which splits Vietnamese syllables in places that produce nonsense.",
 problem="Latin hyphenation is enabled on Vietnamese text, splitting syllables at positions that change meaning.",
 decision="Disable hyphenation for Vietnamese and break only at spaces between syllables.",
 reasoning="Vietnamese syllables are written as separate units, so intra-syllable hyphenation has no valid position.",
 why="Disabling hyphenation removes an operation that can only produce errors in this script.",
 use=["Vietnamese running text","Justified and narrow-measure Vietnamese settings"],
 avoid=["Latin-only text","Mixed text where hyphenation is language-scoped"],
 adv="No invalid word splits", lim="Justified setting produces looser word spacing",
 suit="Vietnamese text at any measure", unsuit="Latin-only settings",
 alts=["Ragged-right setting where loose justification is unacceptable"],
 aps=[("Enabling Latin hyphenation on a Vietnamese text block","Syllables split at positions that produce nonsense words","Hyphenation disabled, breaking at syllable spaces only")],
 impact="Removes invalid word splits from Vietnamese text.", iscore=8, prio=8, conf=0.9,
 viet="Scope hyphenation by language attribute so mixed documents keep Latin hyphenation working.")

P("typography.vietnamese_readability.justification_avoidance.001","Justification in Vietnamese setting","vietnamese_readability",
 purpose="Avoid the loose word spacing justification produces in a language without hyphenation.",
 visual_effect="Ragged right keeps word spacing even, where justification without hyphenation opens visible rivers.",
 signal="Even - the block has consistent texture.",
 hierarchy_rule="Every Vietnamese text level uses ragged-right alignment regardless of the surrounding grid.",
 spacing_rule="Word spacing left at the face default with the measure held between 45 and 65 characters.",
 failure="Justifying narrow Vietnamese columns, where word spacing varies enough to form rivers down the block.",
 problem="Vietnamese columns are justified as Latin ones are, but without hyphenation the word spacing varies extremely.",
 decision="Set Vietnamese text ragged right at a measure between 45 and 65 characters, never justified.",
 reasoning="Justification distributes slack into word spaces, and hyphenation is what normally limits how much slack there is.",
 why="Without hyphenation available, ragged right is the only setting that keeps word spacing even.",
 use=["Vietnamese running text","Multi-column Vietnamese layouts"],
 avoid=["Wide-measure Vietnamese where variation stays small","Latin-only justified settings"],
 adv="Even word spacing with no rivers", lim="Loses the clean right edge of a justified column",
 suit="Vietnamese columns", unsuit="Latin-only justified text",
 alts=["Justification at a wide measure where the variation stays under control"],
 aps=[("Justifying a narrow Vietnamese column","Word spacing varies extremely without hyphenation and rivers form down the block","Ragged-right setting at a 45 to 65 character measure")],
 impact="Keeps Vietnamese word spacing even.", iscore=7, prio=8, conf=0.88,
 viet="The narrower the measure, the worse justification behaves, since there are fewer spaces to absorb the slack.")

P("typography.vietnamese_readability.bilingual_block_pairing.001","Pairing Vietnamese and English blocks","vietnamese_readability",
 purpose="Set two language blocks so they look equally intended.",
 visual_effect="Matched size and weight with Vietnamese-governed leading keeps both blocks visually equal.",
 signal="Balanced - both readers are addressed equally.",
 hierarchy_rule="Both languages occupy the same level, with the Vietnamese block placed first in Vietnamese markets.",
 spacing_rule="Leading set from the Vietnamese requirement and applied to both blocks so their rhythms match.",
 failure="Setting the Vietnamese block at Latin leading, which makes it denser and visibly secondary.",
 problem="Bilingual blocks share leading set for Latin, which makes the Vietnamese block denser and visibly secondary.",
 decision="Set leading from the Vietnamese requirement and apply it to both blocks at identical size and weight.",
 reasoning="The two scripts have different vertical requirements, so shared Latin leading is correct for only one.",
 why="Governing from the stricter requirement makes both blocks correct rather than one.",
 use=["Bilingual Vietnamese and English materials","Packaging, menus and signage"],
 avoid=["Single-language materials","Formats where space forces different treatments"],
 adv="Both blocks look equally intended", lim="Latin block is more loosely set than it needs",
 suit="Bilingual materials", unsuit="Single-language settings",
 alts=["Per-language leading where the blocks are visually separated enough not to compare"],
 aps=[("Setting both bilingual blocks at Latin leading","The Vietnamese block reads as denser and visibly secondary to the English","Leading governed by the Vietnamese requirement for both")],
 impact="Makes bilingual blocks read as equally intended.", iscore=8, prio=8, conf=0.89,
 viet="Placing Vietnamese first is the local convention in Vietnamese markets regardless of the leading rule.")

# ---------- LOCAL BRAND VOICE ----------
P("typography.vietnamese_brand_voice.imported_face_suitability.001","Assessing imported faces for local voice","vietnamese_brand_voice",
 purpose="Judge whether an international face carries the intended meaning locally.",
 visual_effect="A face's historical associations do not transfer, so its local reading may differ from its origin reading.",
 signal="Locally considered - the face was chosen for this audience.",
 hierarchy_rule="Local suitability is assessed at the display level, where the face's character is most visible.",
 spacing_rule="Local assessment includes how the face behaves with marks, not only its Latin proportions.",
 failure="Adopting a face for its associations in its home market, which local audiences do not share.",
 problem="International faces are adopted for their home-market associations, which local audiences do not carry.",
 decision="Assess an imported face on how it reads to the local audience, not on its origin-market associations.",
 reasoning="Typographic association is learned from local exposure, which differs market by market.",
 why="Assessing locally is what makes the face carry the intended meaning where it will be seen.",
 use=["Vietnamese market brand development","International brands localising identity"],
 avoid=["Global systems with mandated single-face identity","Markets with identical exposure history"],
 adv="The face means locally what it is meant to mean", lim="May conflict with a global brand mandate",
 suit="Locally developed Vietnamese brands", unsuit="Globally mandated identity systems",
 alts=["Retaining the global face with locally adjusted usage rules"],
 aps=[("Adopting a face for the associations it carries in its home market","Local audiences do not share the exposure that created those associations","Assessment against local audience reading")],
 impact="Makes imported faces carry the intended local meaning.", iscore=7, prio=8, conf=0.86,
 viet="Assess with real Vietnamese copy at the sizes the brand will actually use.")

P("typography.vietnamese_brand_voice.formality_register_local.001","Formality register in Vietnamese communication","vietnamese_brand_voice",
 purpose="Match typographic formality to the register the copy is written in.",
 visual_effect="A formal serif under informal copy produces a mismatch the reader notices without naming it.",
 signal="Consistent - the way it looks and the way it speaks agree.",
 hierarchy_rule="Face formality is chosen after the copy register is settled, never before.",
 spacing_rule="Formal registers use tighter tracking and denser leading; informal registers use looser both.",
 failure="Pairing a formal display serif with casual copy, which reads as either sarcastic or careless.",
 problem="Face selection precedes copy writing, so formal typography frequently sits under informal Vietnamese copy.",
 decision="Settle the copy register first and choose face formality to match it.",
 reasoning="Vietnamese carries formality explicitly through address terms, so a mismatch with the face is directly visible.",
 why="Choosing the face after the copy lets the two agree rather than compete.",
 use=["Vietnamese brand and campaign communication","Any Vietnamese copy with a defined register"],
 avoid=["Systems where the face is fixed before copy exists","Purely visual assets with no copy"],
 adv="Look and voice agree", lim="Delays face selection until copy is settled",
 suit="Copy-led Vietnamese communication", unsuit="Fixed-face systems",
 alts=["A neutral face where the register varies across the campaign"],
 aps=[("Pairing a formal display serif with casual Vietnamese copy","The mismatch reads as sarcastic or careless to a fluent reader","Face formality chosen after the copy register is settled")],
 impact="Aligns typographic and written register.", iscore=7, prio=8, conf=0.86,
 viet="Vietnamese address terms make register explicit in the copy, so the mismatch is unusually visible.")

P("typography.vietnamese_brand_voice.local_display_customisation.001","Customising display type for Vietnamese","vietnamese_brand_voice",
 purpose="Adjust a display wordmark so its marks are drawn rather than borrowed.",
 visual_effect="Marks drawn to match the wordmark's own stroke logic look integrated rather than applied.",
 signal="Made for here - the identity was designed in this language.",
 hierarchy_rule="Customisation applies to the wordmark only and never propagates into the text system.",
 spacing_rule="Custom marks are positioned per character in the wordmark and fixed at construction.",
 failure="Customising marks in the wordmark and then attempting the same in body copy, which cannot be maintained.",
 problem="Wordmark marks are borrowed from the base face, so they do not match the wordmark's own stroke logic.",
 decision="Draw the wordmark's tone marks to match its stroke logic and fix them at construction.",
 reasoning="A wordmark is a fixed drawing, so its marks can be drawn once where variable text cannot.",
 why="Confining customisation to the fixed drawing gets the quality without an unmaintainable rule.",
 use=["Vietnamese wordmark development","Local brand identity design"],
 avoid=["Variable text settings","Systems without a Vietnamese wordmark"],
 adv="The wordmark reads as designed for the language", lim="Applies to the mark only",
 suit="Vietnamese brand identity", unsuit="Variable text settings",
 alts=["The base face's marks where custom drawing is out of scope"],
 aps=[("Extending wordmark mark customisation into body copy","Variable text cannot carry per-character custom marks and the rule cannot be maintained","Customisation confined to the fixed wordmark drawing")],
 impact="Makes a Vietnamese wordmark read as designed for the language.", iscore=7, prio=7, conf=0.85,
 viet="Draw the marks from the wordmark's own stroke logic rather than scaling the base face's marks.")

P("typography.vietnamese_brand_voice.mixed_language_display.001","Mixed-language display lines","vietnamese_brand_voice",
 purpose="Set a line containing both Vietnamese and English without a visible seam.",
 visual_effect="One face across both languages keeps a mixed line reading as one sentence.",
 signal="Natural - the mixing is how people speak rather than a production compromise.",
 hierarchy_rule="A mixed line is one level in one face; no language within it changes face or weight.",
 spacing_rule="Leading set from the Vietnamese requirement even where the marks fall on the English portion's line.",
 failure="Setting the English portion in a different face, which makes borrowed terms look like foreign insertions.",
 problem="Mixed Vietnamese and English lines use different faces per language, so the line reads as spliced.",
 decision="Set mixed-language lines in one face at one weight with leading governed by the Vietnamese requirement.",
 reasoning="Mixed-language speech is ordinary in the market, so the setting should not mark it as exceptional.",
 why="A single face keeps the line reading as one sentence rather than as two fragments.",
 use=["Vietnamese market campaigns using English terms","Technology and lifestyle categories"],
 avoid=["Formal documents requiring language separation","Bilingual blocks presented as translations"],
 adv="Mixed lines read as one sentence", lim="Requires one face covering both scripts well",
 suit="Mixed-language campaign copy", unsuit="Formal translated documents",
 alts=["Separate blocks where the two languages are translations rather than a mixed sentence"],
 aps=[("Setting the English words in a mixed Vietnamese line in a different face","Borrowed terms read as foreign insertions rather than as ordinary speech","One face and one weight across the whole line")],
 impact="Keeps mixed-language lines reading naturally.", iscore=7, prio=7, conf=0.86,
 viet="English loan terms are ordinary in Vietnamese campaign copy; setting them apart marks them as unnatural.")

flush()
