# -*- coding: utf-8 -*-
"""Batch 4D - spacing intelligence."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_typo_lib import TYPO, flush
LUX = dict(pos=["premium","luxury"])

def P(kid, name, sub, **kw):
    TYPO(kid, name, sub, **kw)

# ---------- NEGATIVE SPACE ----------
P("typography.negative_space.margin_as_value_signal.001","Margin width as a price signal","negative_space",
 purpose="Use unprinted area to communicate what the product costs before the price is read.",
 visual_effect="Margins above 15 percent of the shorter edge make the printed area read as chosen rather than filled.",
 signal="Confident - the brand can afford to leave area empty.",
 hierarchy_rule="Margin is set before any element is placed, and no element is permitted to encroach on it.",
 spacing_rule="Premium positioning uses 15 to 25 percent margins; value positioning uses 5 to 8 percent.",
 failure="Reducing margins late to fit one more message, which converts a premium layout into a value one.",
 problem="Margins are treated as leftover area and eroded whenever content is added, so positioning drifts downward.",
 decision="Set margin percentage from the price positioning before layout and treat it as a fixed boundary.",
 reasoning="Unprinted area has a direct cost in every medium, so leaving it reads as an affordability signal.",
 why="Fixing the margin first makes content compete with content rather than with the positioning signal.",
 use=["Premium and luxury positioning","Packaging and campaign layout"],
 avoid=["Value and promotional positioning","Formats with regulated content minimums"],
 adv="Positioning legible before any word is read", lim="Reduces the message capacity of every asset",
 suit="Premium positioning", unsuit="Value and information-dense formats",
 alts=["Tight margins with strong internal spacing where content volume is fixed"],
 aps=[("Reducing margins to fit one more message","The layout reads as value positioning regardless of what the copy claims","Cutting a message rather than the margin")],
 impact="Makes price positioning legible before reading.", iscore=8, prio=9, conf=0.89, **LUX)

P("typography.negative_space.breathing_room_per_level.001","Space allocation across hierarchy levels","negative_space",
 purpose="Distribute vertical space so rank is readable from spacing alone.",
 visual_effect="Space above an element scaled to its rank makes the hierarchy legible with the text blurred.",
 signal="Ordered - the reader knows the structure before reading a word.",
 hierarchy_rule="Space above an element is proportional to its rank: the highest level takes the largest gap.",
 spacing_rule="Space above scales at roughly 2, 1.5 and 1 times the base unit for the three levels descending.",
 failure="Using uniform spacing between all levels, which flattens rank into an undifferentiated list.",
 problem="Layouts space every element equally, so hierarchy depends entirely on size and disappears when sizes are close.",
 decision="Scale space above each element to its rank at roughly 2, 1.5 and 1 base units descending.",
 reasoning="Proximity groups elements, so the gap above an element declares whether it starts a new section.",
 why="Rank carried by spacing survives even when the size difference between levels is small.",
 use=["Multi-level layouts","Editorial and campaign typography"],
 avoid=["Single-level display assets","Fixed-grid tabular content"],
 adv="Hierarchy readable without size contrast", lim="Requires vertical room the format may not have",
 suit="Multi-level layouts", unsuit="Single-level and tabular content",
 alts=["Size and weight contrast where vertical room is unavailable"],
 aps=[("Applying uniform vertical spacing between every level","Rank flattens into a list and hierarchy depends entirely on size","Space scaled to rank, largest above the highest level")],
 impact="Makes rank readable from spacing alone.", iscore=8, prio=9, conf=0.9)

P("typography.negative_space.asymmetric_margin_tension.001","Asymmetric margins for tension","negative_space",
 purpose="Create directional tension without moving any element off the grid.",
 visual_effect="Unequal opposing margins pull the composition toward the wider side and create implied movement.",
 signal="Deliberate and contemporary - the composition is not merely centred.",
 hierarchy_rule="The wider margin sits on the side away from the primary reading entry point.",
 spacing_rule="Opposing margins differ by at least 40 percent, since smaller differences read as an error.",
 failure="Making margins differ by 10 percent, which reads as a production mistake rather than a decision.",
 problem="Asymmetric layouts use small margin differences that read as misalignment rather than as intent.",
 decision="Make opposing margins differ by at least 40 percent when using asymmetry, never less.",
 reasoning="The eye reads small differences as failed symmetry and large differences as chosen asymmetry.",
 why="Crossing the perception threshold is what converts a difference into a decision.",
 use=["Contemporary editorial and campaign layouts","Formats with room for uneven margins"],
 avoid=["Formal and classical layouts","Regulated formats with fixed safe areas"],
 adv="Movement without breaking the grid", lim="Reads as informal in classical contexts",
 suit="Contemporary editorial", unsuit="Formal and regulated layouts",
 alts=["Symmetric margins with an off-centre focal element"],
 aps=[("Setting opposing margins 10 percent apart","Reads as a production error rather than as deliberate asymmetry","A difference of at least 40 percent")],
 impact="Converts margin difference into visible intent.", iscore=7, prio=8, conf=0.87)

P("typography.negative_space.silence_before_the_claim.001","Space before the primary claim","negative_space",
 purpose="Give the main message a pause so it registers as the point of the asset.",
 visual_effect="An unusually large gap immediately above the claim isolates it from surrounding content.",
 signal="Considered - this sentence was meant to be noticed.",
 hierarchy_rule="The largest single gap in the layout sits directly above the primary claim.",
 spacing_rule="Gap above the claim is at least twice the next largest gap in the composition.",
 failure="Placing the largest gap somewhere other than above the claim, which promotes the wrong element.",
 problem="Layouts distribute space evenly, so the primary claim arrives without emphasis and is skimmed past.",
 decision="Place the layout's largest gap directly above the primary claim at twice the next largest gap.",
 reasoning="An interruption in rhythm draws attention to whatever follows it more reliably than size alone.",
 why="The largest gap is unambiguous, so it cannot be mistaken for ordinary spacing.",
 use=["Campaign assets with one primary claim","Advertising and packaging front panels"],
 avoid=["Multi-claim information layouts","Assets with no single primary message"],
 adv="The claim registers rather than being skimmed", lim="Only works when there is one claim",
 suit="Single-claim campaign assets", unsuit="Multi-claim information layouts",
 alts=["Colour or weight isolation where vertical room is unavailable"],
 aps=[("Placing the largest gap above a secondary element","Promotes the wrong element and the primary claim reads as subordinate","The largest gap reserved for the primary claim")],
 impact="Makes the primary claim register.", iscore=8, prio=9, conf=0.88)

P("typography.negative_space.edge_safe_discipline.001","Edge distance discipline","negative_space",
 purpose="Keep type clear of edges where trimming, cropping and interface chrome intrude.",
 visual_effect="Type held well inside the trim reads as settled rather than as about to fall off.",
 signal="Professional - the asset was produced for its actual output.",
 hierarchy_rule="No text element sits closer to any edge than the smallest inter-level gap in the layout.",
 spacing_rule="Minimum edge distance is 5 percent of the shorter edge in print and 6 percent on social.",
 failure="Placing text at the technical safe-area boundary, where platform chrome still overlaps it.",
 problem="Text is placed at the technical safe area, which prevents trimming but still collides with platform chrome.",
 decision="Hold text at least 5 percent of the shorter edge from every edge, and 6 percent for social formats.",
 reasoning="Technical safe areas prevent loss, but visual comfort requires more distance than loss prevention does.",
 why="Designing to comfort rather than to the technical minimum survives both trimming and chrome.",
 use=["Print production","Social and platform-delivered assets"],
 avoid=["Deliberate full-bleed typographic treatments","Fixed-template formats"],
 adv="Survives trim and platform chrome", lim="Reduces usable area",
 suit="Print and platform delivery", unsuit="Deliberate bleed treatments",
 alts=["Full bleed where the crop is deliberate and controlled"],
 aps=[("Placing text exactly at the technical safe-area boundary","Platform chrome overlaps it in feed even though nothing is trimmed","Text held at 6 percent of the shorter edge on social")],
 impact="Keeps type intact through production and platforms.", iscore=7, prio=8, conf=0.89, ch=["social_media","print"])

P("typography.negative_space.grouping_by_proximity.001","Proximity grouping over rules","negative_space",
 purpose="Show which elements belong together without drawing dividing lines.",
 visual_effect="Related items placed closer than unrelated ones read as a group without any added mark.",
 signal="Clean - structure is present without visible apparatus.",
 hierarchy_rule="Intra-group spacing is at most half the inter-group spacing at every level.",
 spacing_rule="Within a group at 0.5 base units; between groups at 1.5 base units or more.",
 failure="Adding rules between groups that are already separated by space, which doubles the signal.",
 problem="Layouts add dividing rules to structure that spacing already communicates, cluttering the composition.",
 decision="Group by proximity at a two to one ratio and add rules only where spacing cannot be increased.",
 reasoning="Proximity is read pre-attentively, so it establishes grouping before any drawn mark is processed.",
 why="Using the cheaper signal first leaves rules available for cases where space genuinely runs out.",
 use=["Any multi-element layout","Menus, specifications and information panels"],
 avoid=["Dense tables where space is unavailable","Formats requiring visible separation for compliance"],
 adv="Structure without added marks", lim="Requires vertical room to work",
 suit="Multi-element layouts with room", unsuit="Dense tabular content",
 alts=["Hairline rules where space is genuinely unavailable"],
 aps=[("Adding rules between groups already separated by generous space","Doubles the grouping signal and clutters an otherwise clean composition","Spacing alone, with rules held in reserve")],
 impact="Delivers structure without visual apparatus.", iscore=7, prio=8, conf=0.89)

# ---------- TRACKING ----------
P("typography.tracking.display_size_compensation.001","Tracking compensation at display sizes","tracking",
 purpose="Correct the spacing a text-optimised face carries when it is used large.",
 visual_effect="Tightening large type removes the gaps that appear when text spacing is scaled up.",
 signal="Finished - the type looks drawn at that size rather than enlarged.",
 hierarchy_rule="Tracking is set per level, tightening as size increases and loosening as size decreases.",
 spacing_rule="Minus 10 to minus 30 units above 48 points; zero at body; plus 10 to plus 25 below 10 points.",
 failure="Using zero tracking at 72 points, where inter-letter gaps become visibly uneven.",
 problem="Type is set at display size with body tracking, so letter gaps open visibly and the setting looks loose.",
 decision="Track minus 10 to minus 30 units above 48 points and plus 10 to plus 25 units below 10 points.",
 reasoning="Letter spacing is drawn for one size and scales linearly, while optical requirement does not.",
 why="Size-dependent tracking restores the spacing the face would have if drawn at that size.",
 use=["Display and headline typography","Small print and caption settings"],
 avoid=["Faces with optical size cuts","Body text at intended size"],
 adv="Even spacing at every size", lim="Requires per-level tracking values",
 suit="Single-optical-size faces", unsuit="Optical families that self-correct",
 alts=["An optical size family, which handles this in the cut"],
 aps=[("Setting a headline at 72 points with body tracking","Inter-letter gaps open visibly and the setting reads as amateur","Tightening 10 to 30 units at display size")],
 impact="Restores even spacing across the size range.", iscore=8, prio=9, conf=0.9)

P("typography.tracking.all_caps_requirement.001","Tracking for all-capital settings","tracking",
 purpose="Make capital settings readable rather than merely present.",
 visual_effect="Capitals tracked looser separate into distinguishable forms instead of a continuous band.",
 signal="Formal and legible - authority without difficulty.",
 hierarchy_rule="All-caps is confined to labels and eyebrows, and never used at body length.",
 spacing_rule="Tracked 50 to 120 units, tighter at display and looser at small label sizes.",
 failure="Setting capitals at zero tracking, where the uniform height produces an unreadable block.",
 problem="Capital settings use default tracking, which was drawn for mixed case and leaves capitals crowded.",
 decision="Track all-capital settings 50 to 120 units, tightening toward 50 as size increases.",
 reasoning="Default sidebearings assume lowercase neighbours, which capitals never provide.",
 why="Added tracking supplies the separation lowercase would otherwise contribute.",
 use=["Labels, eyebrows and short capital settings","Formal and institutional registers"],
 avoid=["Body-length text","Vietnamese text with heavy diacritic load"],
 adv="Capitals become readable", lim="Consumes horizontal room",
 suit="Short capital labels", unsuit="Body-length capital settings",
 alts=["Small caps, which are drawn for this purpose"],
 aps=[("Setting capitals at zero tracking","Uniform height with no added separation produces a continuous unreadable band","Tracking of 50 to 120 units")],
 impact="Makes capital settings readable.", iscore=8, prio=9, conf=0.91,
 viet="Vietnamese capitals carry marks above the cap line; add leading rather than reducing tracking to fit.")

P("typography.tracking.luxury_letterspacing_ceiling.001","The luxury tracking ceiling","tracking",
 purpose="Use wide tracking for refinement without crossing into illegibility.",
 visual_effect="Tracking beyond roughly 200 units stops reading as a word and becomes separate letters.",
 signal="Refined up to the ceiling, and merely decorative beyond it.",
 hierarchy_rule="Wide tracking applies to one short line only, never to more than four words.",
 spacing_rule="Maximum 200 units, and only on lines of four words or fewer.",
 failure="Tracking a full sentence to 250 units, after which word boundaries dissolve.",
 problem="Luxury layouts track long lines widely, and word boundaries dissolve so the line stops being readable.",
 decision="Cap tracking at 200 units and apply it only to lines of four words or fewer.",
 reasoning="Word recognition depends on inter-word gaps exceeding inter-letter gaps, which wide tracking reverses.",
 why="The ceiling keeps the refinement signal while preserving word boundaries.",
 use=["Luxury eyebrows and short display lines","Fashion and beauty campaign typography"],
 avoid=["Body text and long headlines","Vietnamese text at small sizes"],
 adv="Refinement without illegibility", lim="Restricted to very short lines",
 suit="Short luxury display lines", unsuit="Body and long-form settings",
 alts=["Increased word spacing where the line must be longer"],
 aps=[("Tracking a full sentence to 250 units for a luxury feel","Inter-letter gaps exceed inter-word gaps and word boundaries dissolve","Tracking capped at 200 units on a four-word line")],
 impact="Keeps wide tracking readable.", iscore=7, prio=8, conf=0.88, **LUX)

P("typography.tracking.small_size_opening.001","Opening tracking at small sizes","tracking",
 purpose="Keep small type legible in print and at low screen density.",
 visual_effect="Loosened tracking below 10 points prevents strokes merging under ink spread or pixel rounding.",
 signal="Careful - even the fine print was set properly.",
 hierarchy_rule="Caption, legal and footnote levels each carry their own positive tracking value.",
 spacing_rule="Plus 10 units at 9 points, plus 25 units at 7 points and below.",
 failure="Using body tracking for 7-point legal text, where ink spread merges adjacent strokes.",
 problem="Small print inherits body tracking, so ink spread and pixel rounding merge adjacent letterforms.",
 decision="Track plus 10 units at 9 points and plus 25 units at 7 points and below.",
 reasoning="Ink spread and pixel rounding are absolute effects, so they consume a growing share of a shrinking gap.",
 why="Opening the gap in proportion to the size keeps the effect from closing it.",
 use=["Legal, caption and ingredient text","Print production and low-density screens"],
 avoid=["Display sizes","High-density screens with no ink spread"],
 adv="Small print stays legible", lim="Consumes horizontal room where it is scarcest",
 suit="Small print in production", unsuit="Display typography",
 alts=["Increasing size instead where room allows"],
 aps=[("Setting 7-point legal text at body tracking","Ink spread merges adjacent strokes and the text becomes unreadable in print","Plus 25 units tracking at 7 points")],
 impact="Keeps small print legible through production.", iscore=7, prio=8, conf=0.89)

P("typography.tracking.brand_name_lockup.001","Fixed tracking in a brand lockup","tracking",
 purpose="Keep a brand name identical across every size and surface.",
 visual_effect="Tracking fixed at construction keeps the name recognisable as a constant shape.",
 signal="Reliable - the name is the same object everywhere it appears.",
 hierarchy_rule="The lockup is outside the tracking system and never inherits a level's tracking value.",
 spacing_rule="Tracking is set once at construction and reproduced proportionally at every size.",
 failure="Applying level tracking to the lockup, which changes the name's proportions between assets.",
 problem="Brand lockups inherit the tracking of whichever level they sit in, so proportions vary across assets.",
 decision="Fix lockup tracking at construction and scale it proportionally, never applying level tracking.",
 reasoning="Recognition depends on a constant shape, which changes whenever spacing is recalculated.",
 why="Proportional reproduction keeps the shape constant across every size.",
 use=["Brand identity systems","Multi-asset campaigns"],
 avoid=["Running text mentions of the brand name","Systems with no typographic lockup"],
 adv="Constant recognisable name shape", lim="Requires the lockup to be handled as an exception",
 suit="Typographic brand identities", unsuit="Symbol-only identities",
 alts=["Supplying the lockup as artwork rather than as live text"],
 aps=[("Letting the lockup inherit the headline level's tracking","The name's proportions change between assets and recognition weakens","Tracking fixed at construction and scaled proportionally")],
 impact="Keeps the brand name a constant shape.", iscore=7, prio=8, conf=0.88)

P("typography.tracking.negative_tracking_limit.001","The negative tracking limit","tracking",
 purpose="Tighten display type without letting forms collide.",
 visual_effect="Beyond roughly minus 40 units, round letterforms begin to touch and counters close.",
 signal="Tight and modern up to the limit, and broken past it.",
 hierarchy_rule="Negative tracking applies at display only, never at text or caption levels.",
 spacing_rule="Floor at minus 40 units, checked against the tightest letter pair in the actual string.",
 failure="Tracking to minus 60 units, where round pairs collide and the setting reads as a rendering fault.",
 problem="Display type is tightened aggressively for a contemporary look until letterforms visibly collide.",
 decision="Floor negative tracking at minus 40 units and verify against the tightest pair in the actual string.",
 reasoning="Tracking applies uniformly while letter pairs have unequal natural gaps, so the tightest pair fails first.",
 why="Checking the actual worst pair catches the failure a global value hides.",
 use=["Display and headline typography","Contemporary and technology registers"],
 avoid=["Body and caption text","Vietnamese text where marks need horizontal clearance"],
 adv="Tight modern display without collision", lim="Requires per-string verification",
 suit="Display typography", unsuit="Text and caption levels",
 alts=["A condensed cut rather than negative tracking"],
 aps=[("Tracking display type to minus 60 units","Round letter pairs collide and the setting reads as a rendering fault","Floor at minus 40 with the tightest pair checked")],
 impact="Prevents collision while keeping display tight.", iscore=7, prio=8, conf=0.88)

# ---------- LEADING ----------
P("typography.leading.measure_leading_relationship.001","Leading set from measure","leading",
 purpose="Choose line spacing from line length rather than from a fixed habit.",
 visual_effect="Longer lines with more leading keep the eye from returning to the line it just read.",
 signal="Readable - the block was set for its actual width.",
 hierarchy_rule="Every text block declares its measure first, and leading follows from it.",
 spacing_rule="1.4 leading at 45 characters, 1.5 at 65 characters and 1.6 at 85 characters.",
 failure="Applying 1.4 leading to an 85-character measure, where the eye loses the line on return.",
 problem="Leading is applied as a fixed value regardless of measure, so wide columns lose the reader on line return.",
 decision="Set leading from measure: 1.4 at 45 characters, 1.5 at 65 and 1.6 at 85.",
 reasoning="The return sweep depends on distinguishing the next line from the one just left, which widens with measure.",
 why="Scaling leading with measure keeps the return sweep reliable at any column width.",
 use=["Any running text","Editorial, web and long-form layouts"],
 avoid=["Single-line display settings","Fixed-height tabular content"],
 adv="Reliable line return at any width", lim="Wide measures consume more vertical room",
 suit="Running text at any measure", unsuit="Display and tabular settings",
 alts=["Narrowing the measure instead of increasing leading"],
 aps=[("Applying 1.4 leading to an 85-character measure","The eye returns to the line it just read and the reader loses their place","1.6 leading at that measure, or a narrower column")],
 impact="Keeps line return reliable at any measure.", iscore=8, prio=9, conf=0.91, ch="website")

P("typography.leading.display_negative_leading.001","Negative leading at display sizes","leading",
 purpose="Make a multi-line headline read as one object rather than as separate lines.",
 visual_effect="Leading below 1.0 pulls lines into a single mass with visible internal structure.",
 signal="Assertive - the headline is a block, not a sentence.",
 hierarchy_rule="Negative leading applies only to display, and only where no descender meets an ascender.",
 spacing_rule="0.85 to 0.95 leading above 48 points, verified against the actual line breaks.",
 failure="Applying 0.85 leading where a descender meets a capital, producing a visible collision.",
 problem="Display headlines use body leading, so multi-line headlines read as separate lines rather than one mass.",
 decision="Set display leading to 0.85 to 0.95 above 48 points and verify against the actual line breaks.",
 reasoning="Leading is drawn for text where ascender and descender both occur, which display headlines often avoid.",
 why="Verification against the real breaks captures the clearance the type actually needs.",
 use=["Display headlines above 48 points","Campaign and poster typography"],
 avoid=["Body and caption text","Vietnamese text where marks occupy the ascender zone"],
 adv="Headline reads as one object", lim="Requires checking every line break",
 suit="Large display headlines", unsuit="Text levels and Vietnamese display",
 alts=["1.0 leading where the line breaks cannot be controlled"],
 aps=[("Applying 0.85 leading without checking line breaks","A descender meets a capital on one break and the collision reads as broken","Leading verified against the actual breaks in the set copy")],
 impact="Makes multi-line headlines read as one object.", iscore=7, prio=8, conf=0.88,
 viet="Vietnamese needs at least 1.05 at display, since marks occupy the space negative leading removes.")

P("typography.leading.vietnamese_vertical_allowance.001","Vertical allowance for Vietnamese","leading",
 purpose="Give stacked diacritics the vertical room Latin leading does not reserve.",
 visual_effect="Roughly 20 percent additional leading keeps marks clear of the line above.",
 signal="Locally competent - the setting was made for this language.",
 hierarchy_rule="Every level's leading is raised by the same proportion so hierarchy relationships are preserved.",
 spacing_rule="Latin leading multiplied by 1.2 at every level, giving 1.65 to 1.8 at body.",
 failure="Using Latin leading values for Vietnamese, where marks collide with descenders from the line above.",
 problem="Vietnamese is set with Latin leading, so stacked tone marks collide with the descenders above them.",
 decision="Multiply Latin leading by 1.2 at every level for Vietnamese text, giving 1.65 to 1.8 at body.",
 reasoning="Vietnamese stacks a diacritic above an already-accented vowel, which exceeds the Latin ascender zone.",
 why="Raising every level by the same factor preserves the hierarchy while supplying the extra room.",
 use=["Vietnamese text at any level","Bilingual layouts"],
 avoid=["Latin-only text","Formats where vertical room is fixed and Vietnamese is display-only"],
 adv="No collision, hierarchy preserved", lim="Consumes roughly 20 percent more vertical room",
 suit="Vietnamese and bilingual settings", unsuit="Latin-only text",
 alts=["A face with a compressed mark design where vertical room is genuinely fixed"],
 aps=[("Setting Vietnamese body text at 1.5 Latin leading","Stacked tone marks collide with descenders from the line above","Leading raised to 1.8 for Vietnamese body")],
 impact="Removes diacritic collision in Vietnamese setting.", iscore=9, prio=9, conf=0.92,
 viet="This is the base rule for all Vietnamese setting; every other spacing decision assumes it is applied.")

P("typography.leading.caption_tightening.001","Tighter leading for scanned text","leading",
 purpose="Distinguish scanned text from read text through vertical rhythm.",
 visual_effect="Captions at tighter leading form a visibly denser block than the body around them.",
 signal="Subordinate - this block supports rather than continues the argument.",
 hierarchy_rule="Captions and labels sit 0.15 below the body leading value at the same measure.",
 spacing_rule="Caption leading at 1.35 where body is 1.5, with the measure held under 45 characters.",
 failure="Setting captions at body leading, which makes them compete with the text they support.",
 problem="Captions inherit body leading, so they read as continuation of the argument rather than as support.",
 decision="Set caption leading 0.15 below body leading with the measure held under 45 characters.",
 reasoning="Density difference signals reading mode, and captions are scanned rather than read continuously.",
 why="A tighter block reads as an aside without needing a smaller size or a lighter weight.",
 use=["Editorial captions and labels","Any layout with supporting text"],
 avoid=["Captions of paragraph length","Vietnamese captions where marks need the room"],
 adv="Support text stays subordinate", lim="Fails at paragraph-length captions",
 suit="Short editorial captions", unsuit="Long captions and Vietnamese text",
 alts=["Size or weight reduction where leading cannot be tightened"],
 aps=[("Setting captions at the same leading as body text","Captions compete with the argument they are meant to support","Caption leading 0.15 tighter with a narrower measure")],
 impact="Keeps support text visibly subordinate.", iscore=7, prio=7, conf=0.87)

P("typography.leading.baseline_grid_commitment.001","Baseline grid commitment","leading",
 purpose="Keep text across columns aligned so a multi-column page reads as one plane.",
 visual_effect="Every line landing on a shared baseline keeps adjacent columns horizontally aligned.",
 signal="Rigorous - the page was engineered rather than assembled.",
 hierarchy_rule="Every level's leading is an integer multiple of the baseline unit without exception.",
 spacing_rule="Baseline unit set from the body leading; all other levels snap to multiples of it.",
 failure="Exempting one level from the grid, after which every column below it is misaligned.",
 problem="Baseline grids are applied to body text but not to headings, so columns drift out of alignment below them.",
 decision="Make every level's leading an integer multiple of the baseline unit, with no exemptions.",
 reasoning="A single off-grid element shifts everything beneath it, so partial compliance produces no benefit.",
 why="Total compliance is what makes the grid pay for the constraint it imposes.",
 use=["Multi-column editorial","Reports and long documents"],
 avoid=["Single-column layouts","Free-form campaign compositions"],
 adv="Columns align across the whole page", lim="Constrains every size and leading choice",
 suit="Multi-column editorial", unsuit="Single-column and free-form layouts",
 alts=["Column-independent leading where alignment across columns does not matter"],
 aps=[("Exempting headings from the baseline grid","Every column below a heading is misaligned, so the grid produces no benefit","All levels snapped to integer multiples of the baseline unit")],
 impact="Delivers cross-column alignment.", iscore=7, prio=8, conf=0.88)

P("typography.leading.paragraph_separation_choice.001","Paragraph separation by space or indent","leading",
 purpose="Mark paragraph starts without doing it twice.",
 visual_effect="Either a first-line indent or a space between paragraphs marks the break, and both together over-mark it.",
 signal="Conventional and correct - the setting follows one established rule.",
 hierarchy_rule="Paragraph separation uses indent in continuous prose and space in scanned or screen text.",
 spacing_rule="Indent at one em with no added space, or 0.75 line space with no indent.",
 failure="Using both indent and paragraph space, which marks the same break twice and fragments the column.",
 problem="Text uses both a first-line indent and a paragraph space, marking one break twice and breaking the column.",
 decision="Use either a one-em indent or a 0.75 line space between paragraphs, never both together.",
 reasoning="Both devices mark the same boundary, so applying both makes the boundary louder than the text.",
 why="Choosing one keeps the column continuous while still marking the break clearly.",
 use=["Any running prose","Print and screen long-form"],
 avoid=["Single-paragraph settings","List and tabular content"],
 adv="Clear breaks without column fragmentation", lim="Requires committing to one convention",
 suit="Running prose", unsuit="Lists and single-paragraph text",
 alts=["A drop cap or ornament for the first paragraph only"],
 aps=[("Using a first-line indent and a paragraph space together","Marks the same boundary twice and fragments the column into blocks","One device only, chosen by medium")],
 impact="Marks paragraph breaks once, correctly.", iscore=7, prio=8, conf=0.89)

# ---------- DENSITY CONTROL ----------
P("typography.density_control.message_count_ceiling.001","Message count ceiling per asset","density_control",
 purpose="Limit how many messages an asset carries so each one can be spaced properly.",
 visual_effect="Three or fewer messages leave room for the spacing that makes hierarchy visible.",
 signal="Focused - the asset knows what it is for.",
 hierarchy_rule="A maximum of three message levels per asset: one primary, one supporting, one action.",
 spacing_rule="Each additional message beyond three reduces available spacing below the threshold hierarchy needs.",
 failure="Adding a fourth and fifth message, after which spacing collapses and every level reads the same.",
 problem="Assets accumulate messages until the spacing required for hierarchy no longer fits.",
 decision="Limit each asset to three message levels and move additional messages to another asset.",
 reasoning="Spacing and message count compete for the same fixed area, so one is spent to buy the other.",
 why="Capping messages preserves the spacing budget hierarchy depends on.",
 use=["Campaign and advertising assets","Social and out-of-home formats"],
 avoid=["Specification and information layouts","Regulated content with mandatory disclosures"],
 adv="Hierarchy survives", lim="Requires cutting messages stakeholders want",
 suit="Campaign assets", unsuit="Information and regulated layouts",
 alts=["A multi-asset sequence where messages cannot be cut"],
 aps=[("Adding a fourth and fifth message to a campaign asset","Spacing collapses below what hierarchy needs and every level reads the same","Three message levels, with the rest moved to another asset")],
 impact="Preserves the spacing hierarchy requires.", iscore=8, prio=9, conf=0.89)

P("typography.density_control.information_layout_density.001","Density in information layouts","density_control",
 purpose="Set dense content so it stays navigable rather than merely compact.",
 visual_effect="Grouping and consistent gutters keep a dense page readable where uniform density does not.",
 signal="Competent - complexity is organised rather than avoided.",
 hierarchy_rule="Dense layouts use grouping rather than level contrast, since size contrast has no room.",
 spacing_rule="Intra-group at 0.4 base units, inter-group at 1.2, with gutters fixed across the page.",
 failure="Reducing all spacing uniformly to fit, which removes the grouping that makes density navigable.",
 problem="Dense layouts reduce every gap equally to fit, removing the grouping the reader needs to navigate.",
 decision="Compress intra-group spacing to 0.4 base units while holding inter-group spacing at 1.2.",
 reasoning="Navigation depends on the ratio between gaps, not on their absolute size.",
 why="Preserving the ratio while shrinking the values keeps density navigable.",
 use=["Specification sheets and data layouts","Menus and catalogues"],
 avoid=["Campaign assets with few messages","Premium positioning layouts"],
 adv="Density stays navigable", lim="No room for premium spacing signals",
 suit="Information-dense layouts", unsuit="Premium campaign assets",
 alts=["Reducing content where density genuinely cannot be navigated"],
 aps=[("Reducing every gap uniformly to fit more content","Removes the grouping ratio the reader navigates by, so the page becomes a wall","Intra-group compressed while inter-group is held")],
 impact="Keeps dense layouts navigable.", iscore=7, prio=8, conf=0.88)

P("typography.density_control.social_thumbnail_density.001","Density for thumbnail viewing","density_control",
 purpose="Ensure a social asset still communicates at feed thumbnail size.",
 visual_effect="At thumbnail scale only the largest element survives, so density determines whether anything reads.",
 signal="Platform-aware - the asset was designed for where it is actually seen.",
 hierarchy_rule="One element must remain legible at 15 percent of the asset's full dimensions.",
 spacing_rule="The primary element occupies at least 20 percent of the shorter edge in cap height.",
 failure="Designing at full size only, where a headline that works at 100 percent vanishes at thumbnail.",
 problem="Social assets are designed at full size, but the feed shows them small and nothing survives the reduction.",
 decision="Size the primary element to at least 20 percent of the shorter edge and verify at 15 percent scale.",
 reasoning="Feed viewing is the actual first impression, and it happens at a fraction of the design canvas size.",
 why="Designing to the thumbnail makes the full-size version a bonus rather than the only working state.",
 use=["Social feed assets","Any thumbnail-first distribution"],
 avoid=["Print and out-of-home","Assets viewed only at full size"],
 adv="Communicates at actual viewing size", lim="Limits how much can be said",
 suit="Social feed formats", unsuit="Print and full-size viewing",
 alts=["Carousel formats where more must be said"],
 aps=[("Approving a social asset only at full canvas size","The headline that works at 100 percent vanishes in feed, where it is actually seen","Verification at 15 percent scale before approval")],
 impact="Makes social assets work at real viewing size.", iscore=8, prio=9, conf=0.9, ch="social_media")

P("typography.density_control.white_space_budget.001","Treating white space as a budget","density_control",
 purpose="Make spacing a planned allocation rather than what is left over.",
 visual_effect="A stated unprinted percentage keeps the composition consistent across a campaign.",
 signal="Systematic - every asset in the campaign shares the same restraint.",
 hierarchy_rule="The unprinted percentage is fixed per campaign and applies to every format in it.",
 spacing_rule="State a target unprinted percentage and treat content that exceeds it as over budget.",
 failure="Treating space as leftover, which produces inconsistent density across a campaign's formats.",
 problem="Space is whatever remains after content is placed, so density varies unpredictably across formats.",
 decision="State a target unprinted percentage per campaign and reject content that exceeds the budget.",
 reasoning="Density is a brand signal, and an unmanaged signal varies asset by asset.",
 why="Budgeting makes density a campaign-level decision rather than a per-asset accident.",
 use=["Multi-format campaigns","Brand systems with defined positioning"],
 avoid=["Single-asset work","Formats with mandatory content that exceeds any budget"],
 adv="Consistent density across formats", lim="Forces content cuts on tight formats",
 suit="Multi-format campaigns", unsuit="Single assets and mandatory-content formats",
 alts=["Per-format density targets where formats differ radically in area"],
 aps=[("Letting space be whatever remains after content is placed","Density varies asset by asset and the campaign loses its positioning signal","A stated unprinted percentage applied across every format")],
 impact="Makes density a campaign-level decision.", iscore=7, prio=8, conf=0.87)

P("typography.density_control.legal_text_allocation.001","Allocating space for mandatory text","density_control",
 purpose="Plan for required disclosures before the creative layout is fixed.",
 visual_effect="Reserving the disclosure area first prevents it being squeezed into an unreadable strip.",
 signal="Compliant by design rather than by retrofit.",
 hierarchy_rule="Mandatory text is a declared level with reserved area, placed before creative elements.",
 spacing_rule="Reserved area sized from the disclosure at its minimum legible size, plus 20 percent.",
 failure="Adding disclosures last, which forces them below legible size or over the creative.",
 problem="Mandatory disclosures are added after layout is fixed, forcing them below legible size.",
 decision="Reserve disclosure area first, sized from minimum legible setting plus 20 percent margin.",
 reasoning="Disclosure length is known in advance and its minimum size is fixed by legibility, not by layout.",
 why="Reserving first makes the constraint visible while the layout can still accommodate it.",
 use=["Regulated categories","Beauty, healthcare, food and financial communication"],
 avoid=["Unregulated categories","Assets with no mandatory content"],
 adv="Compliant and legible without retrofit", lim="Reduces creative area from the start",
 suit="Regulated communication", unsuit="Unregulated categories",
 alts=["A dedicated disclosure panel on a separate surface"],
 aps=[("Adding mandatory disclosures after the layout is approved","Forces them below legible size or over the creative, which fails both goals","Disclosure area reserved before creative placement")],
 impact="Keeps disclosures legible without retrofitting.", iscore=7, prio=8, conf=0.88,
 ind=["beauty","healthcare","food_beverage"])

P("typography.density_control.crop_survival_density.001","Density that survives cropping","density_control",
 purpose="Keep a layout working when platforms crop it to other ratios.",
 visual_effect="Content held within the smallest common crop survives every platform reframing.",
 signal="Durable - the asset works wherever it is placed.",
 hierarchy_rule="All hierarchy levels sit inside the intersection of every delivery ratio.",
 spacing_rule="Spacing is calculated against the smallest common area, not the full canvas.",
 failure="Spacing to the full canvas, where cropping removes the margins the hierarchy depended on.",
 problem="Assets are spaced to their full canvas, and platform cropping removes the margins hierarchy needed.",
 decision="Calculate spacing against the intersection of every delivery ratio rather than the full canvas.",
 reasoning="Cropping removes area from the edges, which is exactly where the spacing budget sits.",
 why="Designing to the intersection makes every crop a valid composition.",
 use=["Multi-ratio social delivery","Assets reframed by platforms"],
 avoid=["Single-ratio delivery","Print with a fixed trim"],
 adv="Every crop remains a valid composition", lim="Wastes area at the extremes of each ratio",
 suit="Multi-ratio delivery", unsuit="Single-ratio and print",
 alts=["Separate layouts per ratio where the intersection is too small"],
 aps=[("Spacing an asset to its full canvas before multi-ratio delivery","Cropping removes the margins hierarchy depended on and the layout collapses","Spacing calculated against the smallest common crop")],
 impact="Makes every platform crop a valid composition.", iscore=7, prio=8, conf=0.88, ch="social_media")

# ---------- PREMIUM RESTRAINT ----------
P("typography.premium_restraint.single_weight_discipline.001","Single weight across a premium system","premium_restraint",
 purpose="Build hierarchy from size and space alone, without weight contrast.",
 visual_effect="One weight throughout produces even page colour where rank comes only from size and position.",
 signal="Restrained - the brand does not need emphasis to be heard.",
 hierarchy_rule="Rank established by size and spacing only; no weight change at any level.",
 spacing_rule="Spacing carries the hierarchy work weight would otherwise do, at 2, 1.5 and 1 base units.",
 failure="Adding a bold weight for one call to action, which breaks the restraint the whole system depends on.",
 problem="Premium systems add bold for emphasis, and the single exception undoes the restraint signal.",
 decision="Use one weight throughout a premium system and establish rank through size and spacing only.",
 reasoning="Weight contrast is the loudest available emphasis, and its absence is itself a positioning signal.",
 why="Consistency without exception is what makes restraint read as confidence rather than as omission.",
 use=["Luxury and premium positioning","Fashion, beauty and hospitality identity"],
 avoid=["Conversion-driven layouts","Information-dense and functional content"],
 adv="Restraint reads as confidence", lim="No emphasis available for conversion elements",
 suit="Premium positioning", unsuit="Conversion and information layouts",
 alts=["Two weights where a conversion element genuinely requires emphasis"],
 aps=[("Adding a bold weight for one call to action in a single-weight system","The single exception undoes the restraint the whole system was built on","Emphasis carried by size and spacing instead")],
 impact="Makes restraint read as confidence.", iscore=8, prio=8, conf=0.88, **LUX)

P("typography.premium_restraint.size_contrast_ratio.001","Contained size contrast for premium","premium_restraint",
 purpose="Establish hierarchy without the dramatic scale jumps that read as promotional.",
 visual_effect="A contrast ratio near 2 to 1 gives clear rank without the shout of 5 to 1.",
 signal="Composed - the hierarchy is present without being aggressive.",
 hierarchy_rule="The largest level is no more than 2.5 times the body size in a premium system.",
 spacing_rule="Spacing compensates for the reduced size contrast at 2.5, 1.5 and 1 base units.",
 failure="Using a 5 to 1 size ratio in a premium system, which reads as a discount announcement.",
 problem="Premium layouts use promotional size ratios, which contradicts the positioning the copy claims.",
 decision="Cap the size ratio at 2.5 to 1 in premium systems and compensate with generous spacing.",
 reasoning="Extreme size contrast is the visual grammar of urgency, which premium positioning explicitly rejects.",
 why="A contained ratio keeps rank legible while staying outside the promotional register.",
 use=["Premium and luxury positioning","Editorial and brand-led communication"],
 avoid=["Promotional and conversion assets","Formats requiring thumbnail legibility"],
 adv="Rank without promotional grammar", lim="Weaker legibility at thumbnail scale",
 suit="Premium positioning", unsuit="Promotional and thumbnail-first formats",
 alts=["Higher contrast where thumbnail legibility outranks positioning"],
 aps=[("Using a 5 to 1 size ratio in a luxury campaign","The layout reads as a discount announcement regardless of the copy","A ratio capped at 2.5 to 1 with generous spacing")],
 impact="Keeps rank legible outside the promotional register.", iscore=7, prio=8, conf=0.88, **LUX)

P("typography.premium_restraint.no_emphasis_devices.001","Withholding emphasis devices","premium_restraint",
 purpose="Keep underline, italic, colour and caps out of a premium text setting.",
 visual_effect="A page with no emphasis devices reads as even, with attention directed by position alone.",
 signal="Assured - nothing on the page is competing for attention.",
 hierarchy_rule="Emphasis within text is prohibited; important content is promoted to its own level instead.",
 spacing_rule="Promoted content receives its own gap rather than inline emphasis.",
 failure="Underlining a phrase for emphasis, which introduces a device the rest of the system avoids.",
 problem="Premium text settings use inline emphasis devices, which contradict the restraint of the surrounding system.",
 decision="Prohibit inline emphasis in premium text and promote important content to its own spaced level.",
 reasoning="Inline emphasis is a device of persuasion, and its presence signals the register the brand is avoiding.",
 why="Promotion by position achieves the same prominence within the system's own grammar.",
 use=["Premium and luxury text settings","Brand-led editorial"],
 avoid=["Functional and instructional content","Conversion-focused copy"],
 adv="Even page with no competing devices", lim="Requires restructuring copy rather than marking it",
 suit="Premium editorial", unsuit="Functional and conversion copy",
 alts=["Italic only, where a single restrained device is acceptable"],
 aps=[("Underlining a phrase in a premium text setting","Introduces a persuasion device the rest of the system carefully avoids","Promoting the phrase to its own spaced level")],
 impact="Keeps the premium register intact within text.", iscore=7, prio=8, conf=0.87, **LUX)

P("typography.premium_restraint.alignment_singularity.001","One alignment across a premium layout","premium_restraint",
 purpose="Keep a composition calm by using a single alignment throughout.",
 visual_effect="Every element on one alignment produces a single strong edge that organises the whole layout.",
 signal="Ordered - the composition has one logic rather than several.",
 hierarchy_rule="All levels share one alignment; rank is carried by size and spacing rather than by position.",
 spacing_rule="The shared alignment edge is the reference for all horizontal spacing decisions.",
 failure="Centring one element in a left-aligned layout, which breaks the edge the layout was organised around.",
 problem="Premium layouts mix alignments for variety, which breaks the single edge that organises the composition.",
 decision="Use one alignment for every element in a premium layout, without exception.",
 reasoning="A shared edge is the strongest available organising device and it is destroyed by any exception.",
 why="Singularity of alignment produces calm, which is the core premium signal.",
 use=["Premium and luxury layouts","Minimal and editorial compositions"],
 avoid=["Dynamic and promotional layouts","Grid systems using deliberate alignment variation"],
 adv="Calm composition with one clear logic", lim="Less dynamic than mixed alignment",
 suit="Premium and minimal layouts", unsuit="Dynamic promotional compositions",
 alts=["Two alignments on a strict grid where variety is needed"],
 aps=[("Centring one element within a left-aligned premium layout","Breaks the shared edge that organises the composition and the calm collapses","Every element on the same alignment")],
 impact="Produces the calm premium positioning depends on.", iscore=7, prio=8, conf=0.88, **LUX)

P("typography.premium_restraint.slow_reading_pace.001","Setting a slow reading pace","premium_restraint",
 purpose="Make the reader move through the asset slowly rather than scanning it.",
 visual_effect="Short measures, generous leading and few elements produce a deliberately unhurried read.",
 signal="Unhurried - the brand assumes the reader has time.",
 hierarchy_rule="Two levels maximum, with a large gap between them so each is read separately.",
 spacing_rule="Measure held under 45 characters with leading at 1.7 or above.",
 failure="Combining a slow pace with a scannable dense layout, which contradicts the pace it sets.",
 problem="Premium assets set slow-pace typography inside dense layouts, so the two signals contradict each other.",
 decision="Hold the measure under 45 characters at 1.7 leading with no more than two levels.",
 reasoning="Reading pace is set by measure and leading together, and density overrides both.",
 why="Keeping all three consistent lets the asset actually set the pace it intends.",
 use=["Luxury brand communication","Long-consideration purchase categories"],
 avoid=["Conversion assets","Feed and thumbnail viewing contexts"],
 adv="Reader engages rather than scans", lim="Carries very little information",
 suit="Luxury and considered purchase", unsuit="Conversion and feed contexts",
 alts=["Standard pace where the viewing context is a scanning one"],
 aps=[("Applying slow-pace leading inside a dense multi-element layout","Density overrides the pace signal, so the two contradict each other","Measure, leading and element count all set for the same pace")],
 impact="Lets the asset set the reading pace it intends.", iscore=7, prio=8, conf=0.86, **LUX)

P("typography.premium_restraint.detail_at_small_scale.001","Investing detail at the smallest scale","premium_restraint",
 purpose="Signal quality through the elements nobody is required to notice.",
 visual_effect="Correct small caps, proper figures and true quotation marks read as care at close range.",
 signal="Made properly - the parts nobody checks were done correctly.",
 hierarchy_rule="The smallest levels receive the same specification detail as the largest.",
 spacing_rule="Caption and label levels carry their own tracking and leading values rather than inheriting body values.",
 failure="Specifying display carefully and leaving caption levels at software defaults.",
 problem="Type specifications cover display levels and leave small levels at software defaults, which shows at close range.",
 decision="Give caption and label levels their own tracking and leading values rather than inheriting body values.",
 reasoning="Premium purchases are examined at close range, where default settings become visible as neglect.",
 why="Specifying the small levels is what makes quality legible where the product is actually inspected.",
 use=["Premium packaging and collateral","Products examined at close range"],
 avoid=["Distance-viewed formats","Low-cost fast-turnaround production"],
 adv="Quality legible at inspection range", lim="Adds specification and production time",
 suit="Premium packaging", unsuit="Distance formats and fast production",
 alts=["Display-level specification only, where the asset is never inspected closely"],
 aps=[("Specifying display levels carefully and leaving captions at software defaults","Default settings become visible as neglect at the range premium products are inspected","Every level given explicit tracking and leading values")],
 impact="Makes quality legible at inspection range.", iscore=7, prio=8, conf=0.87, **LUX)

flush()
