# -*- coding: utf-8 -*-
"""Batch 4A — font psychology."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_typo_lib import TYPO, flush

LUX = dict(pos=["premium","luxury"])

# ═══════════ SERIF AUTHORITY ═══════════
TYPO("typography.serif_authority.high_contrast_heritage.001","High contrast serif for heritage claims","serif_authority",
 "Assert institutional longevity before a word of copy is read.",
 "Thick-thin stroke modulation creates optical texture that reads as engraved rather than drawn.",
 "Established, tested by time, accountable — the letterforms of institutions rather than of startups.",
 "Serif carries the headline; every supporting level drops to a neutral sans so the serif keeps its authority.",
 "Leading at 1.15 to 1.25 of type size; tracking left at zero, since added tracking destroys the stroke rhythm.",
 "Set below 16 points the thin strokes break up on screen and the face reads as damaged rather than refined.",
 "Heritage brands are set in contemporary geometric sans, so the letterforms contradict the longevity being claimed.",
 "Use a high-contrast serif for the headline level and drop every supporting level to a neutral sans.",
 "Serif forms carry the visual memory of printing and institutions, and that association arrives before reading begins.",
 "Letterform history does the positioning work at no cost in words or space.",
 ["Heritage, luxury and authority positioning","Print and large-format digital"],
 ["Technology and disruption positioning","Interface text below 16 points"],
 "Instant heritage signal with no copy cost","Conservative, and fragile at small sizes",
 "Luxury and heritage brand work","Technology, interface and small-size settings",
 ["Low-contrast serif where small sizes are unavoidable"],
 [("Geometric sans applied to a brand claiming a century of history","The letterforms contradict the claim, so the copy argues against its own typesetting","A serif whose contrast and proportion match the era being claimed")],
 "Positions the brand before the copy is read.",8,9,0.89,
 viet="Confirm the serif carries drawn Vietnamese diacritics rather than composed fallbacks; thin strokes make composed marks obvious.",
 **LUX)

TYPO("typography.serif_authority.transitional_trust.001","Transitional serif for professional trust","serif_authority",
 "Signal competence and neutrality where authority must not read as grandeur.",
 "Moderate stroke contrast and upright axis produce even colour on the page with no ornamental flourish.",
 "Professional, impartial, unexcitable — the voice of a report rather than a manifesto.",
 "Serif at headline and body both, with weight rather than face change separating the levels.",
 "Leading at 1.4 to 1.5 for body; tracking at zero, with word spacing left at the face's own default.",
 "Applied to youth or lifestyle brands it reads as institutional and distant, which suppresses engagement.",
 "Professional service brands adopt display serifs that read as grandiose rather than competent.",
 "Set both headline and body in one transitional serif and separate levels by weight rather than by changing face.",
 "Trust in professional categories comes from evident restraint, and a single face across levels demonstrates it.",
 "One face across the hierarchy removes the impression of decoration, leaving only the argument.",
 ["Professional services, finance and healthcare","Long-form and report communication"],
 ["Youth and lifestyle categories","Brands positioned on disruption"],
 "Competence without grandeur","Reads as institutional and distant to younger audiences",
 "Professional and report communication","Youth and lifestyle brands",
 ["Humanist sans where warmth must accompany competence"],
 [("Using a high-contrast display serif for a professional services brand","Reads as grandiose rather than competent, which is the wrong claim for the category","A transitional serif with moderate contrast used across the hierarchy")],
 "Communicates competence without grandeur.",7,8,0.87)

TYPO("typography.serif_authority.slab_confidence.001","Slab serif for assertive confidence","serif_authority",
 "Project durability and directness where refinement would read as weakness.",
 "Heavy rectangular serifs give each letter a bracketed base, producing a blocky mass at display size.",
 "Solid, unsubtle, dependable — a claim of substance rather than of taste.",
 "Slab at headline only; body drops to a neutral sans because slab body text fatigues the reader.",
 "Tracking reduced by 10 to 20 units at display size, since slab serifs already fill inter-letter space.",
 "Used at body size the heavy serifs close counters and reading speed drops sharply.",
 "Categories selling durability adopt refined faces, which visually contradicts the robustness being claimed.",
 "Use a slab serif at headline level only, reducing tracking by 10 to 20 units, with body set in a neutral sans.",
 "Weight and squared terminals are read as physical mass, which is the correct signal for durability claims.",
 "Confining slab to headline captures the signal without the reading cost it imposes at text size.",
 ["Trade, industrial and outdoor categories","Durability and robustness claims"],
 ["Luxury and delicacy positioning","Long-form body text"],
 "Strong durability signal","Fatiguing at text size and unrefined at any size",
 "Industrial and trade categories","Luxury and long-form reading",
 ["Bold neutral sans where slab reads as too rustic"],
 [("Setting body copy in a slab serif for brand consistency","Heavy serifs close the counters and reading speed drops sharply","Slab confined to headline, body set in a neutral sans")],
 "Signals durability where refinement would misfire.",7,7,0.85)

TYPO("typography.serif_authority.old_style_craft.001","Old style serif for craft provenance","serif_authority",
 "Claim handmade origin where the product's value is in how it was made.",
 "Angled stress and irregular letterfit leave visible traces of the hand, producing warm uneven colour.",
 "Made rather than manufactured — the signal of a workshop rather than a production line.",
 "Old style at headline and pull quotes; body in a humanist sans to keep reading comfortable.",
 "Leading at 1.45 to 1.55, since the irregular rhythm needs more vertical air than a modern face.",
 "Applied to technology or clinical categories it reads as nostalgic and undermines precision claims.",
 "Craft brands use clean contemporary faces that make handmade production look like factory output.",
 "Use an old style serif for headline and pull quotes with leading at 1.45 to 1.55, keeping body in a humanist sans.",
 "Irregularity is evidence of the hand, and evidence of the hand is what a craft claim rests on.",
 "The visible unevenness of old style forms corroborates a provenance claim that clean faces contradict.",
 ["Craft, artisanal and provenance-led brands","Food, spirits and handmade goods"],
 ["Technology and clinical categories","Precision and engineering claims"],
 "Corroborates a craft claim visually","Reads as nostalgic and imprecise in technical categories",
 "Craft and provenance categories","Technology and precision categories",
 ["Transitional serif where craft must read as professional rather than rustic"],
 [("Using a clean geometric face for an artisanal producer","Makes handmade production look like factory output, contradicting the premium being charged","An old style serif whose irregularity corroborates the craft claim")],
 "Corroborates craft provenance visually.",7,8,0.86)

TYPO("typography.serif_authority.editorial_didone.001","Didone for fashion authority","serif_authority",
 "Assert taste-making authority in categories where refinement is the product.",
 "Extreme thick-thin contrast with hairline serifs produces high optical sparkle at display size.",
 "Cultivated, exacting, above the everyday — the letterforms of fashion mastheads.",
 "Didone at display only, always paired with a neutral sans for every other level.",
 "Tracking increased by 20 to 40 units at large sizes so hairlines are not crowded; never tracked at text size.",
 "At any size below 24 points the hairlines vanish on screen and the word reads as broken.",
 "Fashion brands apply Didone across all levels, so hairlines disappear at text size and the setting looks defective.",
 "Restrict Didone to display sizes of 24 points and above, tracked 20 to 40 units, with all other levels in a neutral sans.",
 "Hairline strokes require physical size to survive rendering, and using them smaller destroys the refinement they signal.",
 "Confining the face to display preserves its authority while removing the size at which it fails.",
 ["Fashion, beauty and cultural authority positioning","Display and masthead applications"],
 ["Any text below 24 points","Small-screen interface typography"],
 "Highest available refinement signal","Fails completely below display size",
 "Fashion and beauty display typography","Interface and small-size settings",
 ["Transitional serif where the same tone is needed at text size"],
 [("Setting body copy in a Didone for brand consistency","Hairlines vanish at text size and the setting reads as broken rather than refined","Didone confined to 24 points and above, body in a neutral sans")],
 "Asserts taste authority at display scale.",8,8,0.88,
 ind=["fashion","beauty"], **LUX)

TYPO("typography.serif_authority.serif_at_small_size.001","Choosing serif for small-size legibility","serif_authority",
 "Retain serif tone where the setting is genuinely small.",
 "Low stroke contrast with a large x-height keeps counters open at reduced size.",
 "Traditional but practical — heritage tone without the fragility of a display serif.",
 "One serif across all levels; hierarchy carried by size and weight rather than by face change.",
 "Leading at 1.5 minimum below 14 points; tracking increased by 5 to 10 units to keep counters open.",
 "Choosing a high-contrast serif instead produces broken thin strokes that read as a rendering fault.",
 "Brands wanting serif tone in small print pick display serifs, which disintegrate below 14 points.",
 "Choose a low-contrast serif with a large x-height for settings under 14 points, tracked 5 to 10 units looser.",
 "Legibility at small size depends on counter openness and stroke evenness, not on the presence of serifs.",
 "A low-contrast serif keeps the historical association while surviving the size the setting requires.",
 ["Small print, captions and interface serif settings","Editorial with dense text"],
 ["Display and masthead applications","Settings where maximum refinement is required"],
 "Serif tone that survives small size","Less refined than a display serif at large size",
 "Small-size serif settings","Display typography",
 ["Neutral sans where legibility outranks tone entirely"],
 [("Using a display serif for footnotes and captions","Thin strokes break below 14 points and the setting reads as a rendering fault","A low-contrast serif with a large x-height, tracked slightly looser")],
 "Keeps serif tone legible at small size.",7,8,0.88)

# ═══════════ MODERN SANS ACCESSIBILITY ═══════════
TYPO("typography.modern_sans.neutral_credibility.001","Neutral grotesque for credibility","modern_sans",
 "Let content carry the brand where personality would read as compensation.",
 "Even stroke weight and closed apertures produce uniform grey on the page with no optical incident.",
 "Competent and current — a brand confident enough not to decorate its own words.",
 "Three levels separated by weight steps rather than by size alone, since the face itself contributes no contrast.",
 "Leading at 1.5 for body; tracking at zero for text, reduced 10 to 20 units at display size.",
 "Applied to craft or heritage brands it reads as corporate and strips the provenance being claimed.",
 "Trust-dependent brands choose expressive display faces, which draw attention to the typesetting over the evidence.",
 "Use a neutral grotesque across all levels and separate the three levels by weight steps rather than by size alone.",
 "Expressive letterforms in a credibility category read as decoration compensating for weak substance.",
 "Neutral forms leave the content and structure to carry the brand, which ages far more slowly than a face does.",
 ["Technology, clinical and efficacy-led categories","Credibility outranks personality"],
 ["Heritage and craft positioning","Categories where personality is the differentiator"],
 "Credible and slow to date","Low distinctiveness from type alone",
 "Technology and clinical categories","Heritage and craft brands",
 ["Humanist sans where warmth is required alongside credibility"],
 [("An expressive display face used for a clinical efficacy claim","Draws attention to styling and away from evidence, which reads as compensating","A neutral grotesque, with distinctiveness carried by layout")],
 "Puts credibility ahead of typographic personality.",8,8,0.88,
 ind=["technology","beauty"])

TYPO("typography.modern_sans.large_x_height_screen.001","Large x-height for screen legibility","modern_sans",
 "Maximise reading speed on screens at typical viewing distance.",
 "A tall x-height relative to cap height fills the line visually and keeps counters open at small size.",
 "Practical and unfussy — a brand that prioritises being understood.",
 "Hierarchy by weight and colour rather than by size, since a tall x-height compresses apparent size differences.",
 "Leading at 1.5 to 1.6 on screen; word spacing slightly tightened to compensate for the wider letterforms.",
 "At display size the tall x-height flattens the word shape, making headlines look inert.",
 "Print-optimised faces are carried onto screen, where small x-heights reduce reading speed measurably.",
 "Choose a face with an x-height at 52 percent of cap height or more for any screen body text, set at 1.5 to 1.6 leading.",
 "Word-shape recognition depends on x-height at small sizes, which is why print faces underperform on screen.",
 "Larger x-height preserves counter openness at the sizes screens actually use.",
 ["Screen body text and interface typography","Long-form digital reading"],
 ["Display and masthead settings","Print at generous size"],
 "Measurably faster screen reading","Flat and inert at display size",
 "Screen body and interface text","Display and print headlines",
 ["A display cut of the same family for headline levels"],
 [("Using a print-optimised small x-height face for screen body text","Counters close at screen sizes and reading speed drops measurably","A face with x-height at 52 percent of cap height or more")],
 "Raises reading speed on screen.",8,8,0.9,
 ch="website")

TYPO("typography.modern_sans.weight_range_system.001","Weight range as a hierarchy system","modern_sans",
 "Build a full hierarchy from one family without changing face.",
 "Consistent letterforms across weights keep the page unified while weight alone separates rank.",
 "Systematic and disciplined — a brand with one voice at several volumes.",
 "Three levels using weights at least two steps apart, such as regular, semibold and black, never adjacent weights.",
 "Leading constant across levels; tracking reduced 10 units at the heaviest weight to prevent crowding.",
 "Using adjacent weights produces differences too small to rank, so the hierarchy disappears.",
 "Hierarchies are built by mixing faces, producing pages that read as several brands at once.",
 "Build the hierarchy from one family using weights at least two steps apart, never adjacent weights.",
 "Rank is perceived from contrast, and adjacent weights sit below the threshold at which a reader can rank them.",
 "One family with wide weight separation gives unambiguous rank and a unified page simultaneously.",
 ["Design systems and multi-asset campaigns","Brands with one licensed family"],
 ["Editorial work needing tonal variety","Brands whose identity depends on a face pairing"],
 "Unified voice with clear rank","Less tonal variety than a pairing",
 "Design systems and campaign sets","Editorial with tonal range",
 ["Serif and sans pairing where tonal contrast is required"],
 [("Separating levels using adjacent weights such as regular and medium","The difference falls below the ranking threshold, so hierarchy is not perceived","Weights at least two steps apart between levels")],
 "Produces unambiguous rank within one family.",8,8,0.89)

TYPO("typography.modern_sans.condensed_density.001","Condensed sans for dense information","modern_sans",
 "Fit more information per line without reducing type size.",
 "Narrowed letterforms increase characters per line while keeping cap height and therefore apparent size.",
 "Efficient and urgent — the voice of schedules, scoreboards and transit.",
 "Condensed at display and labels only; body stays at normal width because condensed body fatigues quickly.",
 "Tracking increased 10 to 20 units to compensate for the tightened counters; leading unchanged.",
 "Used for extended body text the narrow counters cause fixation crowding and reading slows.",
 "Dense layouts reduce type size to fit copy, which pushes text below the legibility floor.",
 "Use a condensed cut for display and labels while keeping body at normal width, tracking condensed text 10 to 20 units looser.",
 "Reducing width preserves apparent size, whereas reducing size sacrifices legibility to fit the same copy.",
 "Keeping body at normal width confines the fatigue cost to the levels that are read briefly.",
 ["Information-dense layouts and schedules","Transit, sports and event communication"],
 ["Long-form reading","Luxury positioning where density reads as cheap"],
 "More content at legible size","Fatiguing for extended reading",
 "Dense information and labels","Long-form and luxury settings",
 ["Reduced copy at normal width where density can be avoided"],
 [("Setting extended body copy in a condensed face to fit the space","Narrow counters cause fixation crowding and reading slows measurably","Body kept at normal width, with copy reduced instead")],
 "Fits more content without dropping below the legibility floor.",7,7,0.86)

TYPO("typography.modern_sans.all_caps_restraint.001","All caps discipline","modern_sans",
 "Use capitals for emphasis without destroying readability.",
 "Uniform cap height removes ascender and descender variation, flattening word shape into a rectangle.",
 "Formal and declarative — a raised voice rather than a spoken one.",
 "All caps confined to labels, eyebrows and single-word emphasis; never for a full sentence over four words.",
 "Tracking increased 50 to 100 units, since capitals are drawn for tighter fit than their default spacing provides.",
 "Set as a paragraph, capitals remove word-shape cues and reading speed drops by roughly a third.",
 "Capitals are used for headlines and sub-headlines, where the loss of word shape slows reading significantly.",
 "Confine all caps to four words or fewer and increase tracking by 50 to 100 units whenever they are used.",
 "Word recognition relies on ascender and descender silhouette, which capitals remove entirely.",
 "A four-word ceiling keeps capitals in the register where their emphasis outweighs their reading cost.",
 ["Labels, eyebrows and short emphasis","Formal and declarative tone"],
 ["Sentences and paragraphs","Vietnamese text where diacritics crowd the cap line"],
 "Strong formal emphasis","Reading speed drops by about a third",
 "Short labels and eyebrows","Sentences and long-form text",
 ["Small caps where formality is needed at greater length"],
 [("Setting a full sentence headline in capitals","Removes word-shape cues, dropping reading speed by roughly a third","Sentence case, with capitals reserved for a four-word eyebrow")],
 "Preserves readability while using capitals for emphasis.",8,8,0.9,
 viet="Capitals crowd Vietnamese tone marks against the cap line; either add 20 percent leading or avoid capitals for Vietnamese headlines.")

TYPO("typography.modern_sans.optical_size_matching.001","Optical size matching","modern_sans",
 "Keep a family looking consistent across the range of sizes it is used at.",
 "Display cuts have tighter spacing and finer detail; text cuts are wider with sturdier strokes.",
 "Precise and considered — a level of care most viewers feel without identifying.",
 "Display cut above 32 points, text cut below 18, with the intermediate range using whichever is closer.",
 "Tracking is built into each cut, so no manual tracking should be applied when the correct cut is used.",
 "Using the text cut at display size leaves headlines looking loose and slightly amateur.",
 "One cut of a family is used at every size, so headlines look loose or body looks cramped.",
 "Use the display cut above 32 points and the text cut below 18, applying no manual tracking to either.",
 "Optical sizes exist because letterform proportions that work at text size look wrong enlarged.",
 "Choosing the right cut removes the need for manual tracking corrections that never quite work.",
 ["Families offering optical size cuts","Design systems spanning display and text"],
 ["Single-cut families","Settings using only one size range"],
 "Consistency across the whole size range","Requires a family with optical cuts and more licensing",
 "Multi-size design systems","Single-size applications",
 ["Manual tracking adjustment where no optical cuts exist"],
 [("Using one cut at every size and correcting with manual tracking","Manual tracking cannot fix stroke weight and proportion, so headlines still read as amateur","The display cut above 32 points and text cut below 18")],
 "Keeps a family consistent across sizes.",7,7,0.87)

# ═══════════ DISPLAY TYPOGRAPHY EMOTION ═══════════
TYPO("typography.display_emotion.scale_as_volume.001","Display scale as volume","display_emotion",
 "Set emotional intensity through size rather than through added ornament.",
 "Type occupying a large share of the frame is read as loudness before the words are decoded.",
 "Urgent or confident depending on context — scale states how strongly the brand is speaking.",
 "One display level only; a second element at similar scale halves the perceived volume of both.",
 "Tracking reduced 20 to 40 units above 60 points, since default spacing looks loose at display scale.",
 "Two elements at similar display scale cancel each other and the frame reads as busy rather than loud.",
 "Emphasis is attempted by adding colour, rules and effects, which produces noise rather than volume.",
 "Set exactly one element at display scale with tracking reduced 20 to 40 units above 60 points.",
 "Perceived loudness comes from relative dominance, so a second element at similar scale halves it.",
 "Scale is the only emphasis device that costs no additional elements.",
 ["Statement-led assets","Awareness and announcement objectives"],
 ["Information-dense layouts","Assets requiring several equal messages"],
 "Volume with no added elements","Only one message can be loud",
 "Statement and announcement assets","Multi-message and dense layouts",
 ["Weight contrast where two messages must both carry"],
 [("Adding colour and rules to increase emphasis alongside large type","Produces noise that lowers perceived volume rather than raising it","One element at display scale with everything else held quiet")],
 "Creates volume without adding elements.",8,8,0.88)

TYPO("typography.display_emotion.tight_tracking_intensity.001","Tight tracking for intensity","display_emotion",
 "Compress a display line so it reads as a single compact object.",
 "Reduced letter spacing merges characters into one continuous mass with a hard silhouette.",
 "Deliberate and forceful — the visual equivalent of speaking through clenched teeth.",
 "Applies at display level only; body text tracked this tightly becomes unreadable.",
 "Tracking reduced 30 to 60 units above 48 points, stopping before counters begin to close.",
 "Tracked past the point where counters close, the word becomes an unreadable dark band.",
 "Display lines are set at default tracking, which looks loose and undermines the intended force.",
 "Reduce tracking 30 to 60 units on display lines above 48 points, stopping before counters begin to close.",
 "Default spacing is optimised for text size, so it always reads loose when enlarged.",
 "Tightening to the point just before counter closure gives maximum density with legibility intact.",
 ["Display headlines above 48 points","Assertive and urgent tone"],
 ["Body and text-size settings","Delicate or airy brand tone"],
 "Maximum display density and force","Illegible if pushed past counter closure",
 "Assertive display typography","Body text and delicate brand tone",
 ["Default tracking where the tone should read as open"],
 [("Applying display tracking values to body text for consistency","Counters close at text size and the paragraph becomes an unreadable band","Tight tracking confined to display sizes above 48 points")],
 "Gives display lines compact force.",7,8,0.87)

TYPO("typography.display_emotion.loose_tracking_calm.001","Loose tracking for calm","display_emotion",
 "Slow the reading of a short line so it registers as deliberate.",
 "Increased letter spacing separates characters, producing an airy line with visible internal rhythm.",
 "Unhurried and composed — a brand with no need to compete for attention.",
 "Loose tracking at display and eyebrow levels only; body tracked this way loses word cohesion.",
 "Tracking increased 80 to 200 units, with word spacing increased proportionally so words stay grouped.",
 "Tracked loosely without increasing word spacing, letters and words become indistinguishable groups.",
 "Luxury brands track headlines loosely but leave word spacing unchanged, so words visually merge.",
 "Increase tracking 80 to 200 units on short display lines and increase word spacing proportionally.",
 "Letter spacing and word spacing must scale together, or the gap between words stops being larger than between letters.",
 "Proportional word spacing preserves word boundaries at any tracking value.",
 ["Luxury and premium display lines","Short eyebrows and wordmarks"],
 ["Body text of any length","Urgent or promotional tone"],
 "Calm, premium, deliberate reading","Costs horizontal space and slows reading",
 "Luxury display typography","Body text and promotional urgency",
 ["Default tracking where space is constrained"],
 [("Increasing letter tracking without increasing word spacing","Word gaps stop being larger than letter gaps and the line reads as one string","Word spacing increased proportionally with tracking")],
 "Makes a short line read as deliberate.",7,8,0.88,
 **LUX)

TYPO("typography.display_emotion.stacked_lockup.001","Stacked display lockup","display_emotion",
 "Turn a multi-word line into one designed object.",
 "Words stacked on tight leading form a rectangular block read as a single shape before as language.",
 "Designed and intentional — a statement built rather than typed.",
 "The stack is one hierarchy level; nothing else in the frame may share its scale.",
 "Leading reduced to 0.85 to 0.95 of type size, with each line optically aligned to the same left edge.",
 "Leading left at default leaves visible gaps between lines and the stack reads as three separate lines.",
 "Multi-word headlines are set on default leading, so they read as a paragraph rather than a mark.",
 "Stack display lines at 0.85 to 0.95 leading with each line optically aligned to a common left edge.",
 "Below single leading the lines fuse into one block, which is what converts type into an object.",
 "Optical alignment prevents the ragged left edge that destroys the block reading.",
 ["Display headlines of two to four words","Poster and cover applications"],
 ["Body text and long headlines","Vietnamese text where tight leading collides diacritics"],
 "Headline reads as a designed mark","Only works for very short copy",
 "Short display headlines","Long copy and Vietnamese settings",
 ["Single-line setting where the copy will not stack"],
 [("Using default leading on a stacked display headline","Lines separate visually and the stack reads as a paragraph rather than a mark","Leading reduced to 0.85 to 0.95 with optical left alignment")],
 "Converts a headline into a designed object.",7,7,0.86,
 viet="Vietnamese stacked marks collide below 1.1 leading; stacked lockups generally cannot be used for Vietnamese headlines.")

TYPO("typography.display_emotion.mixed_scale_drama.001","Mixed scale within one line","display_emotion",
 "Create emphasis inside a headline without changing face or colour.",
 "One word set two to three times larger than its neighbours creates a visible peak in the line.",
 "Expressive and voiced — the typographic equivalent of stressing a word aloud.",
 "The enlarged word carries the primary level; the remaining words drop to secondary within the same line.",
 "Baselines aligned optically rather than mathematically, since differing sizes rarely sit correctly on a shared baseline.",
 "Aligning mixed sizes to a mathematical baseline leaves the smaller words visually floating.",
 "Emphasis inside headlines is added with colour or italics, which introduces a second system.",
 "Set the emphasised word two to three times the size of its neighbours and align the baselines optically.",
 "Scale contrast within a line reproduces spoken stress, which needs no second system to be understood.",
 "Optical baseline alignment is required because mixed sizes never sit correctly on a shared mathematical baseline.",
 ["Expressive display headlines","Brands with a spoken, voiced tone"],
 ["Formal and institutional tone","Information-dense settings"],
 "Voiced emphasis with one system","Informal, and unsuitable for institutional tone",
 "Expressive display typography","Formal and institutional communication",
 ["Weight contrast where scale variation is too informal"],
 [("Aligning mixed-size words to a shared mathematical baseline","Smaller words appear to float, which reads as an error rather than a decision","Baselines aligned optically by eye")],
 "Reproduces spoken stress typographically.",7,7,0.84)

TYPO("typography.display_emotion.negative_leading_impact.001","Negative leading for compression","display_emotion",
 "Compress a multi-line display block into maximum density.",
 "Lines set closer than their type size interlock ascenders and descenders into a single dense mass.",
 "Intense and compressed — energy held under pressure.",
 "Only the display level takes negative leading; all other levels use normal leading for contrast.",
 "Leading at 0.8 to 0.9 of type size, with ascenders and descenders checked line by line for collision.",
 "Applied without checking collisions, descenders strike the following line's ascenders and the block reads as broken.",
 "Compressed display blocks are set without collision checking, so letterforms clash unpredictably.",
 "Set display leading at 0.8 to 0.9 of type size and check every line pair for ascender and descender collision.",
 "Interlocking lines produce density, but only when the specific letter combinations are verified.",
 "Line-by-line checking is unavoidable because collisions depend on the actual words, not on the setting.",
 ["Poster and cover display blocks","Latin-script display work"],
 ["Any Vietnamese text","Body text and long copy"],
 "Maximum display density","Requires manual collision checking on every line",
 "Latin display typography","Vietnamese and body text",
 ["Normal leading where the copy cannot be checked manually"],
 [("Applying negative leading without checking letter collisions","Descenders strike the following line and the block reads as damaged","Every line pair checked for collision after setting")],
 "Achieves display density without collision.",7,7,0.85,
 viet="Negative leading is unusable for Vietnamese; stacked tone marks collide with the line above at any leading below 1.1.")

# ═══════════ HUMANIST TYPOGRAPHY ═══════════
TYPO("typography.humanist.calligraphic_warmth.001","Humanist sans for approachable warmth","humanist",
 "Add human warmth to a sans setting without sacrificing clarity.",
 "Varied stroke weight and open apertures derived from handwriting give letters visible individuality.",
 "Approachable and human — a brand speaking rather than announcing.",
 "Humanist across all levels, with weight carrying hierarchy so the warmth persists at every rank.",
 "Leading at 1.5 to 1.6; tracking at zero, since humanist letterfit is already generous.",
 "Applied to precision or clinical categories the warmth reads as imprecision.",
 "Service and care brands adopt neutral grotesques, which read as institutional and cold.",
 "Use a humanist sans across all levels with weight carrying hierarchy and leading at 1.5 to 1.6.",
 "Open apertures and calligraphic variation are read as human origin, which is what warmth actually is optically.",
 "Keeping one humanist face at every level means the warmth is not lost at supporting ranks.",
 ["Care, education, hospitality and service categories","Brands positioned on human contact"],
 ["Precision and engineering categories","Luxury built on formal distance"],
 "Warmth without loss of clarity","Reads as imprecise in technical categories",
 "Service and care categories","Precision and formal luxury",
 ["Neutral grotesque where precision outranks warmth"],
 [("Using a neutral grotesque for a care or education brand","Reads as institutional and cold, which contradicts the service promise","A humanist sans whose open apertures signal human origin")],
 "Adds warmth without reducing clarity.",8,8,0.88,
 ind=["hospitality","healthcare"])

TYPO("typography.humanist.open_aperture_legibility.001","Open apertures for difficult reading conditions","humanist",
 "Maximise character distinction where reading conditions are poor.",
 "Wide apertures on c, e, s and a keep those letters distinguishable at small size and low contrast.",
 "Considerate — a brand that has thought about who is reading and in what conditions.",
 "One humanist face across all levels; hierarchy by weight, never by switching to a closed-aperture face.",
 "Leading at 1.6 minimum for body; tracking increased 5 to 10 units under poor lighting conditions.",
 "A closed-aperture grotesque in the same setting causes c and e to be confused at small size.",
 "Accessibility settings use geometric faces, whose closed apertures confuse similar characters.",
 "Choose a humanist face with open apertures for any setting read at small size or in poor conditions.",
 "Character confusion between c, e, s and a is the dominant small-size legibility failure, and aperture width governs it.",
 "Open apertures keep those characters distinct where stroke weight alone cannot.",
 ["Accessibility-sensitive settings","Older audiences and low-light reading"],
 ["Display typography where aperture is irrelevant","Brands built on geometric identity"],
 "Measurably fewer character confusions","Less distinctive than a geometric face",
 "Accessibility and small-size settings","Display and geometric brand systems",
 ["Larger type size where the face cannot be changed"],
 [("Using a geometric face for accessibility-focused body text","Closed apertures cause c and e confusion at small size, which is the main legibility failure","A humanist face with open apertures")],
 "Reduces character confusion in hard conditions.",8,9,0.9,
 ind="healthcare")

TYPO("typography.humanist.book_setting_rhythm.001","Humanist rhythm for long-form reading","humanist",
 "Sustain reading across long text without fatigue.",
 "Irregular letterfit derived from the hand produces varied word shapes that the eye tracks easily.",
 "Unhurried and readable — a brand comfortable with a reader's time.",
 "Two levels only in long-form: heading and body, with hierarchy by size rather than by weight.",
 "Leading at 1.5 to 1.7 with measure held to 60 to 75 characters per line.",
 "Measures beyond 80 characters cause line-return errors regardless of how good the face is.",
 "Long-form is set to fill the available column, producing measures far beyond comfortable reading.",
 "Set long-form in a humanist face with measure held to 60 to 75 characters and leading at 1.5 to 1.7.",
 "Reading fatigue is driven by line return accuracy, which depends on measure more than on face choice.",
 "A controlled measure keeps the return sweep short enough for the eye to land accurately.",
 ["Long-form editorial and reports","Any text over 300 words"],
 ["Display and short-form settings","Dense tabular data"],
 "Sustained comfortable reading","Constrains column width and page density",
 "Long-form editorial","Display and tabular settings",
 ["Wider measure with increased leading where column width is fixed"],
 [("Letting body text fill a wide column at 100 characters per line","The eye loses the line on return, and reading errors accumulate as fatigue","Measure held to 60 to 75 characters per line")],
 "Sustains long-form reading without fatigue.",8,8,0.9)

TYPO("typography.humanist.bilingual_setting.001","Humanist faces for bilingual settings","humanist",
 "Set two scripts together so neither looks like an afterthought.",
 "Humanist proportions accommodate diacritics and varied glyph widths without visible strain.",
 "Locally fluent — a brand that belongs in both languages rather than translating into one.",
 "Both languages at the same level use the same face and size; hierarchy never differs between scripts.",
 "Leading set by the taller script's requirement, which for Vietnamese means 20 percent above the Latin default.",
 "Setting each language at its own optimal leading makes the two blocks visibly mismatched.",
 "Bilingual layouts set Latin at its own leading and Vietnamese cramped to match, which clips tone marks.",
 "Set both scripts in one humanist family at identical size, with leading governed by the taller script.",
 "A shared face and a shared leading are what make two languages read as one document.",
 "Governing leading by the taller script prevents clipping without visibly separating the two blocks.",
 ["Bilingual Vietnamese and English layouts","Regional and export communication"],
 ["Single-language settings","Scripts with incompatible proportions"],
 "Both languages read as equally considered","Costs vertical space in the shorter script",
 "Bilingual Vietnamese work","Single-language settings",
 ["Separate typographic systems per language where layouts are independent"],
 [("Setting Vietnamese at Latin leading to match the English block","Tone marks clip or collide, which reads as carelessness to a Vietnamese reader","Leading governed by the Vietnamese requirement for both blocks")],
 "Makes bilingual settings read as one document.",8,9,0.9,
 viet="Vietnamese needs roughly 20 percent more leading than Latin; set both blocks to that value rather than optimising each separately.")

TYPO("typography.humanist.signage_distance.001","Humanist faces at signage distance","humanist",
 "Keep type legible when read at distance and at an angle.",
 "Open apertures and generous counters survive the optical blur that distance and angle introduce.",
 "Practical and welcoming — wayfinding that does not feel institutional.",
 "Two levels maximum on any sign; a third level is not resolvable at signage distance.",
 "Tracking increased 20 to 30 units and leading at 1.3, since signage is read in single glances rather than scanned.",
 "Condensed or geometric faces blur into indistinguishable shapes beyond about ten metres.",
 "Signage uses condensed faces to fit longer names, which blur into unreadable shapes at distance.",
 "Choose a humanist face with open counters for signage, tracked 20 to 30 units looser, with two levels maximum.",
 "Distance introduces optical blur, and blur closes counters, so counter generosity governs distance legibility.",
 "Wider tracking prevents adjacent letters merging as blur increases with distance.",
 ["Wayfinding and environmental signage","Venue and retail interiors"],
 ["Screen and print typography","Settings with long names requiring condensation"],
 "Legible at distance and angle","Requires more physical space per word",
 "Environmental signage","Screen and dense print",
 ["Condensed face at larger physical size where space is fixed"],
 [("Using a condensed face on signage to fit longer names","Counters merge under distance blur and the sign becomes unreadable beyond ten metres","A humanist face with open counters, tracked looser, with the name shortened if needed")],
 "Keeps signage legible at real viewing distance.",7,8,0.87,
 ind="hospitality")

TYPO("typography.humanist.italic_as_voice.001","Humanist italic as a second voice","humanist",
 "Introduce a distinct voice without changing family.",
 "True italics are drawn as separate letterforms with cursive construction, not slanted romans.",
 "Confiding and secondary — an aside rather than a statement.",
 "Italic occupies a sub-level beneath body, used for captions, asides and attribution only.",
 "Tracking increased 5 units, since italic letterfit is tighter than roman by construction.",
 "Using an obliqued roman instead of a true italic produces distorted letterforms that read as a rendering fault.",
 "Emphasis is added with obliqued romans, which are geometric distortions rather than drawn letterforms.",
 "Use a true drawn italic for asides and attribution, tracked 5 units looser, never an obliqued roman.",
 "True italics have different letterforms entirely, which is what makes them read as a different voice rather than tilted type.",
 "A drawn italic changes voice; a slanted roman only changes angle.",
 ["Editorial with asides and attribution","Long-form with quoted material"],
 ["Display typography","Families offering only an oblique"],
 "A genuine second voice within one family","Only available in families with drawn italics",
 "Editorial and long-form","Display and oblique-only families",
 ["Weight or colour change where no true italic exists"],
 [("Using an obliqued roman where a true italic is unavailable","Produces geometrically distorted letterforms that read as a rendering fault","A different weight or a family that includes a drawn italic")],
 "Adds a second voice within one family.",7,7,0.86)

# ═══════════ GEOMETRIC TYPOGRAPHY ═══════════
TYPO("typography.geometric.circular_modernity.001","Geometric sans for modernity","geometric",
 "Signal contemporary design intent where heritage would be a liability.",
 "Circular bowls and uniform stroke width produce a constructed, machine-drawn appearance.",
 "Designed, current, systematic — a brand built rather than grown.",
 "Geometric at display and headline; body drops to a humanist face because geometric body text fatigues.",
 "Tracking increased 10 to 20 units at text size, since circular forms leave uneven gaps at default spacing.",
 "Used for extended body text the identical round forms cause character confusion and reading slows.",
 "Modern brands set everything in a geometric face, and body text becomes slow and tiring to read.",
 "Use a geometric face at display and headline levels only, with body set in a humanist face.",
 "Geometric letterforms sacrifice character distinction for consistency, which is a display virtue and a text liability.",
 "Confining geometric to display keeps the modern signal without the reading cost.",
 ["Contemporary and design-led brands","Technology and modern retail"],
 ["Long-form body text","Heritage and craft positioning"],
 "Strong contemporary signal","Fatiguing and confusable at text size",
 "Display and headline typography","Long-form body and heritage brands",
 ["Humanist sans where the same tone is needed at text size"],
 [("Setting long body copy in a geometric face for brand consistency","Identical circular forms cause character confusion and reading slows measurably","Geometric confined to display, body in a humanist face")],
 "Signals contemporary intent at display level.",8,8,0.88)

TYPO("typography.geometric.uniform_width_systems.001","Geometric uniformity for systems","geometric",
 "Build interface and system typography where predictability matters more than character.",
 "Consistent letter widths make text blocks predictable in length, which stabilises layout.",
 "Systematic and reliable — a product rather than a personality.",
 "Two levels in interface contexts, separated by weight; a third level adds ambiguity without adding information.",
 "Leading at 1.4 for interface text, with tracking at zero since uniform widths already space evenly.",
 "Character confusion between I, l and 1 rises sharply where the face lacks differentiating detail.",
 "Interface faces are chosen for personality, and ambiguous characters cause real input errors.",
 "Choose a geometric face with differentiated I, l and 1 for interface typography, set at 1.4 leading.",
 "Predictable text length stabilises interface layout, but only if ambiguous characters are ruled out first.",
 "Character differentiation is the one geometric weakness that cannot be tolerated in an interface.",
 ["Interface and product typography","Design systems requiring predictable text metrics"],
 ["Editorial and long-form reading","Brands built on warmth"],
 "Predictable metrics and stable layout","Ambiguous characters unless carefully chosen",
 "Interface and system typography","Editorial and warmth-led brands",
 ["Humanist face where character clarity outranks metric predictability"],
 [("Choosing a geometric face without checking I, l and 1 differentiation","Ambiguous characters cause real input errors in codes and identifiers","A face with a tailed l or serifed I explicitly verified")],
 "Stabilises interface layout without input errors.",7,8,0.88,
 ch="website", ind="technology")

TYPO("typography.geometric.tight_lockup_marks.001","Geometric forms for wordmarks","geometric",
 "Build a wordmark that stays recognisable at every size.",
 "Simple circular and rectangular forms remain identifiable when reduced to a favicon or embossed.",
 "Deliberate and reproducible — an identity engineered rather than drawn.",
 "The wordmark is its own level and never shares scale with any other element in the frame.",
 "Tracking customised per letter pair rather than applied globally, since geometric forms create uneven optical gaps.",
 "Global tracking on geometric forms leaves visible gaps beside round letters and tight fits beside straight ones.",
 "Wordmarks are set with global tracking, so round and straight letters space unevenly.",
 "Build wordmarks from geometric forms with tracking adjusted per letter pair rather than applied globally.",
 "Round letters need less space than straight ones, so uniform tracking always produces uneven optical rhythm.",
 "Pair-by-pair adjustment is the only way to achieve even optical spacing in a geometric wordmark.",
 ["Wordmark and logotype construction","Identities needing extreme size range"],
 ["Body and running text","Identities built on handwritten character"],
 "Recognisable at every reproduction size","Requires manual pair adjustment",
 "Wordmark construction","Running text and handwritten identities",
 ["Humanist letterforms where the identity should read as personal"],
 [("Applying one global tracking value across a geometric wordmark","Round letters float and straight letters crowd, producing uneven optical rhythm","Tracking adjusted for each letter pair individually")],
 "Produces wordmarks that hold at any size.",7,7,0.86)

TYPO("typography.geometric.grid_alignment_affinity.001","Geometric type on a strict grid","geometric",
 "Align type to a grid where the letterforms themselves reinforce the structure.",
 "Consistent widths and flat terminals sit cleanly on grid boundaries with no optical correction needed.",
 "Rigorous and constructed — the type belongs to the same system as the layout.",
 "Three levels maximum, all aligned to the same column structure with no element breaking the grid.",
 "Leading set to whole multiples of the baseline grid so every line lands on a grid unit.",
 "Fractional leading leaves lines drifting off the grid and the alignment discipline becomes invisible.",
 "Grid layouts use faces whose optical corrections fight the grid, so alignment never looks exact.",
 "Set leading to whole multiples of the baseline grid and use a geometric face whose flat terminals align cleanly.",
 "Type with flat terminals and even widths needs no optical correction, so grid alignment is also optical alignment.",
 "Whole-multiple leading keeps every line on a grid unit, which is what makes the system visible.",
 ["Swiss and systematic layouts","Grid-based editorial and reports"],
 ["Organic and expressive layouts","Settings where the grid is not visible"],
 "Alignment that is exact optically and mathematically","Rigid, with no room for optical exceptions",
 "Grid-based systematic design","Expressive and organic layouts",
 ["Humanist face with manual optical correction where warmth is needed"],
 [("Using fractional leading values on a baseline grid","Lines drift off the grid and the alignment discipline becomes invisible","Leading set to whole multiples of the baseline unit")],
 "Makes grid alignment optically exact.",7,7,0.86,
 related=["layout.swiss_grid.modular_column_system.001"])

TYPO("typography.geometric.numeral_treatment.001","Geometric numerals for data","geometric",
 "Set numbers so columns align and values compare accurately.",
 "Tabular lining figures occupy identical widths, so digits stack vertically in a column.",
 "Precise and accountable — figures presented as evidence rather than as claims.",
 "Numerals form their own level in data contexts, set at the same size as body but in tabular figures.",
 "No tracking applied to tabular figures, since any adjustment destroys the column alignment they exist for.",
 "Proportional figures in a numeric column leave digits misaligned and comparison becomes unreliable.",
 "Data tables use proportional figures, so digits do not align and columns cannot be compared by eye.",
 "Use tabular lining figures for any numeric column and apply no tracking to them.",
 "Comparison in a table is done by scanning vertically, which requires digits to occupy identical widths.",
 "Tabular figures are the only setting where vertical digit alignment is guaranteed.",
 ["Data tables, pricing and specifications","Financial and technical communication"],
 ["Running text containing numbers","Display figures where proportional fit looks better"],
 "Reliable vertical comparison","Uneven spacing when used in running text",
 "Tables and numeric data","Running text and display figures",
 ["Proportional oldstyle figures for numbers inside running text"],
 [("Using proportional figures in a price comparison column","Digits misalign vertically and the eye cannot compare values reliably","Tabular lining figures with no tracking applied")],
 "Makes numeric comparison reliable.",7,8,0.89,
 ch="website")

TYPO("typography.geometric.avoiding_sterility.001","Warming a geometric system","geometric",
 "Keep a geometric system from reading as cold without abandoning it.",
 "A single humanist element among geometric forms introduces variation the eye reads as human.",
 "Designed but not indifferent — system with a person behind it.",
 "Geometric carries display and body; one humanist element occupies a single supporting level only.",
 "The humanist element takes its own leading, typically 0.1 above the geometric body value.",
 "Introducing humanist elements at several levels dissolves the system and the layout reads as unresolved.",
 "Geometric systems read as cold, and designers fix it by mixing faces until the system disappears.",
 "Retain geometric at display and body and introduce exactly one humanist element at a single supporting level.",
 "One deviation is read as a deliberate accent; several are read as an absence of system.",
 "Confining warmth to one level preserves the system while removing its coldness.",
 ["Geometric brand systems needing warmth","Technology brands with human positioning"],
 ["Systems where coldness is the intent","Single-face licensing constraints"],
 "Warmth without losing the system","Adds a second family to license and manage",
 "Geometric systems needing warmth","Deliberately cold systems",
 ["Weight variation within the geometric family where a second face is not possible"],
 [("Introducing humanist elements at several levels to add warmth","Dissolves the system, so the layout reads as unresolved rather than warm","Exactly one humanist element at a single supporting level")],
 "Adds warmth without dissolving the system.",7,7,0.85)

flush()
