# -*- coding: utf-8 -*-
"""Batch 4B — typography hierarchy."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seed_typo_lib import TYPO, flush
LUX = dict(pos=["premium","luxury"])

# ═══════════ HERO MESSAGE HIERARCHY ═══════════
TYPO("typography.hero_hierarchy.single_dominant_level.001","One dominant level in a hero","hero_hierarchy",
 "Make a hero message land in the first fixation rather than the third.",
 "One element at three times the size of the next creates an unmissable entry point.",
 "Certain — the brand knows which sentence matters.",
 "Primary at three times secondary; secondary at 1.5 times tertiary; never more than three levels.",
 "Leading tightens as size grows: 1.6 at tertiary, 1.3 at secondary, 0.95 at primary.",
 "Two elements within 1.5 times of each other compete, and the viewer must choose where to start.",
 "Hero assets carry several near-equal messages, so the viewer chooses an entry point at random.",
 "Set the primary at three times the secondary size and cap the asset at three levels.",
 "Entry point is decided by relative scale, and a ratio below 1.5 leaves the decision to the viewer.",
 "A three-times ratio removes ambiguity about where reading begins.",
 ["Hero and above-fold assets","Awareness and launch objectives"],
 ["Information-dense layouts","Assets with genuinely equal messages"],
 "Unambiguous entry point","Only one message can dominate",
 "Hero and campaign assets","Dense information layouts",
 ["Colour or position hierarchy where scale cannot vary"],
 [("Setting headline and sub-headline within 1.2 times of each other","The two compete and the viewer picks an entry point at random, so neither lands first","Primary set at three times the secondary size")],
 "Fixes where reading begins.",8,9,0.89)

TYPO("typography.hero_hierarchy.eyebrow_context.001","Eyebrow line for context","hero_hierarchy",
 "Supply category context above a headline without stealing its weight.",
 "A small tracked line above the headline reads as a label rather than as a statement.",
 "Oriented — the reader knows what kind of message this is before reading it.",
 "Eyebrow at 25 to 35 percent of headline size, always above, never below the headline.",
 "Tracked 100 to 150 units and set in caps or small caps, with 0.5 line of space beneath.",
 "An eyebrow at over 40 percent of headline size competes and the two read as a stacked pair.",
 "Context is added as a second headline, which splits attention between two similar-weight lines.",
 "Set the eyebrow at 25 to 35 percent of headline size, tracked 100 to 150 units, placed above.",
 "A label and a statement occupy different registers, and size ratio is what keeps them distinct.",
 "Wide tracking marks the line as a label rather than as prose.",
 ["Campaign and editorial heroes","Assets needing category framing"],
 ["Single-message assets with no context requirement","Very small formats"],
 "Context without competing","Consumes vertical space above the headline",
 "Campaign heroes","Minimal single-message assets",
 ["Headline that carries its own context in the first words"],
 [("Setting the eyebrow at half the headline size","The two read as a stacked pair and attention splits between them","Eyebrow held at 25 to 35 percent of headline size")],
 "Frames a message without competing with it.",7,8,0.87)

TYPO("typography.hero_hierarchy.supporting_line_discipline.001","Supporting line discipline","hero_hierarchy",
 "Add one clarifying line without diluting the headline.",
 "A supporting line at a third of headline size reads as explanation rather than as a second claim.",
 "Considered — the brand anticipated the obvious question.",
 "Exactly one supporting line; a second turns the hero into a paragraph and halves the headline's weight.",
 "Leading at 1.4 with 0.75 line of space between headline and supporting line.",
 "Two supporting lines convert the hero into body copy, which is read at body-copy rates.",
 "Supporting copy accumulates under a headline until the hero reads as a paragraph.",
 "Allow exactly one supporting line at a third of headline size, with 0.75 line of space above it.",
 "Attention available to a hero is fixed, so each added line divides it rather than adding to it.",
 "One line answers the obvious question without converting the hero into text.",
 ["Hero assets needing one clarification","Propositions that are not self-explanatory"],
 ["Self-explanatory headlines","Assets where copy must be extensive"],
 "Clarity without dilution","Only one clarification fits",
 "Hero assets with one open question","Extensive copy requirements",
 ["Headline rewrite that removes the need for clarification"],
 [("Adding a second and third supporting line for completeness","Converts the hero into body copy, which is read at body-copy rates rather than headline rates","One supporting line, with the rest moved to another asset")],
 "Clarifies without diluting the headline.",7,8,0.87)

TYPO("typography.hero_hierarchy.weight_over_size.001","Weight contrast where size is fixed","hero_hierarchy",
 "Create hierarchy in formats too small for large size differences.",
 "A black weight beside a light weight reads as clear rank even at identical size.",
 "Deliberate — rank was designed rather than inherited from available space.",
 "Two levels only; weight contrast cannot reliably support three levels at one size.",
 "Leading constant across levels; tracking reduced 10 units at the heaviest weight to prevent crowding.",
 "Using adjacent weights at identical size produces no perceptible rank at all.",
 "Small formats reduce type size to create hierarchy, pushing text below the legibility floor.",
 "Use weights at least three steps apart at identical size, limited to two levels.",
 "Weight contrast is perceived independently of size, which is what makes it work where size cannot vary.",
 "A three-step separation clears the threshold at which weight difference becomes rank.",
 ["Small formats and constrained layouts","Banners and interface components"],
 ["Formats with room for size variation","Hierarchies needing three or more levels"],
 "Hierarchy without size reduction","Supports only two levels reliably",
 "Small and constrained formats","Multi-level hierarchies",
 ["Size hierarchy where the format allows it"],
 [("Using regular and medium weights at the same size for hierarchy","The difference is below the perceptual threshold and no rank is communicated","Weights at least three steps apart")],
 "Creates rank where size cannot vary.",7,8,0.88,
 asset="banner")

TYPO("typography.hero_hierarchy.entry_point_placement.001","Entry point placement","hero_hierarchy",
 "Put the dominant element where the eye actually lands first.",
 "An element in the upper left third is found before one of equal size placed lower or right.",
 "Confident — the message meets the reader rather than waiting to be found.",
 "The primary level occupies the upper left third; supporting levels fill downward and rightward.",
 "Top margin held to 8 to 12 percent so the primary sits inside the first fixation zone.",
 "A primary element placed low forces a search, and the search happens after the scroll decision.",
 "Hero messages are centred vertically, which places them outside the first fixation zone.",
 "Place the primary level in the upper left third with a top margin of 8 to 12 percent.",
 "Reading in Latin scripts begins upper left, so an element there is found without search.",
 "Removing the search means the message arrives before the decision to leave.",
 ["Web heroes and above-fold layouts","Latin and Vietnamese script settings"],
 ["Right-to-left script layouts","Deliberately centred authority statements"],
 "Message lands in the first fixation","Constrains composition to an upper-left bias",
 "Web and above-fold heroes","Centred authority layouts",
 ["Centred placement where symmetry is the message"],
 [("Centring the hero message vertically like a poster","Places the message outside the first fixation, so bounce occurs before it is read","Primary placed in the upper left third")],
 "Places the message in the first fixation.",8,8,0.88,
 ch="website")

TYPO("typography.hero_hierarchy.headline_length_ceiling.001","Headline length ceiling","hero_hierarchy",
 "Keep a headline short enough to be perceived as a unit.",
 "A line of seven words or fewer is read as one shape; beyond that it becomes a sentence to process.",
 "Decisive — the brand can say it in one breath.",
 "The headline is one level regardless of line count; wrapping does not create a second level.",
 "Measure held to 20 to 30 characters per line at display size, wrapping at a natural phrase break.",
 "Headlines over ten words are processed as body copy and receive body-copy attention.",
 "Headlines expand to carry the whole proposition, and stop being read as headlines.",
 "Hold headlines to seven words or fewer, wrapping at natural phrase breaks with 20 to 30 characters per line.",
 "Short lines are perceived as units, while long ones are parsed sequentially at reading speed.",
 "A seven-word ceiling keeps the headline in the register where it is perceived rather than read.",
 ["All display headlines","Paid media with short exposure"],
 ["Editorial subheads that genuinely require length","Long-form article titles"],
 "Perceived as a unit rather than parsed","Forces hard copy decisions",
 "Display headlines","Editorial subheads",
 ["Two-level split where the copy genuinely cannot be shortened"],
 [("Writing a fourteen-word headline to carry the full proposition","Processed as body copy and given body-copy attention, so the headline advantage is lost","Seven words or fewer, with the remainder moved to a supporting line")],
 "Keeps headlines in the perceptual register.",8,8,0.88)

# ═══════════ CONVERSION HIERARCHY ═══════════
TYPO("typography.conversion_hierarchy.action_prominence.001","Action prominence in conversion","conversion_hierarchy",
 "Make the next action the second thing read, never the last.",
 "An action set at 60 to 70 percent of headline size sits above supporting copy in the reading order.",
 "Direct — the brand states clearly what to do next.",
 "Three levels: proposition, action, supporting detail, in that reading order and that size order.",
 "Action given 1.5 lines of clear space above and below so it is never absorbed into a paragraph.",
 "An action set at body size is read last or not at all, and intent decays before it is found.",
 "Calls to action are set at body size beneath supporting copy, where they are read last.",
 "Set the action at 60 to 70 percent of headline size with 1.5 lines of clear space around it.",
 "Intent decays with every element read between the proposition and the means of acting on it.",
 "Clear space prevents the action being absorbed into the paragraph above it.",
 ["Conversion and direct response assets","Landing pages and performance social"],
 ["Pure awareness campaigns","Editorial with no available action"],
 "Shortens the path from intent to action","Reduces space for supporting argument",
 "Conversion assets","Awareness and editorial",
 ["Repeated action placement where the page is long"],
 [("Placing the call to action below all supporting copy at body size","Read last if at all, and intent decays before it is found","Action at 60 to 70 percent of headline size, second in reading order")],
 "Shortens the path from intent to action.",8,9,0.9,
 obj="conversion")

TYPO("typography.conversion_hierarchy.price_legibility.001","Price legibility in conversion","conversion_hierarchy",
 "Make price findable without making it the whole message.",
 "Price at 40 to 50 percent of headline size reads as information rather than as a claim.",
 "Straightforward — the brand is not hiding what it costs.",
 "Price occupies the level directly beneath the proposition and directly above the action.",
 "Price set with tabular figures and 1 line of space above, so it never merges with body copy.",
 "Price set at body size inside a paragraph is missed entirely and the click is uninformed.",
 "Price is buried in body copy, producing clicks that abandon when the price is discovered.",
 "Set price at 40 to 50 percent of headline size in tabular figures, between the proposition and the action.",
 "A price discovered after the click is experienced as concealment, and the abandonment costs more than the click.",
 "Placing price above the action means the decision is made with the price known.",
 ["Priced conversion assets","E-commerce and subscription offers"],
 ["Enquiry-led services with no fixed price","Brand awareness assets"],
 "Higher quality clicks, lower abandonment","Lower raw click volume",
 "Priced conversion","Enquiry-led and awareness",
 ["Range indication where an exact price cannot be shown"],
 [("Placing price inside a body paragraph at body size","Missed entirely, producing clicks that abandon on discovering the price","Price at 40 to 50 percent of headline size, above the action")],
 "Produces informed clicks rather than raw volume.",8,8,0.88,
 obj="conversion")

TYPO("typography.conversion_hierarchy.risk_reducer_placement.001","Risk reducer placement","conversion_hierarchy",
 "Place reassurance where hesitation actually occurs.",
 "A short reassurance directly beneath the action is read at the moment of deciding.",
 "Considerate — the brand anticipated the objection.",
 "Reassurance sits one level below the action at 30 to 40 percent of headline size.",
 "Set immediately beneath the action with no more than 0.5 line of separation.",
 "Reassurance placed at the page foot is read after the decision, when it can no longer help.",
 "Guarantees and return policies are placed in the footer, far from the moment of hesitation.",
 "Place one reassurance line immediately beneath the action at 30 to 40 percent of headline size.",
 "Hesitation occurs at the action, so reassurance is only useful if it is visible at that point.",
 "Tight adjacency ensures the reassurance is read as part of the action, not as a separate claim.",
 ["Conversion assets with a known objection","Higher-consideration purchases"],
 ["Impulse purchases with no hesitation","Assets with no genuine reassurance to offer"],
 "Addresses hesitation at the point it occurs","Adds an element beside the action",
 "Considered-purchase conversion","Impulse categories",
 ["Objection handling earlier in the page where hesitation starts sooner"],
 [("Placing the guarantee in the page footer","Read after the decision has already been made, when it can no longer influence it","Reassurance placed immediately beneath the action")],
 "Answers hesitation where it happens.",7,8,0.87,
 obj="conversion")

TYPO("typography.conversion_hierarchy.scannable_benefit_list.001","Scannable benefit list","conversion_hierarchy",
 "Let a reader extract benefits without reading sentences.",
 "Bold lead phrases at the start of each item create scannable anchors down the left edge.",
 "Efficient — the brand respects that the reader is scanning.",
 "Benefit list occupies one level; lead phrases within it form a sub-level by weight, not by size.",
 "Leading at 1.6 with 0.75 line between items, so items separate without needing bullets or rules.",
 "Items written as full sentences with no bold lead produce a paragraph the reader skips.",
 "Benefits are written as prose paragraphs, which are not read and not scanned.",
 "Open each benefit item with a bold two to four word lead phrase, separated by 0.75 line.",
 "Scanning fixates on the left edge of each line, so anchors there are found without reading.",
 "Bold leads let a reader extract the list without processing the sentences.",
 ["Feature and benefit communication","Landing pages and considered purchase"],
 ["Emotional brand storytelling","Assets with only one benefit"],
 "Benefits extracted without reading","Reduces persuasive prose to fragments",
 "Benefit-led conversion pages","Emotional brand narrative",
 ["Single benefit stated as a headline where only one matters"],
 [("Writing benefits as full prose paragraphs","Neither read nor scanned, so the benefits do not transfer at all","Bold two to four word lead phrases opening each item")],
 "Makes benefits extractable by scanning.",7,8,0.87,
 ch="website", obj="conversion")

TYPO("typography.conversion_hierarchy.urgency_subordination.001","Urgency subordination","conversion_hierarchy",
 "Add time pressure without displacing the offer.",
 "Urgency at 25 to 30 percent of headline size reads as a condition rather than as the message.",
 "Honest — pressure is present but not the substance of the argument.",
 "Urgency is the lowest level in the hierarchy, read after proposition, price and action.",
 "Set beneath the action with 1 line of separation, never above the proposition.",
 "Urgency set at headline weight makes the deadline the message and the offer becomes secondary.",
 "Urgency is set as the largest element, so the viewer registers pressure without registering the offer.",
 "Set urgency at 25 to 30 percent of headline size as the lowest level, beneath the action.",
 "Urgency modifies an offer rather than replacing it, so it belongs last in reading order.",
 "Subordinate placement means the offer is understood before the pressure applies.",
 ["Time-bound offers with a real deadline","Conversion campaigns"],
 ["Evergreen offers","Premium positioning damaged by pressure"],
 "Pressure without obscuring the offer","False urgency damages trust when detected",
 "Genuine time-bound promotions","Evergreen and premium offers",
 ["Offer-only hierarchy where no deadline exists"],
 [("Setting the deadline as the largest element on the asset","The viewer registers pressure without registering what is offered, so nothing converts","Urgency at 25 to 30 percent of headline size, placed last")],
 "Applies pressure without hiding the offer.",7,8,0.86,
 obj="conversion")

TYPO("typography.conversion_hierarchy.form_field_labels.001","Form field label hierarchy","conversion_hierarchy",
 "Keep labels visible while the field is being filled.",
 "Labels set above fields remain visible during input, unlike placeholder text which disappears.",
 "Usable — the brand designed for the moment of typing, not the moment of looking.",
 "Labels are a sub-level of body: same face, 85 percent size, one weight step heavier.",
 "Label set 0.25 line above its field with 1 line of space between field groups.",
 "Placeholder-only labels vanish on focus, so the user forgets what the field was for.",
 "Forms use placeholder text as labels, which disappears the moment typing begins.",
 "Set field labels above each field at 85 percent of body size, never as placeholder text alone.",
 "A label inside the field is destroyed by the act of using the field, which is when it is needed most.",
 "Placement above keeps the label visible throughout input and after correction.",
 ["Forms and input interfaces","Conversion flows with data entry"],
 ["Single-field search inputs where context is obvious","Display and print typography"],
 "Fewer input errors and abandonments","Costs vertical space per field",
 "Multi-field forms","Single-field inputs",
 ["Floating labels that move above the field on focus"],
 [("Using placeholder text as the only field label","The label disappears on focus, so the user forgets what the field was for","Persistent labels set above each field")],
 "Reduces form input errors.",8,9,0.9,
 ch="website", obj="conversion")

# ═══════════ LUXURY MINIMAL HIERARCHY ═══════════
TYPO("typography.luxury_hierarchy.two_level_restraint.001","Two levels only in luxury","luxury_hierarchy",
 "Signal confidence by declining to explain.",
 "Two levels leave the page quiet; a third introduces the visual busyness luxury avoids.",
 "Assured — the brand does not need to argue its case.",
 "Exactly two levels: one statement and one attribution or mark. No supporting copy.",
 "Leading at 1.6 or more, with margins at 12 to 18 percent of frame width on every side.",
 "A third level introduces the density that separates premium layouts from mass ones.",
 "Luxury layouts add explanatory copy, which is the visual signature of having to persuade.",
 "Limit luxury assets to exactly two typographic levels with margins at 12 to 18 percent.",
 "Explanation implies the value is not self-evident, which contradicts the premium being charged.",
 "Two levels keep the page quiet enough for the restraint itself to be the signal.",
 ["Luxury and premium brand assets","Awareness objectives"],
 ["Conversion assets requiring price and action","Product specification communication"],
 "Strong restraint signal","Carries almost no information",
 "Luxury brand work","Conversion and specification assets",
 ["Three-level hierarchy where information genuinely must be carried"],
 [("Adding explanatory copy beneath a luxury statement","Implies the value is not self-evident, which contradicts the price being asked","Two levels only, with explanation moved to another surface")],
 "Signals confidence through restraint.",8,9,0.89, **LUX)

TYPO("typography.luxury_hierarchy.small_mark_confidence.001","Small brand mark as confidence","luxury_hierarchy",
 "Signal that the brand does not need to shout its own name.",
 "A mark at 3 to 5 percent of frame width reads as a signature rather than a label.",
 "Established — a brand known well enough not to introduce itself.",
 "The mark is the lowest level and never exceeds 40 percent of the smallest type level.",
 "Placed with margins equal to or greater than the type block margins, never tighter.",
 "A mark enlarged for visibility reads as insecurity and lowers the perceived tier.",
 "Brand marks are scaled up for prominence, which reads as a brand that must assert itself.",
 "Hold the brand mark to 3 to 5 percent of frame width with margins no tighter than the type block.",
 "Prominence of self-identification correlates inversely with perceived establishment.",
 "A small mark implies the work is recognisable without it.",
 ["Luxury and established premium brands","Brand and awareness assets"],
 ["New brands building recognition","Performance assets needing attribution"],
 "Reads as established","Weak attribution for unknown brands",
 "Established luxury brands","New brands and performance media",
 ["Larger mark placement where recognition is still being built"],
 [("Enlarging the brand mark for visibility on a luxury asset","Reads as insecurity and lowers the perceived tier of the whole asset","Mark held to 3 to 5 percent of frame width")],
 "Signals establishment through mark restraint.",7,8,0.87, **LUX)

TYPO("typography.luxury_hierarchy.generous_margin_ratio.001","Margin as hierarchy","luxury_hierarchy",
 "Use space around the type block as a level in its own right.",
 "Margins exceeding 15 percent isolate the type block so it reads as an object on a field.",
 "Unhurried — the brand is not competing for room.",
 "The margin is treated as a hierarchy element; type levels are reduced before margins are.",
 "Margins at 15 to 25 percent of frame width, with the top margin 20 percent larger than the bottom.",
 "Margins reduced to fit copy destroy the isolation and the layout drops to category average.",
 "Copy is fitted by reducing margins, which removes the isolation that carried the premium signal.",
 "Hold margins at 15 to 25 percent of frame width and reduce copy rather than margins when space is short.",
 "The isolation the margin creates is what makes the type block read as considered rather than fitted.",
 "Protecting the margin forces copy discipline, which is the correct trade in premium work.",
 ["Luxury and premium layouts","Brand and awareness assets"],
 ["Information-dense assets","Formats where chrome already consumes edges"],
 "Isolation that signals value","Substantially reduces usable area",
 "Premium brand layouts","Dense information assets",
 ["Standard margins where information volume is fixed"],
 [("Reducing margins to fit additional copy","Removes the isolation carrying the premium signal, dropping the asset to category average","Copy reduced instead, margins protected at 15 to 25 percent")],
 "Makes space itself a hierarchy level.",8,8,0.88, **LUX)

TYPO("typography.luxury_hierarchy.centred_symmetry.001","Centred symmetry in luxury","luxury_hierarchy",
 "Assert authority through absence of visual tension.",
 "Perfectly centred type with equal margins removes every directional cue from the frame.",
 "Certain — nothing in the composition is arguing for position.",
 "All levels centred on one axis; mixing centred and aligned levels destroys the symmetry.",
 "Optical centring rather than mathematical, since punctuation and capitals shift perceived centre.",
 "Type centred mathematically appears offset when lines end in punctuation or narrow letters.",
 "Luxury layouts centre mathematically, so lines with punctuation appear visibly off-centre.",
 "Centre all levels optically on one axis, correcting for punctuation and terminal letter width.",
 "Perceived centre differs from mathematical centre whenever line endings differ in visual weight.",
 "Optical correction is what makes symmetry read as intentional rather than approximate.",
 ["Luxury and heritage brand assets","Formal and ceremonial communication"],
 ["Conversion assets needing directional flow","Long-form reading"],
 "Maximum formality and authority","Static, and poor for long reading",
 "Formal luxury communication","Conversion and long-form",
 ["Left-aligned setting where reading flow matters more than formality"],
 [("Centring type mathematically without optical correction","Lines ending in punctuation appear visibly off-centre, undermining the symmetry","Optical centring corrected for line-ending weight")],
 "Makes symmetry read as intentional.",7,8,0.87, **LUX)

TYPO("typography.luxury_hierarchy.whisper_scale.001","Whisper scale typography","luxury_hierarchy",
 "Use small type deliberately so the reader leans in.",
 "Type at 60 to 70 percent of expected size in a large empty frame reads as understatement.",
 "Discreet — the brand is speaking quietly to those who are listening.",
 "All levels reduced proportionally; the ratio between levels stays constant while absolute size drops.",
 "Leading increased to 1.8 or more, since small type in a large field needs more air to avoid looking cramped.",
 "Reducing size without increasing leading makes the block look cramped rather than understated.",
 "Understatement is attempted by shrinking type alone, which reads as an error rather than a choice.",
 "Reduce all levels proportionally to 60 to 70 percent of expected size and raise leading to 1.8 or more.",
 "Understatement requires both reduced size and increased air, or it reads as a mistake.",
 "Proportional reduction preserves the hierarchy while the added leading signals deliberateness.",
 ["Luxury and niche premium brands","Audiences who already know the brand"],
 ["Awareness campaigns to cold audiences","Any accessibility-sensitive setting"],
 "Strong understatement signal","Excludes readers with reduced vision",
 "Established luxury audiences","Cold reach and accessibility contexts",
 ["Normal scale with generous margins where accessibility matters"],
 [("Reducing type size without increasing leading","The block reads as cramped and mistaken rather than as deliberate understatement","Leading raised to 1.8 or more alongside the size reduction")],
 "Makes small type read as deliberate.",7,7,0.84, **LUX)

TYPO("typography.luxury_hierarchy.single_weight_discipline.001","Single weight across a luxury system","luxury_hierarchy",
 "Remove weight variation so the page reads as one voice.",
 "One weight throughout produces even page colour with hierarchy carried by size and space alone.",
 "Composed — the brand does not raise its voice for emphasis.",
 "Hierarchy by size and spacing only; bold and light are excluded from the system entirely.",
 "Level separation by a 1.6 size ratio minimum, since weight is unavailable to reinforce rank.",
 "Adding a bold weight for emphasis introduces the exact loudness the system was built to avoid.",
 "Luxury systems add bold for emphasis, which reintroduces the promotional register they were avoiding.",
 "Use one weight throughout and separate levels by a size ratio of at least 1.6.",
 "Weight variation is read as raised volume, which is the register luxury positioning avoids.",
 "A larger size ratio compensates for the rank information weight would otherwise carry.",
 ["Luxury brand systems","Editorial with a single tonal register"],
 ["Conversion assets needing emphasis","Information-dense layouts"],
 "One consistent voice","No emphasis device available",
 "Luxury brand systems","Conversion and dense information",
 ["Two-weight system where emphasis is genuinely needed"],
 [("Adding a bold weight for emphasis in a single-weight luxury system","Reintroduces the promotional register the single-weight discipline was built to avoid","Emphasis carried by size and spacing within one weight")],
 "Keeps a luxury system in one register.",7,8,0.86, **LUX)

# ═══════════ EDITORIAL HIERARCHY ═══════════
TYPO("typography.editorial_hierarchy.article_entry_system.001","Article entry hierarchy","editorial_hierarchy",
 "Let a reader decide whether to read before committing.",
 "Headline, standfirst and byline form a descending block that summarises the article's claim.",
 "Transparent — the reader is told what they are getting.",
 "Four levels: headline, standfirst, byline, body, each at a 1.4 to 1.6 ratio to the next.",
 "Standfirst leading at 1.4; body at 1.5; byline separated by 1 line above and below.",
 "Omitting the standfirst forces a decision on the headline alone, which raises bounce.",
 "Articles open with headline then body, giving the reader no basis to decide whether to continue.",
 "Use four levels — headline, standfirst, byline, body — each at a 1.4 to 1.6 ratio to the next.",
 "Reading is a commitment, and readers who cannot assess the commitment decline it.",
 "The standfirst supplies the assessment that converts a headline into a decision.",
 ["Editorial and long-form articles","Owned content and publications"],
 ["Advertising with short exposure","Single-message assets"],
 "Informed reading decisions and lower bounce","Delays the body by two elements",
 "Editorial long-form","Advertising and short-form",
 ["Headline and body only where the article is very short"],
 [("Opening an article with headline followed directly by body","The reader must decide on the headline alone, which raises bounce","A standfirst between headline and body")],
 "Lets readers decide before committing.",7,8,0.87, ch="website")

TYPO("typography.editorial_hierarchy.subhead_navigation.001","Subheads as navigation","editorial_hierarchy",
 "Let a scanning reader find the relevant section without reading.",
 "Subheads every 200 to 300 words create scannable entry points down the column.",
 "Navigable — the brand accepts that most readers scan.",
 "Subheads sit one level above body at 1.3 to 1.5 times body size, with weight one step heavier.",
 "1.5 lines of space above each subhead and 0.5 below, so it attaches to the text it introduces.",
 "Equal space above and below leaves the subhead floating between sections rather than heading one.",
 "Long articles run without subheads, so a scanning reader cannot locate the relevant part.",
 "Place a subhead every 200 to 300 words with 1.5 lines above and 0.5 below.",
 "Asymmetric spacing is what attaches a subhead to the section it introduces rather than the one before.",
 "Regular subheads convert an unnavigable block into a scannable structure.",
 ["Long-form articles over 800 words","Reference and instructional content"],
 ["Short articles under 400 words","Narrative writing where breaks disrupt flow"],
 "Scannable and navigable","Interrupts narrative flow",
 "Long-form and reference content","Short and narrative writing",
 ["Pull quotes as visual breaks where subheads would fragment a narrative"],
 [("Setting equal space above and below a subhead","The subhead floats between sections rather than heading the one that follows","1.5 lines above and 0.5 below")],
 "Makes long articles navigable by scanning.",7,8,0.88, ch="website")

TYPO("typography.editorial_hierarchy.pull_quote_rhythm.001","Pull quotes as rhythm","editorial_hierarchy",
 "Break a long column visually without interrupting the argument.",
 "A quote at 1.8 to 2.2 times body size creates a visual rest that also carries content.",
 "Confident — the piece has lines worth repeating.",
 "Pull quotes form their own level between subhead and body, never exceeding subhead prominence.",
 "Set with 2 lines of space above and below and a measure 60 to 70 percent of the body column.",
 "A pull quote set at subhead size or above is mistaken for a section heading.",
 "Long columns run unbroken, and readers abandon at the point the column stops looking finite.",
 "Set pull quotes at 1.8 to 2.2 times body size with 2 lines of space and a narrower measure.",
 "A visual rest extends reading endurance, and a quote provides one without adding new content to process.",
 "Keeping quotes below subhead prominence prevents them being read as structural headings.",
 ["Long-form editorial","Articles over 1000 words"],
 ["Short articles","Instructional content where every line is necessary"],
 "Extends reading endurance","Repeats content already in the body",
 "Long-form editorial","Short and instructional content",
 ["Image breaks where suitable quotes do not exist"],
 [("Setting a pull quote at subhead size or larger","Mistaken for a section heading, which breaks the article's structural logic","Pull quote held below subhead prominence")],
 "Extends reading endurance in long columns.",7,7,0.86, ch="website")

TYPO("typography.editorial_hierarchy.caption_attachment.001","Caption attachment","editorial_hierarchy",
 "Bind a caption to its image so the pair reads as one unit.",
 "A caption within half a line of its image is read as belonging to it rather than to the body.",
 "Organised — the reader never has to work out what a caption refers to.",
 "Captions are a sub-level of body at 80 to 85 percent size, one weight lighter or in italic.",
 "Set 0.5 line beneath the image and 1.5 lines above the following body text.",
 "Equal spacing above and below leaves the caption ambiguous between image and following text.",
 "Captions are spaced evenly between image and body, so their referent is ambiguous.",
 "Set captions 0.5 line beneath their image and 1.5 lines above the following text.",
 "Proximity determines perceived grouping, so asymmetric spacing resolves the referent without a rule.",
 "Tight attachment above and loose separation below makes the pairing unambiguous.",
 ["Editorial with images","Documentary and reference content"],
 ["Full-bleed images with overlay captions","Galleries with no per-image commentary"],
 "Unambiguous caption referents","Costs vertical space between elements",
 "Illustrated editorial","Full-bleed and gallery formats",
 ["Side-set captions where vertical space is unavailable"],
 [("Spacing a caption equally between its image and the following text","The referent becomes ambiguous and the reader must work it out","0.5 line beneath the image, 1.5 lines above the following text")],
 "Removes caption referent ambiguity.",7,8,0.88, ch="website")

TYPO("typography.editorial_hierarchy.footnote_subordination.001","Footnote subordination","editorial_hierarchy",
 "Keep references available without interrupting the main argument.",
 "Footnotes at 70 to 75 percent of body size read as apparatus rather than as content.",
 "Rigorous — the argument is sourced without being cluttered.",
 "Footnotes are the lowest level, below captions, and never share size with any body element.",
 "Leading at 1.4 with 2 lines separating the note block from the body above it.",
 "Footnotes set at body size compete with the argument and interrupt the reading line.",
 "References are set at body size, so they compete with the argument they were meant to support.",
 "Set footnotes at 70 to 75 percent of body size with 2 lines of separation from the body block.",
 "Apparatus must be findable but not competitive, and size is what separates the two registers.",
 "Clear separation prevents the eye treating notes as a continuation of the argument.",
 ["Academic, technical and sourced editorial","Regulatory disclosure"],
 ["Consumer advertising","Short-form content with no citations"],
 "Sourcing without clutter","Small size limits how much can be said",
 "Sourced and technical editorial","Consumer advertising",
 ["Inline parenthetical references where notes are very few"],
 [("Setting footnotes at body size for readability","They compete with the argument and interrupt the reading line","Footnotes at 70 to 75 percent of body size, clearly separated")],
 "Keeps sourcing available without clutter.",6,7,0.86, ch="website")

TYPO("typography.editorial_hierarchy.column_measure_control.001","Measure control in editorial columns","editorial_hierarchy",
 "Hold line length within the range the eye can track accurately.",
 "A measure of 60 to 75 characters keeps the return sweep short enough to land accurately.",
 "Readable — the layout was set for reading rather than for filling space.",
 "Measure is a property of the body level; other levels may exceed it without penalty.",
 "Leading increases with measure: 1.5 at 60 characters, 1.7 at 75, never below 1.4 at any measure.",
 "Beyond 80 characters the eye misses the correct line on return and re-reads or skips lines.",
 "Body text fills the available column width, producing measures well beyond comfortable reading.",
 "Hold body measure to 60 to 75 characters with leading scaled from 1.5 to 1.7 across that range.",
 "Return accuracy governs reading fatigue, and it degrades sharply past roughly 80 characters.",
 "Increasing leading with measure preserves return accuracy as the sweep lengthens.",
 ["Any body text over 200 words","Editorial, reports and long-form web"],
 ["Display and short-form settings","Tabular and list content"],
 "Accurate line return and lower fatigue","Constrains column width and page density",
 "Long-form editorial","Display and tabular content",
 ["Two-column setting where the page width is fixed and wide"],
 [("Letting body text fill a 110-character column","The eye misses the line on return, causing re-reads that accumulate as fatigue","Measure held to 60 to 75 characters, or split into two columns")],
 "Preserves accurate line return.",8,8,0.9, ch="website")

# ═══════════ INFORMATION HIERARCHY ═══════════
TYPO("typography.information_hierarchy.tabular_alignment.001","Tabular data alignment","information_hierarchy",
 "Make columns of data comparable by scanning.",
 "Numbers right-aligned on tabular figures stack so digits of equal place value align vertically.",
 "Accurate — figures are presented for checking rather than for impression.",
 "Column headers form a level above data; data rows share one level regardless of content type.",
 "Row leading at 1.5 with alternating tint rather than rules, and no tracking on figures.",
 "Left-aligned numbers misalign place values, so vertical comparison becomes unreliable.",
 "Numeric columns are left-aligned like text, so place values do not stack and comparison fails.",
 "Right-align numeric columns using tabular figures with row leading at 1.5 and no tracking.",
 "Vertical comparison depends on place-value alignment, which only right-aligned tabular figures provide.",
 "Alternating tint keeps lateral row tracking accurate without adding rules.",
 ["Data tables, pricing and specifications","Financial and technical documents"],
 ["Running text containing figures","Narrative content"],
 "Reliable vertical comparison","Cold and purely functional",
 "Data and specification tables","Narrative and running text",
 ["Oldstyle proportional figures inside running prose"],
 [("Left-aligning a column of prices like text","Place values do not stack, so the eye cannot compare magnitudes reliably","Right-aligned tabular figures")],
 "Makes numeric columns comparable.",8,8,0.9, ch="website")

TYPO("typography.information_hierarchy.nested_list_depth.001","Nested list depth limit","information_hierarchy",
 "Keep structured lists navigable by limiting nesting.",
 "Two levels of indent remain trackable; a third exceeds what the eye holds without a marker.",
 "Organised — structure that helps rather than structure for its own sake.",
 "List levels are sub-levels of body: level one at body size, level two at 95 percent, no level three.",
 "Indent of 1.5 to 2 em per level with 0.5 line between items and 1 line between groups.",
 "A third indent level loses its parent reference and the reader cannot tell what the item belongs to.",
 "Complex information is nested three and four levels deep, at which point structure stops helping.",
 "Limit nested lists to two levels with an indent of 1.5 to 2 em per level.",
 "Tracking a parent reference across more than two indents exceeds working memory during scanning.",
 "Two levels keep every item's parent visible within one fixation.",
 ["Structured and instructional content","Documentation and specifications"],
 ["Deeply hierarchical technical reference","Narrative content"],
 "Structure that stays navigable","Cannot express deep hierarchies",
 "Instructional and structured content","Deep technical reference",
 ["Separate sections with headings where depth genuinely exceeds two levels"],
 [("Nesting list items three or four levels deep","The parent reference is lost and the reader cannot tell what an item belongs to","Two levels maximum, with deeper structure split into sections")],
 "Keeps structured lists navigable.",7,7,0.86, ch="website")

TYPO("typography.information_hierarchy.label_value_pairing.001","Label and value pairing","information_hierarchy",
 "Bind each label to its value so the pair is read as one unit.",
 "Labels set lighter and values heavier make the value the scannable element in each pair.",
 "Clear — the reader finds the value without reading the label.",
 "Label and value share one level; weight difference within the level marks which is which.",
 "Label and value separated by 0.5 em on one line, or 0.25 line if stacked, never more.",
 "Wide separation between label and value breaks the pairing and the eye must re-associate them.",
 "Specification lists space labels and values across the full column width, breaking the pairing.",
 "Set labels one weight lighter than values with 0.5 em separation on one line.",
 "Proximity establishes pairing, and any gap wide enough to hold other content breaks it.",
 "Weight contrast makes the value scannable while the label stays available.",
 ["Specification and detail lists","Product data and profiles"],
 ["Narrative content","Tabular data with many columns"],
 "Values scannable, labels available","Not suitable for many columns",
 "Specification lists","Narrative and wide tables",
 ["Table layout where more than two columns are needed"],
 [("Spacing labels and values across the full column width","The pairing breaks and the eye must re-associate each value with its label","0.5 em separation between label and value")],
 "Keeps label-value pairs readable as units.",7,8,0.87, ch="website")

TYPO("typography.information_hierarchy.warning_prominence.001","Warning and error prominence","information_hierarchy",
 "Make critical information impossible to miss without alarming constantly.",
 "A warning at 1.2 times body size in a heavier weight sits above surrounding text without shouting.",
 "Responsible — the brand flags what matters without manufacturing alarm.",
 "Warnings occupy a level above body but below headings, so they interrupt without restructuring.",
 "1 line of space above and below, with left indent matching the content it qualifies.",
 "Warnings set at body size are absorbed into surrounding text and missed.",
 "Critical information is set at body size inside paragraphs, where it is routinely missed.",
 "Set warnings at 1.2 times body size in a heavier weight with 1 line of clear space around them.",
 "Detection depends on visual difference, and text matching its surroundings is not detected.",
 "Modest size increase plus clear space achieves detection without the fatigue of constant alarm.",
 ["Safety, regulatory and error communication","Interfaces and instructional content"],
 ["Marketing copy with no critical information","Contexts where every line is a warning"],
 "Reliable detection of critical content","Loses force if overused",
 "Safety and error communication","Marketing and low-stakes content",
 ["Colour and icon marking where size increase is not available"],
 [("Setting a safety warning at body size within a paragraph","Absorbed into surrounding text and routinely missed, which is a safety failure","1.2 times body size, heavier weight, with clear space")],
 "Makes critical information detectable.",8,9,0.9, ch="website", ind="healthcare")

TYPO("typography.information_hierarchy.progressive_detail.001","Progressive detail levels","information_hierarchy",
 "Serve both scanning and thorough readers from one layout.",
 "A summary line at 1.3 times body above each detail block lets scanners skip and readers continue.",
 "Considerate — the layout serves two reading modes without choosing between them.",
 "Summary lines form a level between subhead and body, repeated once per detail block.",
 "Summary set 1 line above its block with 0.25 line beneath, binding it to what follows.",
 "Omitting summaries forces every reader to read everything or skip everything.",
 "Technical content is written for thorough readers only, so scanners abandon it entirely.",
 "Open each detail block with a summary line at 1.3 times body size, bound tightly to the block below.",
 "Readers arrive with different intents, and one layout can serve both if summaries are separable.",
 "Tight binding beneath and loose above attaches each summary to the block it introduces.",
 ["Technical and reference documentation","Mixed-audience content"],
 ["Short content with no detail blocks","Narrative writing"],
 "Serves scanners and readers together","Adds a line per block",
 "Technical documentation","Short and narrative content",
 ["Separate summary and detail pages where the split is clean"],
 [("Writing technical content with no per-section summaries","Scanners abandon because they cannot assess relevance without reading everything","A summary line opening each detail block")],
 "Serves scanning and thorough reading at once.",7,7,0.86, ch="website", ind="technology")

TYPO("typography.information_hierarchy.dense_layout_leading.001","Leading in dense layouts","information_hierarchy",
 "Keep dense information readable without reducing type size.",
 "Increased leading separates lines optically, which recovers legibility that density removes.",
 "Legible — density was managed rather than merely accepted.",
 "All levels keep their size; only leading and inter-block spacing absorb the density constraint.",
 "Body leading never below 1.4 even in dense settings, with inter-block spacing at 1 line minimum.",
 "Reducing leading below 1.4 to fit content causes lines to visually merge and reading slows.",
 "Dense layouts reduce leading first, which is the change that damages readability most.",
 "Hold body leading at 1.4 minimum in dense layouts and reduce content rather than leading.",
 "Line separation governs return accuracy more strongly than type size does at normal reading distance.",
 "Protecting leading keeps text readable while density is absorbed elsewhere.",
 ["Dense reports, tables and dashboards","Information-heavy interfaces"],
 ["Display typography","Layouts with generous space"],
 "Readability preserved under density","Requires cutting content instead",
 "Dense information layouts","Display and spacious layouts",
 ["Smaller type at generous leading where content cannot be cut"],
 [("Reducing leading below 1.4 to fit more content","Lines merge visually and reading slows more than a size reduction would have cost","Leading held at 1.4, with content reduced instead")],
 "Protects readability under density.",7,8,0.88, ch="website")

flush()
